<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<node id="n0" labels=":Artist"><data key="labels">:Artist</data><data key="birth_date">1925-03-13</data><data key="bbc">http://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca</data><data key="gender">Male</data><data key="discogs">http://www.discogs.com/artist/255556</data><data key="imdb">http://www.imdb.com/name/nm0371542/</data><data key="viaf">http://viaf.org/viaf/84975999</data><data key="allmusic">http://www.allmusic.com/artist/mn0000290464</data><data key="country">US</data><data key="wikidata">http://www.wikidata.org/wiki/Q448235</data><data key="wikipedia">http://en.wikipedia.org/wiki/Roy_Haynes</data><data key="uuid">2c090b57-5e9d-49c5-9b71-6f0a331cc1ca</data><data key="sort_name">Haynes, Roy</data><data key="source">musicbrainz.org</data><data key="aliases">[Ljava.lang.String;@3831d086</data><data key="musicbrainz">https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca</data><data key="name">Roy Haynes</data></node>
<node id="n1" labels=":Artist"><data key="labels">:Artist</data><data key="birth_date">1931-12-14</data><data key="gender">Male</data><data key="discogs">http://www.discogs.com/artist/824909</data><data key="uuid">e77a6903-a064-4048-b9b9-0a240b6d10c9</data><data key="source">musicbrainz.org</data><data key="allmusic">http://www.allmusic.com/artist/mn0000335889</data><data key="country">US</data><data key="sort_name">Newborn, Phineas, Jr.</data><data key="wikidata">http://www.wikidata.org/wiki/Q707599</data><data key="name">Phineas Newborn, Jr.</data><data key="wikipedia">http://en.wikipedia.org/wiki/Phineas_Newborn,_Jr.</data><data key="death_date">1989-05-26</data><data key="musicbrainz">https://musicbrainz.org/artist/e77a6903-a064-4048-b9b9-0a240b6d10c9</data></node>
<node id="n2" labels=":Artist"><data key="labels">:Artist</data><data key="birth_date">1935-04-22</data><data key="gender">Male</data><data key="discogs">http://www.discogs.com/artist/259778</data><data key="viaf">http://viaf.org/viaf/100313280</data><data key="uuid">b6ff4fd0-03ae-41a6-942e-7de13124b970</data><data key="source">musicbrainz.org</data><data key="country">US</data><data key="wikidata">http://www.wikidata.org/wiki/Q541659</data><data key="name">Paul Chambers</data><data key="sort_name">Chambers, Paul</data><data key="death_date">1969-01-04</data><data key="musicbrainz">https://musicbrainz.org/artist/b6ff4fd0-03ae-41a6-942e-7de13124b970</data><data key="wikipedia">http://en.wikipedia.org/wiki/Paul_Chambers</data><data key="disambiguation">US jazz bassist</data></node>
<node id="n3" labels=":Artist"><data key="labels">:Artist</data><data key="death_date">2011-06-02</data><data key="databases">[Ljava.lang.String;@7f745b53</data><data key="isni_list">[Ljava.lang.String;@53fd0dd3</data><data key="birth_date">1931-12-24</data><data key="gender">Male</data><data key="discogs">http://www.discogs.com/artist/98585</data><data key="country">US</data><data key="wikidata">http://www.wikidata.org/wiki/Q492143</data><data key="wikipedia">http://en.wikipedia.org/wiki/Ray_Bryant</data><data key="viaf">http://viaf.org/viaf/119766558</data><data key="uuid">7feee525-a8ff-4a59-85f6-2b5190ea3e38</data><data key="sort_name">Bryant, Ray</data><data key="source">musicbrainz.org</data><data key="musicbrainz">https://musicbrainz.org/artist/7feee525-a8ff-4a59-85f6-2b5190ea3e38</data><data key="name">Ray Bryant</data><data key="allmusic">http://www.allmusic.com/artist/mn0000869265</data></node>
<node id="n4" labels=":Artist"><data key="labels">:Artist</data><data key="gender">Male</data><data key="uuid">2ebdd071-96b6-4869-b3bf-b2577f0db548</data><data key="sort_name">Nutter, Carl</data><data key="source">musicbrainz.org</data><data key="musicbrainz">http://musicbrainz.org/artist/2ebdd071-96b6-4869-b3bf-b2577f0db548</data><data key="name">Carl Nutter</data><data key="discogs">http://www.discogs.com/artist/718807-Carl-Nutter</data></node>
<node id="n5" labels=":Artist"><data key="labels">:Artist</data><data key="uuid">4c2b8324-d69f-4464-baf2-0ee1f149d993</data><data key="source">musicbrainz.org</data><data key="discogs">http://www.discogs.com/artist/718805-King-Guion</data><data key="gender">Male</data><data key="name">King Guion</data><data key="sort_name">Guion, King</data></node>
<node id="n6" labels=":Artist"><data key="labels">:Artist</data><data key="uuid">5e95d04a-a9cb-49f6-99f3-931a54846f84</data><data key="sort_name">Borek, Reneé</data><data key="discogs">http://www.discogs.com/artist/718808-Renee-Borek</data><data key="name">Reneé Borek</data><data key="source">musicbrainz.org</data></node>
<node id="n7" labels=":Artist"><data key="labels">:Artist</data><data key="death_date">1959-12-01</data><data key="isni_list">[Ljava.lang.String;@60fe2b28</data><data key="birth_date">1917-01-24</data><data key="gender">Male</data><data key="discogs">http://www.discogs.com/artist/732209</data><data key="allmusic">http://www.allmusic.com/artist/mn0000063735</data><data key="country">US</data><data key="wikidata">http://www.wikidata.org/wiki/Q790660</data><data key="wikipedia">http://en.wikipedia.org/wiki/Avery_Parrish</data><data key="uuid">d506bd73-942c-4055-b89e-50eee4665342</data><data key="sort_name">Parrish, Avery</data><data key="source">musicbrainz.org</data><data key="aliases">[Ljava.lang.String;@56fd6251</data><data key="musicbrainz">https://musicbrainz.org/artist/d506bd73-942c-4055-b89e-50eee4665342</data><data key="name">Avery Parrish</data></node>
<node id="n8" labels=":Artist"><data key="labels">:Artist</data><data key="uuid">6ece4abc-394e-45e8-ad10-5a6bc2ec617e</data><data key="source">musicbrainz.org</data><data key="name">Buddy Feyne</data><data key="sort_name">Feyne, Buddy</data></node>
<node id="n9" labels=":Artist"><data key="labels">:Artist</data><data key="birth_date">1882-01-15</data><data key="uuid">3af47722-3115-48b4-9653-575520c43b89</data><data key="sort_name">Bruce, Robert</data><data key="source">musicbrainz.org</data><data key="death_date">1941-04-06</data><data key="name">Robert Bruce</data></node>
<node id="n10" labels=":Artist"><data key="labels">:Artist</data><data key="death_date">1965-03-08</data><data key="birth_date">1917-02-21</data><data key="gender">Male</data><data key="discogs">http://www.discogs.com/artist/251783</data><data key="viaf">http://viaf.org/viaf/7554707</data><data key="allmusic">http://www.allmusic.com/artist/mn0000016759</data><data key="country">US</data><data key="wikidata">http://www.wikidata.org/wiki/Q498736</data><data key="wikipedia">http://en.wikipedia.org/wiki/Tadd_Dameron</data><data key="uuid">52763c17-465b-48e9-9e2b-3345ea8ba761</data><data key="sort_name">Dameron, Tadd</data><data key="source">musicbrainz.org</data><data key="aliases">[Ljava.lang.String;@b0e051e</data><data key="musicbrainz">https://musicbrainz.org/artist/52763c17-465b-48e9-9e2b-3345ea8ba761</data><data key="name">Tadd Dameron</data></node>
<node id="n11" labels=":Artist"><data key="labels">:Artist</data><data key="databases">[Ljava.lang.String;@30260239</data><data key="isni_list">[Ljava.lang.String;@2190d87e</data><data key="discogs">http://www.discogs.com/artist/252966</data><data key="wikipedia">http://en.wikipedia.org/wiki/Rudy_Van_Gelder</data><data key="birth_date">1924-11-02</data><data key="gender">Male</data><data key="viaf">http://viaf.org/viaf/33997197</data><data key="uuid">f0707f1d-55e1-46b6-8a9c-05d508e09a73</data><data key="source">musicbrainz.org</data><data key="allmusic">http://www.allmusic.com/artist/mn0000305301</data><data key="country">US</data><data key="sort_name">Gelder, van, Rudy</data><data key="wikidata">http://www.wikidata.org/wiki/Q945681</data><data key="musicbrainz">https://musicbrainz.org/artist/f0707f1d-55e1-46b6-8a9c-05d508e09a73</data><data key="name">Rudy van Gelder</data></node>
<node id="n12" labels=":Artist"><data key="labels">:Artist</data><data key="discogs">http://www.discogs.com/artist/254944</data><data key="uuid">68c93572-8296-49ea-b94e-b804df7fa6bb</data><data key="source">musicbrainz.org</data><data key="sort_name">Edwards, Esmond</data><data key="musicbrainz">https://musicbrainz.org/artist/68c93572-8296-49ea-b94e-b804df7fa6bb</data><data key="name">Esmond Edwards</data></node>
<node id="n13" labels=":Release"><data key="labels">:Release</data><data key="country">US</data><data key="discogs">http://www.discogs.com/release/3543935</data><data key="format">12" Vinyl</data><data key="date">1958-11-14</data><data key="uuid">8b6162f0-2876-44b2-842c-9b2fe9761e20</data><data key="discode">NJ-8210</data><data key="source">musicbrainz.org</data><data key="musicbrainz">http://musicbrainz.org/release/8b6162f0-2876-44b2-842c-9b2fe9761e20</data><data key="name">We Three</data><data key="links">[Ljava.lang.String;@1cc2c9f7</data></node>
<node id="n14" labels=":Label"><data key="labels">:Label</data><data key="uuid">3690758a-3ec1-4fd3-a250-d510b586b396</data><data key="name">New Jazz</data><data key="source">musicbrainz.org</data></node>
<node id="n15" labels=":Performance"><data key="labels">:Performance</data><data key="duration">4:21</data><data key="uuid">fdafa68d-b309-4f98-b3fe-bbea3daffeb7</data><data key="name">Reflection</data><data key="source">musicbrainz.org</data></node>
<node id="n16" labels=":Performance"><data key="labels">:Performance</data><data key="duration">6:24</data><data key="uuid">64d04739-f2ae-4b00-892f-1c08b9e8c968</data><data key="name">Sugar Ray</data><data key="source">musicbrainz.org</data></node>
<node id="n17" labels=":Performance"><data key="labels">:Performance</data><data key="duration">8:50</data><data key="uuid">03efdfb2-dbdb-493b-afd6-334a8a3a4ddf</data><data key="name">Solitaire</data><data key="source">musicbrainz.org</data></node>
<node id="n18" labels=":Performance"><data key="labels">:Performance</data><data key="duration">11:18</data><data key="uuid">89fabf91-b971-4fad-a1a0-a73108bfed4d</data><data key="name">After Hours</data><data key="source">musicbrainz.org</data></node>
<node id="n19" labels=":Performance"><data key="labels">:Performance</data><data key="uuid">11a3bf1a-4864-44b9-b567-c50dbbe879b6</data><data key="source">musicbrainz.org</data><data key="duration">4:22</data><data key="name">Sneakin' Around</data></node>
<node id="n20" labels=":Performance"><data key="labels">:Performance</data><data key="duration">4:00</data><data key="uuid">feedca3b-e48e-46c7-9ea1-5f5e00f800f9</data><data key="name">Our Delight</data><data key="source">musicbrainz.org</data></node>
<node id="n21" labels=":Work"><data key="labels">:Work</data><data key="uuid">64d3c8b8-f645-4ee7-b906-cabbfe407303</data><data key="name">Reflection</data><data key="type">Song</data></node>
<node id="n22" labels=":Work"><data key="labels">:Work</data><data key="uuid">9e045ac7-5875-43fe-9c21-20220f054467</data><data key="name">Sugar Ray</data><data key="type">Song</data></node>
<node id="n23" labels=":Work"><data key="labels">:Work</data><data key="uuid">78e3b731-8126-4923-90a2-58f83cf43480</data><data key="name">Solitaire</data><data key="type">Song</data></node>
<node id="n24" labels=":Work"><data key="labels">:Work</data><data key="uuid">01690481-f7ac-45b8-bebf-a7d2ed768e1d</data><data key="name">After Hours</data><data key="type">Song</data></node>
<node id="n25" labels=":Work"><data key="labels">:Work</data><data key="uuid">cbb6d84f-6cf8-4bb2-82e4-0ba594c5a41c</data><data key="name">Sneakin' Around</data><data key="type">Song</data></node>
<node id="n26" labels=":Work"><data key="labels">:Work</data><data key="uuid">8e0c4f88-724e-4dfb-afa1-a3079866bab8</data><data key="name">Our Delight</data><data key="type">Song</data></node>
<node id="n27" labels=":Session"><data key="labels">:Session</data><data key="timestamp">1451752885270</data><data key="dates">[Ljava.lang.String;@679f1984</data><data key="uuid">211af67d-9032-4518-b589-a37ffc63908e</data><data key="source">lordisco.com</data><data key="type">recording session</data><data key="name">We Three: Roy Haynes</data><data key="lordisco">[Ljava.lang.String;@6728e884</data></node>
<node id="n28" labels=":Location"><data key="labels">:Location</data><data key="country">USA</data><data key="wikipedia">https://en.wikipedia.org/wiki/Van_Gelder_Studio</data><data key="city">Hackensack</data><data key="uuid">035fa92f-d9d6-412b-8f1e-4f59cf8ba366</data><data key="name">Van Gelder Studio - Hackensack</data><data key="lat">40.885933</data><data key="lng">-74.043474</data><data key="street">25 Prospect Avenue</data><data key="state">NJ</data></node>
<edge id="e0" source="n13" target="n14" label="HAS_LABEL"><data key="label">HAS_LABEL</data></edge>
<edge id="e1" source="n13" target="n15" label="HAS_TRACK"><data key="label">HAS_TRACK</data><data key="name">A1</data><data key="sequence">1</data></edge>
<edge id="e2" source="n13" target="n16" label="HAS_TRACK"><data key="label">HAS_TRACK</data><data key="name">A2</data><data key="sequence">2</data></edge>
<edge id="e3" source="n13" target="n17" label="HAS_TRACK"><data key="label">HAS_TRACK</data><data key="name">A3</data><data key="sequence">3</data></edge>
<edge id="e4" source="n13" target="n18" label="HAS_TRACK"><data key="label">HAS_TRACK</data><data key="name">B1</data><data key="sequence">4</data></edge>
<edge id="e5" source="n13" target="n19" label="HAS_TRACK"><data key="label">HAS_TRACK</data><data key="name">B2</data><data key="sequence">5</data></edge>
<edge id="e6" source="n13" target="n20" label="HAS_TRACK"><data key="label">HAS_TRACK</data><data key="name">B3</data><data key="sequence">6</data></edge>
<edge id="e7" source="n13" target="n0" label="HAS_LEADER"><data key="label">HAS_LEADER</data></edge>
<edge id="e8" source="n13" target="n1" label="HAS_LEADER"><data key="label">HAS_LEADER</data></edge>
<edge id="e9" source="n13" target="n2" label="HAS_LEADER"><data key="label">HAS_LEADER</data></edge>
<edge id="e10" source="n3" target="n21" label="COMPOSED"><data key="label">COMPOSED</data></edge>
<edge id="e11" source="n15" target="n21" label="PERFORMANCE_OF"><data key="label">PERFORMANCE_OF</data></edge>
<edge id="e12" source="n1" target="n22" label="COMPOSED"><data key="label">COMPOSED</data></edge>
<edge id="e13" source="n16" target="n22" label="PERFORMANCE_OF"><data key="label">PERFORMANCE_OF</data></edge>
<edge id="e14" source="n4" target="n23" label="COMPOSED"><data key="label">COMPOSED</data><data key="roles">[Ljava.lang.String;@2229babc</data></edge>
<edge id="e15" source="n5" target="n23" label="COMPOSED"><data key="label">COMPOSED</data><data key="roles">[Ljava.lang.String;@3cebb3a6</data></edge>
<edge id="e16" source="n6" target="n23" label="COMPOSED"><data key="label">COMPOSED</data><data key="roles">[Ljava.lang.String;@5e0c0682</data></edge>
<edge id="e17" source="n17" target="n23" label="PERFORMANCE_OF"><data key="label">PERFORMANCE_OF</data></edge>
<edge id="e18" source="n7" target="n24" label="COMPOSED"><data key="label">COMPOSED</data></edge>
<edge id="e19" source="n8" target="n24" label="COMPOSED"><data key="label">COMPOSED</data></edge>
<edge id="e20" source="n9" target="n24" label="COMPOSED"><data key="label">COMPOSED</data></edge>
<edge id="e21" source="n18" target="n24" label="PERFORMANCE_OF"><data key="label">PERFORMANCE_OF</data></edge>
<edge id="e22" source="n3" target="n25" label="COMPOSED"><data key="label">COMPOSED</data></edge>
<edge id="e23" source="n19" target="n25" label="PERFORMANCE_OF"><data key="label">PERFORMANCE_OF</data></edge>
<edge id="e24" source="n10" target="n26" label="COMPOSED"><data key="label">COMPOSED</data></edge>
<edge id="e25" source="n20" target="n26" label="PERFORMANCE_OF"><data key="label">PERFORMANCE_OF</data></edge>
<edge id="e26" source="n27" target="n15" label="HAS_PERFORMANCE"><data key="label">HAS_PERFORMANCE</data></edge>
<edge id="e27" source="n27" target="n16" label="HAS_PERFORMANCE"><data key="label">HAS_PERFORMANCE</data></edge>
<edge id="e28" source="n27" target="n17" label="HAS_PERFORMANCE"><data key="label">HAS_PERFORMANCE</data></edge>
<edge id="e29" source="n27" target="n18" label="HAS_PERFORMANCE"><data key="label">HAS_PERFORMANCE</data></edge>
<edge id="e30" source="n27" target="n19" label="HAS_PERFORMANCE"><data key="label">HAS_PERFORMANCE</data></edge>
<edge id="e31" source="n27" target="n20" label="HAS_PERFORMANCE"><data key="label">HAS_PERFORMANCE</data></edge>
<edge id="e32" source="n27" target="n28" label="HAS_LOCATION"><data key="label">HAS_LOCATION</data></edge>
<edge id="e33" source="n11" target="n13" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="roles">[Ljava.lang.String;@e5da612</data></edge>
<edge id="e34" source="n12" target="n13" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="roles">[Ljava.lang.String;@614e013f</data></edge>
<edge id="e35" source="n0" target="n15" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@d9e833</data></edge>
<edge id="e36" source="n0" target="n16" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@3e5fc6bc</data></edge>
<edge id="e37" source="n0" target="n17" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@5dd18a53</data></edge>
<edge id="e38" source="n0" target="n18" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@4c073f2f</data></edge>
<edge id="e39" source="n0" target="n19" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@350ceec</data></edge>
<edge id="e40" source="n0" target="n20" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@437a821c</data></edge>
<edge id="e41" source="n1" target="n15" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@12281b32</data></edge>
<edge id="e42" source="n1" target="n16" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@6723b01f</data></edge>
<edge id="e43" source="n1" target="n17" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@628135b9</data></edge>
<edge id="e44" source="n1" target="n18" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@757c2197</data></edge>
<edge id="e45" source="n1" target="n19" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@275f5581</data></edge>
<edge id="e46" source="n1" target="n20" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@5d86aa3d</data></edge>
<edge id="e47" source="n2" target="n15" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@364160c9</data></edge>
<edge id="e48" source="n2" target="n16" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@22a58f0f</data></edge>
<edge id="e49" source="n2" target="n17" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@7f0b3587</data></edge>
<edge id="e50" source="n2" target="n18" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@1734bf19</data></edge>
<edge id="e51" source="n2" target="n19" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@2a4ed21e</data></edge>
<edge id="e52" source="n2" target="n20" label="PARTICIPATED_IN"><data key="label">PARTICIPATED_IN</data><data key="instruments">[Ljava.lang.String;@241dfdaf</data></edge>
</graph>
</graphml>
