MERGE (place_3a9fad8b26a6:Place{ uuid: '7cde5fff-fdb3-40d7-be6f-3a9fad8b26a6' })
SET place_3a9fad8b26a6.name = 'Skyline Studios'
SET place_3a9fad8b26a6.type = 'studio'
SET place_3a9fad8b26a6.address = '36 West 37th Street, New York City, New York, 10018, United States'
SET place_3a9fad8b26a6.begin = 1979
SET place_3a9fad8b26a6.end = 1995
SET place_3a9fad8b26a6.lat = '40.7509778'
SET place_3a9fad8b26a6.lng = '-73.9872409'
SET place_3a9fad8b26a6.source = 'musicbrainz.org'