// releases

MERGE (release_fe166e04cb18:Release{ uuid: 'bfe29cd3-2577-4237-9b34-fe166e04cb18' })
SET release_fe166e04cb18.name = 'The Amazing Bud Powell'
SET release_fe166e04cb18.country = 'US'
SET release_fe166e04cb18.date = '1951'
SET release_fe166e04cb18.format = '10" Vinyl'
SET release_fe166e04cb18.discode = 'BLP 5003'
SET release_fe166e04cb18.musicbrainz = 'http://musicbrainz.org/release/bfe29cd3-2577-4237-9b34-fe166e04cb18'
SET release_fe166e04cb18.source = 'musicbrainz.org'
SET release_fe166e04cb18.timestamp = timestamp()

MERGE (person_bad80243802a:Person{ uuid: '3b47247e-5b57-49b6-a0ed-bad80243802a' })
SET person_bad80243802a.name = 'Sonny Rollins'
SET person_bad80243802a.gender = 'Male'
SET person_bad80243802a.country = 'US'
SET person_bad80243802a.wikipedia = 'http://en.wikipedia.org/wiki/Sonny_Rollins'
SET person_bad80243802a.viaf = 'http://viaf.org/viaf/7368226'
SET person_bad80243802a.allmusic = 'http://www.allmusic.com/artist/mn0000039656'
SET person_bad80243802a.bbc = 'http://www.bbc.co.uk/music/artists/3b47247e-5b57-49b6-a0ed-bad80243802a'
SET person_bad80243802a.discogs = 'http://www.discogs.com/artist/145264'
SET person_bad80243802a.wikidata = 'http://www.wikidata.org/wiki/Q299208'
SET person_bad80243802a.databases = ['http://d-nb.info/gnd/118749552', 'https://www.worldcat.org/identities/lccn-n82-144213']
SET person_bad80243802a.musicbrainz = 'https://musicbrainz.org/artist/3b47247e-5b57-49b6-a0ed-bad80243802a'
SET person_bad80243802a.isni_list = ['http://isni.org/isni/0000000110367920']
SET person_bad80243802a.source = 'musicbrainz.org'
SET person_bad80243802a.timestamp = timestamp()

MERGE (person_340d64fbb41c:Person{ uuid: 'dbc5809c-7837-4b6f-961e-340d64fbb41c' })
SET person_340d64fbb41c.name = 'Bud Powell'
SET person_340d64fbb41c.gender = 'Male'
SET person_340d64fbb41c.country = 'US'
SET person_340d64fbb41c.wikipedia = 'http://en.wikipedia.org/wiki/Bud_Powell'
SET person_340d64fbb41c.viaf = 'http://viaf.org/viaf/197369'
SET person_340d64fbb41c.allmusic = 'http://www.allmusic.com/artist/mn0000640675'
SET person_340d64fbb41c.bbc = 'http://www.bbc.co.uk/music/artists/dbc5809c-7837-4b6f-961e-340d64fbb41c'
SET person_340d64fbb41c.discogs = 'http://www.discogs.com/artist/29992'
SET person_340d64fbb41c.wikidata = 'http://www.wikidata.org/wiki/Q312692'
SET person_340d64fbb41c.databases = ['http://rateyourmusic.com/artist/bud_powell']
SET person_340d64fbb41c.musicbrainz = 'https://musicbrainz.org/artist/dbc5809c-7837-4b6f-961e-340d64fbb41c'
SET person_340d64fbb41c.source = 'musicbrainz.org'
SET person_340d64fbb41c.timestamp = timestamp()

MERGE (person_1899e0d44169:Person{ uuid: 'c898870b-b704-4c52-99d5-1899e0d44169' })
SET person_1899e0d44169.name = 'Curley Russell'
SET person_1899e0d44169.gender = 'Male'
SET person_1899e0d44169.country = 'US'
SET person_1899e0d44169.wikipedia = 'http://en.wikipedia.org/wiki/Curley_Russell'
SET person_1899e0d44169.allmusic = 'http://www.allmusic.com/artist/mn0000137301'
SET person_1899e0d44169.discogs = 'http://www.discogs.com/artist/259075'
SET person_1899e0d44169.wikidata = 'http://www.wikidata.org/wiki/Q956634'
SET person_1899e0d44169.musicbrainz = 'https://musicbrainz.org/artist/c898870b-b704-4c52-99d5-1899e0d44169'
SET person_1899e0d44169.source = 'musicbrainz.org'
SET person_1899e0d44169.timestamp = timestamp()

MERGE (person_37e57681a3cf:Person{ uuid: '7d606f44-a90c-4c1e-909d-37e57681a3cf' })
SET person_37e57681a3cf.name = 'Tommy Potter'
SET person_37e57681a3cf.gender = 'Male'
SET person_37e57681a3cf.country = 'US'
SET person_37e57681a3cf.wikipedia = 'http://en.wikipedia.org/wiki/Tommy_Potter'
SET person_37e57681a3cf.allmusic = 'http://www.allmusic.com/artist/mn0000521303'
SET person_37e57681a3cf.discogs = 'http://www.discogs.com/artist/251780'
SET person_37e57681a3cf.wikidata = 'http://www.wikidata.org/wiki/Q1369941'
SET person_37e57681a3cf.musicbrainz = 'https://musicbrainz.org/artist/7d606f44-a90c-4c1e-909d-37e57681a3cf'
SET person_37e57681a3cf.source = 'musicbrainz.org'
SET person_37e57681a3cf.timestamp = timestamp()

MERGE (person_b0280dd28684:Person{ uuid: '0b6aea55-d855-4a33-ae08-b0280dd28684' })
SET person_b0280dd28684.name = 'Max Roach'
SET person_b0280dd28684.gender = 'Male'
SET person_b0280dd28684.country = 'US'
SET person_b0280dd28684.wikipedia = 'http://en.wikipedia.org/wiki/Max_Roach'
SET person_b0280dd28684.viaf = 'http://viaf.org/viaf/7575133'
SET person_b0280dd28684.allmusic = 'http://www.allmusic.com/artist/mn0000396372'
SET person_b0280dd28684.bbc = 'http://www.bbc.co.uk/music/artists/0b6aea55-d855-4a33-ae08-b0280dd28684'
SET person_b0280dd28684.discogs = 'http://www.discogs.com/artist/229498'
SET person_b0280dd28684.imdb = 'http://www.imdb.com/name/nm0730046/'
SET person_b0280dd28684.wikidata = 'http://www.wikidata.org/wiki/Q175899'
SET person_b0280dd28684.musicbrainz = 'https://musicbrainz.org/artist/0b6aea55-d855-4a33-ae08-b0280dd28684'
SET person_b0280dd28684.source = 'musicbrainz.org'
SET person_b0280dd28684.timestamp = timestamp()

MERGE (person_115e740b7fe0:Person{ uuid: 'd2a135f4-bb6b-4fb6-a09b-115e740b7fe0' })
SET person_115e740b7fe0.name = 'Fats Navarro'
SET person_115e740b7fe0.gender = 'Male'
SET person_115e740b7fe0.country = 'US'
SET person_115e740b7fe0.wikipedia = 'http://en.wikipedia.org/wiki/Fats_Navarro'
SET person_115e740b7fe0.viaf = 'http://viaf.org/viaf/7574828'
SET person_115e740b7fe0.allmusic = 'http://www.allmusic.com/artist/mn0000792175'
SET person_115e740b7fe0.discogs = 'http://www.discogs.com/artist/309986'
SET person_115e740b7fe0.wikidata = 'http://www.wikidata.org/wiki/Q711198'
SET person_115e740b7fe0.musicbrainz = 'https://musicbrainz.org/artist/d2a135f4-bb6b-4fb6-a09b-115e740b7fe0'
SET person_115e740b7fe0.source = 'musicbrainz.org'
SET person_115e740b7fe0.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' })
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.wikipedia = 'http://en.wikipedia.org/wiki/Roy_Haynes'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.allmusic = 'http://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'http://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'http://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'http://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.wikidata = 'http://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()
// labels

MERGE (label_14e1ddfd5946:Label{ uuid: '713c4a95-6616-442b-9cf6-14e1ddfd5946' })
SET label_14e1ddfd5946.name= 'Blue Note'

// performances

MERGE (perf_adce16b0ed75:Performance{ uuid: '84c147c7-4a55-4c80-92c4-adce16b0ed75' })
SET perf_adce16b0ed75.name = 'Un Poco Loco'
SET perf_adce16b0ed75.duration = '4:42'
SET perf_adce16b0ed75.begin = '1951-05-01'
SET perf_adce16b0ed75.end = '1951-05-01'
SET perf_adce16b0ed75.source = 'musicbrainz.org'
SET perf_adce16b0ed75.timestamp = timestamp()

MERGE (perf_57808b2a6d5d:Performance{ uuid: '346e0665-2d39-4164-93fa-57808b2a6d5d' })
SET perf_57808b2a6d5d.name = 'Over the Rainbow'
SET perf_57808b2a6d5d.duration = '2:55'
SET perf_57808b2a6d5d.begin = '1951-05-01'
SET perf_57808b2a6d5d.end = '1951-05-01'
SET perf_57808b2a6d5d.source = 'musicbrainz.org'
SET perf_57808b2a6d5d.timestamp = timestamp()

MERGE (perf_cc03e7b7a64a:Performance{ uuid: '0af641d7-ddbf-48b9-81ce-cc03e7b7a64a' })
SET perf_cc03e7b7a64a.name = 'Ornithology'
SET perf_cc03e7b7a64a.duration = '2:20'
SET perf_cc03e7b7a64a.begin = '1949-08-09'
SET perf_cc03e7b7a64a.end = '1949-08-09'
SET perf_cc03e7b7a64a.source = 'musicbrainz.org'
SET perf_cc03e7b7a64a.timestamp = timestamp()

MERGE (perf_dbedb2a5ef47:Performance{ uuid: '89dca7d5-78e8-4ef8-b8c6-dbedb2a5ef47' })
SET perf_dbedb2a5ef47.name = 'Wail'
SET perf_dbedb2a5ef47.duration = '3:02'
SET perf_dbedb2a5ef47.begin = '1949-08-09'
SET perf_dbedb2a5ef47.end = '1949-08-09'
SET perf_dbedb2a5ef47.source = 'musicbrainz.org'
SET perf_dbedb2a5ef47.timestamp = timestamp()

MERGE (perf_44fa4ea267f1:Performance{ uuid: 'dd3b0579-6380-4349-b318-44fa4ea267f1' })
SET perf_44fa4ea267f1.name = 'A Night in Tunisia'
SET perf_44fa4ea267f1.duration = '4:12'
SET perf_44fa4ea267f1.begin = '1951-05-01'
SET perf_44fa4ea267f1.end = '1951-05-01'
SET perf_44fa4ea267f1.source = 'musicbrainz.org'
SET perf_44fa4ea267f1.timestamp = timestamp()

MERGE (perf_ffcb9c8fa1e3:Performance{ uuid: 'f4687723-0042-4b5d-83fb-ffcb9c8fa1e3' })
SET perf_ffcb9c8fa1e3.name = 'It Could Happen to You'
SET perf_ffcb9c8fa1e3.duration = '3:12'
SET perf_ffcb9c8fa1e3.begin = '1951-05-01'
SET perf_ffcb9c8fa1e3.end = '1951-05-01'
SET perf_ffcb9c8fa1e3.source = 'musicbrainz.org'
SET perf_ffcb9c8fa1e3.timestamp = timestamp()

MERGE (perf_9fc1530f53e5:Performance{ uuid: '3e73b36b-6f68-4c2e-bb11-9fc1530f53e5' })
SET perf_9fc1530f53e5.name = 'You Go to My Head'
SET perf_9fc1530f53e5.duration = '3:11'
SET perf_9fc1530f53e5.begin = '1949-08-09'
SET perf_9fc1530f53e5.end = '1949-08-09'
SET perf_9fc1530f53e5.source = 'musicbrainz.org'
SET perf_9fc1530f53e5.timestamp = timestamp()

MERGE (perf_ad3f8a35a9b0:Performance{ uuid: '24bacc4a-2e38-4f09-8a18-ad3f8a35a9b0' })
SET perf_ad3f8a35a9b0.name = 'Bouncing With Bud'
SET perf_ad3f8a35a9b0.duration = '3:01'
SET perf_ad3f8a35a9b0.begin = '1949-08-09'
SET perf_ad3f8a35a9b0.end = '1949-08-09'
SET perf_ad3f8a35a9b0.source = 'musicbrainz.org'
SET perf_ad3f8a35a9b0.timestamp = timestamp()



// labels
MERGE (release_fe166e04cb18)-[:HAS_LABEL]->(label_14e1ddfd5946)


// tracks
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_adce16b0ed75)
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_57808b2a6d5d)
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'A3', sequence: 3}]->(perf_cc03e7b7a64a)
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'A4', sequence: 4}]->(perf_dbedb2a5ef47)
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'B1', sequence: 5}]->(perf_44fa4ea267f1)
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'B2', sequence: 6}]->(perf_ffcb9c8fa1e3)
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'B3', sequence: 7}]->(perf_9fc1530f53e5)
MERGE (release_fe166e04cb18)-[:HAS_TRACK {name: 'B4', sequence: 8}]->(perf_ad3f8a35a9b0)

// works

MERGE (person_a4cb6fbe4434:Person{ uuid: '57e1817c-4ff5-4079-9381-a4cb6fbe4434' })
SET person_a4cb6fbe4434.name = 'Benny Harris'
SET person_a4cb6fbe4434.gender = 'Male'
SET person_a4cb6fbe4434.country = 'US'
SET person_a4cb6fbe4434.wikipedia = 'http://en.wikipedia.org/wiki/Benny_Harris'
SET person_a4cb6fbe4434.allmusic = 'http://www.allmusic.com/artist/mn0000792654'
SET person_a4cb6fbe4434.wikidata = 'http://www.wikidata.org/wiki/Q818056'
SET person_a4cb6fbe4434.musicbrainz = 'https://musicbrainz.org/artist/57e1817c-4ff5-4079-9381-a4cb6fbe4434'
SET person_a4cb6fbe4434.source = 'musicbrainz.org'
SET person_a4cb6fbe4434.timestamp = timestamp()

MERGE (person_65998d0d35b5:Person{ uuid: 'e9ba8ccb-505f-4e5c-b909-65998d0d35b5' })
SET person_65998d0d35b5.name = 'Dizzy Gillespie'
SET person_65998d0d35b5.gender = 'Male'
SET person_65998d0d35b5.country = 'US'
SET person_65998d0d35b5.wikipedia = 'http://en.wikipedia.org/wiki/Dizzy_Gillespie'
SET person_65998d0d35b5.viaf = 'http://viaf.org/viaf/77110276'
SET person_65998d0d35b5.allmusic = 'http://www.allmusic.com/artist/mn0000162677'
SET person_65998d0d35b5.bbc = 'http://www.bbc.co.uk/music/artists/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.discogs = 'http://www.discogs.com/artist/64694'
SET person_65998d0d35b5.wikidata = 'http://www.wikidata.org/wiki/Q49575'
SET person_65998d0d35b5.discographies = ['http://www.jazzdisco.org/dizzy-gillespie/']
SET person_65998d0d35b5.databases = ['http://rateyourmusic.com/artist/dizzy_gillespie']
SET person_65998d0d35b5.musicbrainz = 'https://musicbrainz.org/artist/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.isni_list = ['http://isni.org/isni/0000000109181520']
SET person_65998d0d35b5.source = 'musicbrainz.org'
SET person_65998d0d35b5.timestamp = timestamp()

MERGE (person_376736bb6cde:Person{ uuid: '3508f3fd-3b18-493c-a362-376736bb6cde' })
SET person_376736bb6cde.name = 'Harold Arlen'
SET person_376736bb6cde.gender = 'Male'
SET person_376736bb6cde.country = 'US'
SET person_376736bb6cde.wikipedia = 'http://en.wikipedia.org/wiki/Harold_Arlen'
SET person_376736bb6cde.viaf = 'http://viaf.org/viaf/59268723'
SET person_376736bb6cde.allmusic = 'http://www.allmusic.com/artist/mn0000060306'
SET person_376736bb6cde.discogs = 'http://www.discogs.com/artist/301975'
SET person_376736bb6cde.imdb = 'http://www.imdb.com/name/nm0002182/'
SET person_376736bb6cde.wikidata = 'http://www.wikidata.org/wiki/Q448644'
SET person_376736bb6cde.databases = ['http://ibdb.com/person.php?id=11319', 'https://rateyourmusic.com/artist/harold_arlen']
SET person_376736bb6cde.musicbrainz = 'https://musicbrainz.org/artist/3508f3fd-3b18-493c-a362-376736bb6cde'
SET person_376736bb6cde.isni_list = ['http://isni.org/isni/0000000083863098']
SET person_376736bb6cde.source = 'musicbrainz.org'
SET person_376736bb6cde.timestamp = timestamp()

MERGE (person_c73775716312:Person{ uuid: 'c7356af9-9ea6-4a78-a55b-c73775716312' })
SET person_c73775716312.name = 'Charlie Parker'
SET person_c73775716312.gender = 'Male'
SET person_c73775716312.disambiguation = 'aka "Bird", jazz alto saxophonist'
SET person_c73775716312.country = 'US'
SET person_c73775716312.wikipedia = 'http://en.wikipedia.org/wiki/Charlie_Parker'
SET person_c73775716312.viaf = 'http://viaf.org/viaf/10034216'
SET person_c73775716312.allmusic = 'http://www.allmusic.com/artist/mn0000211758'
SET person_c73775716312.bbc = 'http://www.bbc.co.uk/music/artists/c7356af9-9ea6-4a78-a55b-c73775716312'
SET person_c73775716312.discogs = 'http://www.discogs.com/artist/75617'
SET person_c73775716312.imdb = 'http://www.imdb.com/name/nm0662127/'
SET person_c73775716312.wikidata = 'http://www.wikidata.org/wiki/Q103767'
SET person_c73775716312.discographies = ['http://www.jazzdisco.org/bird/', 'http://www.kyushu-ns.ac.jp/~allan/Documents/CP_M.html']
SET person_c73775716312.databases = ['http://rateyourmusic.com/artist/charlie_parker']
SET person_c73775716312.musicbrainz = 'https://musicbrainz.org/artist/c7356af9-9ea6-4a78-a55b-c73775716312'
SET person_c73775716312.isni_list = ['http://isni.org/isni/0000000120955806']
SET person_c73775716312.source = 'musicbrainz.org'
SET person_c73775716312.timestamp = timestamp()

MERGE (person_a6d92136636f:Person{ uuid: '8d3f8b43-0d28-4500-900e-a6d92136636f' })
SET person_a6d92136636f.name = 'Jimmy Van Heusen'
SET person_a6d92136636f.gender = 'Male'
SET person_a6d92136636f.country = 'US'
SET person_a6d92136636f.wikipedia = 'http://en.wikipedia.org/wiki/Jimmy_Van_Heusen'
SET person_a6d92136636f.viaf = 'http://viaf.org/viaf/54338466'
SET person_a6d92136636f.allmusic = 'http://www.allmusic.com/artist/mn0000309464'
SET person_a6d92136636f.allmusic = 'http://www.allmusic.com/artist/mn0003168282'
SET person_a6d92136636f.discogs = 'http://www.discogs.com/artist/255313'
SET person_a6d92136636f.imdb = 'http://www.imdb.com/name/nm0006329/'
SET person_a6d92136636f.wikidata = 'http://www.wikidata.org/wiki/Q33124'
SET person_a6d92136636f.databases = ['http://ibdb.com/person.php?id=12521', 'https://rateyourmusic.com/artist/jimmy_van_heusen']
SET person_a6d92136636f.musicbrainz = 'https://musicbrainz.org/artist/8d3f8b43-0d28-4500-900e-a6d92136636f'
SET person_a6d92136636f.isni_list = ['http://isni.org/isni/0000000081333253']
SET person_a6d92136636f.source = 'musicbrainz.org'
SET person_a6d92136636f.timestamp = timestamp()

MERGE (person_3cc1e480a060:Person{ uuid: '3bcb90e6-c8d9-463d-870a-3cc1e480a060' })
SET person_3cc1e480a060.name = 'J. Fred Coots'
SET person_3cc1e480a060.gender = 'Male'
SET person_3cc1e480a060.country = 'US'
SET person_3cc1e480a060.wikipedia = 'http://en.wikipedia.org/wiki/John_Frederick_Coots'
SET person_3cc1e480a060.viaf = 'http://viaf.org/viaf/5196885'
SET person_3cc1e480a060.discogs = 'http://www.discogs.com/artist/583506'
SET person_3cc1e480a060.wikidata = 'http://www.wikidata.org/wiki/Q1284588'
SET person_3cc1e480a060.musicbrainz = 'https://musicbrainz.org/artist/3bcb90e6-c8d9-463d-870a-3cc1e480a060'
SET person_3cc1e480a060.source = 'musicbrainz.org'
SET person_3cc1e480a060.timestamp = timestamp()

MERGE (person_66f3736e0ac5:Person{ uuid: '67ec74fe-0e96-4e3d-96a7-66f3736e0ac5' })
SET person_66f3736e0ac5.name = 'Frank Paparelli'
SET person_66f3736e0ac5.gender = 'Male'
SET person_66f3736e0ac5.country = 'US'
SET person_66f3736e0ac5.allmusic = 'http://www.allmusic.com/artist/mn0000146400'
SET person_66f3736e0ac5.discogs = 'http://www.discogs.com/artist/370787'
SET person_66f3736e0ac5.musicbrainz = 'https://musicbrainz.org/artist/67ec74fe-0e96-4e3d-96a7-66f3736e0ac5'
SET person_66f3736e0ac5.source = 'musicbrainz.org'
SET person_66f3736e0ac5.timestamp = timestamp()

MERGE (work_d427be3d3a80:Work{ uuid: '9005e69f-9a74-3642-a92f-d427be3d3a80' })
SET work_d427be3d3a80.name = 'Un Poco Loco'
SET work_d427be3d3a80.wikidata = 'https://www.wikidata.org/wiki/Q3548944'
SET work_d427be3d3a80.musicbrainz = 'https://musicbrainz.org/work/9005e69f-9a74-3642-a92f-d427be3d3a80'
SET work_d427be3d3a80.source = 'musicbrainz.org'
SET work_d427be3d3a80.timestamp = timestamp()

MERGE (work_cf7b456d7570:Work{ uuid: 'a0faf79f-08bb-49c3-8443-cf7b456d7570' })
SET work_cf7b456d7570.name = 'Somewhere Over the Rainbow'
SET work_cf7b456d7570.source = 'musicbrainz.org'
SET work_cf7b456d7570.timestamp = timestamp()

MERGE (work_bc5765ec131f:Work{ uuid: '6c3b2860-0c5f-38fc-9e92-bc5765ec131f' })
SET work_bc5765ec131f.name = 'Ornithology'
SET work_bc5765ec131f.source = 'musicbrainz.org'
SET work_bc5765ec131f.timestamp = timestamp()

MERGE (work_232ecf2118a0:Work{ uuid: '2305f33d-094e-30a9-bb7c-232ecf2118a0' })
SET work_232ecf2118a0.name = 'Wail'
SET work_232ecf2118a0.source = 'musicbrainz.org'
SET work_232ecf2118a0.timestamp = timestamp()

MERGE (work_3c2dda79454a:Work{ uuid: 'fdf59350-09d0-4892-b766-3c2dda79454a' })
SET work_3c2dda79454a.name = 'A Night in Tunisia'
SET work_3c2dda79454a.type = 'Song'
SET work_3c2dda79454a.musicbrainz = 'https://musicbrainz.org/work/fdf59350-09d0-4892-b766-3c2dda79454a'
SET work_3c2dda79454a.source = 'musicbrainz.org'
SET work_3c2dda79454a.timestamp = timestamp()

MERGE (work_caa47b30366c:Work{ uuid: '6d489d45-3e3b-3bd9-a178-caa47b30366c' })
SET work_caa47b30366c.name = 'It Could Happen to You'
SET work_caa47b30366c.type = 'Song'
SET work_caa47b30366c.wikidata = 'http://www.wikidata.org/wiki/Q820861'
SET work_caa47b30366c.musicbrainz = 'https://musicbrainz.org/work/6d489d45-3e3b-3bd9-a178-caa47b30366c'
SET work_caa47b30366c.source = 'musicbrainz.org'
SET work_caa47b30366c.timestamp = timestamp()

MERGE (work_14cea4bc6292:Work{ uuid: '72715cfb-1ade-30ed-951f-14cea4bc6292' })
SET work_14cea4bc6292.name = 'You Go to My Head'
SET work_14cea4bc6292.type = 'Song'
SET work_14cea4bc6292.wikipedia = 'http://en.wikipedia.org/wiki/You_Go_to_My_Head'
SET work_14cea4bc6292.wikidata = 'http://www.wikidata.org/wiki/Q753614'
SET work_14cea4bc6292.musicbrainz = 'https://musicbrainz.org/work/72715cfb-1ade-30ed-951f-14cea4bc6292'
SET work_14cea4bc6292.source = 'musicbrainz.org'
SET work_14cea4bc6292.timestamp = timestamp()

MERGE (work_9d1baf9ff1cc:Work{ uuid: '49025c5f-060e-4993-816f-9d1baf9ff1cc' })
SET work_9d1baf9ff1cc.name = 'Bouncing With Bud'
SET work_9d1baf9ff1cc.source = 'musicbrainz.org'
SET work_9d1baf9ff1cc.timestamp = timestamp()


// performances of
MERGE (perf_adce16b0ed75)-[:PERFORMANCE_OF]->(work_d427be3d3a80)
MERGE (perf_57808b2a6d5d)-[:PERFORMANCE_OF]->(work_cf7b456d7570)
MERGE (perf_cc03e7b7a64a)-[:PERFORMANCE_OF]->(work_bc5765ec131f)
MERGE (perf_dbedb2a5ef47)-[:PERFORMANCE_OF]->(work_232ecf2118a0)
MERGE (perf_44fa4ea267f1)-[:PERFORMANCE_OF]->(work_3c2dda79454a)
MERGE (perf_ffcb9c8fa1e3)-[:PERFORMANCE_OF]->(work_caa47b30366c)
MERGE (perf_9fc1530f53e5)-[:PERFORMANCE_OF]->(work_14cea4bc6292)
MERGE (perf_ad3f8a35a9b0)-[:PERFORMANCE_OF]->(work_9d1baf9ff1cc)


// composers
MERGE (person_340d64fbb41c)-[:COMPOSED]->(work_d427be3d3a80)
MERGE (person_376736bb6cde)-[:COMPOSED]->(work_cf7b456d7570)
MERGE (person_a4cb6fbe4434)-[:COMPOSED]->(work_bc5765ec131f)
MERGE (person_c73775716312)-[:COMPOSED]->(work_bc5765ec131f)
MERGE (person_340d64fbb41c)-[:COMPOSED]->(work_232ecf2118a0)
MERGE (person_66f3736e0ac5)-[:COMPOSED]->(work_3c2dda79454a)
MERGE (person_65998d0d35b5)-[:COMPOSED]->(work_3c2dda79454a)
MERGE (person_a6d92136636f)-[:COMPOSED]->(work_caa47b30366c)
MERGE (person_3cc1e480a060)-[:COMPOSED]->(work_14cea4bc6292)
MERGE (person_340d64fbb41c)-[:COMPOSED]->(work_9d1baf9ff1cc)


// place nodes

MERGE (place_3a21318421ef:Place{ uuid: 'cc6513c4-c1d3-46eb-838a-3a21318421ef' })
SET place_3a21318421ef.name = 'WOR Studios'
SET place_3a21318421ef.address = '1440 Broadway (1926-2005)'
SET place_3a21318421ef.source = 'musicbrainz.org'


// place relationships
MERGE (perf_adce16b0ed75)-[:HAS_PLACE { type: 'recorded at', begin: '1951-05-01', end: '1951-05-01' }]->(place_3a21318421ef)
MERGE (perf_57808b2a6d5d)-[:HAS_PLACE { type: 'recorded at', begin: '1951-05-01', end: '1951-05-01' }]->(place_3a21318421ef)
MERGE (perf_cc03e7b7a64a)-[:HAS_PLACE { type: 'recorded at', begin: '1949-08-09', end: '1949-08-09' }]->(place_3a21318421ef)
MERGE (perf_dbedb2a5ef47)-[:HAS_PLACE { type: 'recorded at', begin: '1949-08-09', end: '1949-08-09' }]->(place_3a21318421ef)
MERGE (perf_44fa4ea267f1)-[:HAS_PLACE { type: 'recorded at', begin: '1951-05-01', end: '1951-05-01' }]->(place_3a21318421ef)
MERGE (perf_ffcb9c8fa1e3)-[:HAS_PLACE { type: 'recorded at', begin: '1951-05-01', end: '1951-05-01' }]->(place_3a21318421ef)
MERGE (perf_9fc1530f53e5)-[:HAS_PLACE { type: 'recorded at', begin: '1949-08-09', end: '1949-08-09' }]->(place_3a21318421ef)
MERGE (perf_ad3f8a35a9b0)-[:HAS_PLACE { type: 'recorded at', begin: '1949-08-09', end: '1949-08-09' }]->(place_3a21318421ef)

MERGE (person_b0280dd28684)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_adce16b0ed75)
MERGE (person_1899e0d44169)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_adce16b0ed75)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_adce16b0ed75)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano', 'solo'] }]->(perf_57808b2a6d5d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_cc03e7b7a64a)
MERGE (person_37e57681a3cf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_cc03e7b7a64a)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_cc03e7b7a64a)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_dbedb2a5ef47)
MERGE (person_bad80243802a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_dbedb2a5ef47)
MERGE (person_37e57681a3cf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_dbedb2a5ef47)
MERGE (person_115e740b7fe0)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_dbedb2a5ef47)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_dbedb2a5ef47)
MERGE (person_b0280dd28684)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_44fa4ea267f1)
MERGE (person_1899e0d44169)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_44fa4ea267f1)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_44fa4ea267f1)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano', 'solo'] }]->(perf_ffcb9c8fa1e3)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_9fc1530f53e5)
MERGE (person_37e57681a3cf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_9fc1530f53e5)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_9fc1530f53e5)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_ad3f8a35a9b0)
MERGE (person_bad80243802a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_ad3f8a35a9b0)
MERGE (person_37e57681a3cf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_ad3f8a35a9b0)
MERGE (person_115e740b7fe0)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_ad3f8a35a9b0)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_ad3f8a35a9b0)
