// releases

MERGE (release_6eb47ad2b355:Release{ uuid: 'a0502705-db18-4fb9-bbcd-6eb47ad2b355' })
SET release_6eb47ad2b355.name = 'Smoke Stack'
SET release_6eb47ad2b355.disambiguation = 'Stereo'
SET release_6eb47ad2b355.country = 'US'
SET release_6eb47ad2b355.date = '1963'
SET release_6eb47ad2b355.format = '12" Vinyl'
SET release_6eb47ad2b355.discode = 'BST 84160'
SET release_6eb47ad2b355.discogs = 'https://www.discogs.com/release/3777991'
SET release_6eb47ad2b355.musicbrainz = 'http://musicbrainz.org/release/a0502705-db18-4fb9-bbcd-6eb47ad2b355'
SET release_6eb47ad2b355.source = 'musicbrainz.org'
SET release_6eb47ad2b355.timestamp = timestamp()

MERGE (person_05d508e09a73:Person{ uuid: 'f0707f1d-55e1-46b6-8a9c-05d508e09a73' }) 
SET person_05d508e09a73.name = 'Rudy van Gelder'
SET person_05d508e09a73.gender = 'Male'
SET person_05d508e09a73.country = 'US'
SET person_05d508e09a73.allmusic = 'https://www.allmusic.com/artist/mn0000305301'
SET person_05d508e09a73.discogs = 'https://www.discogs.com/artist/252966'
SET person_05d508e09a73.viaf = 'http://viaf.org/viaf/33997197'
SET person_05d508e09a73.wikidata = 'https://www.wikidata.org/wiki/Q945681'
SET person_05d508e09a73.databases = ['http://d-nb.info/gnd/133648508', 'http://id.loc.gov/authorities/names/no00020144', 'https://rateyourmusic.com/artist/rudy_van_gelder', 'https://www.worldcat.org/identities/lccn-no00020144']
SET person_05d508e09a73.musicbrainz = 'https://musicbrainz.org/artist/f0707f1d-55e1-46b6-8a9c-05d508e09a73'
SET person_05d508e09a73.isni_list = ['http://isni.org/isni/0000000019691076']
SET person_05d508e09a73.source = 'musicbrainz.org'
SET person_05d508e09a73.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://d-nb.info/gnd/134400623', 'http://id.loc.gov/authorities/names/n81140108', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_dd4a08d1b65d:Person{ uuid: '0d2c9e00-ef4c-4f18-bfcf-dd4a08d1b65d' }) 
SET person_dd4a08d1b65d.name = 'Eddie Khan'
SET person_dd4a08d1b65d.gender = 'Male'
SET person_dd4a08d1b65d.country = 'US'
SET person_dd4a08d1b65d.viaf = 'http://viaf.org/viaf/61735826'
SET person_dd4a08d1b65d.wikidata = 'https://www.wikidata.org/wiki/Q1282861'
SET person_dd4a08d1b65d.databases = ['http://d-nb.info/gnd/134425782', 'http://id.loc.gov/authorities/names/n87818548', 'https://catalogue.bnf.fr/ark:/12148/cb13938438g', 'https://www.worldcat.org/identities/lccn-n87818548']
SET person_dd4a08d1b65d.musicbrainz = 'https://musicbrainz.org/artist/0d2c9e00-ef4c-4f18-bfcf-dd4a08d1b65d'
SET person_dd4a08d1b65d.isni_list = ['http://isni.org/isni/0000000055188005']
SET person_dd4a08d1b65d.source = 'musicbrainz.org'
SET person_dd4a08d1b65d.timestamp = timestamp()

MERGE (person_ff9017878cdd:Person{ uuid: 'b59843a1-bb97-45f0-84b9-ff9017878cdd' }) 
SET person_ff9017878cdd.name = 'Richard Davis'
SET person_ff9017878cdd.gender = 'Male'
SET person_ff9017878cdd.disambiguation = 'American jazz bassist'
SET person_ff9017878cdd.country = 'US'
SET person_ff9017878cdd.allmusic = 'https://www.allmusic.com/artist/mn0000851653'
SET person_ff9017878cdd.discogs = 'https://www.discogs.com/artist/263441'
SET person_ff9017878cdd.viaf = 'http://viaf.org/viaf/120739764'
SET person_ff9017878cdd.wikidata = 'https://www.wikidata.org/wiki/Q716851'
SET person_ff9017878cdd.databases = ['http://d-nb.info/gnd/134355792', 'http://id.loc.gov/authorities/names/n81015291', 'https://catalogue.bnf.fr/ark:/12148/cb13893033h', 'http://snaccooperative.org/ark:/99166/w66d6dj7', 'https://rateyourmusic.com/artist/richard_davis', 'https://www.worldcat.org/identities/lccn-n81015291']
SET person_ff9017878cdd.musicbrainz = 'https://musicbrainz.org/artist/b59843a1-bb97-45f0-84b9-ff9017878cdd'
SET person_ff9017878cdd.isni_list = ['http://isni.org/isni/0000000079564079']
SET person_ff9017878cdd.source = 'musicbrainz.org'
SET person_ff9017878cdd.timestamp = timestamp()

MERGE (person_2584a0b30ec9:Person{ uuid: 'ede80a9f-f114-4041-b0d9-2584a0b30ec9' }) 
SET person_2584a0b30ec9.name = 'Andrew Hill'
SET person_2584a0b30ec9.gender = 'Male'
SET person_2584a0b30ec9.disambiguation = 'jazz pianist'
SET person_2584a0b30ec9.country = 'US'
SET person_2584a0b30ec9.allmusic = 'https://www.allmusic.com/artist/mn0000034617'
SET person_2584a0b30ec9.discogs = 'https://www.discogs.com/artist/61584'
SET person_2584a0b30ec9.viaf = 'http://viaf.org/viaf/22327521'
SET person_2584a0b30ec9.wikidata = 'https://www.wikidata.org/wiki/Q505138'
SET person_2584a0b30ec9.databases = ['http://d-nb.info/gnd/132903911', 'http://id.loc.gov/authorities/names/n81035955', 'https://catalogue.bnf.fr/ark:/12148/cb13895208b', 'http://snaccooperative.org/ark:/99166/w6zw917f', 'https://rateyourmusic.com/artist/andrew_hill', 'https://www.worldcat.org/identities/lccn-n81035955']
SET person_2584a0b30ec9.musicbrainz = 'https://musicbrainz.org/artist/ede80a9f-f114-4041-b0d9-2584a0b30ec9'
SET person_2584a0b30ec9.isni_list = ['http://isni.org/isni/000000012022259X']
SET person_2584a0b30ec9.source = 'musicbrainz.org'
SET person_2584a0b30ec9.timestamp = timestamp()

MERGE (person_317b31f6c035:Person{ uuid: 'c332fcf2-cc5c-424e-a5ea-317b31f6c035' }) 
SET person_317b31f6c035.name = 'Alfred Lion'
SET person_317b31f6c035.gender = 'Male'
SET person_317b31f6c035.country = 'US'
SET person_317b31f6c035.allmusic = 'https://www.allmusic.com/artist/mn0000742011'
SET person_317b31f6c035.discogs = 'https://www.discogs.com/artist/252962'
SET person_317b31f6c035.viaf = 'http://viaf.org/viaf/11504589'
SET person_317b31f6c035.wikidata = 'https://www.wikidata.org/wiki/Q68260'
SET person_317b31f6c035.wikipedia = 'https://en.wikipedia.org/wiki/Alfred_Lion'
SET person_317b31f6c035.databases = ['http://id.loc.gov/authorities/names/n92085849', 'https://d-nb.info/gnd/1068409134', 'http://snaccooperative.org/ark:/99166/w6qv685s', 'https://rateyourmusic.com/artist/alfred_lion', 'https://www.worldcat.org/identities/lccn-n92085849']
SET person_317b31f6c035.musicbrainz = 'https://musicbrainz.org/artist/c332fcf2-cc5c-424e-a5ea-317b31f6c035'
SET person_317b31f6c035.isni_list = ['http://isni.org/isni/000000003027090X']
SET person_317b31f6c035.source = 'musicbrainz.org'
SET person_317b31f6c035.timestamp = timestamp()
// labels

MERGE (label_14e1ddfd5946:Label{ uuid: '713c4a95-6616-442b-9cf6-14e1ddfd5946' })
SET label_14e1ddfd5946.name= 'Blue Note'

// performances

MERGE (perf_da4c12d793af:Performance{ uuid: '7ddb67f8-25fa-4e89-87fa-da4c12d793af' })
SET perf_da4c12d793af.name = 'Smoke Stack'
SET perf_da4c12d793af.duration = '5:00'
SET perf_da4c12d793af.begin = '1963-12-13'
SET perf_da4c12d793af.end = '1963-12-13'
SET perf_da4c12d793af.source = 'musicbrainz.org'
SET perf_da4c12d793af.timestamp = timestamp()

MERGE (perf_c1c573db9b52:Performance{ uuid: '2b870ee6-0b00-40cb-9b25-c1c573db9b52' })
SET perf_c1c573db9b52.name = 'The Day After'
SET perf_c1c573db9b52.duration = '5:09'
SET perf_c1c573db9b52.begin = '1963-12-13'
SET perf_c1c573db9b52.end = '1963-12-13'
SET perf_c1c573db9b52.source = 'musicbrainz.org'
SET perf_c1c573db9b52.timestamp = timestamp()

MERGE (perf_0e606f861d9b:Performance{ uuid: 'aeab1e9f-fd4e-436a-a3de-0e606f861d9b' })
SET perf_0e606f861d9b.name = 'Wailing Wall'
SET perf_0e606f861d9b.duration = '5:47'
SET perf_0e606f861d9b.begin = '1963-12-13'
SET perf_0e606f861d9b.end = '1963-12-13'
SET perf_0e606f861d9b.source = 'musicbrainz.org'
SET perf_0e606f861d9b.timestamp = timestamp()

MERGE (perf_779f7fd982ba:Performance{ uuid: '7b38a985-2f4d-4536-876a-779f7fd982ba' })
SET perf_779f7fd982ba.name = 'Ode to Von'
SET perf_779f7fd982ba.duration = '4:30'
SET perf_779f7fd982ba.begin = '1963-12-13'
SET perf_779f7fd982ba.end = '1963-12-13'
SET perf_779f7fd982ba.source = 'musicbrainz.org'
SET perf_779f7fd982ba.timestamp = timestamp()

MERGE (perf_2d404c6011e6:Performance{ uuid: 'af895eac-dc57-4d72-8232-2d404c6011e6' })
SET perf_2d404c6011e6.name = 'Not So'
SET perf_2d404c6011e6.duration = '6:26'
SET perf_2d404c6011e6.begin = '1963-12-13'
SET perf_2d404c6011e6.end = '1963-12-13'
SET perf_2d404c6011e6.source = 'musicbrainz.org'
SET perf_2d404c6011e6.timestamp = timestamp()

MERGE (perf_c40989517460:Performance{ uuid: '7695e5ed-18c8-4234-9f98-c40989517460' })
SET perf_c40989517460.name = 'Verne'
SET perf_c40989517460.duration = '5:49'
SET perf_c40989517460.begin = '1963-12-13'
SET perf_c40989517460.end = '1963-12-13'
SET perf_c40989517460.source = 'musicbrainz.org'
SET perf_c40989517460.timestamp = timestamp()

MERGE (perf_35f2afe14106:Performance{ uuid: '7e1fb1d2-3cf7-4d42-987d-35f2afe14106' })
SET perf_35f2afe14106.name = '30 Pier Avenue'
SET perf_35f2afe14106.duration = '7:09'
SET perf_35f2afe14106.begin = '1963-12-13'
SET perf_35f2afe14106.end = '1963-12-13'
SET perf_35f2afe14106.source = 'musicbrainz.org'
SET perf_35f2afe14106.timestamp = timestamp()



// labels
MERGE (release_6eb47ad2b355)-[:HAS_LABEL]->(label_14e1ddfd5946)


// tracks
MERGE (release_6eb47ad2b355)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_da4c12d793af)
MERGE (release_6eb47ad2b355)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_c1c573db9b52)
MERGE (release_6eb47ad2b355)-[:HAS_TRACK {name: 'A3', sequence: 3}]->(perf_0e606f861d9b)
MERGE (release_6eb47ad2b355)-[:HAS_TRACK {name: 'A4', sequence: 4}]->(perf_779f7fd982ba)
MERGE (release_6eb47ad2b355)-[:HAS_TRACK {name: 'B1', sequence: 5}]->(perf_2d404c6011e6)
MERGE (release_6eb47ad2b355)-[:HAS_TRACK {name: 'B2', sequence: 6}]->(perf_c40989517460)
MERGE (release_6eb47ad2b355)-[:HAS_TRACK {name: 'B3', sequence: 7}]->(perf_35f2afe14106)

// works

MERGE (work_c986cc80edb0:Work{ uuid: 'b936843b-8bb0-4b96-823a-c986cc80edb0' })
SET work_c986cc80edb0.name = 'Wailing Wall'
SET work_c986cc80edb0.source = 'musicbrainz.org'
SET work_c986cc80edb0.timestamp = timestamp()

MERGE (work_d7bcbece3867:Work{ uuid: '81a78b3e-0888-4d4d-81d3-d7bcbece3867' })
SET work_d7bcbece3867.name = 'Smoke Stack'
SET work_d7bcbece3867.source = 'musicbrainz.org'
SET work_d7bcbece3867.timestamp = timestamp()

MERGE (work_aeb3ddd037b4:Work{ uuid: '21b4de51-7eba-482b-bc72-aeb3ddd037b4' })
SET work_aeb3ddd037b4.name = 'Ode to Von'
SET work_aeb3ddd037b4.source = 'musicbrainz.org'
SET work_aeb3ddd037b4.timestamp = timestamp()

MERGE (work_9e139fed707f:Work{ uuid: '7b8340d2-3e8e-447c-99eb-9e139fed707f' })
SET work_9e139fed707f.name = 'Verne'
SET work_9e139fed707f.source = 'musicbrainz.org'
SET work_9e139fed707f.timestamp = timestamp()

MERGE (work_0c6a7aa7bf1d:Work{ uuid: 'b0d627fd-c293-4287-b188-0c6a7aa7bf1d' })
SET work_0c6a7aa7bf1d.name = '30 Pier Avenue'
SET work_0c6a7aa7bf1d.source = 'musicbrainz.org'
SET work_0c6a7aa7bf1d.timestamp = timestamp()

MERGE (work_badf6d814e42:Work{ uuid: 'a7ff9993-ce83-42d7-a798-badf6d814e42' })
SET work_badf6d814e42.name = 'The Day After'
SET work_badf6d814e42.source = 'musicbrainz.org'
SET work_badf6d814e42.timestamp = timestamp()

MERGE (work_008da336922c:Work{ uuid: '52f63eba-4328-4137-8969-008da336922c' })
SET work_008da336922c.name = 'Not So'
SET work_008da336922c.source = 'musicbrainz.org'
SET work_008da336922c.timestamp = timestamp()


// performances of
MERGE (perf_0e606f861d9b)-[:PERFORMANCE_OF]->(work_c986cc80edb0)
MERGE (perf_da4c12d793af)-[:PERFORMANCE_OF]->(work_d7bcbece3867)
MERGE (perf_779f7fd982ba)-[:PERFORMANCE_OF]->(work_aeb3ddd037b4)
MERGE (perf_c40989517460)-[:PERFORMANCE_OF]->(work_9e139fed707f)
MERGE (perf_35f2afe14106)-[:PERFORMANCE_OF]->(work_0c6a7aa7bf1d)
MERGE (perf_c1c573db9b52)-[:PERFORMANCE_OF]->(work_badf6d814e42)
MERGE (perf_2d404c6011e6)-[:PERFORMANCE_OF]->(work_008da336922c)


// composers
MERGE (person_2584a0b30ec9)-[:COMPOSED]->(work_c986cc80edb0)
MERGE (person_2584a0b30ec9)-[:COMPOSED]->(work_d7bcbece3867)
MERGE (person_2584a0b30ec9)-[:COMPOSED]->(work_aeb3ddd037b4)
MERGE (person_2584a0b30ec9)-[:COMPOSED]->(work_9e139fed707f)
MERGE (person_2584a0b30ec9)-[:COMPOSED]->(work_0c6a7aa7bf1d)
MERGE (person_2584a0b30ec9)-[:COMPOSED]->(work_badf6d814e42)
MERGE (person_2584a0b30ec9)-[:COMPOSED]->(work_008da336922c)


// place nodes

MERGE (place_569fa8b97644:Place{ uuid: '1165ef7d-371c-4e03-98db-569fa8b97644' })
SET place_569fa8b97644.name = 'Van Gelder Studio'
SET place_569fa8b97644.source = 'musicbrainz.org'


// place relationships
MERGE (perf_da4c12d793af)-[:HAS_PLACE { type: 'recorded at', begin: '1963-12-13', end: '1963-12-13' }]->(place_569fa8b97644)
MERGE (perf_c1c573db9b52)-[:HAS_PLACE { type: 'recorded at', begin: '1963-12-13', end: '1963-12-13' }]->(place_569fa8b97644)
MERGE (perf_0e606f861d9b)-[:HAS_PLACE { type: 'recorded at', begin: '1963-12-13', end: '1963-12-13' }]->(place_569fa8b97644)
MERGE (perf_779f7fd982ba)-[:HAS_PLACE { type: 'recorded at', begin: '1963-12-13', end: '1963-12-13' }]->(place_569fa8b97644)
MERGE (perf_2d404c6011e6)-[:HAS_PLACE { type: 'recorded at', begin: '1963-12-13', end: '1963-12-13' }]->(place_569fa8b97644)
MERGE (perf_c40989517460)-[:HAS_PLACE { type: 'recorded at', begin: '1963-12-13', end: '1963-12-13' }]->(place_569fa8b97644)
MERGE (perf_35f2afe14106)-[:HAS_PLACE { type: 'recorded at', begin: '1963-12-13', end: '1963-12-13' }]->(place_569fa8b97644)

MERGE (person_ff9017878cdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_da4c12d793af)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_da4c12d793af)
MERGE (person_2584a0b30ec9)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_da4c12d793af)
MERGE (person_dd4a08d1b65d)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_da4c12d793af)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_da4c12d793af)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_da4c12d793af)
MERGE (person_ff9017878cdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_c1c573db9b52)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_c1c573db9b52)
MERGE (person_2584a0b30ec9)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_c1c573db9b52)
MERGE (person_dd4a08d1b65d)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_c1c573db9b52)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_c1c573db9b52)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_c1c573db9b52)
MERGE (person_ff9017878cdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_0e606f861d9b)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_0e606f861d9b)
MERGE (person_2584a0b30ec9)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_0e606f861d9b)
MERGE (person_dd4a08d1b65d)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_0e606f861d9b)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_0e606f861d9b)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_0e606f861d9b)
MERGE (person_ff9017878cdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_779f7fd982ba)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_779f7fd982ba)
MERGE (person_2584a0b30ec9)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_779f7fd982ba)
MERGE (person_dd4a08d1b65d)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_779f7fd982ba)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_779f7fd982ba)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_779f7fd982ba)
MERGE (person_ff9017878cdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_2d404c6011e6)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_2d404c6011e6)
MERGE (person_2584a0b30ec9)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_2d404c6011e6)
MERGE (person_dd4a08d1b65d)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_2d404c6011e6)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_2d404c6011e6)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_2d404c6011e6)
MERGE (person_ff9017878cdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_c40989517460)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_c40989517460)
MERGE (person_2584a0b30ec9)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_c40989517460)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_c40989517460)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_c40989517460)
MERGE (person_ff9017878cdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_35f2afe14106)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_35f2afe14106)
MERGE (person_2584a0b30ec9)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_35f2afe14106)
MERGE (person_dd4a08d1b65d)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_35f2afe14106)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_35f2afe14106)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_35f2afe14106)

