// releases

MERGE (release_e4c73aaabe26:Release{ uuid: '3304bb70-c44f-44ed-a14b-e4c73aaabe26' })
SET release_e4c73aaabe26.name = 'Introducing Triveni'
SET release_e4c73aaabe26.country = 'XW'
SET release_e4c73aaabe26.date = '2010-09-28'
SET release_e4c73aaabe26.format = 'Digital Media'
SET release_e4c73aaabe26.musicbrainz = 'http://musicbrainz.org/release/3304bb70-c44f-44ed-a14b-e4c73aaabe26'
SET release_e4c73aaabe26.source = 'musicbrainz.org'
SET release_e4c73aaabe26.timestamp = timestamp()

MERGE (person_6d0bc0ca74fd:Person{ uuid: '850dba82-4abb-44d0-b498-6d0bc0ca74fd' }) 
SET person_6d0bc0ca74fd.name = 'Joe Marciano'
SET person_6d0bc0ca74fd.gender = 'Male'
SET person_6d0bc0ca74fd.country = 'US'
SET person_6d0bc0ca74fd.allmusic = 'https://www.allmusic.com/artist/mn0000142806'
SET person_6d0bc0ca74fd.discogs = 'https://www.discogs.com/artist/327388'
SET person_6d0bc0ca74fd.databases = ['https://rateyourmusic.com/artist/joe_marciano']
SET person_6d0bc0ca74fd.musicbrainz = 'https://musicbrainz.org/artist/850dba82-4abb-44d0-b498-6d0bc0ca74fd'
SET person_6d0bc0ca74fd.source = 'musicbrainz.org'
SET person_6d0bc0ca74fd.timestamp = timestamp()

MERGE (person_a859ee576d78:Person{ uuid: 'ea75d592-70c1-4d08-a0b5-a859ee576d78' }) 
SET person_a859ee576d78.name = 'Omer Avital'
SET person_a859ee576d78.gender = 'Male'
SET person_a859ee576d78.country = 'US'
SET person_a859ee576d78.allmusic = 'https://www.allmusic.com/artist/mn0000472075'
SET person_a859ee576d78.discogs = 'https://www.discogs.com/artist/346612'
SET person_a859ee576d78.viaf = 'http://viaf.org/viaf/31793110'
SET person_a859ee576d78.wikidata = 'https://www.wikidata.org/wiki/Q2023299'
SET person_a859ee576d78.wikipedia = 'https://en.wikipedia.org/wiki/Omer_Avital'
SET person_a859ee576d78.databases = ['http://id.loc.gov/authorities/names/no2007156778', 'https://catalogue.bnf.fr/ark:/12148/cb141515952', 'https://d-nb.info/gnd/134849485', 'https://rateyourmusic.com/artist/omer-avital', 'https://www.worldcat.org/identities/lccn-no2007156778']
SET person_a859ee576d78.musicbrainz = 'https://musicbrainz.org/artist/ea75d592-70c1-4d08-a0b5-a859ee576d78'
SET person_a859ee576d78.isni_list = ['http://isni.org/isni/0000000055515360']
SET person_a859ee576d78.source = 'musicbrainz.org'
SET person_a859ee576d78.timestamp = timestamp()

MERGE (person_647ab35db025:Person{ uuid: '07a64c0f-3e77-4d2f-8324-647ab35db025' }) 
SET person_647ab35db025.name = 'Max Ross'
SET person_647ab35db025.gender = 'Male'
SET person_647ab35db025.disambiguation = 'engineer'
SET person_647ab35db025.country = 'US'
SET person_647ab35db025.allmusic = 'https://www.allmusic.com/artist/mn0000535902'
SET person_647ab35db025.discogs = 'https://www.discogs.com/artist/723914'
SET person_647ab35db025.databases = ['https://rateyourmusic.com/artist/max_ross']
SET person_647ab35db025.musicbrainz = 'https://musicbrainz.org/artist/07a64c0f-3e77-4d2f-8324-647ab35db025'
SET person_647ab35db025.source = 'musicbrainz.org'
SET person_647ab35db025.timestamp = timestamp()

MERGE (person_cf15b8735268:Person{ uuid: 'ab3363db-53ac-44c1-abfe-cf15b8735268' }) 
SET person_cf15b8735268.name = 'Nasheet Waits'
SET person_cf15b8735268.gender = 'Male'
SET person_cf15b8735268.country = 'US'
SET person_cf15b8735268.allmusic = 'https://www.allmusic.com/artist/mn0000315826'
SET person_cf15b8735268.discogs = 'https://www.discogs.com/artist/334551'
SET person_cf15b8735268.viaf = 'http://viaf.org/viaf/37128340'
SET person_cf15b8735268.wikidata = 'https://www.wikidata.org/wiki/Q1965729'
SET person_cf15b8735268.databases = ['http://id.loc.gov/authorities/names/no2001000847', 'https://catalogue.bnf.fr/ark:/12148/cb142374501', 'https://d-nb.info/gnd/135043077', 'https://www.worldcat.org/identities/lccn-no2001000847']
SET person_cf15b8735268.musicbrainz = 'https://musicbrainz.org/artist/ab3363db-53ac-44c1-abfe-cf15b8735268'
SET person_cf15b8735268.isni_list = ['http://isni.org/isni/0000000055174105']
SET person_cf15b8735268.source = 'musicbrainz.org'
SET person_cf15b8735268.timestamp = timestamp()

MERGE (person_3623e66f6e76:Person{ uuid: 'a9adebe6-3436-4746-bc76-3623e66f6e76' }) 
SET person_3623e66f6e76.name = 'Avishai Cohen'
SET person_3623e66f6e76.gender = 'Male'
SET person_3623e66f6e76.disambiguation = 'trumpeter, member of Third World Love'
SET person_3623e66f6e76.allmusic = 'https://www.allmusic.com/artist/mn0001875710'
SET person_3623e66f6e76.discogs = 'https://www.discogs.com/artist/542342'
SET person_3623e66f6e76.viaf = 'http://viaf.org/viaf/171046587'
SET person_3623e66f6e76.wikidata = 'https://www.wikidata.org/wiki/Q2898115'
SET person_3623e66f6e76.databases = ['http://id.loc.gov/authorities/names/no2003113585', 'https://catalogue.bnf.fr/ark:/12148/cb16508540d', 'https://d-nb.info/gnd/1093853263', 'https://www.worldcat.org/identities/lccn-no2003113585']
SET person_3623e66f6e76.musicbrainz = 'https://musicbrainz.org/artist/a9adebe6-3436-4746-bc76-3623e66f6e76'
SET person_3623e66f6e76.isni_list = ['http://isni.org/isni/0000000120013050']
SET person_3623e66f6e76.source = 'musicbrainz.org'
SET person_3623e66f6e76.timestamp = timestamp()

MERGE (person_a2441632d24d:Person{ uuid: '7e97fc0c-48a6-4295-b334-a2441632d24d' }) 
SET person_a2441632d24d.name = 'Brian Montgomery'
SET person_a2441632d24d.country = 'US'
SET person_a2441632d24d.discogs = 'https://www.discogs.com/artist/376982'
SET person_a2441632d24d.musicbrainz = 'https://musicbrainz.org/artist/7e97fc0c-48a6-4295-b334-a2441632d24d'
SET person_a2441632d24d.source = 'musicbrainz.org'
SET person_a2441632d24d.timestamp = timestamp()
// labels

MERGE (label_b46f44fa0909:Label{ uuid: '081f9f5d-27a0-4115-b70e-b46f44fa0909' })
SET label_b46f44fa0909.name= 'Anzic Records'

// performances

MERGE (perf_98a7773d4c0e:Performance{ uuid: '5dd09f22-84c0-4802-82e0-98a7773d4c0e' })
SET perf_98a7773d4c0e.name = 'One Man\'s Idea'
SET perf_98a7773d4c0e.duration = '3:46'
SET perf_98a7773d4c0e.begin = '2010-12-17'
SET perf_98a7773d4c0e.end = '2010-12-18'
SET perf_98a7773d4c0e.source = 'musicbrainz.org'
SET perf_98a7773d4c0e.timestamp = timestamp()

MERGE (perf_d00ea12b5fe1:Performance{ uuid: 'a4eff97b-3c00-483f-b95b-d00ea12b5fe1' })
SET perf_d00ea12b5fe1.name = 'Ferrara Napoly'
SET perf_d00ea12b5fe1.duration = '12:42'
SET perf_d00ea12b5fe1.begin = '2010-12-17'
SET perf_d00ea12b5fe1.end = '2010-12-18'
SET perf_d00ea12b5fe1.source = 'musicbrainz.org'
SET perf_d00ea12b5fe1.timestamp = timestamp()

MERGE (perf_43bd315220b4:Performance{ uuid: '9401b7eb-0b49-4ada-9ff6-43bd315220b4' })
SET perf_43bd315220b4.name = 'Art Deco'
SET perf_43bd315220b4.duration = '7:17'
SET perf_43bd315220b4.begin = '2010-12-17'
SET perf_43bd315220b4.end = '2010-12-18'
SET perf_43bd315220b4.source = 'musicbrainz.org'
SET perf_43bd315220b4.timestamp = timestamp()

MERGE (perf_c9de6538899e:Performance{ uuid: '0196557f-2790-45a2-88ba-c9de6538899e' })
SET perf_c9de6538899e.name = 'Mood Indigo'
SET perf_c9de6538899e.duration = '5:03'
SET perf_c9de6538899e.begin = '2010-12-17'
SET perf_c9de6538899e.end = '2010-12-18'
SET perf_c9de6538899e.source = 'musicbrainz.org'
SET perf_c9de6538899e.timestamp = timestamp()

MERGE (perf_61e28012362d:Performance{ uuid: 'fcd95509-ab5d-41ef-9c18-61e28012362d' })
SET perf_61e28012362d.name = 'Wise One'
SET perf_61e28012362d.duration = '11:47'
SET perf_61e28012362d.begin = '2010-12-17'
SET perf_61e28012362d.end = '2010-12-18'
SET perf_61e28012362d.source = 'musicbrainz.org'
SET perf_61e28012362d.timestamp = timestamp()

MERGE (perf_cbb7484f07f9:Performance{ uuid: '96211650-78bd-4cac-8e7e-cbb7484f07f9' })
SET perf_cbb7484f07f9.name = 'Amenu'
SET perf_cbb7484f07f9.duration = '4:26'
SET perf_cbb7484f07f9.begin = '2010-12-17'
SET perf_cbb7484f07f9.end = '2010-12-18'
SET perf_cbb7484f07f9.source = 'musicbrainz.org'
SET perf_cbb7484f07f9.timestamp = timestamp()

MERGE (perf_c362458aac94:Performance{ uuid: '4f12536d-70c6-4f9f-b1a0-c362458aac94' })
SET perf_c362458aac94.name = 'You\'d Be So Nice to Come Home To'
SET perf_c362458aac94.duration = '5:31'
SET perf_c362458aac94.begin = '2010-12-17'
SET perf_c362458aac94.end = '2010-12-18'
SET perf_c362458aac94.source = 'musicbrainz.org'
SET perf_c362458aac94.timestamp = timestamp()

MERGE (perf_b381da23e1c1:Performance{ uuid: 'f2fd2d67-42e0-446c-9666-b381da23e1c1' })
SET perf_b381da23e1c1.name = 'October 25th'
SET perf_b381da23e1c1.duration = '6:46'
SET perf_b381da23e1c1.begin = '2010-12-17'
SET perf_b381da23e1c1.end = '2010-12-18'
SET perf_b381da23e1c1.source = 'musicbrainz.org'
SET perf_b381da23e1c1.timestamp = timestamp()



// labels
MERGE (release_e4c73aaabe26)-[:HAS_LABEL]->(label_b46f44fa0909)


// tracks
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_98a7773d4c0e)
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_d00ea12b5fe1)
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_43bd315220b4)
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_c9de6538899e)
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_61e28012362d)
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_cbb7484f07f9)
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '7', sequence: 7}]->(perf_c362458aac94)
MERGE (release_e4c73aaabe26)-[:HAS_TRACK {name: '8', sequence: 8}]->(perf_b381da23e1c1)

// works

MERGE (person_861a7a3e3abe:Person{ uuid: 'adf3879a-e091-4f73-8792-861a7a3e3abe' }) 
SET person_861a7a3e3abe.name = 'Don Cherry'
SET person_861a7a3e3abe.gender = 'Male'
SET person_861a7a3e3abe.disambiguation = 'jazz trumpeter'
SET person_861a7a3e3abe.country = 'US'
SET person_861a7a3e3abe.allmusic = 'https://www.allmusic.com/artist/mn0000796166'
SET person_861a7a3e3abe.discogs = 'https://www.discogs.com/artist/42757'
SET person_861a7a3e3abe.imdb = 'https://www.imdb.com/name/nm0156066/'
SET person_861a7a3e3abe.viaf = 'http://viaf.org/viaf/64191256'
SET person_861a7a3e3abe.wikidata = 'https://www.wikidata.org/wiki/Q456180'
SET person_861a7a3e3abe.databases = ['http://id.loc.gov/authorities/names/n82132925', 'https://catalogue.bnf.fr/ark:/12148/cb138924441', 'https://d-nb.info/gnd/138213143', 'https://rateyourmusic.com/artist/don_cherry', 'https://www.musik-sammler.de/artist/don-cherry/', 'https://www.worldcat.org/identities/lccn-n82132925']
SET person_861a7a3e3abe.musicbrainz = 'https://musicbrainz.org/artist/adf3879a-e091-4f73-8792-861a7a3e3abe'
SET person_861a7a3e3abe.isni_list = ['http://isni.org/isni/0000000110677283']
SET person_861a7a3e3abe.source = 'musicbrainz.org'
SET person_861a7a3e3abe.timestamp = timestamp()

MERGE (person_72ad46cdb831:Person{ uuid: 'b625448e-bf4a-41c3-a421-72ad46cdb831' }) 
SET person_72ad46cdb831.name = 'John Coltrane'
SET person_72ad46cdb831.gender = 'Male'
SET person_72ad46cdb831.country = 'US'
SET person_72ad46cdb831.allmusic = 'https://www.allmusic.com/artist/mn0000175553'
SET person_72ad46cdb831.bbc = 'https://www.bbc.co.uk/music/artists/b625448e-bf4a-41c3-a421-72ad46cdb831'
SET person_72ad46cdb831.discogs = 'https://www.discogs.com/artist/97545'
SET person_72ad46cdb831.imdb = 'https://www.imdb.com/name/nm0173328/'
SET person_72ad46cdb831.viaf = 'http://viaf.org/viaf/61731379'
SET person_72ad46cdb831.wikidata = 'https://www.wikidata.org/wiki/Q7346'
SET person_72ad46cdb831.databases = ['http://id.loc.gov/authorities/names/n50031907', 'https://adp.library.ucsb.edu/names/309224', 'https://catalogue.bnf.fr/ark:/12148/cb138926615', 'https://d-nb.info/gnd/118521667', 'https://ibdb.com/person.php?id=485239', 'http://snaccooperative.org/ark:/99166/w6x92hns', 'https://nla.gov.au/nla.party-1006213', 'https://openlibrary.org/works/OL7513936A', 'https://rateyourmusic.com/artist/john_coltrane', 'https://www.45cat.com/artist/john-coltrane', 'https://www.45worlds.com/cdalbum/artist/john-coltrane', 'https://www.45worlds.com/tape/artist/john-coltrane', 'https://www.45worlds.com/vinyl/artist/john-coltrane', 'https://www.musik-sammler.de/artist/john-coltrane/', 'https://www.whosampled.com/John-Coltrane/', 'https://www.worldcat.org/identities/lccn-n50-031907']
SET person_72ad46cdb831.musicbrainz = 'https://musicbrainz.org/artist/b625448e-bf4a-41c3-a421-72ad46cdb831'
SET person_72ad46cdb831.isni_list = ['http://isni.org/isni/000000012280792X']
SET person_72ad46cdb831.source = 'musicbrainz.org'
SET person_72ad46cdb831.timestamp = timestamp()

MERGE (person_a37897b950ce:Person{ uuid: '4a94a6cb-e70a-418b-bb53-a37897b950ce' }) 
SET person_a37897b950ce.name = 'Cole Porter'
SET person_a37897b950ce.gender = 'Male'
SET person_a37897b950ce.disambiguation = 'composer'
SET person_a37897b950ce.country = 'US'
SET person_a37897b950ce.allmusic = 'https://www.allmusic.com/artist/mn0000109607'
SET person_a37897b950ce.discogs = 'https://www.discogs.com/artist/264026'
SET person_a37897b950ce.imdb = 'https://www.imdb.com/name/nm0006234/'
SET person_a37897b950ce.viaf = 'http://viaf.org/viaf/5118684'
SET person_a37897b950ce.wikidata = 'https://www.wikidata.org/wiki/Q215120'
SET person_a37897b950ce.databases = ['http://id.loc.gov/authorities/names/n80017862', 'https://adp.library.ucsb.edu/names/102688', 'https://catalogue.bnf.fr/ark:/12148/cb13898618g', 'https://d-nb.info/gnd/11879292X', 'https://ibdb.com/person.php?id=12257', 'http://snaccooperative.org/ark:/99166/w6j38s5m', 'https://nla.gov.au/nla.party-949524', 'https://openlibrary.org/works/OL709416A', 'http://soundtrackcollector.com/composer/166/', 'https://rateyourmusic.com/artist/cole_porter', 'https://www.worldcat.org/identities/lccn-n80017862', 'http://www.lortel.org/LLA_archive/index.cfm?search_by=people&first=Cole&last=Porter&middle=']
SET person_a37897b950ce.musicbrainz = 'https://musicbrainz.org/artist/4a94a6cb-e70a-418b-bb53-a37897b950ce'
SET person_a37897b950ce.isni_list = ['http://isni.org/isni/0000000108653610']
SET person_a37897b950ce.source = 'musicbrainz.org'
SET person_a37897b950ce.timestamp = timestamp()

MERGE (work_0ae1351b5707:Work{ uuid: '63c27e4a-731b-36b9-ae84-0ae1351b5707' })
SET work_0ae1351b5707.name = 'Wise One'
SET work_0ae1351b5707.iswc = 'T-700.081.288-6'
SET work_0ae1351b5707.type = 'Song'
SET work_0ae1351b5707.allmusic = 'https://www.allmusic.com/song/mt0029113572'
SET work_0ae1351b5707.wikidata = 'https://www.wikidata.org/wiki/Q65153274'
SET work_0ae1351b5707.musicbrainz = 'https://musicbrainz.org/work/63c27e4a-731b-36b9-ae84-0ae1351b5707'
SET work_0ae1351b5707.source = 'musicbrainz.org'
SET work_0ae1351b5707.timestamp = timestamp()

MERGE (work_4b26dd08034e:Work{ uuid: 'e600976f-dea0-49a7-8167-4b26dd08034e' })
SET work_4b26dd08034e.name = 'Art Deco'
SET work_4b26dd08034e.iswc = 'T-070.225.536-4'
SET work_4b26dd08034e.type = 'Song'
SET work_4b26dd08034e.source = 'musicbrainz.org'
SET work_4b26dd08034e.timestamp = timestamp()

MERGE (work_6126d682fab2:Work{ uuid: 'dca3d1eb-0365-37fd-97de-6126d682fab2' })
SET work_6126d682fab2.name = 'You’d Be So Nice to Come Home To'
SET work_6126d682fab2.iswc = 'T-070.211.122-5'
SET work_6126d682fab2.type = 'Song'
SET work_6126d682fab2.wikidata = 'https://www.wikidata.org/wiki/Q2601445'
SET work_6126d682fab2.wikipedia = 'https://en.wikipedia.org/wiki/You%27d_Be_So_Nice_to_Come_Home_To'
SET work_6126d682fab2.musicbrainz = 'https://musicbrainz.org/work/dca3d1eb-0365-37fd-97de-6126d682fab2'
SET work_6126d682fab2.source = 'musicbrainz.org'
SET work_6126d682fab2.timestamp = timestamp()


// performances of
MERGE (perf_61e28012362d)-[:PERFORMANCE_OF]->(work_0ae1351b5707)
MERGE (perf_43bd315220b4)-[:PERFORMANCE_OF]->(work_4b26dd08034e)
MERGE (perf_c362458aac94)-[:PERFORMANCE_OF]->(work_6126d682fab2)


// composers
MERGE (person_72ad46cdb831)-[:COMPOSED]->(work_0ae1351b5707)
MERGE (person_861a7a3e3abe)-[:COMPOSED]->(work_4b26dd08034e)
MERGE (person_861a7a3e3abe)-[:WROTE_LYRICS]->(work_4b26dd08034e)
MERGE (person_a37897b950ce)-[:COMPOSED]->(work_6126d682fab2)
MERGE (person_a37897b950ce)-[:WROTE_LYRICS]->(work_6126d682fab2)


// place nodes

MERGE (place_70b236d3aa47:Place{ uuid: 'f1526c4b-b38e-42e5-897e-70b236d3aa47' })
SET place_70b236d3aa47.name = 'Systems Two Recording Studio'
SET place_70b236d3aa47.source = 'musicbrainz.org'


// place relationships
MERGE (perf_98a7773d4c0e)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)
MERGE (perf_d00ea12b5fe1)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)
MERGE (perf_43bd315220b4)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)
MERGE (perf_c9de6538899e)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)
MERGE (perf_61e28012362d)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)
MERGE (perf_cbb7484f07f9)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)
MERGE (perf_c362458aac94)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)
MERGE (perf_b381da23e1c1)-[:HAS_PLACE { type: 'recorded at', begin: '2010-12-17', end: '2010-12-18' }]->(place_70b236d3aa47)

MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_98a7773d4c0e)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_98a7773d4c0e)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_98a7773d4c0e)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_98a7773d4c0e)
MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_d00ea12b5fe1)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_d00ea12b5fe1)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_d00ea12b5fe1)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_d00ea12b5fe1)
MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_43bd315220b4)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_43bd315220b4)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_43bd315220b4)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_43bd315220b4)
MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_c9de6538899e)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_c9de6538899e)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_c9de6538899e)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_c9de6538899e)
MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_61e28012362d)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_61e28012362d)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_61e28012362d)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_61e28012362d)
MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_cbb7484f07f9)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_cbb7484f07f9)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_cbb7484f07f9)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_cbb7484f07f9)
MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_c362458aac94)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_c362458aac94)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_c362458aac94)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_c362458aac94)
MERGE (person_a859ee576d78)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_b381da23e1c1)
MERGE (person_3623e66f6e76)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['trumpet'] }]->(perf_b381da23e1c1)
MERGE (person_cf15b8735268)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['membranophone'] }]->(perf_b381da23e1c1)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_b381da23e1c1)

