// releases

MERGE (release_0ea24e1b43d1:Release{ uuid: 'b984eb0d-1474-47bb-8d63-0ea24e1b43d1' })
SET release_0ea24e1b43d1.name = 'Stick-Up!'
SET release_0ea24e1b43d1.disambiguation = 'Blue Note Connoisseur Series'
SET release_0ea24e1b43d1.country = 'US'
SET release_0ea24e1b43d1.date = '1997'
SET release_0ea24e1b43d1.format = 'CD'
SET release_0ea24e1b43d1.discode = 'CDP 724385937828'
SET release_0ea24e1b43d1.discogs = 'https://www.discogs.com/release/1830657'
SET release_0ea24e1b43d1.musicbrainz = 'http://musicbrainz.org/release/b984eb0d-1474-47bb-8d63-0ea24e1b43d1'
SET release_0ea24e1b43d1.source = 'musicbrainz.org'
SET release_0ea24e1b43d1.timestamp = timestamp()

MERGE (person_3479a48a0eea:Person{ uuid: '9ad42bd8-bf7e-4a8e-af90-3479a48a0eea' }) 
SET person_3479a48a0eea.name = 'Herbie Lewis'
SET person_3479a48a0eea.gender = 'Male'
SET person_3479a48a0eea.country = 'US'
SET person_3479a48a0eea.allmusic = 'https://www.allmusic.com/artist/mn0000957338'
SET person_3479a48a0eea.discogs = 'https://www.discogs.com/artist/315947'
SET person_3479a48a0eea.viaf = 'http://viaf.org/viaf/100314225'
SET person_3479a48a0eea.wikidata = 'https://www.wikidata.org/wiki/Q1609414'
SET person_3479a48a0eea.wikipedia = 'https://en.wikipedia.org/wiki/Herbie_Lewis'
SET person_3479a48a0eea.databases = ['http://d-nb.info/gnd/134444337', 'http://id.loc.gov/authorities/names/n88630869', 'https://catalogue.bnf.fr/ark:/12148/cb13896621w', 'https://www.worldcat.org/identities/lccn-n88630869']
SET person_3479a48a0eea.musicbrainz = 'https://musicbrainz.org/artist/9ad42bd8-bf7e-4a8e-af90-3479a48a0eea'
SET person_3479a48a0eea.isni_list = ['http://isni.org/isni/0000000071450819']
SET person_3479a48a0eea.source = 'musicbrainz.org'
SET person_3479a48a0eea.timestamp = timestamp()

MERGE (person_317b31f6c035:Person{ uuid: 'c332fcf2-cc5c-424e-a5ea-317b31f6c035' }) 
SET person_317b31f6c035.name = 'Alfred Lion'
SET person_317b31f6c035.gender = 'Male'
SET person_317b31f6c035.country = 'US'
SET person_317b31f6c035.allmusic = 'https://www.allmusic.com/artist/mn0000742011'
SET person_317b31f6c035.discogs = 'https://www.discogs.com/artist/252962'
SET person_317b31f6c035.viaf = 'http://viaf.org/viaf/11504589'
SET person_317b31f6c035.wikidata = 'https://www.wikidata.org/wiki/Q68260'
SET person_317b31f6c035.wikipedia = 'https://en.wikipedia.org/wiki/Alfred_Lion'
SET person_317b31f6c035.databases = ['http://d-nb.info/gnd/1068409134', 'http://id.loc.gov/authorities/names/n92085849', 'http://snaccooperative.org/ark:/99166/w6qv685s', 'https://rateyourmusic.com/artist/alfred_lion', 'https://www.worldcat.org/identities/lccn-n92085849']
SET person_317b31f6c035.musicbrainz = 'https://musicbrainz.org/artist/c332fcf2-cc5c-424e-a5ea-317b31f6c035'
SET person_317b31f6c035.isni_list = ['http://isni.org/isni/000000003027090X']
SET person_317b31f6c035.source = 'musicbrainz.org'
SET person_317b31f6c035.timestamp = timestamp()

MERGE (person_9ee947b4ce37:Person{ uuid: 'bcab8301-c7e5-4689-a4ad-9ee947b4ce37' }) 
SET person_9ee947b4ce37.name = 'Joe Henderson'
SET person_9ee947b4ce37.gender = 'Male'
SET person_9ee947b4ce37.disambiguation = 'US jazz tenor saxophonist'
SET person_9ee947b4ce37.country = 'US'
SET person_9ee947b4ce37.allmusic = 'https://www.allmusic.com/artist/mn0000139804'
SET person_9ee947b4ce37.allmusic = 'https://www.allmusic.com/artist/mn0002687715'
SET person_9ee947b4ce37.discogs = 'https://www.discogs.com/artist/10079'
SET person_9ee947b4ce37.viaf = 'http://viaf.org/viaf/115064662'
SET person_9ee947b4ce37.wikidata = 'https://www.wikidata.org/wiki/Q506006'
SET person_9ee947b4ce37.databases = ['http://d-nb.info/gnd/131961454', 'http://id.loc.gov/authorities/names/n82164702', 'https://catalogue.bnf.fr/ark:/12148/cb138951291', 'http://snaccooperative.org/ark:/99166/w6hm8fsd', 'https://nla.gov.au/nla.party-1048452', 'https://openlibrary.org/works/OL5629680A', 'https://rateyourmusic.com/artist/joe_henderson', 'https://www.worldcat.org/identities/lccn-n82164702']
SET person_9ee947b4ce37.musicbrainz = 'https://musicbrainz.org/artist/bcab8301-c7e5-4689-a4ad-9ee947b4ce37'
SET person_9ee947b4ce37.isni_list = ['http://isni.org/isni/0000000081835181']
SET person_9ee947b4ce37.source = 'musicbrainz.org'
SET person_9ee947b4ce37.timestamp = timestamp()

MERGE (person_8fe19080caaf:Person{ uuid: 'edbe5d7f-9511-4dfe-847a-8fe19080caaf' }) 
SET person_8fe19080caaf.name = 'Bobby Hutcherson'
SET person_8fe19080caaf.gender = 'Male'
SET person_8fe19080caaf.country = 'US'
SET person_8fe19080caaf.allmusic = 'https://www.allmusic.com/artist/mn0000081231'
SET person_8fe19080caaf.discogs = 'https://www.discogs.com/artist/29968'
SET person_8fe19080caaf.imdb = 'https://www.imdb.com/name/nm0404201/'
SET person_8fe19080caaf.viaf = 'http://viaf.org/viaf/85517308'
SET person_8fe19080caaf.wikidata = 'https://www.wikidata.org/wiki/Q888571'
SET person_8fe19080caaf.databases = ['http://d-nb.info/gnd/134413393', 'http://id.loc.gov/authorities/names/n81149294', 'https://catalogue.bnf.fr/ark:/12148/cb13895429v', 'https://rateyourmusic.com/artist/bobby_hutcherson', 'https://www.musik-sammler.de/artist/bobby-hutcherson/', 'https://www.worldcat.org/identities/lccn-n81-149294']
SET person_8fe19080caaf.musicbrainz = 'https://musicbrainz.org/artist/edbe5d7f-9511-4dfe-847a-8fe19080caaf'
SET person_8fe19080caaf.isni_list = ['http://isni.org/isni/0000000114505729']
SET person_8fe19080caaf.source = 'musicbrainz.org'
SET person_8fe19080caaf.timestamp = timestamp()

MERGE (person_05d508e09a73:Person{ uuid: 'f0707f1d-55e1-46b6-8a9c-05d508e09a73' }) 
SET person_05d508e09a73.name = 'Rudy van Gelder'
SET person_05d508e09a73.gender = 'Male'
SET person_05d508e09a73.country = 'US'
SET person_05d508e09a73.allmusic = 'https://www.allmusic.com/artist/mn0000305301'
SET person_05d508e09a73.discogs = 'https://www.discogs.com/artist/252966'
SET person_05d508e09a73.viaf = 'http://viaf.org/viaf/33997197'
SET person_05d508e09a73.wikidata = 'https://www.wikidata.org/wiki/Q945681'
SET person_05d508e09a73.databases = ['http://d-nb.info/gnd/133648508', 'http://id.loc.gov/authorities/names/no00020144', 'https://rateyourmusic.com/artist/rudy_van_gelder', 'https://www.worldcat.org/identities/lccn-no00020144']
SET person_05d508e09a73.musicbrainz = 'https://musicbrainz.org/artist/f0707f1d-55e1-46b6-8a9c-05d508e09a73'
SET person_05d508e09a73.isni_list = ['http://isni.org/isni/0000000019691076']
SET person_05d508e09a73.source = 'musicbrainz.org'
SET person_05d508e09a73.timestamp = timestamp()

MERGE (person_8971e7a2912e:Person{ uuid: '22fe7b6f-af38-458e-87bd-8971e7a2912e' }) 
SET person_8971e7a2912e.name = 'McCoy Tyner'
SET person_8971e7a2912e.gender = 'Male'
SET person_8971e7a2912e.disambiguation = 'jazz pianist'
SET person_8971e7a2912e.country = 'US'
SET person_8971e7a2912e.allmusic = 'https://www.allmusic.com/artist/mn0000868092'
SET person_8971e7a2912e.bbc = 'https://www.bbc.co.uk/music/artists/22fe7b6f-af38-458e-87bd-8971e7a2912e'
SET person_8971e7a2912e.discogs = 'https://www.discogs.com/artist/10620'
SET person_8971e7a2912e.imdb = 'https://www.imdb.com/name/nm1743784/'
SET person_8971e7a2912e.viaf = 'http://viaf.org/viaf/84970893'
SET person_8971e7a2912e.wikidata = 'https://www.wikidata.org/wiki/Q318619'
SET person_8971e7a2912e.databases = ['http://d-nb.info/gnd/134543734', 'http://id.loc.gov/authorities/names/n81058256', 'https://catalogue.bnf.fr/ark:/12148/cb139006254', 'http://snaccooperative.org/ark:/99166/w6183cz4', 'https://www.worldcat.org/identities/lccn-n81-058256']
SET person_8971e7a2912e.musicbrainz = 'https://musicbrainz.org/artist/22fe7b6f-af38-458e-87bd-8971e7a2912e'
SET person_8971e7a2912e.isni_list = ['http://isni.org/isni/0000000120184511']
SET person_8971e7a2912e.source = 'musicbrainz.org'
SET person_8971e7a2912e.timestamp = timestamp()

MERGE (person_23e60ffced44:Person{ uuid: '53019232-166e-4788-8b13-23e60ffced44' }) 
SET person_23e60ffced44.name = 'Billy Higgins'
SET person_23e60ffced44.gender = 'Male'
SET person_23e60ffced44.disambiguation = 'US jazz drummer'
SET person_23e60ffced44.country = 'US'
SET person_23e60ffced44.allmusic = 'https://www.allmusic.com/artist/mn0000070507'
SET person_23e60ffced44.discogs = 'https://www.discogs.com/artist/135871'
SET person_23e60ffced44.viaf = 'http://viaf.org/viaf/7574166'
SET person_23e60ffced44.wikidata = 'https://www.wikidata.org/wiki/Q324522'
SET person_23e60ffced44.databases = ['http://d-nb.info/gnd/134405862', 'http://id.loc.gov/authorities/names/n83196051', 'https://catalogue.bnf.fr/ark:/12148/cb138951996', 'http://snaccooperative.org/ark:/99166/w6h7455q', 'https://rateyourmusic.com/artist/billy_higgins', 'https://www.worldcat.org/identities/lccn-n83196051']
SET person_23e60ffced44.musicbrainz = 'https://musicbrainz.org/artist/53019232-166e-4788-8b13-23e60ffced44'
SET person_23e60ffced44.isni_list = ['http://isni.org/isni/0000000120204180']
SET person_23e60ffced44.source = 'musicbrainz.org'
SET person_23e60ffced44.timestamp = timestamp()
// labels

MERGE (label_14e1ddfd5946:Label{ uuid: '713c4a95-6616-442b-9cf6-14e1ddfd5946' })
SET label_14e1ddfd5946.name= 'Blue Note'

// performances

MERGE (perf_d98eca990a3e:Performance{ uuid: '975d401f-dd7e-4102-8db6-d98eca990a3e' })
SET perf_d98eca990a3e.name = 'Una Muy Bonita'
SET perf_d98eca990a3e.duration = '6:27'
SET perf_d98eca990a3e.begin = '1966-07-14'
SET perf_d98eca990a3e.end = '1966-07-14'
SET perf_d98eca990a3e.source = 'musicbrainz.org'
SET perf_d98eca990a3e.timestamp = timestamp()

MERGE (perf_e8271a78e484:Performance{ uuid: 'd0c30a2c-1277-4610-bfc1-e8271a78e484' })
SET perf_e8271a78e484.name = '8/4 Beat'
SET perf_e8271a78e484.duration = '6:57'
SET perf_e8271a78e484.begin = '1966-07-14'
SET perf_e8271a78e484.end = '1966-07-14'
SET perf_e8271a78e484.source = 'musicbrainz.org'
SET perf_e8271a78e484.timestamp = timestamp()

MERGE (perf_a22d30c6392a:Performance{ uuid: '05cd4b2a-1bc7-4ef0-85fd-a22d30c6392a' })
SET perf_a22d30c6392a.name = 'Summer Nights'
SET perf_a22d30c6392a.duration = '6:59'
SET perf_a22d30c6392a.begin = '1966-07-14'
SET perf_a22d30c6392a.end = '1966-07-14'
SET perf_a22d30c6392a.source = 'musicbrainz.org'
SET perf_a22d30c6392a.timestamp = timestamp()

MERGE (perf_ce3e60d2ec7d:Performance{ uuid: 'a4aca75d-b4c9-4e1b-b964-ce3e60d2ec7d' })
SET perf_ce3e60d2ec7d.name = 'Black Circle'
SET perf_ce3e60d2ec7d.duration = '6:56'
SET perf_ce3e60d2ec7d.begin = '1966-07-14'
SET perf_ce3e60d2ec7d.end = '1966-07-14'
SET perf_ce3e60d2ec7d.source = 'musicbrainz.org'
SET perf_ce3e60d2ec7d.timestamp = timestamp()

MERGE (perf_df7372630e1a:Performance{ uuid: '4dc73f34-d862-46ad-b56b-df7372630e1a' })
SET perf_df7372630e1a.name = 'Verse'
SET perf_df7372630e1a.duration = '9:32'
SET perf_df7372630e1a.begin = '1966-07-14'
SET perf_df7372630e1a.end = '1966-07-14'
SET perf_df7372630e1a.source = 'musicbrainz.org'
SET perf_df7372630e1a.timestamp = timestamp()

MERGE (perf_009e9df81e08:Performance{ uuid: '0d5e095e-6eb6-4f18-9362-009e9df81e08' })
SET perf_009e9df81e08.name = 'Blues Mind Matter'
SET perf_009e9df81e08.duration = '3:32'
SET perf_009e9df81e08.begin = '1966-07-14'
SET perf_009e9df81e08.end = '1966-07-14'
SET perf_009e9df81e08.source = 'musicbrainz.org'
SET perf_009e9df81e08.timestamp = timestamp()



// labels
MERGE (release_0ea24e1b43d1)-[:HAS_LABEL]->(label_14e1ddfd5946)


// tracks
MERGE (release_0ea24e1b43d1)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_d98eca990a3e)
MERGE (release_0ea24e1b43d1)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_e8271a78e484)
MERGE (release_0ea24e1b43d1)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_a22d30c6392a)
MERGE (release_0ea24e1b43d1)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_ce3e60d2ec7d)
MERGE (release_0ea24e1b43d1)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_df7372630e1a)
MERGE (release_0ea24e1b43d1)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_009e9df81e08)

// works

MERGE (person_829aa7b39205:Person{ uuid: '169c0d1b-fcb8-4a43-9097-829aa7b39205' }) 
SET person_829aa7b39205.name = 'Ornette Coleman'
SET person_829aa7b39205.gender = 'Male'
SET person_829aa7b39205.country = 'US'
SET person_829aa7b39205.allmusic = 'https://www.allmusic.com/artist/mn0000484396'
SET person_829aa7b39205.bbc = 'https://www.bbc.co.uk/music/artists/169c0d1b-fcb8-4a43-9097-829aa7b39205'
SET person_829aa7b39205.discogs = 'https://www.discogs.com/artist/224506'
SET person_829aa7b39205.imdb = 'https://www.imdb.com/name/nm0171170/'
SET person_829aa7b39205.viaf = 'http://viaf.org/viaf/79166373'
SET person_829aa7b39205.wikidata = 'https://www.wikidata.org/wiki/Q208797'
SET person_829aa7b39205.databases = ['http://d-nb.info/gnd/118890964', 'http://id.loc.gov/authorities/names/n83071536', 'https://catalogue.bnf.fr/ark:/12148/cb13892628b', 'http://snaccooperative.org/ark:/99166/w6rz0q2w', 'https://rateyourmusic.com/artist/ornette_coleman', 'https://www.musik-sammler.de/artist/ornette-coleman/', 'https://www.worldcat.org/oclc/935032488']
SET person_829aa7b39205.musicbrainz = 'https://musicbrainz.org/artist/169c0d1b-fcb8-4a43-9097-829aa7b39205'
SET person_829aa7b39205.isni_list = ['http://isni.org/isni/0000000117719685']
SET person_829aa7b39205.source = 'musicbrainz.org'
SET person_829aa7b39205.timestamp = timestamp()

MERGE (work_b9355c63b56d:Work{ uuid: 'f3d1fe49-548a-4823-a254-b9355c63b56d' })
SET work_b9355c63b56d.name = 'Blues Mind Matter'
SET work_b9355c63b56d.type = 'Song'
SET work_b9355c63b56d.source = 'musicbrainz.org'
SET work_b9355c63b56d.timestamp = timestamp()

MERGE (work_5fa830f2323f:Work{ uuid: 'b668b501-a4c4-470d-beae-5fa830f2323f' })
SET work_5fa830f2323f.name = 'Black Circle'
SET work_5fa830f2323f.source = 'musicbrainz.org'
SET work_5fa830f2323f.timestamp = timestamp()

MERGE (work_51244227613e:Work{ uuid: 'e30cb820-bc9b-48ab-ba1f-51244227613e' })
SET work_51244227613e.name = 'Summer Nights'
SET work_51244227613e.source = 'musicbrainz.org'
SET work_51244227613e.timestamp = timestamp()

MERGE (work_e3737b73d0a3:Work{ uuid: '0917bf7f-f658-4214-97c1-e3737b73d0a3' })
SET work_e3737b73d0a3.name = '8/4 Beat'
SET work_e3737b73d0a3.type = 'Song'
SET work_e3737b73d0a3.source = 'musicbrainz.org'
SET work_e3737b73d0a3.timestamp = timestamp()

MERGE (work_b0fea083ba5c:Work{ uuid: '15d98110-ff0e-301a-b58c-b0fea083ba5c' })
SET work_b0fea083ba5c.name = 'Una Muy Bonita'
SET work_b0fea083ba5c.source = 'musicbrainz.org'
SET work_b0fea083ba5c.timestamp = timestamp()

MERGE (work_f78bb3725e13:Work{ uuid: 'dc049cba-6bf5-4db6-af64-f78bb3725e13' })
SET work_f78bb3725e13.name = 'Verse'
SET work_f78bb3725e13.source = 'musicbrainz.org'
SET work_f78bb3725e13.timestamp = timestamp()


// performances of
MERGE (perf_009e9df81e08)-[:PERFORMANCE_OF]->(work_b9355c63b56d)
MERGE (perf_ce3e60d2ec7d)-[:PERFORMANCE_OF]->(work_5fa830f2323f)
MERGE (perf_a22d30c6392a)-[:PERFORMANCE_OF]->(work_51244227613e)
MERGE (perf_e8271a78e484)-[:PERFORMANCE_OF]->(work_e3737b73d0a3)
MERGE (perf_d98eca990a3e)-[:PERFORMANCE_OF]->(work_b0fea083ba5c)
MERGE (perf_df7372630e1a)-[:PERFORMANCE_OF]->(work_f78bb3725e13)


// composers
MERGE (person_8fe19080caaf)-[:COMPOSED]->(work_b9355c63b56d)
MERGE (person_8fe19080caaf)-[:COMPOSED]->(work_5fa830f2323f)
MERGE (person_8fe19080caaf)-[:COMPOSED]->(work_51244227613e)
MERGE (person_8fe19080caaf)-[:COMPOSED]->(work_e3737b73d0a3)
MERGE (person_829aa7b39205)-[:COMPOSED]->(work_b0fea083ba5c)
MERGE (person_8fe19080caaf)-[:COMPOSED]->(work_f78bb3725e13)


// place nodes

MERGE (place_569fa8b97644:Place{ uuid: '1165ef7d-371c-4e03-98db-569fa8b97644' })
SET place_569fa8b97644.name = 'Van Gelder Studio'
SET place_569fa8b97644.source = 'musicbrainz.org'


// place relationships
MERGE (perf_d98eca990a3e)-[:HAS_PLACE { type: 'recorded at', begin: '1966-07-14', end: '1966-07-14' }]->(place_569fa8b97644)
MERGE (perf_e8271a78e484)-[:HAS_PLACE { type: 'recorded at', begin: '1966-07-14', end: '1966-07-14' }]->(place_569fa8b97644)
MERGE (perf_a22d30c6392a)-[:HAS_PLACE { type: 'recorded at', begin: '1966-07-14', end: '1966-07-14' }]->(place_569fa8b97644)
MERGE (perf_ce3e60d2ec7d)-[:HAS_PLACE { type: 'recorded at', begin: '1966-07-14', end: '1966-07-14' }]->(place_569fa8b97644)
MERGE (perf_df7372630e1a)-[:HAS_PLACE { type: 'recorded at', begin: '1966-07-14', end: '1966-07-14' }]->(place_569fa8b97644)
MERGE (perf_009e9df81e08)-[:HAS_PLACE { type: 'recorded at', begin: '1966-07-14', end: '1966-07-14' }]->(place_569fa8b97644)

MERGE (person_9ee947b4ce37)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_d98eca990a3e)
MERGE (person_23e60ffced44)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_d98eca990a3e)
MERGE (person_8fe19080caaf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['vibraphone'] }]->(perf_d98eca990a3e)
MERGE (person_3479a48a0eea)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_d98eca990a3e)
MERGE (person_8971e7a2912e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_d98eca990a3e)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_d98eca990a3e)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_d98eca990a3e)
MERGE (person_9ee947b4ce37)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_e8271a78e484)
MERGE (person_23e60ffced44)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_e8271a78e484)
MERGE (person_8fe19080caaf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['vibraphone'] }]->(perf_e8271a78e484)
MERGE (person_3479a48a0eea)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_e8271a78e484)
MERGE (person_8971e7a2912e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e8271a78e484)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_e8271a78e484)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_e8271a78e484)
MERGE (person_9ee947b4ce37)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_a22d30c6392a)
MERGE (person_23e60ffced44)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_a22d30c6392a)
MERGE (person_8fe19080caaf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['vibraphone'] }]->(perf_a22d30c6392a)
MERGE (person_3479a48a0eea)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_a22d30c6392a)
MERGE (person_8971e7a2912e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_a22d30c6392a)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_a22d30c6392a)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_a22d30c6392a)
MERGE (person_9ee947b4ce37)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_ce3e60d2ec7d)
MERGE (person_23e60ffced44)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_ce3e60d2ec7d)
MERGE (person_8fe19080caaf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['vibraphone'] }]->(perf_ce3e60d2ec7d)
MERGE (person_3479a48a0eea)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_ce3e60d2ec7d)
MERGE (person_8971e7a2912e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_ce3e60d2ec7d)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_ce3e60d2ec7d)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_ce3e60d2ec7d)
MERGE (person_9ee947b4ce37)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_df7372630e1a)
MERGE (person_23e60ffced44)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_df7372630e1a)
MERGE (person_8fe19080caaf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['vibraphone'] }]->(perf_df7372630e1a)
MERGE (person_3479a48a0eea)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_df7372630e1a)
MERGE (person_8971e7a2912e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_df7372630e1a)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_df7372630e1a)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_df7372630e1a)
MERGE (person_9ee947b4ce37)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_009e9df81e08)
MERGE (person_23e60ffced44)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_009e9df81e08)
MERGE (person_8fe19080caaf)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['vibraphone'] }]->(perf_009e9df81e08)
MERGE (person_3479a48a0eea)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_009e9df81e08)
MERGE (person_8971e7a2912e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_009e9df81e08)
MERGE (person_317b31f6c035)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_009e9df81e08)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_009e9df81e08)

