// releases

MERGE (release_861d399d8c3f:Release{ uuid: '0212b65c-497a-4490-991b-861d399d8c3f' })
SET release_861d399d8c3f.name = 'Bravo! Brubeck!'
SET release_861d399d8c3f.country = 'US'
SET release_861d399d8c3f.date = '1967-07-17'
SET release_861d399d8c3f.format = '12" Vinyl'
SET release_861d399d8c3f.discode = 'CS 9495'
SET release_861d399d8c3f.discogs = 'https://www.discogs.com/release/1247180'
SET release_861d399d8c3f.musicbrainz = 'http://musicbrainz.org/release/0212b65c-497a-4490-991b-861d399d8c3f'
SET release_861d399d8c3f.source = 'musicbrainz.org'
SET release_861d399d8c3f.timestamp = timestamp()

MERGE (person_22a3e53a555c:Person{ uuid: 'c9a1fe8c-340a-46c4-87c4-22a3e53a555c' })
SET person_22a3e53a555c.name = 'Joe Morello'
SET person_22a3e53a555c.gender = 'Male'
SET person_22a3e53a555c.country = 'US'
SET person_22a3e53a555c.viaf = 'http://viaf.org/viaf/5118446'
SET person_22a3e53a555c.allmusic = 'http://www.allmusic.com/artist/mn0000207988'
SET person_22a3e53a555c.imdb = 'http://www.imdb.com/name/nm0603775/'
SET person_22a3e53a555c.wikipedia = 'https://en.wikipedia.org/wiki/Joe_Morello'
SET person_22a3e53a555c.discogs = 'https://www.discogs.com/artist/254976'
SET person_22a3e53a555c.wikidata = 'https://www.wikidata.org/wiki/Q448995'
SET person_22a3e53a555c.musicbrainz = 'https://musicbrainz.org/artist/c9a1fe8c-340a-46c4-87c4-22a3e53a555c'
SET person_22a3e53a555c.source = 'musicbrainz.org'
SET person_22a3e53a555c.timestamp = timestamp()

MERGE (person_1749199a4da5:Person{ uuid: '7d803cbf-5b57-4579-8c5f-1749199a4da5' })
SET person_1749199a4da5.name = 'Eugene Wright'
SET person_1749199a4da5.gender = 'Male'
SET person_1749199a4da5.country = 'US'
SET person_1749199a4da5.viaf = 'http://viaf.org/viaf/102368902'
SET person_1749199a4da5.allmusic = 'http://www.allmusic.com/artist/mn0000211186'
SET person_1749199a4da5.wikipedia = 'https://en.wikipedia.org/wiki/Eugene_Wright'
SET person_1749199a4da5.discogs = 'https://www.discogs.com/artist/274797'
SET person_1749199a4da5.wikidata = 'https://www.wikidata.org/wiki/Q490275'
SET person_1749199a4da5.musicbrainz = 'https://musicbrainz.org/artist/7d803cbf-5b57-4579-8c5f-1749199a4da5'
SET person_1749199a4da5.source = 'musicbrainz.org'
SET person_1749199a4da5.timestamp = timestamp()

MERGE (person_1fc0ebf8637e:Person{ uuid: 'a08c67bf-e254-4917-8154-1fc0ebf8637e' })
SET person_1fc0ebf8637e.name = 'Chamín Correa'
SET person_1fc0ebf8637e.country = 'MX'
SET person_1fc0ebf8637e.wikipedia = 'https://en.wikipedia.org/wiki/Chamin_Correa'
SET person_1fc0ebf8637e.wikidata = 'https://www.wikidata.org/wiki/Q5764377'
SET person_1fc0ebf8637e.musicbrainz = 'https://musicbrainz.org/artist/a08c67bf-e254-4917-8154-1fc0ebf8637e'
SET person_1fc0ebf8637e.source = 'musicbrainz.org'
SET person_1fc0ebf8637e.timestamp = timestamp()

MERGE (person_4b7c80fe34de:Person{ uuid: 'd5bf3447-c526-4f7c-9931-4b7c80fe34de' })
SET person_4b7c80fe34de.name = 'Paul Desmond'
SET person_4b7c80fe34de.gender = 'Male'
SET person_4b7c80fe34de.country = 'US'
SET person_4b7c80fe34de.viaf = 'http://viaf.org/viaf/117767459'
SET person_4b7c80fe34de.allmusic = 'http://www.allmusic.com/artist/mn0000069348'
SET person_4b7c80fe34de.imdb = 'http://www.imdb.com/name/nm0221474/'
SET person_4b7c80fe34de.wikipedia = 'https://en.wikipedia.org/wiki/Paul_Desmond'
SET person_4b7c80fe34de.discogs = 'https://www.discogs.com/artist/170329'
SET person_4b7c80fe34de.wikidata = 'https://www.wikidata.org/wiki/Q332471'
SET person_4b7c80fe34de.databases = ['http://rateyourmusic.com/artist/paul_desmond']
SET person_4b7c80fe34de.musicbrainz = 'https://musicbrainz.org/artist/d5bf3447-c526-4f7c-9931-4b7c80fe34de'
SET person_4b7c80fe34de.source = 'musicbrainz.org'
SET person_4b7c80fe34de.timestamp = timestamp()

MERGE (person_3f66d505061b:Person{ uuid: 'de0222a6-e1c4-403d-8b01-3f66d505061b' })
SET person_3f66d505061b.name = 'Dave Brubeck'
SET person_3f66d505061b.gender = 'Male'
SET person_3f66d505061b.country = 'US'
SET person_3f66d505061b.viaf = 'http://viaf.org/viaf/14957683'
SET person_3f66d505061b.allmusic = 'http://www.allmusic.com/artist/mn0000958533'
SET person_3f66d505061b.bbc = 'http://www.bbc.co.uk/music/artists/de0222a6-e1c4-403d-8b01-3f66d505061b'
SET person_3f66d505061b.imdb = 'http://www.imdb.com/name/nm0115399/'
SET person_3f66d505061b.wikipedia = 'https://en.wikipedia.org/wiki/Dave_Brubeck'
SET person_3f66d505061b.discogs = 'https://www.discogs.com/artist/37737'
SET person_3f66d505061b.wikidata = 'https://www.wikidata.org/wiki/Q108597'
SET person_3f66d505061b.discographies = ['http://www.jazzdisco.org/dave-brubeck/catalog/']
SET person_3f66d505061b.databases = ['http://rateyourmusic.com/artist/dave_brubeck', 'http://www.45cat.com/artist/dave-brubeck']
SET person_3f66d505061b.musicbrainz = 'https://musicbrainz.org/artist/de0222a6-e1c4-403d-8b01-3f66d505061b'
SET person_3f66d505061b.isni_list = ['http://isni.org/isni/000000011021617X']
SET person_3f66d505061b.source = 'musicbrainz.org'
SET person_3f66d505061b.timestamp = timestamp()

MERGE (person_782ab218f45a:Person{ uuid: '0be1b5b9-36c3-4ba3-b3a2-782ab218f45a' })
SET person_782ab218f45a.name = 'Salvatore Agüeros'
SET person_782ab218f45a.source = 'musicbrainz.org'
SET person_782ab218f45a.timestamp = timestamp()

MERGE (person_d5fead5a7988:Person{ uuid: '64e2e449-234c-480d-89d3-d5fead5a7988' })
SET person_d5fead5a7988.name = 'Teo Macero'
SET person_d5fead5a7988.gender = 'Male'
SET person_d5fead5a7988.country = 'US'
SET person_d5fead5a7988.viaf = 'http://viaf.org/viaf/32185295'
SET person_d5fead5a7988.allmusic = 'http://www.allmusic.com/artist/mn0000020762'
SET person_d5fead5a7988.imdb = 'http://www.imdb.com/name/nm0532163/'
SET person_d5fead5a7988.wikipedia = 'https://en.wikipedia.org/wiki/Teo_Macero'
SET person_d5fead5a7988.discogs = 'https://www.discogs.com/artist/237977'
SET person_d5fead5a7988.wikidata = 'https://www.wikidata.org/wiki/Q265494'
SET person_d5fead5a7988.musicbrainz = 'https://musicbrainz.org/artist/64e2e449-234c-480d-89d3-d5fead5a7988'
SET person_d5fead5a7988.source = 'musicbrainz.org'
SET person_d5fead5a7988.timestamp = timestamp()

MERGE (person_c0cb5805f1e7:Person{ uuid: '7bf711e9-4e69-4e08-b6e8-c0cb5805f1e7' })
SET person_c0cb5805f1e7.name = 'The Dave Brubeck Quartet'
SET person_c0cb5805f1e7.country = 'US'
SET person_c0cb5805f1e7.viaf = 'http://viaf.org/viaf/14957683'
SET person_c0cb5805f1e7.allmusic = 'http://www.allmusic.com/artist/mn0000142767'
SET person_c0cb5805f1e7.bbc = 'http://www.bbc.co.uk/music/artists/7bf711e9-4e69-4e08-b6e8-c0cb5805f1e7'
SET person_c0cb5805f1e7.imdb = 'http://www.imdb.com/name/nm1437162/'
SET person_c0cb5805f1e7.wikipedia = 'https://en.wikipedia.org/wiki/Dave_Brubeck#Dave_Brubeck_Quartet'
SET person_c0cb5805f1e7.discogs = 'https://www.discogs.com/artist/251689'
SET person_c0cb5805f1e7.wikidata = 'https://www.wikidata.org/wiki/Q264163'
SET person_c0cb5805f1e7.databases = ['http://www.45cat.com/artist/the-dave-brubeck-quartet']
SET person_c0cb5805f1e7.musicbrainz = 'https://musicbrainz.org/artist/7bf711e9-4e69-4e08-b6e8-c0cb5805f1e7'
SET person_c0cb5805f1e7.source = 'musicbrainz.org'
SET person_c0cb5805f1e7.timestamp = timestamp()
// labels

MERGE (label_0400dd45693e:Label{ uuid: '011d1192-6f65-45bd-85c4-0400dd45693e' })
SET label_0400dd45693e.name= 'Columbia'

// performances

MERGE (perf_b79c43821682:Performance{ uuid: '3a81d489-6548-4d82-a1c1-b79c43821682' })
SET perf_b79c43821682.name = 'Cielito Lindo (Blue Sky)'
SET perf_b79c43821682.duration = '5:01'
SET perf_b79c43821682.source = 'musicbrainz.org'
SET perf_b79c43821682.timestamp = timestamp()

MERGE (perf_83aaac3fa8df:Performance{ uuid: '42b4d3c5-4462-4d4f-9674-83aaac3fa8df' })
SET perf_83aaac3fa8df.name = 'La Paloma Azul (The Blue Dove)'
SET perf_83aaac3fa8df.duration = '6:16'
SET perf_83aaac3fa8df.source = 'musicbrainz.org'
SET perf_83aaac3fa8df.timestamp = timestamp()

MERGE (perf_472a25eeb5d4:Performance{ uuid: '5eee845b-f5ae-4b04-9fbb-472a25eeb5d4' })
SET perf_472a25eeb5d4.name = 'Sobre las Olas (Over the Waves)'
SET perf_472a25eeb5d4.duration = '3:17'
SET perf_472a25eeb5d4.source = 'musicbrainz.org'
SET perf_472a25eeb5d4.timestamp = timestamp()

MERGE (perf_33d6eb8cf5c4:Performance{ uuid: '2383d1ba-2184-4a0b-bd76-33d6eb8cf5c4' })
SET perf_33d6eb8cf5c4.name = 'Bésame Mucho (Kiss Me Much)'
SET perf_33d6eb8cf5c4.duration = '5:53'
SET perf_33d6eb8cf5c4.source = 'musicbrainz.org'
SET perf_33d6eb8cf5c4.timestamp = timestamp()

MERGE (perf_d4da0f7cbc73:Performance{ uuid: '590a3b83-8422-41f6-a8c0-d4da0f7cbc73' })
SET perf_d4da0f7cbc73.name = 'Nostalgia de México'
SET perf_d4da0f7cbc73.duration = '4:03'
SET perf_d4da0f7cbc73.source = 'musicbrainz.org'
SET perf_d4da0f7cbc73.timestamp = timestamp()

MERGE (perf_25c2538edb5f:Performance{ uuid: 'd003ba8a-5ce9-4143-8a81-25c2538edb5f' })
SET perf_25c2538edb5f.name = 'Poinciana (Song of the Tree)'
SET perf_25c2538edb5f.duration = '6:43'
SET perf_25c2538edb5f.source = 'musicbrainz.org'
SET perf_25c2538edb5f.timestamp = timestamp()

MERGE (perf_e03467c61af0:Performance{ uuid: 'b66a2aad-2936-4648-be9d-e03467c61af0' })
SET perf_e03467c61af0.name = 'Allá en el Rancho Grande (My Ranch)'
SET perf_e03467c61af0.duration = '3:07'
SET perf_e03467c61af0.source = 'musicbrainz.org'
SET perf_e03467c61af0.timestamp = timestamp()

MERGE (perf_c4e540492e06:Performance{ uuid: '44bbb28d-69d2-4ac4-80a6-c4e540492e06' })
SET perf_c4e540492e06.name = 'Estrellita (Little Star)'
SET perf_c4e540492e06.duration = '4:50'
SET perf_c4e540492e06.source = 'musicbrainz.org'
SET perf_c4e540492e06.timestamp = timestamp()

MERGE (perf_f13ede446027:Performance{ uuid: '4c0a5db9-e871-45e9-8f8c-f13ede446027' })
SET perf_f13ede446027.name = 'La Bamba'
SET perf_f13ede446027.duration = '4:50'
SET perf_f13ede446027.source = 'musicbrainz.org'
SET perf_f13ede446027.timestamp = timestamp()



// labels
MERGE (release_861d399d8c3f)-[:HAS_LABEL]->(label_0400dd45693e)


// tracks
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_b79c43821682)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_83aaac3fa8df)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'A3', sequence: 3}]->(perf_472a25eeb5d4)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'A4', sequence: 4}]->(perf_33d6eb8cf5c4)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'B1', sequence: 5}]->(perf_d4da0f7cbc73)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'B2', sequence: 6}]->(perf_25c2538edb5f)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'B3', sequence: 7}]->(perf_e03467c61af0)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'B4', sequence: 8}]->(perf_c4e540492e06)
MERGE (release_861d399d8c3f)-[:HAS_TRACK {name: 'B5', sequence: 9}]->(perf_f13ede446027)

// works

MERGE (person_6d994d1d043d:Person{ uuid: '8ef957ae-41f7-44aa-afc4-6d994d1d043d' })
SET person_6d994d1d043d.name = 'Emilio Uranga'
SET person_6d994d1d043d.imdb = 'http://www.imdb.com/name/nm0881559/'
SET person_6d994d1d043d.musicbrainz = 'https://musicbrainz.org/artist/8ef957ae-41f7-44aa-afc4-6d994d1d043d'
SET person_6d994d1d043d.source = 'musicbrainz.org'
SET person_6d994d1d043d.timestamp = timestamp()

MERGE (person_1da0a2985cb1:Person{ uuid: 'a2c4674d-35eb-4e86-9100-1da0a2985cb1' })
SET person_1da0a2985cb1.name = 'Consuelo Velázquez'
SET person_1da0a2985cb1.gender = 'Female'
SET person_1da0a2985cb1.country = 'MX'
SET person_1da0a2985cb1.allmusic = 'http://www.allmusic.com/artist/mn0000779201'
SET person_1da0a2985cb1.wikipedia = 'https://en.wikipedia.org/wiki/Consuelo_Vel%C3%A1zquez'
SET person_1da0a2985cb1.discogs = 'https://www.discogs.com/artist/556380'
SET person_1da0a2985cb1.wikidata = 'https://www.wikidata.org/wiki/Q232750'
SET person_1da0a2985cb1.musicbrainz = 'https://musicbrainz.org/artist/a2c4674d-35eb-4e86-9100-1da0a2985cb1'
SET person_1da0a2985cb1.isni_list = ['http://isni.org/isni/0000000081163469']
SET person_1da0a2985cb1.source = 'musicbrainz.org'
SET person_1da0a2985cb1.timestamp = timestamp()

MERGE (person_40ed0736e815:Person{ uuid: 'b2e7da33-0bab-4249-b302-40ed0736e815' })
SET person_40ed0736e815.name = 'Juventino Rosas'
SET person_40ed0736e815.gender = 'Male'
SET person_40ed0736e815.country = 'MX'
SET person_40ed0736e815.viaf = 'http://viaf.org/viaf/46947517'
SET person_40ed0736e815.imdb = 'http://www.imdb.com/name/nm0741097/'
SET person_40ed0736e815.wikipedia = 'https://en.wikipedia.org/wiki/Juventino_Rosas'
SET person_40ed0736e815.discogs = 'https://www.discogs.com/artist/800999'
SET person_40ed0736e815.wikidata = 'https://www.wikidata.org/wiki/Q461403'
SET person_40ed0736e815.databases = ['http://catalogue.bnf.fr/ark:/12148/cb138991635', 'http://d-nb.info/gnd/123093848']
SET person_40ed0736e815.musicbrainz = 'https://musicbrainz.org/artist/b2e7da33-0bab-4249-b302-40ed0736e815'
SET person_40ed0736e815.isni_list = ['http://isni.org/isni/0000000081255785']
SET person_40ed0736e815.source = 'musicbrainz.org'
SET person_40ed0736e815.timestamp = timestamp()

MERGE (person_8cd4f6f94a5c:Person{ uuid: '22ee6983-fab6-4ac1-872c-8cd4f6f94a5c' })
SET person_8cd4f6f94a5c.name = 'Manuel María Ponce'
SET person_8cd4f6f94a5c.gender = 'Male'
SET person_8cd4f6f94a5c.country = 'MX'
SET person_8cd4f6f94a5c.viaf = 'http://viaf.org/viaf/24788185'
SET person_8cd4f6f94a5c.allmusic = 'http://www.allmusic.com/artist/mn0000590334'
SET person_8cd4f6f94a5c.wikipedia = 'https://en.wikipedia.org/wiki/Manuel_Ponce'
SET person_8cd4f6f94a5c.discogs = 'https://www.discogs.com/artist/843631'
SET person_8cd4f6f94a5c.wikidata = 'https://www.wikidata.org/wiki/Q360206'
SET person_8cd4f6f94a5c.databases = ['http://catalogue.bnf.fr/ark:/12148/cb13898593z', 'https://d-nb.info/gnd/119466953', 'https://openlibrary.org/works/OL2250189A']
SET person_8cd4f6f94a5c.musicbrainz = 'https://musicbrainz.org/artist/22ee6983-fab6-4ac1-872c-8cd4f6f94a5c'
SET person_8cd4f6f94a5c.isni_list = ['http://isni.org/isni/0000000116093617']
SET person_8cd4f6f94a5c.source = 'musicbrainz.org'
SET person_8cd4f6f94a5c.timestamp = timestamp()

MERGE (person_cd98fb995419:Person{ uuid: '9fed659a-6da7-48ec-87f5-cd98fb995419' })
SET person_cd98fb995419.name = 'Juan Del Moral'
SET person_cd98fb995419.gender = 'Male'
SET person_cd98fb995419.disambiguation = 'songwriter'
SET person_cd98fb995419.musicbrainz = 'https://musicbrainz.org/artist/9fed659a-6da7-48ec-87f5-cd98fb995419'
SET person_cd98fb995419.source = 'musicbrainz.org'
SET person_cd98fb995419.timestamp = timestamp()

MERGE (person_96d33efd33d9:Person{ uuid: 'c6aaadfe-e604-407f-b954-96d33efd33d9' })
SET person_96d33efd33d9.name = 'Silvano Ramos'
SET person_96d33efd33d9.gender = 'Male'
SET person_96d33efd33d9.disambiguation = 'songwriter'
SET person_96d33efd33d9.musicbrainz = 'https://musicbrainz.org/artist/c6aaadfe-e604-407f-b954-96d33efd33d9'
SET person_96d33efd33d9.source = 'musicbrainz.org'
SET person_96d33efd33d9.timestamp = timestamp()

MERGE (person_8d40b5dcbc41:Person{ uuid: '9be7f096-97ec-4615-8957-8d40b5dcbc41' })
SET person_8d40b5dcbc41.name = '[traditional]'
SET person_8d40b5dcbc41.disambiguation = 'Special Purpose Artist'
SET person_8d40b5dcbc41.allmusic = 'http://www.allmusic.com/artist/mn0000022266'
SET person_8d40b5dcbc41.discogs = 'https://www.discogs.com/artist/151641'
SET person_8d40b5dcbc41.databases = ['http://www.whosampled.com/Traditional-Folk/', 'https://rateyourmusic.com/artist/traditional']
SET person_8d40b5dcbc41.musicbrainz = 'https://musicbrainz.org/artist/9be7f096-97ec-4615-8957-8d40b5dcbc41'
SET person_8d40b5dcbc41.source = 'musicbrainz.org'
SET person_8d40b5dcbc41.timestamp = timestamp()

MERGE (person_0046599561e9:Person{ uuid: '357888b8-a8b9-483d-b2f1-0046599561e9' })
SET person_0046599561e9.name = 'Quirino Mendoza y Cortés'
SET person_0046599561e9.gender = 'Male'
SET person_0046599561e9.country = 'MX'
SET person_0046599561e9.imdb = 'http://www.imdb.com/name/nm0579348/'
SET person_0046599561e9.discogs = 'https://www.discogs.com/artist/1122757'
SET person_0046599561e9.wikidata = 'https://www.wikidata.org/wiki/Q6095384'
SET person_0046599561e9.musicbrainz = 'https://musicbrainz.org/artist/357888b8-a8b9-483d-b2f1-0046599561e9'
SET person_0046599561e9.source = 'musicbrainz.org'
SET person_0046599561e9.timestamp = timestamp()

MERGE (person_3f9a959bc006:Person{ uuid: '513aef7f-970a-4b01-9ffb-3f9a959bc006' })
SET person_3f9a959bc006.name = 'Nat Simon'
SET person_3f9a959bc006.gender = 'Male'
SET person_3f9a959bc006.country = 'US'
SET person_3f9a959bc006.viaf = 'http://viaf.org/viaf/16573497'
SET person_3f9a959bc006.imdb = 'http://www.imdb.com/name/nm0800317/'
SET person_3f9a959bc006.discogs = 'https://www.discogs.com/artist/556391'
SET person_3f9a959bc006.wikidata = 'https://www.wikidata.org/wiki/Q6967884'
SET person_3f9a959bc006.databases = ['http://catalogue.bnf.fr/ark:/12148/cb14776782x']
SET person_3f9a959bc006.musicbrainz = 'https://musicbrainz.org/artist/513aef7f-970a-4b01-9ffb-3f9a959bc006'
SET person_3f9a959bc006.source = 'musicbrainz.org'
SET person_3f9a959bc006.timestamp = timestamp()

MERGE (work_bc263d27e672:Work{ uuid: '43090fa2-5683-35dd-a659-bc263d27e672' })
SET work_bc263d27e672.name = 'Cielito lindo'
SET work_bc263d27e672.type = 'Song'
SET work_bc263d27e672.wikidata = 'https://www.wikidata.org/wiki/Q2308941'
SET work_bc263d27e672.musicbrainz = 'https://musicbrainz.org/work/43090fa2-5683-35dd-a659-bc263d27e672'
SET work_bc263d27e672.source = 'musicbrainz.org'
SET work_bc263d27e672.timestamp = timestamp()

MERGE (work_824299484a47:Work{ uuid: '0e71888a-3e07-3262-9820-824299484a47' })
SET work_824299484a47.name = 'Sobre las olas'
SET work_824299484a47.wikidata = 'https://www.wikidata.org/wiki/Q540114'
SET work_824299484a47.musicbrainz = 'https://musicbrainz.org/work/0e71888a-3e07-3262-9820-824299484a47'
SET work_824299484a47.source = 'musicbrainz.org'
SET work_824299484a47.timestamp = timestamp()

MERGE (work_7594fec0821a:Work{ uuid: '06f1bf25-cf7f-3039-9aa4-7594fec0821a' })
SET work_7594fec0821a.name = 'Poinciana (Song of the Tree)'
SET work_7594fec0821a.iswc = 'T-070.166.154-2'
SET work_7594fec0821a.type = 'Song'
SET work_7594fec0821a.wikipedia = 'https://en.wikipedia.org/wiki/Poinciana_(song)'
SET work_7594fec0821a.musicbrainz = 'https://musicbrainz.org/work/06f1bf25-cf7f-3039-9aa4-7594fec0821a'
SET work_7594fec0821a.source = 'musicbrainz.org'
SET work_7594fec0821a.timestamp = timestamp()

MERGE (work_c054454b8468:Work{ uuid: 'f2522609-7359-395b-9d2e-c054454b8468' })
SET work_c054454b8468.name = 'Allá en el Rancho Grande (My Ranch)'
SET work_c054454b8468.source = 'musicbrainz.org'
SET work_c054454b8468.timestamp = timestamp()

MERGE (work_c278ad73c751:Work{ uuid: 'c53d4b1b-cae3-3ce2-ad5e-c278ad73c751' })
SET work_c278ad73c751.name = 'Bésame mucho'
SET work_c278ad73c751.type = 'Song'
SET work_c278ad73c751.wikidata = 'https://www.wikidata.org/wiki/Q391180'
SET work_c278ad73c751.musicbrainz = 'https://musicbrainz.org/work/c53d4b1b-cae3-3ce2-ad5e-c278ad73c751'
SET work_c278ad73c751.source = 'musicbrainz.org'
SET work_c278ad73c751.timestamp = timestamp()

MERGE (work_d2a4b4be8049:Work{ uuid: '871b61e5-ca5d-3b16-8c17-d2a4b4be8049' })
SET work_d2a4b4be8049.name = 'La paloma azul'
SET work_d2a4b4be8049.source = 'musicbrainz.org'
SET work_d2a4b4be8049.timestamp = timestamp()

MERGE (work_124ccd06cbdb:Work{ uuid: 'f1ef85e8-10bc-337f-a3b4-124ccd06cbdb' })
SET work_124ccd06cbdb.name = 'La bamba'
SET work_124ccd06cbdb.type = 'Song'
SET work_124ccd06cbdb.wikipedia = 'https://en.wikipedia.org/wiki/La_Bamba_(song)'
SET work_124ccd06cbdb.musicbrainz = 'https://musicbrainz.org/work/f1ef85e8-10bc-337f-a3b4-124ccd06cbdb'
SET work_124ccd06cbdb.source = 'musicbrainz.org'
SET work_124ccd06cbdb.timestamp = timestamp()

MERGE (work_c498cb7a38c7:Work{ uuid: '983a9107-99a8-33fb-bb0a-c498cb7a38c7' })
SET work_c498cb7a38c7.name = 'Estrellita'
SET work_c498cb7a38c7.iswc = 'T-035.000.608-4'
SET work_c498cb7a38c7.type = 'Song'
SET work_c498cb7a38c7.wikidata = 'https://www.wikidata.org/wiki/Q5849697'
SET work_c498cb7a38c7.musicbrainz = 'https://musicbrainz.org/work/983a9107-99a8-33fb-bb0a-c498cb7a38c7'
SET work_c498cb7a38c7.source = 'musicbrainz.org'
SET work_c498cb7a38c7.timestamp = timestamp()

MERGE (work_6416c3ff1396:Work{ uuid: '8a8d717f-78ea-385a-9a64-6416c3ff1396' })
SET work_6416c3ff1396.name = 'Nostalgia de México'
SET work_6416c3ff1396.source = 'musicbrainz.org'
SET work_6416c3ff1396.timestamp = timestamp()


// performances of
MERGE (perf_b79c43821682)-[:PERFORMANCE_OF]->(work_bc263d27e672)
MERGE (perf_472a25eeb5d4)-[:PERFORMANCE_OF]->(work_824299484a47)
MERGE (perf_25c2538edb5f)-[:PERFORMANCE_OF]->(work_7594fec0821a)
MERGE (perf_e03467c61af0)-[:PERFORMANCE_OF]->(work_c054454b8468)
MERGE (perf_33d6eb8cf5c4)-[:PERFORMANCE_OF]->(work_c278ad73c751)
MERGE (perf_83aaac3fa8df)-[:PERFORMANCE_OF]->(work_d2a4b4be8049)
MERGE (perf_f13ede446027)-[:PERFORMANCE_OF]->(work_124ccd06cbdb)
MERGE (perf_c4e540492e06)-[:PERFORMANCE_OF]->(work_c498cb7a38c7)
MERGE (perf_d4da0f7cbc73)-[:PERFORMANCE_OF]->(work_6416c3ff1396)


// composers
MERGE (person_0046599561e9)-[:COMPOSED]->(work_bc263d27e672)
MERGE (person_40ed0736e815)-[:COMPOSED]->(work_824299484a47)
MERGE (person_3f9a959bc006)-[:COMPOSED]->(work_7594fec0821a)
MERGE (person_6d994d1d043d)-[:COMPOSED]->(work_c054454b8468)
MERGE (person_cd98fb995419)-[:COMPOSED]->(work_c054454b8468)
MERGE (person_96d33efd33d9)-[:COMPOSED]->(work_c054454b8468)
MERGE (person_1da0a2985cb1)-[:COMPOSED]->(work_c278ad73c751)
MERGE (person_8d40b5dcbc41)-[:COMPOSED]->(work_d2a4b4be8049)
MERGE (person_8d40b5dcbc41)-[:COMPOSED]->(work_124ccd06cbdb)
MERGE (person_8cd4f6f94a5c)-[:COMPOSED]->(work_c498cb7a38c7)
MERGE (person_3f66d505061b)-[:COMPOSED]->(work_6416c3ff1396)

MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_b79c43821682)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_b79c43821682)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_b79c43821682)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_b79c43821682)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_b79c43821682)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_b79c43821682)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_b79c43821682)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_83aaac3fa8df)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_83aaac3fa8df)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_83aaac3fa8df)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_83aaac3fa8df)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_83aaac3fa8df)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_83aaac3fa8df)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_83aaac3fa8df)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_472a25eeb5d4)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_472a25eeb5d4)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_472a25eeb5d4)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_472a25eeb5d4)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_472a25eeb5d4)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_472a25eeb5d4)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_472a25eeb5d4)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_33d6eb8cf5c4)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_33d6eb8cf5c4)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_33d6eb8cf5c4)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_33d6eb8cf5c4)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_33d6eb8cf5c4)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_33d6eb8cf5c4)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_33d6eb8cf5c4)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_d4da0f7cbc73)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_d4da0f7cbc73)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_d4da0f7cbc73)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_d4da0f7cbc73)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_d4da0f7cbc73)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_d4da0f7cbc73)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_d4da0f7cbc73)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_25c2538edb5f)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_25c2538edb5f)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_25c2538edb5f)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_25c2538edb5f)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_25c2538edb5f)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_25c2538edb5f)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_25c2538edb5f)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_e03467c61af0)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_e03467c61af0)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_e03467c61af0)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_e03467c61af0)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_e03467c61af0)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_e03467c61af0)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e03467c61af0)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_c4e540492e06)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_c4e540492e06)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_c4e540492e06)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_c4e540492e06)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_c4e540492e06)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_c4e540492e06)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_c4e540492e06)
MERGE (person_782ab218f45a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bongos', 'congas', 'guest'] }]->(perf_f13ede446027)
MERGE (person_d5fead5a7988)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_f13ede446027)
MERGE (person_1749199a4da5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_f13ede446027)
MERGE (person_1fc0ebf8637e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guest', 'guitar'] }]->(perf_f13ede446027)
MERGE (person_22a3e53a555c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_f13ede446027)
MERGE (person_4b7c80fe34de)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_f13ede446027)
MERGE (person_3f66d505061b)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_f13ede446027)
