// releases

MERGE (release_545fa4d8a6c8:Release{ uuid: '139cd405-59f3-40f8-accc-545fa4d8a6c8' })
SET release_545fa4d8a6c8.name = 'Spring Broadcasts 1953'
SET release_545fa4d8a6c8.country = 'DE'
SET release_545fa4d8a6c8.format = 'CD'
SET release_545fa4d8a6c8.discode = '3022-2'
SET release_545fa4d8a6c8.discogs = 'https://www.discogs.com/release/12283641'
SET release_545fa4d8a6c8.musicbrainz = 'http://musicbrainz.org/release/139cd405-59f3-40f8-accc-545fa4d8a6c8'
SET release_545fa4d8a6c8.source = 'musicbrainz.org'
SET release_545fa4d8a6c8.timestamp = timestamp()

MERGE (person_1f29826df090:Person{ uuid: 'b6372c2f-a092-4d96-a6f3-1f29826df090' }) 
SET person_1f29826df090.name = 'Sonny Payne'
SET person_1f29826df090.gender = 'Male'
SET person_1f29826df090.country = 'US'
SET person_1f29826df090.allmusic = 'https://www.allmusic.com/artist/mn0000755947'
SET person_1f29826df090.discogs = 'https://www.discogs.com/artist/321928'
SET person_1f29826df090.viaf = 'http://viaf.org/viaf/22328333'
SET person_1f29826df090.wikidata = 'https://www.wikidata.org/wiki/Q358286'
SET person_1f29826df090.wikipedia = 'https://en.wikipedia.org/wiki/Sonny_Payne'
SET person_1f29826df090.databases = ['http://d-nb.info/gnd/134622677', 'http://id.loc.gov/authorities/names/no92003408', 'https://catalogue.bnf.fr/ark:/12148/cb13898316z', 'http://snaccooperative.org/ark:/99166/w6891sqq', 'https://www.worldcat.org/identities/lccn-no92003408']
SET person_1f29826df090.musicbrainz = 'https://musicbrainz.org/artist/b6372c2f-a092-4d96-a6f3-1f29826df090'
SET person_1f29826df090.isni_list = ['http://isni.org/isni/0000000079866528']
SET person_1f29826df090.source = 'musicbrainz.org'
SET person_1f29826df090.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://d-nb.info/gnd/134400623', 'http://id.loc.gov/authorities/names/n81140108', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_340d64fbb41c:Person{ uuid: 'dbc5809c-7837-4b6f-961e-340d64fbb41c' }) 
SET person_340d64fbb41c.name = 'Bud Powell'
SET person_340d64fbb41c.gender = 'Male'
SET person_340d64fbb41c.country = 'US'
SET person_340d64fbb41c.allmusic = 'https://www.allmusic.com/artist/mn0000640675'
SET person_340d64fbb41c.bbc = 'https://www.bbc.co.uk/music/artists/dbc5809c-7837-4b6f-961e-340d64fbb41c'
SET person_340d64fbb41c.discogs = 'https://www.discogs.com/artist/29992'
SET person_340d64fbb41c.imdb = 'https://www.imdb.com/name/nm0694046/'
SET person_340d64fbb41c.viaf = 'http://viaf.org/viaf/197369'
SET person_340d64fbb41c.wikidata = 'https://www.wikidata.org/wiki/Q312692'
SET person_340d64fbb41c.databases = ['http://d-nb.info/gnd/119379457', 'http://id.loc.gov/authorities/names/n81146628', 'https://catalogue.bnf.fr/ark:/12148/cb13898636d', 'http://snaccooperative.org/ark:/99166/w66j93wh', 'https://rateyourmusic.com/artist/bud_powell', 'https://www.worldcat.org/identities/lccn-n81146628']
SET person_340d64fbb41c.musicbrainz = 'https://musicbrainz.org/artist/dbc5809c-7837-4b6f-961e-340d64fbb41c'
SET person_340d64fbb41c.isni_list = ['http://isni.org/isni/0000000063083027']
SET person_340d64fbb41c.source = 'musicbrainz.org'
SET person_340d64fbb41c.timestamp = timestamp()

MERGE (person_4a4ee995e71f:Person{ uuid: 'f3b8e107-abe8-4743-b6a3-4a4ee995e71f' }) 
SET person_4a4ee995e71f.name = 'Charles Mingus'
SET person_4a4ee995e71f.gender = 'Male'
SET person_4a4ee995e71f.country = 'US'
SET person_4a4ee995e71f.allmusic = 'https://www.allmusic.com/artist/mn0000009680'
SET person_4a4ee995e71f.bbc = 'https://www.bbc.co.uk/music/artists/f3b8e107-abe8-4743-b6a3-4a4ee995e71f'
SET person_4a4ee995e71f.discogs = 'https://www.discogs.com/artist/200815'
SET person_4a4ee995e71f.imdb = 'https://www.imdb.com/name/nm0591323/'
SET person_4a4ee995e71f.viaf = 'http://viaf.org/viaf/111286947'
SET person_4a4ee995e71f.wikidata = 'https://www.wikidata.org/wiki/Q107432'
SET person_4a4ee995e71f.databases = ['http://d-nb.info/gnd/118582631', 'http://id.loc.gov/authorities/names/n80057165', 'http://musicmoz.org/Bands_and_Artists/M/Mingus,_Charles/', 'https://catalogue.bnf.fr/ark:/12148/cb119162211', 'http://snaccooperative.org/ark:/99166/w6n58swn', 'https://nla.gov.au/nla.party-1053460', 'https://openlibrary.org/works/OL774758A', 'https://rateyourmusic.com/artist/charles_mingus', 'https://www.musik-sammler.de/artist/charles-mingus/', 'https://www.whosampled.com/Charles-Mingus/', 'https://www.worldcat.org/identities/lccn-n80-057165']
SET person_4a4ee995e71f.musicbrainz = 'https://musicbrainz.org/artist/f3b8e107-abe8-4743-b6a3-4a4ee995e71f'
SET person_4a4ee995e71f.isni_list = ['http://isni.org/isni/0000000110832626']
SET person_4a4ee995e71f.source = 'musicbrainz.org'
SET person_4a4ee995e71f.timestamp = timestamp()

MERGE (person_1c787d37a8c5:Person{ uuid: 'd3ba7a66-f3a5-4b85-b5e4-1c787d37a8c5' }) 
SET person_1c787d37a8c5.name = 'Franklin Skeete'
SET person_1c787d37a8c5.gender = 'Male'
SET person_1c787d37a8c5.country = 'US'
SET person_1c787d37a8c5.discogs = 'https://www.discogs.com/artist/675733'
SET person_1c787d37a8c5.musicbrainz = 'https://musicbrainz.org/artist/d3ba7a66-f3a5-4b85-b5e4-1c787d37a8c5'
SET person_1c787d37a8c5.source = 'musicbrainz.org'
SET person_1c787d37a8c5.timestamp = timestamp()
// labels

MERGE (label_6347577dfc09:Label{ uuid: '8f200b94-5233-432a-9d7a-6347577dfc09' })
SET label_6347577dfc09.name= 'ESP-Disk’'

// performances

MERGE (perf_207632c639cf:Performance{ uuid: '9c422565-b755-40db-8637-207632c639cf' })
SET perf_207632c639cf.name = 'How High the Moon'
SET perf_207632c639cf.duration = '2:57'
SET perf_207632c639cf.begin = '1953-03-07'
SET perf_207632c639cf.end = '1953-03-07'
SET perf_207632c639cf.source = 'musicbrainz.org'
SET perf_207632c639cf.timestamp = timestamp()

MERGE (perf_9f5a84d66279:Performance{ uuid: '61528e60-8c02-4227-ba7e-9f5a84d66279' })
SET perf_9f5a84d66279.name = 'Budo'
SET perf_9f5a84d66279.duration = '2:05'
SET perf_9f5a84d66279.begin = '1953-03-07'
SET perf_9f5a84d66279.end = '1953-03-07'
SET perf_9f5a84d66279.source = 'musicbrainz.org'
SET perf_9f5a84d66279.timestamp = timestamp()

MERGE (perf_a908b2e82d30:Performance{ uuid: 'efe31468-1ddc-4e0b-8afa-a908b2e82d30' })
SET perf_a908b2e82d30.name = 'Hallelujah'
SET perf_a908b2e82d30.duration = '2:48'
SET perf_a908b2e82d30.begin = '1953-03-07'
SET perf_a908b2e82d30.end = '1953-03-07'
SET perf_a908b2e82d30.source = 'musicbrainz.org'
SET perf_a908b2e82d30.timestamp = timestamp()

MERGE (perf_73f497c5ec45:Performance{ uuid: 'ce175e37-d901-4649-9bf9-73f497c5ec45' })
SET perf_73f497c5ec45.name = 'I\'ve Got You Under My Skin'
SET perf_73f497c5ec45.duration = '2:40'
SET perf_73f497c5ec45.begin = '1953-03-07'
SET perf_73f497c5ec45.end = '1953-03-07'
SET perf_73f497c5ec45.source = 'musicbrainz.org'
SET perf_73f497c5ec45.timestamp = timestamp()

MERGE (perf_251b4ddc6fef:Performance{ uuid: 'de986798-842c-4444-9882-251b4ddc6fef' })
SET perf_251b4ddc6fef.name = 'Embraceable You'
SET perf_251b4ddc6fef.duration = '4:34'
SET perf_251b4ddc6fef.begin = '1953-03-07'
SET perf_251b4ddc6fef.end = '1953-03-07'
SET perf_251b4ddc6fef.source = 'musicbrainz.org'
SET perf_251b4ddc6fef.timestamp = timestamp()

MERGE (perf_25d5e8356a5d:Performance{ uuid: 'cda378dd-1cb1-459c-a870-25d5e8356a5d' })
SET perf_25d5e8356a5d.name = 'I Want to Be Happy'
SET perf_25d5e8356a5d.duration = '3:09'
SET perf_25d5e8356a5d.begin = '1953-03-21'
SET perf_25d5e8356a5d.end = '1953-03-21'
SET perf_25d5e8356a5d.source = 'musicbrainz.org'
SET perf_25d5e8356a5d.timestamp = timestamp()

MERGE (perf_cafaf5ae2179:Performance{ uuid: '3018c92d-a22d-48b7-a93a-cafaf5ae2179' })
SET perf_cafaf5ae2179.name = 'I\'ve Got You Under My Skin'
SET perf_cafaf5ae2179.duration = '2:32'
SET perf_cafaf5ae2179.begin = '1953-03-21'
SET perf_cafaf5ae2179.end = '1953-03-21'
SET perf_cafaf5ae2179.source = 'musicbrainz.org'
SET perf_cafaf5ae2179.timestamp = timestamp()

MERGE (perf_9fa263dabff5:Performance{ uuid: '2929d59d-248f-4512-add1-9fa263dabff5' })
SET perf_9fa263dabff5.name = 'Sure Thing'
SET perf_9fa263dabff5.duration = '2:01'
SET perf_9fa263dabff5.begin = '1953-03-21'
SET perf_9fa263dabff5.end = '1953-03-21'
SET perf_9fa263dabff5.source = 'musicbrainz.org'
SET perf_9fa263dabff5.timestamp = timestamp()

MERGE (perf_cf3e01428fe2:Performance{ uuid: '0ee71609-222c-4936-940c-cf3e01428fe2' })
SET perf_cf3e01428fe2.name = 'Embraceable You'
SET perf_cf3e01428fe2.duration = '3:31'
SET perf_cf3e01428fe2.begin = '1953-03-21'
SET perf_cf3e01428fe2.end = '1953-03-21'
SET perf_cf3e01428fe2.source = 'musicbrainz.org'
SET perf_cf3e01428fe2.timestamp = timestamp()

MERGE (perf_146fd33a32bc:Performance{ uuid: 'a0e19b8f-3c84-4761-85ab-146fd33a32bc' })
SET perf_146fd33a32bc.name = 'Woody ’n You'
SET perf_146fd33a32bc.duration = '2:55'
SET perf_146fd33a32bc.begin = '1953-03-21'
SET perf_146fd33a32bc.end = '1953-03-21'
SET perf_146fd33a32bc.source = 'musicbrainz.org'
SET perf_146fd33a32bc.timestamp = timestamp()

MERGE (perf_f373b5529742:Performance{ uuid: '5b41546d-6a4a-41d6-9087-f373b5529742' })
SET perf_f373b5529742.name = 'Salt Peanuts'
SET perf_f373b5529742.duration = '4:16'
SET perf_f373b5529742.begin = '1953-03-21'
SET perf_f373b5529742.end = '1953-03-21'
SET perf_f373b5529742.source = 'musicbrainz.org'
SET perf_f373b5529742.timestamp = timestamp()



// labels
MERGE (release_545fa4d8a6c8)-[:HAS_LABEL]->(label_6347577dfc09)


// tracks
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_207632c639cf)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_9f5a84d66279)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_a908b2e82d30)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_73f497c5ec45)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_251b4ddc6fef)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_25d5e8356a5d)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '7', sequence: 7}]->(perf_cafaf5ae2179)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '8', sequence: 8}]->(perf_9fa263dabff5)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '9', sequence: 9}]->(perf_cf3e01428fe2)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '10', sequence: 10}]->(perf_146fd33a32bc)
MERGE (release_545fa4d8a6c8)-[:HAS_TRACK {name: '11', sequence: 11}]->(perf_f373b5529742)

// works

MERGE (person_b693a808a158:Person{ uuid: '65744963-191a-44ef-a3c7-b693a808a158' }) 
SET person_b693a808a158.name = 'George Gershwin'
SET person_b693a808a158.gender = 'Male'
SET person_b693a808a158.disambiguation = 'composer'
SET person_b693a808a158.country = 'US'
SET person_b693a808a158.allmusic = 'https://www.allmusic.com/artist/mn0000197918'
SET person_b693a808a158.bbc = 'https://www.bbc.co.uk/music/artists/65744963-191a-44ef-a3c7-b693a808a158'
SET person_b693a808a158.discogs = 'https://www.discogs.com/artist/261293'
SET person_b693a808a158.imdb = 'https://www.imdb.com/name/nm0006097/'
SET person_b693a808a158.viaf = 'http://viaf.org/viaf/61554329'
SET person_b693a808a158.wikidata = 'https://www.wikidata.org/wiki/Q123829'
SET person_b693a808a158.databases = ['http://d-nb.info/gnd/118639226', 'http://id.loc.gov/authorities/names/n79077265', 'https://catalogue.bnf.fr/ark:/12148/cb119493251', 'https://ibdb.com/person.php?id=5813', 'http://snaccooperative.org/ark:/99166/w6x065dx', 'https://nla.gov.au/nla.party-832382', 'https://openlibrary.org/works/OL67761A', 'http://soundtrackcollector.com/composer/33/', 'https://rateyourmusic.com/artist/george_gershwin', 'https://www.worldcat.org/identities/lccn-n79077265']
SET person_b693a808a158.musicbrainz = 'https://musicbrainz.org/artist/65744963-191a-44ef-a3c7-b693a808a158'
SET person_b693a808a158.isni_list = ['http://isni.org/isni/0000000121355968']
SET person_b693a808a158.source = 'musicbrainz.org'
SET person_b693a808a158.timestamp = timestamp()

MERGE (person_65998d0d35b5:Person{ uuid: 'e9ba8ccb-505f-4e5c-b909-65998d0d35b5' }) 
SET person_65998d0d35b5.name = 'Dizzy Gillespie'
SET person_65998d0d35b5.gender = 'Male'
SET person_65998d0d35b5.country = 'US'
SET person_65998d0d35b5.allmusic = 'https://www.allmusic.com/artist/mn0000162677'
SET person_65998d0d35b5.bbc = 'https://www.bbc.co.uk/music/artists/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.discogs = 'https://www.discogs.com/artist/64694'
SET person_65998d0d35b5.imdb = 'https://www.imdb.com/name/nm0318926/'
SET person_65998d0d35b5.viaf = 'http://viaf.org/viaf/77110276'
SET person_65998d0d35b5.wikidata = 'https://www.wikidata.org/wiki/Q49575'
SET person_65998d0d35b5.databases = ['http://d-nb.info/gnd/118694960', 'http://id.loc.gov/authorities/names/n50033872', 'https://adp.library.ucsb.edu/names/102015', 'https://catalogue.bnf.fr/ark:/12148/cb138944733', 'https://ibdb.com/person.php?id=83656', 'http://snaccooperative.org/ark:/99166/w6jw8cjh', 'https://openlibrary.org/works/OL1238547A', 'https://rateyourmusic.com/artist/dizzy_gillespie', 'https://www.musik-sammler.de/artist/dizzy-gillespie/', 'https://www.worldcat.org/identities/lccn-n50033872']
SET person_65998d0d35b5.musicbrainz = 'https://musicbrainz.org/artist/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.isni_list = ['http://isni.org/isni/0000000109181520']
SET person_65998d0d35b5.source = 'musicbrainz.org'
SET person_65998d0d35b5.timestamp = timestamp()

MERGE (person_23af9c7c9462:Person{ uuid: 'd5c58002-376b-4961-8ab3-23af9c7c9462' }) 
SET person_23af9c7c9462.name = 'Clifford Grey'
SET person_23af9c7c9462.gender = 'Male'
SET person_23af9c7c9462.country = 'GB'
SET person_23af9c7c9462.discogs = 'https://www.discogs.com/artist/301997'
SET person_23af9c7c9462.imdb = 'https://www.imdb.com/name/nm0340540/'
SET person_23af9c7c9462.viaf = 'http://viaf.org/viaf/43856190'
SET person_23af9c7c9462.wikidata = 'https://www.wikidata.org/wiki/Q1101276'
SET person_23af9c7c9462.databases = ['http://d-nb.info/gnd/1059955407', 'http://id.loc.gov/authorities/names/no89019130', 'https://catalogue.bnf.fr/ark:/12148/cb14762010z', 'http://snaccooperative.org/ark:/99166/w6q81xfg', 'https://nla.gov.au/nla.party-1027984', 'https://www.ibdb.com/person.php?id=4882', 'https://www.worldcat.org/identities/lccn-no89019130/']
SET person_23af9c7c9462.musicbrainz = 'https://musicbrainz.org/artist/d5c58002-376b-4961-8ab3-23af9c7c9462'
SET person_23af9c7c9462.isni_list = ['http://isni.org/isni/0000000073266935']
SET person_23af9c7c9462.source = 'musicbrainz.org'
SET person_23af9c7c9462.timestamp = timestamp()

MERGE (person_323e6ce46c2a:Person{ uuid: '561d854a-6a28-4aa7-8c99-323e6ce46c2a' }) 
SET person_323e6ce46c2a.name = 'Miles Davis'
SET person_323e6ce46c2a.gender = 'Male'
SET person_323e6ce46c2a.disambiguation = 'jazz trumpeter, bandleader, songwriter'
SET person_323e6ce46c2a.country = 'US'
SET person_323e6ce46c2a.allmusic = 'https://www.allmusic.com/artist/mn0000423829'
SET person_323e6ce46c2a.bbc = 'https://www.bbc.co.uk/music/artists/561d854a-6a28-4aa7-8c99-323e6ce46c2a'
SET person_323e6ce46c2a.discogs = 'https://www.discogs.com/artist/23755'
SET person_323e6ce46c2a.imdb = 'https://www.imdb.com/name/nm0002537/'
SET person_323e6ce46c2a.viaf = 'http://viaf.org/viaf/97762193'
SET person_323e6ce46c2a.wikidata = 'https://www.wikidata.org/wiki/Q93341'
SET person_323e6ce46c2a.databases = ['http://d-nb.info/gnd/118524046', 'http://id.loc.gov/authorities/names/n50035608', 'http://musicmoz.org/Bands_and_Artists/D/Davis,_Miles/', 'https://catalogue.bnf.fr/ark:/12148/cb13893030g', 'http://snaccooperative.org/ark:/99166/w68k7wq0', 'https://openlibrary.org/works/OL4359245A', 'https://rateyourmusic.com/artist/miles_davis', 'https://www.45cat.com/artist/miles-davis', 'https://www.45worlds.com/78rpm/artist/miles-davis', 'https://www.45worlds.com/cdalbum/artist/miles-davis', 'https://www.45worlds.com/live/artist/miles-davis', 'https://www.45worlds.com/tape/artist/miles-davis', 'https://www.45worlds.com/vinyl/artist/miles-davis', 'https://www.muziekweb.nl/Link/M00000286446/', 'https://www.worldcat.org/identities/lccn-n50035608']
SET person_323e6ce46c2a.musicbrainz = 'https://musicbrainz.org/artist/561d854a-6a28-4aa7-8c99-323e6ce46c2a'
SET person_323e6ce46c2a.isni_list = ['http://isni.org/isni/000000012144707X']
SET person_323e6ce46c2a.source = 'musicbrainz.org'
SET person_323e6ce46c2a.timestamp = timestamp()

MERGE (person_191ca24ad661:Person{ uuid: '7e43f216-d19c-4668-a939-191ca24ad661' }) 
SET person_191ca24ad661.name = 'Vincent Youmans'
SET person_191ca24ad661.gender = 'Male'
SET person_191ca24ad661.country = 'US'
SET person_191ca24ad661.discogs = 'https://www.discogs.com/artist/301996'
SET person_191ca24ad661.imdb = 'https://www.imdb.com/name/nm0949207/'
SET person_191ca24ad661.viaf = 'http://viaf.org/viaf/74039292'
SET person_191ca24ad661.wikidata = 'https://www.wikidata.org/wiki/Q746951'
SET person_191ca24ad661.databases = ['http://d-nb.info/gnd/11880815X', 'http://id.loc.gov/authorities/names/n80107199', 'https://catalogue.bnf.fr/ark:/12148/cb13901338w', 'https://ibdb.com/person.php?id=12607', 'http://snaccooperative.org/ark:/99166/w66t1fkb', 'https://nla.gov.au/nla.party-1227269', 'https://openlibrary.org/works/OL7514377A', 'https://www.worldcat.org/identities/lccn-n80107199/']
SET person_191ca24ad661.musicbrainz = 'https://musicbrainz.org/artist/7e43f216-d19c-4668-a939-191ca24ad661'
SET person_191ca24ad661.isni_list = ['http://isni.org/isni/0000000081543066']
SET person_191ca24ad661.source = 'musicbrainz.org'
SET person_191ca24ad661.timestamp = timestamp()

MERGE (person_392d39d08ce3:Person{ uuid: 'e4c00cfe-8393-416b-90da-392d39d08ce3' }) 
SET person_392d39d08ce3.name = 'Nancy Hamilton'
SET person_392d39d08ce3.gender = 'Female'
SET person_392d39d08ce3.country = 'US'
SET person_392d39d08ce3.allmusic = 'https://www.allmusic.com/artist/mn0000366325'
SET person_392d39d08ce3.discogs = 'https://www.discogs.com/artist/714004'
SET person_392d39d08ce3.imdb = 'https://www.imdb.com/name/nm0358071/'
SET person_392d39d08ce3.viaf = 'http://viaf.org/viaf/67703673'
SET person_392d39d08ce3.wikidata = 'https://www.wikidata.org/wiki/Q13560398'
SET person_392d39d08ce3.databases = ['http://d-nb.info/gnd/1135507333', 'http://id.loc.gov/authorities/names/n00114903', 'http://snaccooperative.org/ark:/99166/w6tq65bb', 'https://rateyourmusic.com/artist/nancy_hamilton', 'https://www.ibdb.com/person.php?id=7862', 'https://www.worldcat.org/identities/lccn-n00114903/']
SET person_392d39d08ce3.musicbrainz = 'https://musicbrainz.org/artist/e4c00cfe-8393-416b-90da-392d39d08ce3'
SET person_392d39d08ce3.isni_list = ['http://isni.org/isni/000000005939149X']
SET person_392d39d08ce3.source = 'musicbrainz.org'
SET person_392d39d08ce3.timestamp = timestamp()

MERGE (person_98b47fc19825:Person{ uuid: 'f31022a9-f702-430d-9315-98b47fc19825' }) 
SET person_98b47fc19825.name = 'Irving Caesar'
SET person_98b47fc19825.gender = 'Male'
SET person_98b47fc19825.country = 'US'
SET person_98b47fc19825.allmusic = 'https://www.allmusic.com/artist/mn0000773150'
SET person_98b47fc19825.discogs = 'https://www.discogs.com/artist/301994'
SET person_98b47fc19825.imdb = 'https://www.imdb.com/name/nm0128371/'
SET person_98b47fc19825.viaf = 'http://viaf.org/viaf/54415815'
SET person_98b47fc19825.wikidata = 'https://www.wikidata.org/wiki/Q1284219'
SET person_98b47fc19825.databases = ['http://d-nb.info/gnd/135139783', 'http://id.loc.gov/authorities/names/no90027480', 'https://catalogue.bnf.fr/ark:/12148/cb14849329n', 'https://ibdb.com/person.php?id=6455', 'http://snaccooperative.org/ark:/99166/w6jd5b8j', 'https://nla.gov.au/nla.party-1203672', 'https://rateyourmusic.com/artist/irving_caesar', 'https://www.worldcat.org/identities/lccn-no90027480/']
SET person_98b47fc19825.musicbrainz = 'https://musicbrainz.org/artist/f31022a9-f702-430d-9315-98b47fc19825'
SET person_98b47fc19825.isni_list = ['http://isni.org/isni/0000000121337209']
SET person_98b47fc19825.source = 'musicbrainz.org'
SET person_98b47fc19825.timestamp = timestamp()

MERGE (person_14f95e6ce86d:Person{ uuid: 'e8006a80-7c18-4b1c-a10f-14f95e6ce86d' }) 
SET person_14f95e6ce86d.name = 'Leo Robin'
SET person_14f95e6ce86d.gender = 'Male'
SET person_14f95e6ce86d.disambiguation = 'US composer, lyricist & songwriter'
SET person_14f95e6ce86d.country = 'US'
SET person_14f95e6ce86d.allmusic = 'https://www.allmusic.com/artist/mn0000821040'
SET person_14f95e6ce86d.discogs = 'https://www.discogs.com/artist/531605'
SET person_14f95e6ce86d.imdb = 'https://www.imdb.com/name/nm0732209/'
SET person_14f95e6ce86d.viaf = 'http://viaf.org/viaf/28536574'
SET person_14f95e6ce86d.wikidata = 'https://www.wikidata.org/wiki/Q364124'
SET person_14f95e6ce86d.databases = ['http://d-nb.info/gnd/13477535X', 'http://id.loc.gov/authorities/names/n85378850', 'https://catalogue.bnf.fr/ark:/12148/cb13948729j', 'https://ibdb.com/person.php?id=13232', 'http://snaccooperative.org/ark:/99166/w6jj6cx7', 'https://nla.gov.au/nla.party-1072860', 'https://rateyourmusic.com/artist/leo_robin', 'https://www.worldcat.org/identities/lccn-n85378850/']
SET person_14f95e6ce86d.musicbrainz = 'https://musicbrainz.org/artist/e8006a80-7c18-4b1c-a10f-14f95e6ce86d'
SET person_14f95e6ce86d.isni_list = ['http://isni.org/isni/0000000110233164']
SET person_14f95e6ce86d.source = 'musicbrainz.org'
SET person_14f95e6ce86d.timestamp = timestamp()

MERGE (person_322e34240ffc:Person{ uuid: '509086c2-9cc8-4e77-89e9-322e34240ffc' }) 
SET person_322e34240ffc.name = 'Ira Gershwin'
SET person_322e34240ffc.gender = 'Male'
SET person_322e34240ffc.country = 'US'
SET person_322e34240ffc.allmusic = 'https://www.allmusic.com/artist/mn0000200301'
SET person_322e34240ffc.discogs = 'https://www.discogs.com/artist/264105'
SET person_322e34240ffc.imdb = 'https://www.imdb.com/name/nm0314857/'
SET person_322e34240ffc.viaf = 'http://viaf.org/viaf/39519496'
SET person_322e34240ffc.wikidata = 'https://www.wikidata.org/wiki/Q61059'
SET person_322e34240ffc.databases = ['http://d-nb.info/gnd/119500027', 'http://id.loc.gov/authorities/names/n50076010', 'https://catalogue.bnf.fr/ark:/12148/cb13194929s', 'https://ibdb.com/person.php?id=6435', 'http://snaccooperative.org/ark:/99166/w60w94tm', 'https://nla.gov.au/nla.party-965252', 'https://openlibrary.org/works/OL233692A', 'https://rateyourmusic.com/artist/ira_gershwin', 'https://www.worldcat.org/identities/lccn-n50076010/']
SET person_322e34240ffc.musicbrainz = 'https://musicbrainz.org/artist/509086c2-9cc8-4e77-89e9-322e34240ffc'
SET person_322e34240ffc.isni_list = ['http://isni.org/isni/0000000108901469']
SET person_322e34240ffc.source = 'musicbrainz.org'
SET person_322e34240ffc.timestamp = timestamp()

MERGE (person_a37897b950ce:Person{ uuid: '4a94a6cb-e70a-418b-bb53-a37897b950ce' }) 
SET person_a37897b950ce.name = 'Cole Porter'
SET person_a37897b950ce.gender = 'Male'
SET person_a37897b950ce.disambiguation = 'composer'
SET person_a37897b950ce.country = 'US'
SET person_a37897b950ce.allmusic = 'https://www.allmusic.com/artist/mn0000109607'
SET person_a37897b950ce.discogs = 'https://www.discogs.com/artist/264026'
SET person_a37897b950ce.imdb = 'https://www.imdb.com/name/nm0006234/'
SET person_a37897b950ce.viaf = 'http://viaf.org/viaf/5118684'
SET person_a37897b950ce.wikidata = 'https://www.wikidata.org/wiki/Q215120'
SET person_a37897b950ce.databases = ['http://d-nb.info/gnd/11879292X', 'http://id.loc.gov/authorities/names/n80017862', 'https://catalogue.bnf.fr/ark:/12148/cb13898618g', 'https://ibdb.com/person.php?id=12257', 'http://snaccooperative.org/ark:/99166/w6j38s5m', 'https://nla.gov.au/nla.party-949524', 'https://openlibrary.org/works/OL709416A', 'http://soundtrackcollector.com/composer/166/', 'https://rateyourmusic.com/artist/cole_porter', 'https://www.worldcat.org/identities/lccn-n80017862', 'http://www.lortel.org/LLA_archive/index.cfm?search_by=people&first=Cole&last=Porter&middle=']
SET person_a37897b950ce.musicbrainz = 'https://musicbrainz.org/artist/4a94a6cb-e70a-418b-bb53-a37897b950ce'
SET person_a37897b950ce.isni_list = ['http://isni.org/isni/0000000108653610']
SET person_a37897b950ce.source = 'musicbrainz.org'
SET person_a37897b950ce.timestamp = timestamp()

MERGE (person_736867f1ba50:Person{ uuid: '48eaf8a1-6e44-488c-a91a-736867f1ba50' }) 
SET person_736867f1ba50.name = 'Kenny Clarke'
SET person_736867f1ba50.gender = 'Male'
SET person_736867f1ba50.country = 'US'
SET person_736867f1ba50.allmusic = 'https://www.allmusic.com/artist/mn0000081796'
SET person_736867f1ba50.discogs = 'https://www.discogs.com/artist/228917'
SET person_736867f1ba50.imdb = 'https://www.imdb.com/name/nm0164858/'
SET person_736867f1ba50.viaf = 'http://viaf.org/viaf/116335684'
SET person_736867f1ba50.wikidata = 'https://www.wikidata.org/wiki/Q346779'
SET person_736867f1ba50.databases = ['http://d-nb.info/gnd/118834827', 'http://id.loc.gov/authorities/names/n81055676', 'https://catalogue.bnf.fr/ark:/12148/cb13892538c', 'http://snaccooperative.org/ark:/99166/w6cj91b2', 'https://nla.gov.au/nla.party-1176449', 'https://rateyourmusic.com/artist/kenny_clarke', 'https://www.worldcat.org/identities/lccn-n81055676']
SET person_736867f1ba50.musicbrainz = 'https://musicbrainz.org/artist/48eaf8a1-6e44-488c-a91a-736867f1ba50'
SET person_736867f1ba50.isni_list = ['http://isni.org/isni/0000000084131382']
SET person_736867f1ba50.source = 'musicbrainz.org'
SET person_736867f1ba50.timestamp = timestamp()

MERGE (person_307524b9919b:Person{ uuid: '49e0ff4d-5d7b-419b-8b93-307524b9919b' }) 
SET person_307524b9919b.name = 'Morgan Lewis'
SET person_307524b9919b.gender = 'Male'
SET person_307524b9919b.country = 'US'
SET person_307524b9919b.allmusic = 'https://www.allmusic.com/artist/mn0000501474'
SET person_307524b9919b.discogs = 'https://www.discogs.com/artist/714002'
SET person_307524b9919b.imdb = 'https://www.imdb.com/name/nm1200498/'
SET person_307524b9919b.viaf = 'http://viaf.org/viaf/60319107'
SET person_307524b9919b.wikidata = 'https://www.wikidata.org/wiki/Q6911746'
SET person_307524b9919b.databases = ['http://d-nb.info/gnd/1135507198', 'http://id.loc.gov/authorities/names/n00114900', 'https://catalogue.bnf.fr/ark:/12148/cb138023170', 'http://snaccooperative.org/ark:/99166/w69m52b1', 'https://www.ibdb.com/person.php?id=12061', 'https://www.worldcat.org/identities/lccn-n00114900/']
SET person_307524b9919b.musicbrainz = 'https://musicbrainz.org/artist/49e0ff4d-5d7b-419b-8b93-307524b9919b'
SET person_307524b9919b.isni_list = ['http://isni.org/isni/000000008139913X']
SET person_307524b9919b.source = 'musicbrainz.org'
SET person_307524b9919b.timestamp = timestamp()

MERGE (work_7c0d2793d8d9:Work{ uuid: '13869248-f36a-3fe0-a8bd-7c0d2793d8d9' })
SET work_7c0d2793d8d9.name = 'Embraceable You'
SET work_7c0d2793d8d9.iswc = 'T-010.433.969-6'
SET work_7c0d2793d8d9.type = 'Song'
SET work_7c0d2793d8d9.wikidata = 'https://www.wikidata.org/wiki/Q753607'
SET work_7c0d2793d8d9.musicbrainz = 'https://musicbrainz.org/work/13869248-f36a-3fe0-a8bd-7c0d2793d8d9'
SET work_7c0d2793d8d9.source = 'musicbrainz.org'
SET work_7c0d2793d8d9.timestamp = timestamp()

MERGE (work_acc473cdeb71:Work{ uuid: 'e9e3c2f7-77c5-365a-b6b8-acc473cdeb71' })
SET work_acc473cdeb71.name = 'Budo'
SET work_acc473cdeb71.iswc = 'T-070.880.948-6'
SET work_acc473cdeb71.source = 'musicbrainz.org'
SET work_acc473cdeb71.timestamp = timestamp()

MERGE (work_5c9cfcd50e62:Work{ uuid: '1f69a658-acd8-32ca-9d6d-5c9cfcd50e62' })
SET work_5c9cfcd50e62.name = 'I’ve Got You Under My Skin'
SET work_5c9cfcd50e62.iswc = 'T-070.907.808-9'
SET work_5c9cfcd50e62.type = 'Song'
SET work_5c9cfcd50e62.wikidata = 'https://www.wikidata.org/wiki/Q2165861'
SET work_5c9cfcd50e62.musicbrainz = 'https://musicbrainz.org/work/1f69a658-acd8-32ca-9d6d-5c9cfcd50e62'
SET work_5c9cfcd50e62.source = 'musicbrainz.org'
SET work_5c9cfcd50e62.timestamp = timestamp()

MERGE (work_8752c89c7034:Work{ uuid: '4ee0ac5c-a2d2-3f7c-991a-8752c89c7034' })
SET work_8752c89c7034.name = 'I Want to Be Happy'
SET work_8752c89c7034.iswc = 'T-070.904.673-0'
SET work_8752c89c7034.type = 'Song'
SET work_8752c89c7034.wikidata = 'https://www.wikidata.org/wiki/Q5979567'
SET work_8752c89c7034.wikipedia = 'https://en.wikipedia.org/wiki/I_Want_to_Be_Happy'
SET work_8752c89c7034.musicbrainz = 'https://musicbrainz.org/work/4ee0ac5c-a2d2-3f7c-991a-8752c89c7034'
SET work_8752c89c7034.source = 'musicbrainz.org'
SET work_8752c89c7034.timestamp = timestamp()

MERGE (work_5f384434a06f:Work{ uuid: '683d70a3-be0c-36c8-95e8-5f384434a06f' })
SET work_5f384434a06f.name = 'Woody ’n’ You'
SET work_5f384434a06f.type = 'Song'
SET work_5f384434a06f.wikidata = 'https://www.wikidata.org/wiki/Q8033687'
SET work_5f384434a06f.musicbrainz = 'https://musicbrainz.org/work/683d70a3-be0c-36c8-95e8-5f384434a06f'
SET work_5f384434a06f.source = 'musicbrainz.org'
SET work_5f384434a06f.timestamp = timestamp()

MERGE (work_6f97d42f9f5d:Work{ uuid: 'bbb45de0-50f9-3065-b712-6f97d42f9f5d' })
SET work_6f97d42f9f5d.name = 'How High the Moon'
SET work_6f97d42f9f5d.iswc = 'T-070.074.622-0'
SET work_6f97d42f9f5d.type = 'Song'
SET work_6f97d42f9f5d.wikidata = 'https://www.wikidata.org/wiki/Q1631676'
SET work_6f97d42f9f5d.musicbrainz = 'https://musicbrainz.org/work/bbb45de0-50f9-3065-b712-6f97d42f9f5d'
SET work_6f97d42f9f5d.source = 'musicbrainz.org'
SET work_6f97d42f9f5d.timestamp = timestamp()

MERGE (work_6e36648e529a:Work{ uuid: 'c1805ac9-7233-4636-b607-6e36648e529a' })
SET work_6e36648e529a.name = 'Sure Thing'
SET work_6e36648e529a.source = 'musicbrainz.org'
SET work_6e36648e529a.timestamp = timestamp()

MERGE (work_c77299cca221:Work{ uuid: '50685bab-4a91-389c-81e6-c77299cca221' })
SET work_c77299cca221.name = 'Salt Peanuts'
SET work_c77299cca221.iswc = 'T-910.060.087-1'
SET work_c77299cca221.type = 'Song'
SET work_c77299cca221.wikidata = 'https://www.wikidata.org/wiki/Q753543'
SET work_c77299cca221.musicbrainz = 'https://musicbrainz.org/work/50685bab-4a91-389c-81e6-c77299cca221'
SET work_c77299cca221.source = 'musicbrainz.org'
SET work_c77299cca221.timestamp = timestamp()

MERGE (work_47e2248193b2:Work{ uuid: '1ebfe42c-a15e-3464-8699-47e2248193b2' })
SET work_47e2248193b2.name = 'Hallelujah!'
SET work_47e2248193b2.iswc = 'T-070.072.110-3'
SET work_47e2248193b2.type = 'Song'
SET work_47e2248193b2.source = 'musicbrainz.org'
SET work_47e2248193b2.timestamp = timestamp()


// performances of
MERGE (perf_251b4ddc6fef)-[:PERFORMANCE_OF]->(work_7c0d2793d8d9)
MERGE (perf_cf3e01428fe2)-[:PERFORMANCE_OF]->(work_7c0d2793d8d9)
MERGE (perf_9f5a84d66279)-[:PERFORMANCE_OF]->(work_acc473cdeb71)
MERGE (perf_73f497c5ec45)-[:PERFORMANCE_OF]->(work_5c9cfcd50e62)
MERGE (perf_cafaf5ae2179)-[:PERFORMANCE_OF]->(work_5c9cfcd50e62)
MERGE (perf_25d5e8356a5d)-[:PERFORMANCE_OF]->(work_8752c89c7034)
MERGE (perf_146fd33a32bc)-[:PERFORMANCE_OF]->(work_5f384434a06f)
MERGE (perf_207632c639cf)-[:PERFORMANCE_OF]->(work_6f97d42f9f5d)
MERGE (perf_9fa263dabff5)-[:PERFORMANCE_OF]->(work_6e36648e529a)
MERGE (perf_f373b5529742)-[:PERFORMANCE_OF]->(work_c77299cca221)
MERGE (perf_a908b2e82d30)-[:PERFORMANCE_OF]->(work_47e2248193b2)


// composers
MERGE (person_b693a808a158)-[:COMPOSED]->(work_7c0d2793d8d9)
MERGE (person_322e34240ffc)-[:WROTE_LYRICS]->(work_7c0d2793d8d9)
MERGE (person_323e6ce46c2a)-[:COMPOSED]->(work_acc473cdeb71)
MERGE (person_340d64fbb41c)-[:COMPOSED]->(work_acc473cdeb71)
MERGE (person_a37897b950ce)-[:COMPOSED]->(work_5c9cfcd50e62)
MERGE (person_a37897b950ce)-[:WROTE_LYRICS]->(work_5c9cfcd50e62)
MERGE (person_98b47fc19825)-[:COMPOSED]->(work_8752c89c7034)
MERGE (person_191ca24ad661)-[:COMPOSED]->(work_8752c89c7034)
MERGE (person_98b47fc19825)-[:WROTE_LYRICS]->(work_8752c89c7034)
MERGE (person_65998d0d35b5)-[:COMPOSED]->(work_5f384434a06f)
MERGE (person_307524b9919b)-[:COMPOSED]->(work_6f97d42f9f5d)
MERGE (person_392d39d08ce3)-[:WROTE_LYRICS]->(work_6f97d42f9f5d)
MERGE (person_340d64fbb41c)-[:COMPOSED]->(work_6e36648e529a)
MERGE (person_736867f1ba50)-[:COMPOSED]->(work_c77299cca221)
MERGE (person_65998d0d35b5)-[:COMPOSED]->(work_c77299cca221)
MERGE (person_191ca24ad661)-[:COMPOSED]->(work_47e2248193b2)
MERGE (person_23af9c7c9462)-[:WROTE_LYRICS]->(work_47e2248193b2)
MERGE (person_14f95e6ce86d)-[:WROTE_LYRICS]->(work_47e2248193b2)


// place nodes

MERGE (place_9808a9b287fa:Place{ uuid: '578aeeca-1616-49b2-9ff9-9808a9b287fa' })
SET place_9808a9b287fa.name = 'Birdland'
SET place_9808a9b287fa.source = 'musicbrainz.org'


// place relationships
MERGE (perf_207632c639cf)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-07', end: '1953-03-07' }]->(place_9808a9b287fa)
MERGE (perf_9f5a84d66279)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-07', end: '1953-03-07' }]->(place_9808a9b287fa)
MERGE (perf_a908b2e82d30)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-07', end: '1953-03-07' }]->(place_9808a9b287fa)
MERGE (perf_73f497c5ec45)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-07', end: '1953-03-07' }]->(place_9808a9b287fa)
MERGE (perf_251b4ddc6fef)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-07', end: '1953-03-07' }]->(place_9808a9b287fa)
MERGE (perf_25d5e8356a5d)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-21', end: '1953-03-21' }]->(place_9808a9b287fa)
MERGE (perf_cafaf5ae2179)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-21', end: '1953-03-21' }]->(place_9808a9b287fa)
MERGE (perf_9fa263dabff5)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-21', end: '1953-03-21' }]->(place_9808a9b287fa)
MERGE (perf_cf3e01428fe2)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-21', end: '1953-03-21' }]->(place_9808a9b287fa)
MERGE (perf_146fd33a32bc)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-21', end: '1953-03-21' }]->(place_9808a9b287fa)
MERGE (perf_f373b5529742)-[:HAS_PLACE { type: 'recorded at', begin: '1953-03-21', end: '1953-03-21' }]->(place_9808a9b287fa)

MERGE (person_1f29826df090)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_207632c639cf)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_207632c639cf)
MERGE (person_1c787d37a8c5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_207632c639cf)
MERGE (person_1f29826df090)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_9f5a84d66279)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_9f5a84d66279)
MERGE (person_1c787d37a8c5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_9f5a84d66279)
MERGE (person_1f29826df090)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_a908b2e82d30)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_a908b2e82d30)
MERGE (person_1c787d37a8c5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_a908b2e82d30)
MERGE (person_1f29826df090)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_73f497c5ec45)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_73f497c5ec45)
MERGE (person_1c787d37a8c5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_73f497c5ec45)
MERGE (person_1f29826df090)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_251b4ddc6fef)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_251b4ddc6fef)
MERGE (person_1c787d37a8c5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_251b4ddc6fef)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_25d5e8356a5d)
MERGE (person_4a4ee995e71f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_25d5e8356a5d)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_25d5e8356a5d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_cafaf5ae2179)
MERGE (person_4a4ee995e71f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_cafaf5ae2179)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_cafaf5ae2179)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_9fa263dabff5)
MERGE (person_4a4ee995e71f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_9fa263dabff5)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_9fa263dabff5)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_cf3e01428fe2)
MERGE (person_4a4ee995e71f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_cf3e01428fe2)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_cf3e01428fe2)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_146fd33a32bc)
MERGE (person_4a4ee995e71f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_146fd33a32bc)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_146fd33a32bc)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_f373b5529742)
MERGE (person_4a4ee995e71f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_f373b5529742)
MERGE (person_340d64fbb41c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_f373b5529742)

