// releases

MERGE (release_3036fffd03c6:Release{ uuid: '364e97e2-bc08-4d33-97d2-3036fffd03c6' })
SET release_3036fffd03c6.name = 'Trio Music'
SET release_3036fffd03c6.country = 'US'
SET release_3036fffd03c6.date = '1982'
SET release_3036fffd03c6.format = '12" Vinyl'
SET release_3036fffd03c6.format = '12" Vinyl'
SET release_3036fffd03c6.discode = 'ECM 1232'
SET release_3036fffd03c6.discogs = 'https://www.discogs.com/release/2551427'
SET release_3036fffd03c6.musicbrainz = 'http://musicbrainz.org/release/364e97e2-bc08-4d33-97d2-3036fffd03c6'
SET release_3036fffd03c6.source = 'musicbrainz.org'
SET release_3036fffd03c6.timestamp = timestamp()

MERGE (person_be027b7bb16e:Person{ uuid: 'd214235c-cf6f-4c8a-bf68-be027b7bb16e' }) 
SET person_be027b7bb16e.name = 'Miroslav Vitouš'
SET person_be027b7bb16e.gender = 'Male'
SET person_be027b7bb16e.country = 'CZ'
SET person_be027b7bb16e.allmusic = 'https://www.allmusic.com/artist/mn0000499683'
SET person_be027b7bb16e.bbc = 'https://www.bbc.co.uk/music/artists/d214235c-cf6f-4c8a-bf68-be027b7bb16e'
SET person_be027b7bb16e.discogs = 'https://www.discogs.com/artist/128396'
SET person_be027b7bb16e.imdb = 'https://www.imdb.com/name/nm1008417/'
SET person_be027b7bb16e.viaf = 'http://viaf.org/viaf/49409692'
SET person_be027b7bb16e.wikidata = 'https://www.wikidata.org/wiki/Q558162'
SET person_be027b7bb16e.wikipedia = 'https://en.wikipedia.org/wiki/Miroslav_Vitou%C5%A1'
SET person_be027b7bb16e.databases = ['http://d-nb.info/gnd/134547616', 'http://id.loc.gov/authorities/names/n82020005', 'https://catalogue.bnf.fr/ark:/12148/cb13900892t', 'https://www.worldcat.org/identities/lccn-n82020005']
SET person_be027b7bb16e.musicbrainz = 'https://musicbrainz.org/artist/d214235c-cf6f-4c8a-bf68-be027b7bb16e'
SET person_be027b7bb16e.isni_list = ['http://isni.org/isni/000000008128130X']
SET person_be027b7bb16e.source = 'musicbrainz.org'
SET person_be027b7bb16e.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://d-nb.info/gnd/134400623', 'http://id.loc.gov/authorities/names/n81140108', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_5a269b32b4c2:Person{ uuid: '8446fcca-109e-4c6d-a2ff-5a269b32b4c2' }) 
SET person_5a269b32b4c2.name = 'Chick Corea'
SET person_5a269b32b4c2.gender = 'Male'
SET person_5a269b32b4c2.disambiguation = 'jazz pianist'
SET person_5a269b32b4c2.country = 'US'
SET person_5a269b32b4c2.allmusic = 'https://www.allmusic.com/artist/mn0000110541'
SET person_5a269b32b4c2.discogs = 'https://www.discogs.com/artist/37731'
SET person_5a269b32b4c2.imdb = 'https://www.imdb.com/name/nm0179706/'
SET person_5a269b32b4c2.viaf = 'http://viaf.org/viaf/37337806'
SET person_5a269b32b4c2.wikidata = 'https://www.wikidata.org/wiki/Q192465'
SET person_5a269b32b4c2.databases = ['http://d-nb.info/gnd/119238489', 'http://id.loc.gov/authorities/names/n81080890', 'https://catalogue.bnf.fr/ark:/12148/cb13892744v', 'https://rateyourmusic.com/artist/chick_corea', 'https://www.worldcat.org/identities/lccn-n81080890']
SET person_5a269b32b4c2.musicbrainz = 'https://musicbrainz.org/artist/8446fcca-109e-4c6d-a2ff-5a269b32b4c2'
SET person_5a269b32b4c2.isni_list = ['http://isni.org/isni/0000000121285074']
SET person_5a269b32b4c2.source = 'musicbrainz.org'
SET person_5a269b32b4c2.timestamp = timestamp()

MERGE (person_2d752218d8f1:Person{ uuid: '5990bfa9-aba4-4b4e-87aa-2d752218d8f1' }) 
SET person_2d752218d8f1.name = 'Manfred Eicher'
SET person_2d752218d8f1.gender = 'Male'
SET person_2d752218d8f1.country = 'DE'
SET person_2d752218d8f1.allmusic = 'https://www.allmusic.com/artist/mn0000674652'
SET person_2d752218d8f1.discogs = 'https://www.discogs.com/artist/247567'
SET person_2d752218d8f1.imdb = 'https://www.imdb.com/name/nm0251502/'
SET person_2d752218d8f1.viaf = 'http://viaf.org/viaf/30718304'
SET person_2d752218d8f1.wikidata = 'https://www.wikidata.org/wiki/Q61919'
SET person_2d752218d8f1.wikipedia = 'https://en.wikipedia.org/wiki/Manfred_Eicher'
SET person_2d752218d8f1.databases = ['http://d-nb.info/gnd/133131203', 'http://id.loc.gov/authorities/names/no2005062474', 'https://catalogue.bnf.fr/ark:/12148/cb16221338h', 'http://snaccooperative.org/ark:/99166/w6w12jgw', 'https://rateyourmusic.com/artist/manfred_eicher', 'https://www.worldcat.org/identities/lccn-no2005062474']
SET person_2d752218d8f1.musicbrainz = 'https://musicbrainz.org/artist/5990bfa9-aba4-4b4e-87aa-2d752218d8f1'
SET person_2d752218d8f1.isni_list = ['http://isni.org/isni/0000000114407395']
SET person_2d752218d8f1.source = 'musicbrainz.org'
SET person_2d752218d8f1.timestamp = timestamp()

MERGE (person_4aef822ea97d:Person{ uuid: 'a19d3e1a-ef70-464a-a91c-4aef822ea97d' }) 
SET person_4aef822ea97d.name = 'Bernie Kirsh'
SET person_4aef822ea97d.gender = 'Male'
SET person_4aef822ea97d.country = 'US'
SET person_4aef822ea97d.discogs = 'https://www.discogs.com/artist/315355'
SET person_4aef822ea97d.musicbrainz = 'https://musicbrainz.org/artist/a19d3e1a-ef70-464a-a91c-4aef822ea97d'
SET person_4aef822ea97d.source = 'musicbrainz.org'
SET person_4aef822ea97d.timestamp = timestamp()

MERGE (person_ba7c4e91694e:Person{ uuid: '9b378a6e-0995-4d08-9264-ba7c4e91694e' }) 
SET person_ba7c4e91694e.name = 'Martin Wieland'
SET person_ba7c4e91694e.gender = 'Male'
SET person_ba7c4e91694e.disambiguation = 'recording engineer from Tonstudio Bauer'
SET person_ba7c4e91694e.discogs = 'https://www.discogs.com/artist/331054'
SET person_ba7c4e91694e.musicbrainz = 'https://musicbrainz.org/artist/9b378a6e-0995-4d08-9264-ba7c4e91694e'
SET person_ba7c4e91694e.source = 'musicbrainz.org'
SET person_ba7c4e91694e.timestamp = timestamp()

MERGE (person_16405d42c80a:Person{ uuid: '69e1f79f-4b1a-4520-9cef-16405d42c80a' }) 
SET person_16405d42c80a.name = 'Duncan Aldrich'
SET person_16405d42c80a.discogs = 'https://www.discogs.com/artist/956035'
SET person_16405d42c80a.musicbrainz = 'https://musicbrainz.org/artist/69e1f79f-4b1a-4520-9cef-16405d42c80a'
SET person_16405d42c80a.source = 'musicbrainz.org'
SET person_16405d42c80a.timestamp = timestamp()

// labels

MERGE (label_f31882443f89:Label{ uuid: '1edf842b-d727-4d27-8db6-f31882443f89' })
SET label_f31882443f89.name= 'ECM Records'

// performances

MERGE (perf_40e229f7f9a0:Performance{ uuid: 'df255612-6f96-463c-b784-40e229f7f9a0' })
SET perf_40e229f7f9a0.name = 'Trio Improvisation, Part 1'
SET perf_40e229f7f9a0.duration = '3:16'
SET perf_40e229f7f9a0.begin = '1981-11'
SET perf_40e229f7f9a0.end = '1981-11'
SET perf_40e229f7f9a0.source = 'musicbrainz.org'
SET perf_40e229f7f9a0.timestamp = timestamp()

MERGE (perf_4fdf76dfb0c1:Performance{ uuid: '97603f35-8412-434a-9f00-4fdf76dfb0c1' })
SET perf_4fdf76dfb0c1.name = 'Trio Improvisation, Part 2'
SET perf_4fdf76dfb0c1.duration = '3:44'
SET perf_4fdf76dfb0c1.begin = '1981-11'
SET perf_4fdf76dfb0c1.end = '1981-11'
SET perf_4fdf76dfb0c1.source = 'musicbrainz.org'
SET perf_4fdf76dfb0c1.timestamp = timestamp()

MERGE (perf_4ff94ddc74a1:Performance{ uuid: '7f841ba4-592d-4cc1-a13c-4ff94ddc74a1' })
SET perf_4ff94ddc74a1.name = 'Trio Improvisation, Part 3'
SET perf_4ff94ddc74a1.duration = '3:01'
SET perf_4ff94ddc74a1.begin = '1981-11'
SET perf_4ff94ddc74a1.end = '1981-11'
SET perf_4ff94ddc74a1.source = 'musicbrainz.org'
SET perf_4ff94ddc74a1.timestamp = timestamp()

MERGE (perf_5f85e02703ce:Performance{ uuid: '22a5c164-3f3b-49e6-b93b-5f85e02703ce' })
SET perf_5f85e02703ce.name = 'Duet Improvisation, Part 1'
SET perf_5f85e02703ce.duration = '4:23'
SET perf_5f85e02703ce.begin = '1981-11'
SET perf_5f85e02703ce.end = '1981-11'
SET perf_5f85e02703ce.source = 'musicbrainz.org'
SET perf_5f85e02703ce.timestamp = timestamp()

MERGE (perf_3c42983159ee:Performance{ uuid: '22a62fa8-f6b2-425a-a6e8-3c42983159ee' })
SET perf_3c42983159ee.name = 'Duet Improvisation, Part 2'
SET perf_3c42983159ee.duration = '5:14'
SET perf_3c42983159ee.begin = '1981-11'
SET perf_3c42983159ee.end = '1981-11'
SET perf_3c42983159ee.source = 'musicbrainz.org'
SET perf_3c42983159ee.timestamp = timestamp()

MERGE (perf_975c551770ae:Performance{ uuid: '59e2b44e-4f84-4560-8f15-975c551770ae' })
SET perf_975c551770ae.name = 'Trio Improvisation, Part 4'
SET perf_975c551770ae.duration = '4:33'
SET perf_975c551770ae.begin = '1981-11'
SET perf_975c551770ae.end = '1981-11'
SET perf_975c551770ae.source = 'musicbrainz.org'
SET perf_975c551770ae.timestamp = timestamp()

MERGE (perf_8667368361b6:Performance{ uuid: '6e99a9b4-f435-4f43-a641-8667368361b6' })
SET perf_8667368361b6.name = 'Trio Improvisation, Part 5'
SET perf_8667368361b6.duration = '7:35'
SET perf_8667368361b6.begin = '1981-11'
SET perf_8667368361b6.end = '1981-11'
SET perf_8667368361b6.source = 'musicbrainz.org'
SET perf_8667368361b6.timestamp = timestamp()

MERGE (perf_60e787334344:Performance{ uuid: '6500a7c0-cd7f-44c4-adcc-60e787334344' })
SET perf_60e787334344.name = 'Slippery When Wet'
SET perf_60e787334344.duration = '5:54'
SET perf_60e787334344.begin = '1981-11'
SET perf_60e787334344.end = '1981-11'
SET perf_60e787334344.source = 'musicbrainz.org'
SET perf_60e787334344.timestamp = timestamp()

MERGE (perf_38211d4f74ab:Performance{ uuid: '556958cd-c94c-42dc-949f-38211d4f74ab' })
SET perf_38211d4f74ab.name = 'Rhythm-A-Ning'
SET perf_38211d4f74ab.duration = '5:06'
SET perf_38211d4f74ab.begin = '1981-11'
SET perf_38211d4f74ab.end = '1981-11'
SET perf_38211d4f74ab.source = 'musicbrainz.org'
SET perf_38211d4f74ab.timestamp = timestamp()

MERGE (perf_6fe5fcfd0768:Performance{ uuid: '60e4f3f3-45c3-4843-8ba1-6fe5fcfd0768' })
SET perf_6fe5fcfd0768.name = '\'Round Midnight'
SET perf_6fe5fcfd0768.duration = '5:11'
SET perf_6fe5fcfd0768.begin = '1981-11'
SET perf_6fe5fcfd0768.end = '1981-11'
SET perf_6fe5fcfd0768.source = 'musicbrainz.org'
SET perf_6fe5fcfd0768.timestamp = timestamp()

MERGE (perf_e24ba555ac7f:Performance{ uuid: '7317919b-f059-4146-95ef-e24ba555ac7f' })
SET perf_e24ba555ac7f.name = 'Eronel'
SET perf_e24ba555ac7f.duration = '4:37'
SET perf_e24ba555ac7f.begin = '1981-11'
SET perf_e24ba555ac7f.end = '1981-11'
SET perf_e24ba555ac7f.source = 'musicbrainz.org'
SET perf_e24ba555ac7f.timestamp = timestamp()

MERGE (perf_e9a61da3df72:Performance{ uuid: 'b13e50a5-1be3-4fbb-8680-e9a61da3df72' })
SET perf_e9a61da3df72.name = 'Think of One'
SET perf_e9a61da3df72.duration = '4:20'
SET perf_e9a61da3df72.begin = '1981-11'
SET perf_e9a61da3df72.end = '1981-11'
SET perf_e9a61da3df72.source = 'musicbrainz.org'
SET perf_e9a61da3df72.timestamp = timestamp()

MERGE (perf_a350bf8f2e3f:Performance{ uuid: '2f8fd807-a83e-4907-90f8-a350bf8f2e3f' })
SET perf_a350bf8f2e3f.name = 'Little Rootie Tootie'
SET perf_a350bf8f2e3f.duration = '4:47'
SET perf_a350bf8f2e3f.begin = '1981-11'
SET perf_a350bf8f2e3f.end = '1981-11'
SET perf_a350bf8f2e3f.source = 'musicbrainz.org'
SET perf_a350bf8f2e3f.timestamp = timestamp()

MERGE (perf_8bae23f6c1ef:Performance{ uuid: 'cea9bdc5-f574-4609-ac12-8bae23f6c1ef' })
SET perf_8bae23f6c1ef.name = 'Reflections'
SET perf_8bae23f6c1ef.duration = '6:43'
SET perf_8bae23f6c1ef.begin = '1981-11'
SET perf_8bae23f6c1ef.end = '1981-11'
SET perf_8bae23f6c1ef.source = 'musicbrainz.org'
SET perf_8bae23f6c1ef.timestamp = timestamp()

MERGE (perf_8383ee2a43c2:Performance{ uuid: '9bc1c4ac-f9ed-432a-9802-8383ee2a43c2' })
SET perf_8383ee2a43c2.name = 'Hackensack'
SET perf_8383ee2a43c2.duration = '6:11'
SET perf_8383ee2a43c2.begin = '1981-11'
SET perf_8383ee2a43c2.end = '1981-11'
SET perf_8383ee2a43c2.source = 'musicbrainz.org'
SET perf_8383ee2a43c2.timestamp = timestamp()



// labels
MERGE (release_3036fffd03c6)-[:HAS_LABEL]->(label_f31882443f89)
MERGE (release_3036fffd03c6)-[:HAS_LABEL]->(label_f31882443f89)


// tracks
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_40e229f7f9a0)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_4fdf76dfb0c1)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'A3', sequence: 3}]->(perf_4ff94ddc74a1)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'A4', sequence: 4}]->(perf_5f85e02703ce)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'A5', sequence: 5}]->(perf_3c42983159ee)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'B1', sequence: 6}]->(perf_975c551770ae)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'B2', sequence: 7}]->(perf_8667368361b6)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'B3', sequence: 8}]->(perf_60e787334344)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'C1', sequence: 1}]->(perf_38211d4f74ab)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'C2', sequence: 2}]->(perf_6fe5fcfd0768)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'C3', sequence: 3}]->(perf_e24ba555ac7f)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'C4', sequence: 4}]->(perf_e9a61da3df72)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'D1', sequence: 5}]->(perf_a350bf8f2e3f)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'D2', sequence: 6}]->(perf_8bae23f6c1ef)
MERGE (release_3036fffd03c6)-[:HAS_TRACK {name: 'D3', sequence: 7}]->(perf_8383ee2a43c2)

// works

MERGE (person_224ffa1c263c:Person{ uuid: '754ed78e-d5c5-4a5f-846d-224ffa1c263c' }) 
SET person_224ffa1c263c.name = 'Cootie Williams'
SET person_224ffa1c263c.gender = 'Male'
SET person_224ffa1c263c.country = 'US'
SET person_224ffa1c263c.allmusic = 'https://www.allmusic.com/artist/mn0000780401'
SET person_224ffa1c263c.discogs = 'https://www.discogs.com/artist/258696'
SET person_224ffa1c263c.imdb = 'https://www.imdb.com/name/nm1102362/'
SET person_224ffa1c263c.viaf = 'http://viaf.org/viaf/35779900'
SET person_224ffa1c263c.wikidata = 'https://www.wikidata.org/wiki/Q523899'
SET person_224ffa1c263c.databases = ['http://d-nb.info/gnd/134557468', 'http://id.loc.gov/authorities/names/n81095925', 'https://catalogue.bnf.fr/ark:/12148/cb13901176w', 'http://snaccooperative.org/ark:/99166/w6j10pt5', 'https://rateyourmusic.com/artist/cootie_williams', 'https://www.worldcat.org/identities/lccn-n81095925']
SET person_224ffa1c263c.musicbrainz = 'https://musicbrainz.org/artist/754ed78e-d5c5-4a5f-846d-224ffa1c263c'
SET person_224ffa1c263c.isni_list = ['http://isni.org/isni/0000000081896996', 'http://isni.org/isni/0000000120129248']
SET person_224ffa1c263c.source = 'musicbrainz.org'
SET person_224ffa1c263c.timestamp = timestamp()

MERGE (person_37e17d15cdab:Person{ uuid: '8598186d-826e-4860-b8c7-37e17d15cdab' }) 
SET person_37e17d15cdab.name = 'Bernie Hanighen'
SET person_37e17d15cdab.gender = 'Male'
SET person_37e17d15cdab.country = 'US'
SET person_37e17d15cdab.allmusic = 'https://www.allmusic.com/artist/mn0000049803'
SET person_37e17d15cdab.discogs = 'https://www.discogs.com/artist/264203'
SET person_37e17d15cdab.imdb = 'https://www.imdb.com/name/nm0359887/'
SET person_37e17d15cdab.viaf = 'http://viaf.org/viaf/78318349'
SET person_37e17d15cdab.wikidata = 'https://www.wikidata.org/wiki/Q4894399'
SET person_37e17d15cdab.databases = ['http://d-nb.info/gnd/134902696', 'http://id.loc.gov/authorities/names/no00016569', 'https://catalogue.bnf.fr/ark:/12148/cb13798018n', 'http://snaccooperative.org/ark:/99166/w6vj8k79', 'https://nla.gov.au/nla.party-1496866', 'https://rateyourmusic.com/artist/bernie_hanighen', 'https://www.ibdb.com/person.php?id=12695', 'https://www.worldcat.org/identities/lccn-no00016569/']
SET person_37e17d15cdab.musicbrainz = 'https://musicbrainz.org/artist/8598186d-826e-4860-b8c7-37e17d15cdab'
SET person_37e17d15cdab.isni_list = ['http://isni.org/isni/0000000039653181']
SET person_37e17d15cdab.source = 'musicbrainz.org'
SET person_37e17d15cdab.timestamp = timestamp()

MERGE (person_5260b4274ed4:Person{ uuid: '8e8c7417-c905-46b1-b42a-5260b4274ed4' }) 
SET person_5260b4274ed4.name = 'Thelonious Monk'
SET person_5260b4274ed4.gender = 'Male'
SET person_5260b4274ed4.country = 'US'
SET person_5260b4274ed4.allmusic = 'https://www.allmusic.com/artist/mn0000490416'
SET person_5260b4274ed4.bbc = 'https://www.bbc.co.uk/music/artists/8e8c7417-c905-46b1-b42a-5260b4274ed4'
SET person_5260b4274ed4.discogs = 'https://www.discogs.com/artist/145256'
SET person_5260b4274ed4.imdb = 'https://www.imdb.com/name/nm0598243/'
SET person_5260b4274ed4.viaf = 'http://viaf.org/viaf/44485892'
SET person_5260b4274ed4.wikidata = 'https://www.wikidata.org/wiki/Q109612'
SET person_5260b4274ed4.databases = ['http://d-nb.info/gnd/118826158', 'http://id.loc.gov/authorities/names/n82218969', 'https://catalogue.bnf.fr/ark:/12148/cb13897622g', 'http://snaccooperative.org/ark:/99166/w6j38zvn', 'https://rateyourmusic.com/artist/thelonious_monk', 'https://www.worldcat.org/identities/lccn-n82218969']
SET person_5260b4274ed4.musicbrainz = 'https://musicbrainz.org/artist/8e8c7417-c905-46b1-b42a-5260b4274ed4'
SET person_5260b4274ed4.isni_list = ['http://isni.org/isni/0000000120249127']
SET person_5260b4274ed4.source = 'musicbrainz.org'
SET person_5260b4274ed4.timestamp = timestamp()

MERGE (work_515f995542c2:Work{ uuid: '50993acd-521c-3292-9657-515f995542c2' })
SET work_515f995542c2.name = 'Little Rootie Tootie'
SET work_515f995542c2.iswc = 'T-700.038.157-9'
SET work_515f995542c2.type = 'Song'
SET work_515f995542c2.source = 'musicbrainz.org'
SET work_515f995542c2.timestamp = timestamp()

MERGE (work_74346b67d8e2:Work{ uuid: '8248d2b7-0645-4688-b152-74346b67d8e2' })
SET work_74346b67d8e2.name = 'Duet Improvisation, Part 1'
SET work_74346b67d8e2.source = 'musicbrainz.org'
SET work_74346b67d8e2.timestamp = timestamp()

MERGE (work_7d4e645db0e8:Work{ uuid: 'f37ef753-6bc6-4ad5-b6e3-7d4e645db0e8' })
SET work_7d4e645db0e8.name = 'Trio Improvisation, Part 2'
SET work_7d4e645db0e8.source = 'musicbrainz.org'
SET work_7d4e645db0e8.timestamp = timestamp()

MERGE (work_5bd419f08c0b:Work{ uuid: '7456a26a-f5a2-34cf-91c1-5bd419f08c0b' })
SET work_5bd419f08c0b.name = 'Eronel'
SET work_5bd419f08c0b.iswc = 'T-700.012.288-5'
SET work_5bd419f08c0b.type = 'Song'
SET work_5bd419f08c0b.source = 'musicbrainz.org'
SET work_5bd419f08c0b.timestamp = timestamp()

MERGE (work_5d188ed504b3:Work{ uuid: 'e7a36e93-5832-43df-b673-5d188ed504b3' })
SET work_5d188ed504b3.name = 'Duet Improvisation, Part 2'
SET work_5d188ed504b3.source = 'musicbrainz.org'
SET work_5d188ed504b3.timestamp = timestamp()

MERGE (work_c6cfe3b5cb12:Work{ uuid: '63ca960f-0c70-309f-b9f0-c6cfe3b5cb12' })
SET work_c6cfe3b5cb12.name = 'Reflections'
SET work_c6cfe3b5cb12.iswc = 'T-700.057.164-4'
SET work_c6cfe3b5cb12.type = 'Song'
SET work_c6cfe3b5cb12.source = 'musicbrainz.org'
SET work_c6cfe3b5cb12.timestamp = timestamp()

MERGE (work_1fcc2e48951a:Work{ uuid: '091fb98b-4a04-3a59-9a50-1fcc2e48951a' })
SET work_1fcc2e48951a.name = 'Think of One'
SET work_1fcc2e48951a.type = 'Song'
SET work_1fcc2e48951a.source = 'musicbrainz.org'
SET work_1fcc2e48951a.timestamp = timestamp()

MERGE (work_64fba31e3d56:Work{ uuid: '14b4ccd4-b4b8-3b50-8ff3-64fba31e3d56' })
SET work_64fba31e3d56.name = 'Hackensack'
SET work_64fba31e3d56.iswc = 'T-700.019.019-4'
SET work_64fba31e3d56.type = 'Song'
SET work_64fba31e3d56.musicbrainz = 'https://musicbrainz.org/work/14b4ccd4-b4b8-3b50-8ff3-64fba31e3d56'
SET work_64fba31e3d56.source = 'musicbrainz.org'
SET work_64fba31e3d56.timestamp = timestamp()

MERGE (work_93b2eae47c29:Work{ uuid: '022a61dc-6132-4991-a35e-93b2eae47c29' })
SET work_93b2eae47c29.name = 'Trio Improvisation, Part 1'
SET work_93b2eae47c29.source = 'musicbrainz.org'
SET work_93b2eae47c29.timestamp = timestamp()

MERGE (work_d979da217ad5:Work{ uuid: 'b4dc94ec-a90e-4d14-ba2b-d979da217ad5' })
SET work_d979da217ad5.name = 'Trio Improvisation, Part 4'
SET work_d979da217ad5.source = 'musicbrainz.org'
SET work_d979da217ad5.timestamp = timestamp()

MERGE (work_dd23a2697faf:Work{ uuid: 'ae24ff8f-7160-47b6-9ee5-dd23a2697faf' })
SET work_dd23a2697faf.name = 'Trio Improvisation, Part 5'
SET work_dd23a2697faf.source = 'musicbrainz.org'
SET work_dd23a2697faf.timestamp = timestamp()

MERGE (work_db6b69b449e2:Work{ uuid: '3bf12c6f-edc5-42a7-a364-db6b69b449e2' })
SET work_db6b69b449e2.name = 'Slippery When Wet'
SET work_db6b69b449e2.source = 'musicbrainz.org'
SET work_db6b69b449e2.timestamp = timestamp()

MERGE (work_1fb072ab2042:Work{ uuid: 'f99aa87a-d665-3d56-8df6-1fb072ab2042' })
SET work_1fb072ab2042.name = '’Round Midnight'
SET work_1fb072ab2042.iswc = 'T-070.002.363-7'
SET work_1fb072ab2042.type = 'Song'
SET work_1fb072ab2042.tags = ['jazz']
SET work_1fb072ab2042.wikidata = 'https://www.wikidata.org/wiki/Q383357'
SET work_1fb072ab2042.databases = ['http://d-nb.info/gnd/1031479511', 'http://id.loc.gov/authorities/names/no00058463', 'https://www.worldcat.org/identities/lccn-no00058463']
SET work_1fb072ab2042.musicbrainz = 'https://musicbrainz.org/work/f99aa87a-d665-3d56-8df6-1fb072ab2042'
SET work_1fb072ab2042.source = 'musicbrainz.org'
SET work_1fb072ab2042.timestamp = timestamp()

MERGE (work_ecaeddf44a98:Work{ uuid: 'ee619352-ce88-3fe2-a065-ecaeddf44a98' })
SET work_ecaeddf44a98.name = 'Rhythm-a-Ning'
SET work_ecaeddf44a98.iswc = 'T-700.057.764-2'
SET work_ecaeddf44a98.type = 'Song'
SET work_ecaeddf44a98.source = 'musicbrainz.org'
SET work_ecaeddf44a98.timestamp = timestamp()

MERGE (work_a664e2d8a5b5:Work{ uuid: '3df0d25b-2633-4194-a605-a664e2d8a5b5' })
SET work_a664e2d8a5b5.name = 'Trio Improvisation, Part 3'
SET work_a664e2d8a5b5.source = 'musicbrainz.org'
SET work_a664e2d8a5b5.timestamp = timestamp()


// performances of
MERGE (perf_a350bf8f2e3f)-[:PERFORMANCE_OF]->(work_515f995542c2)
MERGE (perf_5f85e02703ce)-[:PERFORMANCE_OF]->(work_74346b67d8e2)
MERGE (perf_4fdf76dfb0c1)-[:PERFORMANCE_OF]->(work_7d4e645db0e8)
MERGE (perf_e24ba555ac7f)-[:PERFORMANCE_OF]->(work_5bd419f08c0b)
MERGE (perf_3c42983159ee)-[:PERFORMANCE_OF]->(work_5d188ed504b3)
MERGE (perf_8bae23f6c1ef)-[:PERFORMANCE_OF]->(work_c6cfe3b5cb12)
MERGE (perf_e9a61da3df72)-[:PERFORMANCE_OF]->(work_1fcc2e48951a)
MERGE (perf_8383ee2a43c2)-[:PERFORMANCE_OF]->(work_64fba31e3d56)
MERGE (perf_40e229f7f9a0)-[:PERFORMANCE_OF]->(work_93b2eae47c29)
MERGE (perf_975c551770ae)-[:PERFORMANCE_OF]->(work_d979da217ad5)
MERGE (perf_8667368361b6)-[:PERFORMANCE_OF]->(work_dd23a2697faf)
MERGE (perf_60e787334344)-[:PERFORMANCE_OF]->(work_db6b69b449e2)
MERGE (perf_6fe5fcfd0768)-[:PERFORMANCE_OF]->(work_1fb072ab2042)
MERGE (perf_38211d4f74ab)-[:PERFORMANCE_OF]->(work_ecaeddf44a98)
MERGE (perf_4ff94ddc74a1)-[:PERFORMANCE_OF]->(work_a664e2d8a5b5)


// composers
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_515f995542c2)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_74346b67d8e2)
MERGE (person_be027b7bb16e)-[:COMPOSED]->(work_74346b67d8e2)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_7d4e645db0e8)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_7d4e645db0e8)
MERGE (person_be027b7bb16e)-[:COMPOSED]->(work_7d4e645db0e8)
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_5bd419f08c0b)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_5d188ed504b3)
MERGE (person_be027b7bb16e)-[:COMPOSED]->(work_5d188ed504b3)
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_c6cfe3b5cb12)
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_1fcc2e48951a)
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_64fba31e3d56)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_93b2eae47c29)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_93b2eae47c29)
MERGE (person_be027b7bb16e)-[:COMPOSED]->(work_93b2eae47c29)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_d979da217ad5)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_d979da217ad5)
MERGE (person_be027b7bb16e)-[:COMPOSED]->(work_d979da217ad5)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_dd23a2697faf)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_dd23a2697faf)
MERGE (person_be027b7bb16e)-[:COMPOSED]->(work_dd23a2697faf)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_db6b69b449e2)
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_1fb072ab2042)
MERGE (person_224ffa1c263c)-[:COMPOSED]->(work_1fb072ab2042)
MERGE (person_37e17d15cdab)-[:WROTE_LYRICS]->(work_1fb072ab2042)
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_ecaeddf44a98)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_a664e2d8a5b5)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_a664e2d8a5b5)
MERGE (person_be027b7bb16e)-[:COMPOSED]->(work_a664e2d8a5b5)


// place nodes

MERGE (place_2e4fb7f1f919:Place{ uuid: 'd9950f38-db0a-45be-8768-2e4fb7f1f919' })
SET place_2e4fb7f1f919.name = 'Bauer Studios'
SET place_2e4fb7f1f919.source = 'musicbrainz.org'

MERGE (place_d0318297fbb8:Place{ uuid: '709695e4-5fcb-4d7f-8fc0-d0318297fbb8' })
SET place_d0318297fbb8.name = 'Mad Hatter Studios'
SET place_d0318297fbb8.source = 'musicbrainz.org'


// place relationships
MERGE (perf_40e229f7f9a0)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_40e229f7f9a0)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_4fdf76dfb0c1)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_4fdf76dfb0c1)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_4ff94ddc74a1)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_4ff94ddc74a1)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_5f85e02703ce)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_5f85e02703ce)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_3c42983159ee)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_3c42983159ee)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_975c551770ae)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_975c551770ae)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_8667368361b6)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_8667368361b6)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_60e787334344)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_60e787334344)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_38211d4f74ab)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_38211d4f74ab)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_6fe5fcfd0768)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_6fe5fcfd0768)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_e24ba555ac7f)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_e24ba555ac7f)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_e9a61da3df72)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_e9a61da3df72)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_a350bf8f2e3f)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_a350bf8f2e3f)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_8bae23f6c1ef)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_8bae23f6c1ef)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)
MERGE (perf_8383ee2a43c2)-[:HAS_PLACE { type: 'mixed at' }]->(place_2e4fb7f1f919)
MERGE (perf_8383ee2a43c2)-[:HAS_PLACE { type: 'recorded at', begin: '1981-11', end: '1981-11' }]->(place_d0318297fbb8)

MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_40e229f7f9a0)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_40e229f7f9a0)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_40e229f7f9a0)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_40e229f7f9a0)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_4fdf76dfb0c1)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_4fdf76dfb0c1)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_4fdf76dfb0c1)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_4fdf76dfb0c1)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_4ff94ddc74a1)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_4ff94ddc74a1)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_4ff94ddc74a1)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_4ff94ddc74a1)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_5f85e02703ce)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_5f85e02703ce)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_5f85e02703ce)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_5f85e02703ce)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_3c42983159ee)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_3c42983159ee)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_3c42983159ee)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_3c42983159ee)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_975c551770ae)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_975c551770ae)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_975c551770ae)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_975c551770ae)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_8667368361b6)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_8667368361b6)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_8667368361b6)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_8667368361b6)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_60e787334344)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_60e787334344)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_60e787334344)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_60e787334344)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_38211d4f74ab)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_38211d4f74ab)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_38211d4f74ab)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_38211d4f74ab)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_6fe5fcfd0768)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_6fe5fcfd0768)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_6fe5fcfd0768)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_6fe5fcfd0768)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e24ba555ac7f)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_e24ba555ac7f)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_e24ba555ac7f)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_e24ba555ac7f)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e9a61da3df72)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_e9a61da3df72)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_e9a61da3df72)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_e9a61da3df72)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_a350bf8f2e3f)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_a350bf8f2e3f)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_a350bf8f2e3f)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_a350bf8f2e3f)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_8bae23f6c1ef)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_8bae23f6c1ef)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_8bae23f6c1ef)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_8bae23f6c1ef)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_8383ee2a43c2)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_8383ee2a43c2)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_8383ee2a43c2)
MERGE (person_2d752218d8f1)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_8383ee2a43c2)

