// releases

MERGE (release_e07e145d5b54:Release{ uuid: '2b01b641-ad01-4903-8028-e07e145d5b54' })
SET release_e07e145d5b54.name = 'Outward Bound'
SET release_e07e145d5b54.disambiguation = 'Original release, mono, deep groove, spindle ring on one side, A/B sides, purple label, laminated'
SET release_e07e145d5b54.country = 'US'
SET release_e07e145d5b54.date = '1960'
SET release_e07e145d5b54.format = '12" Vinyl'
SET release_e07e145d5b54.discode = 'NJLP 8236'
SET release_e07e145d5b54.discogs = 'https://www.discogs.com/release/2973552'
SET release_e07e145d5b54.musicbrainz = 'http://musicbrainz.org/release/2b01b641-ad01-4903-8028-e07e145d5b54'
SET release_e07e145d5b54.source = 'musicbrainz.org'
SET release_e07e145d5b54.timestamp = timestamp()

MERGE (person_a315ffe2a522:Person{ uuid: 'bc8ee7a2-727a-4af5-9954-a315ffe2a522' }) 
SET person_a315ffe2a522.name = 'George Tucker'
SET person_a315ffe2a522.gender = 'Male'
SET person_a315ffe2a522.disambiguation = 'bass'
SET person_a315ffe2a522.country = 'US'
SET person_a315ffe2a522.allmusic = 'https://www.allmusic.com/artist/mn0000647835'
SET person_a315ffe2a522.discogs = 'https://www.discogs.com/artist/295777'
SET person_a315ffe2a522.viaf = 'http://viaf.org/viaf/102397729'
SET person_a315ffe2a522.wikidata = 'https://www.wikidata.org/wiki/Q338805'
SET person_a315ffe2a522.wikipedia = 'https://en.wikipedia.org/wiki/George_Tucker_(musician)'
SET person_a315ffe2a522.databases = ['http://id.loc.gov/authorities/names/n91068818', 'https://catalogue.bnf.fr/ark:/12148/cb139005862', 'https://d-nb.info/gnd/134542983', 'https://www.worldcat.org/identities/lccn-n91068818']
SET person_a315ffe2a522.musicbrainz = 'https://musicbrainz.org/artist/bc8ee7a2-727a-4af5-9954-a315ffe2a522'
SET person_a315ffe2a522.isni_list = ['http://isni.org/isni/0000000107192605']
SET person_a315ffe2a522.source = 'musicbrainz.org'
SET person_a315ffe2a522.timestamp = timestamp()

MERGE (person_07467bdf0f71:Person{ uuid: 'badda5cf-f2c5-4dc2-b3d3-07467bdf0f71' }) 
SET person_07467bdf0f71.name = 'Eric Dolphy'
SET person_07467bdf0f71.gender = 'Male'
SET person_07467bdf0f71.country = 'US'
SET person_07467bdf0f71.allmusic = 'https://www.allmusic.com/artist/mn0000800100'
SET person_07467bdf0f71.bbc = 'https://www.bbc.co.uk/music/artists/badda5cf-f2c5-4dc2-b3d3-07467bdf0f71'
SET person_07467bdf0f71.discogs = 'https://www.discogs.com/artist/1239436'
SET person_07467bdf0f71.discogs = 'https://www.discogs.com/artist/145272'
SET person_07467bdf0f71.discogs = 'https://www.discogs.com/artist/327639'
SET person_07467bdf0f71.discogs = 'https://www.discogs.com/artist/5788817'
SET person_07467bdf0f71.discogs = 'https://www.discogs.com/artist/6932006'
SET person_07467bdf0f71.discogs = 'https://www.discogs.com/artist/943319'
SET person_07467bdf0f71.imdb = 'https://www.imdb.com/name/nm0231238/'
SET person_07467bdf0f71.viaf = 'http://viaf.org/viaf/66651545'
SET person_07467bdf0f71.wikidata = 'https://www.wikidata.org/wiki/Q367508'
SET person_07467bdf0f71.databases = ['http://id.loc.gov/authorities/names/n81035956', 'https://adp.library.ucsb.edu/names/312477', 'https://catalogue.bnf.fr/ark:/12148/cb13893337q', 'https://d-nb.info/gnd/118812866', 'http://snaccooperative.org/ark:/99166/w6s18p3z', 'https://nla.gov.au/nla.party-910562', 'https://rateyourmusic.com/artist/eric_dolphy', 'https://www.worldcat.org/identities/lccn-n81035956']
SET person_07467bdf0f71.musicbrainz = 'https://musicbrainz.org/artist/badda5cf-f2c5-4dc2-b3d3-07467bdf0f71'
SET person_07467bdf0f71.isni_list = ['http://isni.org/isni/000000008146531X', 'http://isni.org/isni/0000000081897569']
SET person_07467bdf0f71.source = 'musicbrainz.org'
SET person_07467bdf0f71.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://id.loc.gov/authorities/names/n81140108', 'https://adp.library.ucsb.edu/names/320530', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'https://d-nb.info/gnd/134400623', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_e327e692bb5a:Person{ uuid: '59ae7a1a-f454-435b-8a5a-e327e692bb5a' }) 
SET person_e327e692bb5a.name = 'Freddie Hubbard'
SET person_e327e692bb5a.gender = 'Male'
SET person_e327e692bb5a.country = 'US'
SET person_e327e692bb5a.allmusic = 'https://www.allmusic.com/artist/mn0000798326'
SET person_e327e692bb5a.bbc = 'https://www.bbc.co.uk/music/artists/59ae7a1a-f454-435b-8a5a-e327e692bb5a'
SET person_e327e692bb5a.discogs = 'https://www.discogs.com/artist/55745'
SET person_e327e692bb5a.imdb = 'https://www.imdb.com/name/nm0399174/'
SET person_e327e692bb5a.viaf = 'http://viaf.org/viaf/64192087'
SET person_e327e692bb5a.wikidata = 'https://www.wikidata.org/wiki/Q346762'
SET person_e327e692bb5a.databases = ['http://id.loc.gov/authorities/names/n83163529', 'https://catalogue.bnf.fr/ark:/12148/cb13895374d', 'https://d-nb.info/gnd/134411773', 'https://rateyourmusic.com/artist/freddie_hubbard', 'https://www.musik-sammler.de/artist/freddie-hubbard/', 'https://www.worldcat.org/identities/lccn-n83163529']
SET person_e327e692bb5a.musicbrainz = 'https://musicbrainz.org/artist/59ae7a1a-f454-435b-8a5a-e327e692bb5a'
SET person_e327e692bb5a.isni_list = ['http://isni.org/isni/0000000114462300']
SET person_e327e692bb5a.source = 'musicbrainz.org'
SET person_e327e692bb5a.timestamp = timestamp()

MERGE (person_05d508e09a73:Person{ uuid: 'f0707f1d-55e1-46b6-8a9c-05d508e09a73' }) 
SET person_05d508e09a73.name = 'Rudy van Gelder'
SET person_05d508e09a73.gender = 'Male'
SET person_05d508e09a73.country = 'US'
SET person_05d508e09a73.allmusic = 'https://www.allmusic.com/artist/mn0000305301'
SET person_05d508e09a73.discogs = 'https://www.discogs.com/artist/252966'
SET person_05d508e09a73.viaf = 'http://viaf.org/viaf/33997197'
SET person_05d508e09a73.wikidata = 'https://www.wikidata.org/wiki/Q945681'
SET person_05d508e09a73.databases = ['http://id.loc.gov/authorities/names/no00020144', 'https://d-nb.info/gnd/133648508', 'https://rateyourmusic.com/artist/rudy_van_gelder', 'https://www.worldcat.org/identities/lccn-no00020144']
SET person_05d508e09a73.musicbrainz = 'https://musicbrainz.org/artist/f0707f1d-55e1-46b6-8a9c-05d508e09a73'
SET person_05d508e09a73.isni_list = ['http://isni.org/isni/0000000019691076']
SET person_05d508e09a73.source = 'musicbrainz.org'
SET person_05d508e09a73.timestamp = timestamp()

MERGE (person_84a8b7f41799:Person{ uuid: '3f627e4e-4d29-45f0-8dd0-84a8b7f41799' }) 
SET person_84a8b7f41799.name = 'Jaki Byard'
SET person_84a8b7f41799.gender = 'Male'
SET person_84a8b7f41799.country = 'US'
SET person_84a8b7f41799.allmusic = 'https://www.allmusic.com/artist/mn0000112535'
SET person_84a8b7f41799.discogs = 'https://www.discogs.com/artist/252610'
SET person_84a8b7f41799.viaf = 'http://viaf.org/viaf/61731187'
SET person_84a8b7f41799.wikidata = 'https://www.wikidata.org/wiki/Q1346401'
SET person_84a8b7f41799.databases = ['http://id.loc.gov/authorities/names/n78048954', 'https://catalogue.bnf.fr/ark:/12148/cb138920338', 'https://d-nb.info/gnd/134582888', 'http://snaccooperative.org/ark:/99166/w6pg2qp8', 'https://www.worldcat.org/identities/lccn-n78048954']
SET person_84a8b7f41799.musicbrainz = 'https://musicbrainz.org/artist/3f627e4e-4d29-45f0-8dd0-84a8b7f41799'
SET person_84a8b7f41799.isni_list = ['http://isni.org/isni/0000000096156501']
SET person_84a8b7f41799.source = 'musicbrainz.org'
SET person_84a8b7f41799.timestamp = timestamp()
// labels

MERGE (label_d510b586b396:Label{ uuid: '3690758a-3ec1-4fd3-a250-d510b586b396' })
SET label_d510b586b396.name= 'New Jazz'

// performances

MERGE (perf_6b994eb9d31f:Performance{ uuid: 'ed8e9ee5-c6c7-4f81-901b-6b994eb9d31f' })
SET perf_6b994eb9d31f.name = 'G.W.'
SET perf_6b994eb9d31f.disambiguation = 'studio, 1960-04-01: 2101 Prestige (Outward Bound), main take'
SET perf_6b994eb9d31f.duration = '7:58'
SET perf_6b994eb9d31f.begin = '1960-04-01'
SET perf_6b994eb9d31f.end = '1960-04-01'
SET perf_6b994eb9d31f.source = 'musicbrainz.org'
SET perf_6b994eb9d31f.timestamp = timestamp()

MERGE (perf_08dba9f9c4b0:Performance{ uuid: '52b02148-d63d-4b9c-8463-08dba9f9c4b0' })
SET perf_08dba9f9c4b0.name = 'On Green Dolphin Street'
SET perf_08dba9f9c4b0.disambiguation = 'studio, 1960-04-01: 2103 Prestige (Outward Bound)'
SET perf_08dba9f9c4b0.duration = '5:45'
SET perf_08dba9f9c4b0.begin = '1960-04-01'
SET perf_08dba9f9c4b0.end = '1960-04-01'
SET perf_08dba9f9c4b0.source = 'musicbrainz.org'
SET perf_08dba9f9c4b0.timestamp = timestamp()

MERGE (perf_5e9f4da9bb0d:Performance{ uuid: '31398d3f-6eab-46cd-80e5-5e9f4da9bb0d' })
SET perf_5e9f4da9bb0d.name = 'Les'
SET perf_5e9f4da9bb0d.disambiguation = 'studio, 1960-04-01: 2105 Prestige (Outward Bound)'
SET perf_5e9f4da9bb0d.duration = '5:14'
SET perf_5e9f4da9bb0d.begin = '1960-04-01'
SET perf_5e9f4da9bb0d.end = '1960-04-01'
SET perf_5e9f4da9bb0d.source = 'musicbrainz.org'
SET perf_5e9f4da9bb0d.timestamp = timestamp()

MERGE (perf_457c08c66ba1:Performance{ uuid: '5caf5949-63c0-4f0b-a05c-457c08c66ba1' })
SET perf_457c08c66ba1.name = '245'
SET perf_457c08c66ba1.disambiguation = 'studio, 1960-04-01: 2102 Prestige (Outward Bound)'
SET perf_457c08c66ba1.duration = '6:49'
SET perf_457c08c66ba1.begin = '1960-04-01'
SET perf_457c08c66ba1.end = '1960-04-01'
SET perf_457c08c66ba1.source = 'musicbrainz.org'
SET perf_457c08c66ba1.timestamp = timestamp()

MERGE (perf_e983a0ea6e95:Performance{ uuid: '6bd50779-9c2c-4acb-b9ac-e983a0ea6e95' })
SET perf_e983a0ea6e95.name = 'Glad to Be Unhappy'
SET perf_e983a0ea6e95.disambiguation = 'studio, 1960-04-01: 2104 Prestige (Outward Bound)'
SET perf_e983a0ea6e95.duration = '5:29'
SET perf_e983a0ea6e95.begin = '1960-04-01'
SET perf_e983a0ea6e95.end = '1960-04-01'
SET perf_e983a0ea6e95.source = 'musicbrainz.org'
SET perf_e983a0ea6e95.timestamp = timestamp()

MERGE (perf_ba25a9a72b45:Performance{ uuid: 'c15a6ccc-12d5-427f-aeac-ba25a9a72b45' })
SET perf_ba25a9a72b45.name = 'Miss Toni'
SET perf_ba25a9a72b45.disambiguation = 'studio, 1960-04-01: 2106 Prestige (Outward Bound)'
SET perf_ba25a9a72b45.duration = '5:41'
SET perf_ba25a9a72b45.begin = '1960-04-01'
SET perf_ba25a9a72b45.end = '1960-04-01'
SET perf_ba25a9a72b45.source = 'musicbrainz.org'
SET perf_ba25a9a72b45.timestamp = timestamp()



// labels
MERGE (release_e07e145d5b54)-[:HAS_LABEL]->(label_d510b586b396)


// tracks
MERGE (release_e07e145d5b54)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_6b994eb9d31f)
MERGE (release_e07e145d5b54)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_08dba9f9c4b0)
MERGE (release_e07e145d5b54)-[:HAS_TRACK {name: 'A3', sequence: 3}]->(perf_5e9f4da9bb0d)
MERGE (release_e07e145d5b54)-[:HAS_TRACK {name: 'B1', sequence: 4}]->(perf_457c08c66ba1)
MERGE (release_e07e145d5b54)-[:HAS_TRACK {name: 'B2', sequence: 5}]->(perf_e983a0ea6e95)
MERGE (release_e07e145d5b54)-[:HAS_TRACK {name: 'B3', sequence: 6}]->(perf_ba25a9a72b45)

// works

MERGE (person_acc0205f7513:Person{ uuid: '346448f5-25a0-4f78-bbd6-acc0205f7513' }) 
SET person_acc0205f7513.name = 'Richard Rodgers'
SET person_acc0205f7513.gender = 'Male'
SET person_acc0205f7513.disambiguation = 'composer'
SET person_acc0205f7513.country = 'US'
SET person_acc0205f7513.allmusic = 'https://www.allmusic.com/artist/mn0000820913'
SET person_acc0205f7513.bbc = 'https://www.bbc.co.uk/music/artists/346448f5-25a0-4f78-bbd6-acc0205f7513'
SET person_acc0205f7513.discogs = 'https://www.discogs.com/artist/255801'
SET person_acc0205f7513.imdb = 'https://www.imdb.com/name/nm0006256/'
SET person_acc0205f7513.viaf = 'http://viaf.org/viaf/113475079'
SET person_acc0205f7513.wikidata = 'https://www.wikidata.org/wiki/Q269094'
SET person_acc0205f7513.databases = ['http://id.loc.gov/authorities/names/n50048058', 'https://adp.library.ucsb.edu/names/102086', 'https://catalogue.bnf.fr/ark:/12148/cb13899099w', 'https://d-nb.info/gnd/118790862', 'https://ibdb.com/person.php?id=8323', 'http://snaccooperative.org/ark:/99166/w69h6cvt', 'https://nla.gov.au/nla.party-1015762', 'https://openlibrary.org/works/OL35365A', 'https://rateyourmusic.com/artist/richard_rodgers', 'https://www.worldcat.org/identities/lccn-n50048058/']
SET person_acc0205f7513.musicbrainz = 'https://musicbrainz.org/artist/346448f5-25a0-4f78-bbd6-acc0205f7513'
SET person_acc0205f7513.isni_list = ['http://isni.org/isni/0000000121482043']
SET person_acc0205f7513.source = 'musicbrainz.org'
SET person_acc0205f7513.timestamp = timestamp()

MERGE (person_9ecd8b2daa0d:Person{ uuid: '0fb41597-d1a0-480c-93f3-9ecd8b2daa0d' }) 
SET person_9ecd8b2daa0d.name = 'Ned Washington'
SET person_9ecd8b2daa0d.gender = 'Male'
SET person_9ecd8b2daa0d.country = 'US'
SET person_9ecd8b2daa0d.allmusic = 'https://www.allmusic.com/artist/mn0000324645'
SET person_9ecd8b2daa0d.discogs = 'https://www.discogs.com/artist/299280'
SET person_9ecd8b2daa0d.imdb = 'https://www.imdb.com/name/nm0913513/'
SET person_9ecd8b2daa0d.viaf = 'http://viaf.org/viaf/69121638'
SET person_9ecd8b2daa0d.wikidata = 'https://www.wikidata.org/wiki/Q1973924'
SET person_9ecd8b2daa0d.databases = ['http://id.loc.gov/authorities/names/no89006651', 'https://adp.library.ucsb.edu/names/108781', 'https://catalogue.bnf.fr/ark:/12148/cb13952962p', 'https://d-nb.info/gnd/130173606', 'http://snaccooperative.org/ark:/99166/w6g73q46', 'https://nla.gov.au/nla.party-1494135', 'https://openlibrary.org/works/OL363737A', 'https://rateyourmusic.com/artist/ned_washington', 'https://www.ibdb.com/person.php?id=12550', 'https://www.worldcat.org/identities/lccn-no89006651/']
SET person_9ecd8b2daa0d.musicbrainz = 'https://musicbrainz.org/artist/0fb41597-d1a0-480c-93f3-9ecd8b2daa0d'
SET person_9ecd8b2daa0d.isni_list = ['http://isni.org/isni/0000000081490873']
SET person_9ecd8b2daa0d.source = 'musicbrainz.org'
SET person_9ecd8b2daa0d.timestamp = timestamp()

MERGE (person_cea001d23165:Person{ uuid: '868344f0-bbc4-4ce5-8fb4-cea001d23165' }) 
SET person_cea001d23165.name = 'Charles Greenlee'
SET person_cea001d23165.gender = 'Male'
SET person_cea001d23165.country = 'US'
SET person_cea001d23165.allmusic = 'https://www.allmusic.com/artist/mn0000204240'
SET person_cea001d23165.discogs = 'https://www.discogs.com/artist/282467'
SET person_cea001d23165.viaf = 'http://viaf.org/viaf/79686568'
SET person_cea001d23165.wikidata = 'https://www.wikidata.org/wiki/Q1064616'
SET person_cea001d23165.wikipedia = 'https://en.wikipedia.org/wiki/Charles_Greenlee_(musician)'
SET person_cea001d23165.databases = ['http://id.loc.gov/authorities/names/nr90019590', 'https://catalogue.bnf.fr/ark:/12148/cb14183287q', 'https://d-nb.info/gnd/134592859', 'https://www.worldcat.org/identities/lccn-nr90019590']
SET person_cea001d23165.musicbrainz = 'https://musicbrainz.org/artist/868344f0-bbc4-4ce5-8fb4-cea001d23165'
SET person_cea001d23165.isni_list = ['http://isni.org/isni/0000000056503249']
SET person_cea001d23165.source = 'musicbrainz.org'
SET person_cea001d23165.timestamp = timestamp()

MERGE (person_6b36e322507b:Person{ uuid: 'cdc82126-9892-4bed-864d-6b36e322507b' }) 
SET person_6b36e322507b.name = 'Bronisław Kaper'
SET person_6b36e322507b.gender = 'Male'
SET person_6b36e322507b.country = 'US'
SET person_6b36e322507b.allmusic = 'https://www.allmusic.com/artist/mn0003217868'
SET person_6b36e322507b.discogs = 'https://www.discogs.com/artist/715404'
SET person_6b36e322507b.imdb = 'https://www.imdb.com/name/nm0006147/'
SET person_6b36e322507b.viaf = 'http://viaf.org/viaf/59273738'
SET person_6b36e322507b.wikidata = 'https://www.wikidata.org/wiki/Q927472'
SET person_6b36e322507b.databases = ['http://id.loc.gov/authorities/names/n79075647', 'https://adp.library.ucsb.edu/names/102422', 'https://catalogue.bnf.fr/ark:/12148/cb139401963', 'https://d-nb.info/gnd/130206156', 'https://nla.gov.au/nla.party-1082410', 'http://soundtrackcollector.com/composer/88/', 'https://www.ibdb.com/person.php?id=11976', 'https://www.worldcat.org/identities/lccn-n79075647']
SET person_6b36e322507b.musicbrainz = 'https://musicbrainz.org/artist/cdc82126-9892-4bed-864d-6b36e322507b'
SET person_6b36e322507b.isni_list = ['http://isni.org/isni/0000000121351385']
SET person_6b36e322507b.source = 'musicbrainz.org'
SET person_6b36e322507b.timestamp = timestamp()

MERGE (person_1904aa4268f4:Person{ uuid: '3fb75d97-5dfd-4e72-9aee-1904aa4268f4' }) 
SET person_1904aa4268f4.name = 'Lorenz Hart'
SET person_1904aa4268f4.gender = 'Male'
SET person_1904aa4268f4.country = 'US'
SET person_1904aa4268f4.allmusic = 'https://www.allmusic.com/artist/mn0000209620'
SET person_1904aa4268f4.discogs = 'https://www.discogs.com/artist/255800'
SET person_1904aa4268f4.imdb = 'https://www.imdb.com/name/nm0366414/'
SET person_1904aa4268f4.viaf = 'http://viaf.org/viaf/5122279'
SET person_1904aa4268f4.wikidata = 'https://www.wikidata.org/wiki/Q725828'
SET person_1904aa4268f4.databases = ['http://id.loc.gov/authorities/names/n81097890', 'https://adp.library.ucsb.edu/names/103285', 'https://catalogue.bnf.fr/ark:/12148/cb13939224g', 'https://d-nb.info/gnd/118720538', 'https://ibdb.com/Person/View/11244', 'http://snaccooperative.org/ark:/99166/w6x34z1s', 'https://nla.gov.au/nla.party-1266476', 'https://openlibrary.org/works/OL446542A', 'https://rateyourmusic.com/artist/lorenz_hart', 'https://www.worldcat.org/identities/lccn-n81097890/', 'http://www.lortel.org/LLA_archive/index.cfm?search_by=people&first=Lorenz&last=Hart&middle=']
SET person_1904aa4268f4.musicbrainz = 'https://musicbrainz.org/artist/3fb75d97-5dfd-4e72-9aee-1904aa4268f4'
SET person_1904aa4268f4.isni_list = ['http://isni.org/isni/0000000083526307']
SET person_1904aa4268f4.source = 'musicbrainz.org'
SET person_1904aa4268f4.timestamp = timestamp()

MERGE (work_ef33ddf69a33:Work{ uuid: 'a0d2a07a-aaba-418b-ae08-ef33ddf69a33' })
SET work_ef33ddf69a33.name = '245'
SET work_ef33ddf69a33.iswc = 'T-070.940.951-7'
SET work_ef33ddf69a33.type = 'Song'
SET work_ef33ddf69a33.source = 'musicbrainz.org'
SET work_ef33ddf69a33.timestamp = timestamp()

MERGE (work_e5e3eabb72ba:Work{ uuid: '39d87891-d664-3db0-a4a3-e5e3eabb72ba' })
SET work_e5e3eabb72ba.name = 'On Green Dolphin Street'
SET work_e5e3eabb72ba.iswc = 'T-070.158.829-5'
SET work_e5e3eabb72ba.type = 'Song'
SET work_e5e3eabb72ba.wikidata = 'https://www.wikidata.org/wiki/Q2023627'
SET work_e5e3eabb72ba.musicbrainz = 'https://musicbrainz.org/work/39d87891-d664-3db0-a4a3-e5e3eabb72ba'
SET work_e5e3eabb72ba.source = 'musicbrainz.org'
SET work_e5e3eabb72ba.timestamp = timestamp()

MERGE (work_90543f4f8220:Work{ uuid: '2cce480d-1006-4fd2-870e-90543f4f8220' })
SET work_90543f4f8220.name = 'G.W.'
SET work_90543f4f8220.iswc = 'T-070.881.529-5'
SET work_90543f4f8220.type = 'Song'
SET work_90543f4f8220.source = 'musicbrainz.org'
SET work_90543f4f8220.timestamp = timestamp()

MERGE (work_7a6978b2ad8f:Work{ uuid: 'd0bf9b68-a1f9-318d-9f5f-7a6978b2ad8f' })
SET work_7a6978b2ad8f.name = 'Glad to Be Unhappy'
SET work_7a6978b2ad8f.iswc = 'T-070.064.331-7'
SET work_7a6978b2ad8f.type = 'Song'
SET work_7a6978b2ad8f.wikidata = 'https://www.wikidata.org/wiki/Q5566200'
SET work_7a6978b2ad8f.musicbrainz = 'https://musicbrainz.org/work/d0bf9b68-a1f9-318d-9f5f-7a6978b2ad8f'
SET work_7a6978b2ad8f.source = 'musicbrainz.org'
SET work_7a6978b2ad8f.timestamp = timestamp()

MERGE (work_69aaac4d84c0:Work{ uuid: '93bfb56a-5da1-4680-b418-69aaac4d84c0' })
SET work_69aaac4d84c0.name = 'Les'
SET work_69aaac4d84c0.iswc = 'T-700.036.358-8'
SET work_69aaac4d84c0.musicbrainz = 'https://musicbrainz.org/work/93bfb56a-5da1-4680-b418-69aaac4d84c0'
SET work_69aaac4d84c0.source = 'musicbrainz.org'
SET work_69aaac4d84c0.timestamp = timestamp()

MERGE (work_8e3ca0bc3dfe:Work{ uuid: '2a59a90d-a3d2-478f-9baf-8e3ca0bc3dfe' })
SET work_8e3ca0bc3dfe.name = 'Miss Toni'
SET work_8e3ca0bc3dfe.iswc = 'T-700.044.250-4'
SET work_8e3ca0bc3dfe.type = 'Song'
SET work_8e3ca0bc3dfe.source = 'musicbrainz.org'
SET work_8e3ca0bc3dfe.timestamp = timestamp()


// performances of
MERGE (perf_457c08c66ba1)-[:PERFORMANCE_OF]->(work_ef33ddf69a33)
MERGE (perf_08dba9f9c4b0)-[:PERFORMANCE_OF]->(work_e5e3eabb72ba)
MERGE (perf_6b994eb9d31f)-[:PERFORMANCE_OF]->(work_90543f4f8220)
MERGE (perf_e983a0ea6e95)-[:PERFORMANCE_OF]->(work_7a6978b2ad8f)
MERGE (perf_5e9f4da9bb0d)-[:PERFORMANCE_OF]->(work_69aaac4d84c0)
MERGE (perf_ba25a9a72b45)-[:PERFORMANCE_OF]->(work_8e3ca0bc3dfe)


// composers
MERGE (person_07467bdf0f71)-[:COMPOSED]->(work_ef33ddf69a33)
MERGE (person_6b36e322507b)-[:COMPOSED]->(work_e5e3eabb72ba)
MERGE (person_9ecd8b2daa0d)-[:WROTE_LYRICS]->(work_e5e3eabb72ba)
MERGE (person_07467bdf0f71)-[:COMPOSED]->(work_90543f4f8220)
MERGE (person_acc0205f7513)-[:COMPOSED]->(work_7a6978b2ad8f)
MERGE (person_1904aa4268f4)-[:WROTE_LYRICS]->(work_7a6978b2ad8f)
MERGE (person_07467bdf0f71)-[:COMPOSED]->(work_69aaac4d84c0)
MERGE (person_cea001d23165)-[:COMPOSED]->(work_8e3ca0bc3dfe)


// place nodes

MERGE (place_569fa8b97644:Place{ uuid: '1165ef7d-371c-4e03-98db-569fa8b97644' })
SET place_569fa8b97644.name = 'Van Gelder Studio'
SET place_569fa8b97644.source = 'musicbrainz.org'


// place relationships
MERGE (perf_6b994eb9d31f)-[:HAS_PLACE { type: 'recorded at', begin: '1960-04-01', end: '1960-04-01' }]->(place_569fa8b97644)
MERGE (perf_08dba9f9c4b0)-[:HAS_PLACE { type: 'recorded at', begin: '1960-04-01', end: '1960-04-01' }]->(place_569fa8b97644)
MERGE (perf_5e9f4da9bb0d)-[:HAS_PLACE { type: 'recorded at', begin: '1960-04-01', end: '1960-04-01' }]->(place_569fa8b97644)
MERGE (perf_457c08c66ba1)-[:HAS_PLACE { type: 'recorded at', begin: '1960-04-01', end: '1960-04-01' }]->(place_569fa8b97644)
MERGE (perf_e983a0ea6e95)-[:HAS_PLACE { type: 'recorded at', begin: '1960-04-01', end: '1960-04-01' }]->(place_569fa8b97644)
MERGE (perf_ba25a9a72b45)-[:HAS_PLACE { type: 'recorded at', begin: '1960-04-01', end: '1960-04-01' }]->(place_569fa8b97644)

MERGE (person_84a8b7f41799)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_6b994eb9d31f)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_6b994eb9d31f)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_6b994eb9d31f)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_6b994eb9d31f)
MERGE (person_a315ffe2a522)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_6b994eb9d31f)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_6b994eb9d31f)
MERGE (person_84a8b7f41799)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_08dba9f9c4b0)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass clarinet'] }]->(perf_08dba9f9c4b0)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_08dba9f9c4b0)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_08dba9f9c4b0)
MERGE (person_a315ffe2a522)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_08dba9f9c4b0)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_08dba9f9c4b0)
MERGE (person_84a8b7f41799)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_5e9f4da9bb0d)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_5e9f4da9bb0d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_5e9f4da9bb0d)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_5e9f4da9bb0d)
MERGE (person_a315ffe2a522)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_5e9f4da9bb0d)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_5e9f4da9bb0d)
MERGE (person_84a8b7f41799)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_457c08c66ba1)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_457c08c66ba1)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_457c08c66ba1)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_457c08c66ba1)
MERGE (person_a315ffe2a522)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_457c08c66ba1)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_457c08c66ba1)
MERGE (person_84a8b7f41799)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e983a0ea6e95)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute'] }]->(perf_e983a0ea6e95)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_e983a0ea6e95)
MERGE (person_a315ffe2a522)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_e983a0ea6e95)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_e983a0ea6e95)
MERGE (person_84a8b7f41799)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_ba25a9a72b45)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass clarinet'] }]->(perf_ba25a9a72b45)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_ba25a9a72b45)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_ba25a9a72b45)
MERGE (person_a315ffe2a522)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_ba25a9a72b45)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_ba25a9a72b45)

// liner notes
MERGE (person_c3ea1fca0dd8:Person{ uuid: '95e86db2-7d52-48ed-a4cb-c3ea1fca0dd8' })
SET person_c3ea1fca0dd8.name = 'Ron Eyre'
SET person_c3ea1fca0dd8.gender = 'Male'
SET person_c3ea1fca0dd8.country = 'US'
SET person_c3ea1fca0dd8.discogs = 'https://www.discogs.com/artist/1650513-Ron-Eyre'
SET person_c3ea1fca0dd8.musicbrainz = 'https://musicbrainz.org/artist/95e86db2-7d52-48ed-a4cb-c3ea1fca0dd8'
SET person_c3ea1fca0dd8.source = 'musicbrainz.org'

MERGE (liner_notes_ef33ddf69a55:LinerNotes{ uuid: 'a0d2a07a-aaba-418b-ae08-ef33ddf69a55' })
SET liner_notes_ef33ddf69a55.name = 'Outward Bound, Liner Notes by Ron Eyre'
SET liner_notes_ef33ddf69a55.date = '1960'
SET liner_notes_ef33ddf69a55.type = 'Original'
SET liner_notes_ef33ddf69a55.thejazztome = 'https://thejazztome.info/eric-dolphy-outward-bound/'
SET liner_notes_ef33ddf69a55.internetarchive = 'https://archive.org/details/cd_outward-bound_eric-dolphy/page/n1/mode/1up'
SET liner_notes_ef33ddf69a55.discogs = 'https://i.discogs.com/Kqj9UxgaHbqXSf6udE4xXcjmGytLYW5tLY55FvvhTx8/rs:fit/g:sm/q:90/h:600/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5NzM1/NTItMTQ1ODAwMjY1/Ni04OTk5LmpwZWc.jpeg'


MERGE (person_c3ea1fca0dd8)-[:AUTHORED]->(liner_notes_ef33ddf69a55)

MERGE (release_e07e145d5b54)-[:HAS_LINER_NOTES]->(liner_notes_ef33ddf69a55)