// releases

MERGE (release_2bfffd00cdc9:Release{ uuid: 'a151f61f-a873-49cc-b9d5-2bfffd00cdc9' })
SET release_2bfffd00cdc9.name = 'Wanton Spirit'
SET release_2bfffd00cdc9.country = 'FR'
SET release_2bfffd00cdc9.date = '1994'
SET release_2bfffd00cdc9.format = 'CD'
SET release_2bfffd00cdc9.discode = '522 364-2'
SET release_2bfffd00cdc9.musicbrainz = 'http://musicbrainz.org/release/a151f61f-a873-49cc-b9d5-2bfffd00cdc9'
SET release_2bfffd00cdc9.source = 'musicbrainz.org'
SET release_2bfffd00cdc9.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://d-nb.info/gnd/134400623', 'http://id.loc.gov/authorities/names/n81140108', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_37ec0c289b48:Person{ uuid: '1f0cdc02-c8d5-4228-8227-37ec0c289b48' }) 
SET person_37ec0c289b48.name = 'Charlie Haden'
SET person_37ec0c289b48.gender = 'Male'
SET person_37ec0c289b48.disambiguation = 'American jazz bassist'
SET person_37ec0c289b48.country = 'US'
SET person_37ec0c289b48.allmusic = 'https://www.allmusic.com/artist/mn0000211483'
SET person_37ec0c289b48.bbc = 'https://www.bbc.co.uk/music/artists/1f0cdc02-c8d5-4228-8227-37ec0c289b48'
SET person_37ec0c289b48.discogs = 'https://www.discogs.com/artist/253592'
SET person_37ec0c289b48.imdb = 'https://www.imdb.com/name/nm0352767/'
SET person_37ec0c289b48.viaf = 'http://viaf.org/viaf/19865496'
SET person_37ec0c289b48.wikidata = 'https://www.wikidata.org/wiki/Q319283'
SET person_37ec0c289b48.databases = ['http://d-nb.info/gnd/134394712', 'http://id.loc.gov/authorities/names/n81146634', 'https://catalogue.bnf.fr/ark:/12148/cb138948678', 'http://snaccooperative.org/ark:/99166/w6007mkj', 'https://rateyourmusic.com/artist/charlie_haden', 'https://www.musik-sammler.de/artist/charlie-haden/', 'https://www.worldcat.org/identities/lccn-n81146634']
SET person_37ec0c289b48.musicbrainz = 'https://musicbrainz.org/artist/1f0cdc02-c8d5-4228-8227-37ec0c289b48'
SET person_37ec0c289b48.isni_list = ['http://isni.org/isni/0000000083624572']
SET person_37ec0c289b48.source = 'musicbrainz.org'
SET person_37ec0c289b48.timestamp = timestamp()

MERGE (person_120e386da267:Person{ uuid: '6b2e6e7c-4289-447c-a3dc-120e386da267' }) 
SET person_120e386da267.name = 'Kenny Barron'
SET person_120e386da267.gender = 'Male'
SET person_120e386da267.country = 'US'
SET person_120e386da267.allmusic = 'https://www.allmusic.com/artist/mn0000081181'
SET person_120e386da267.discogs = 'https://www.discogs.com/artist/65746'
SET person_120e386da267.imdb = 'https://www.imdb.com/name/nm0057686/'
SET person_120e386da267.viaf = 'http://viaf.org/viaf/119903038'
SET person_120e386da267.wikidata = 'https://www.wikidata.org/wiki/Q489233'
SET person_120e386da267.databases = ['http://d-nb.info/gnd/134321804', 'http://id.loc.gov/authorities/names/n80124274', 'https://catalogue.bnf.fr/ark:/12148/cb13891186w', 'http://snaccooperative.org/ark:/99166/w6c5871b', 'https://rateyourmusic.com/artist/kenny_barron', 'https://www.musik-sammler.de/artist/kenny-barron/', 'https://www.worldcat.org/identities/lccn-n80124274']
SET person_120e386da267.musicbrainz = 'https://musicbrainz.org/artist/6b2e6e7c-4289-447c-a3dc-120e386da267'
SET person_120e386da267.isni_list = ['http://isni.org/isni/0000000081889024']
SET person_120e386da267.source = 'musicbrainz.org'
SET person_120e386da267.timestamp = timestamp()

MERGE (person_82d3fd2469d4:Person{ uuid: '6974ce3e-456b-42ff-a35a-82d3fd2469d4' }) 
SET person_82d3fd2469d4.name = 'Joanne Klein'
SET person_82d3fd2469d4.gender = 'Female'
SET person_82d3fd2469d4.discogs = 'https://www.discogs.com/artist/1940648'
SET person_82d3fd2469d4.musicbrainz = 'https://musicbrainz.org/artist/6974ce3e-456b-42ff-a35a-82d3fd2469d4'
SET person_82d3fd2469d4.source = 'musicbrainz.org'
SET person_82d3fd2469d4.timestamp = timestamp()

MERGE (person_b0f2dfbe8828:Person{ uuid: '4a7e4896-7c3f-48a2-b658-b0f2dfbe8828' }) 
SET person_b0f2dfbe8828.name = 'Don Ranieri'
SET person_b0f2dfbe8828.gender = 'Male'
SET person_b0f2dfbe8828.discogs = 'https://www.discogs.com/artist/1031840'
SET person_b0f2dfbe8828.musicbrainz = 'https://musicbrainz.org/artist/4a7e4896-7c3f-48a2-b658-b0f2dfbe8828'
SET person_b0f2dfbe8828.source = 'musicbrainz.org'
SET person_b0f2dfbe8828.timestamp = timestamp()

MERGE (person_6d0bc0ca74fd:Person{ uuid: '850dba82-4abb-44d0-b498-6d0bc0ca74fd' }) 
SET person_6d0bc0ca74fd.name = 'Joe Marciano'
SET person_6d0bc0ca74fd.gender = 'Male'
SET person_6d0bc0ca74fd.country = 'US'
SET person_6d0bc0ca74fd.discogs = 'https://www.discogs.com/artist/327388'
SET person_6d0bc0ca74fd.databases = ['https://rateyourmusic.com/artist/joe_marciano']
SET person_6d0bc0ca74fd.musicbrainz = 'https://musicbrainz.org/artist/850dba82-4abb-44d0-b498-6d0bc0ca74fd'
SET person_6d0bc0ca74fd.source = 'musicbrainz.org'
SET person_6d0bc0ca74fd.timestamp = timestamp()
// labels

MERGE (label_4b4670dc9f4f:Label{ uuid: '5c995217-2129-417a-82e3-4b4670dc9f4f' })
SET label_4b4670dc9f4f.name= 'Gitanes Jazz Productions'

// performances

MERGE (perf_846ac138be11:Performance{ uuid: 'd8efd19a-95cb-47b7-a113-846ac138be11' })
SET perf_846ac138be11.name = 'Take the Coltrane'
SET perf_846ac138be11.duration = '6:10'
SET perf_846ac138be11.begin = '1994-02-22'
SET perf_846ac138be11.end = '1994-02-23'
SET perf_846ac138be11.source = 'musicbrainz.org'
SET perf_846ac138be11.timestamp = timestamp()

MERGE (perf_7e10ca2eeeb1:Performance{ uuid: '79cba5fb-de49-42b6-9b3d-7e10ca2eeeb1' })
SET perf_7e10ca2eeeb1.name = 'Sail Away'
SET perf_7e10ca2eeeb1.duration = '6:27'
SET perf_7e10ca2eeeb1.begin = '1994-02-22'
SET perf_7e10ca2eeeb1.end = '1994-02-23'
SET perf_7e10ca2eeeb1.source = 'musicbrainz.org'
SET perf_7e10ca2eeeb1.timestamp = timestamp()

MERGE (perf_58dba01eacda:Performance{ uuid: 'cd0e18ee-c30f-49e6-b2ed-58dba01eacda' })
SET perf_58dba01eacda.name = 'Bebop'
SET perf_58dba01eacda.duration = '8:34'
SET perf_58dba01eacda.begin = '1994-02-22'
SET perf_58dba01eacda.end = '1994-02-23'
SET perf_58dba01eacda.source = 'musicbrainz.org'
SET perf_58dba01eacda.timestamp = timestamp()

MERGE (perf_72269e7d4a7e:Performance{ uuid: '276b9f38-3098-49bf-875e-72269e7d4a7e' })
SET perf_72269e7d4a7e.name = 'Passion Flower'
SET perf_72269e7d4a7e.duration = '7:40'
SET perf_72269e7d4a7e.begin = '1994-02-22'
SET perf_72269e7d4a7e.end = '1994-02-23'
SET perf_72269e7d4a7e.source = 'musicbrainz.org'
SET perf_72269e7d4a7e.timestamp = timestamp()

MERGE (perf_cd2ed8659dc5:Performance{ uuid: '92b45f75-bc9c-432a-b779-cd2ed8659dc5' })
SET perf_cd2ed8659dc5.name = 'Madman'
SET perf_cd2ed8659dc5.duration = '5:38'
SET perf_cd2ed8659dc5.begin = '1994-02-22'
SET perf_cd2ed8659dc5.end = '1994-02-23'
SET perf_cd2ed8659dc5.source = 'musicbrainz.org'
SET perf_cd2ed8659dc5.timestamp = timestamp()

MERGE (perf_3e3577099637:Performance{ uuid: '6d2fff9d-2653-40ab-9273-3e3577099637' })
SET perf_3e3577099637.name = 'Nightlake'
SET perf_3e3577099637.duration = '6:53'
SET perf_3e3577099637.begin = '1994-02-22'
SET perf_3e3577099637.end = '1994-02-23'
SET perf_3e3577099637.source = 'musicbrainz.org'
SET perf_3e3577099637.timestamp = timestamp()

MERGE (perf_a13b4917c41d:Performance{ uuid: '6c649401-68fa-4792-bb14-a13b4917c41d' })
SET perf_a13b4917c41d.name = 'The Loss of a Moment'
SET perf_a13b4917c41d.duration = '8:01'
SET perf_a13b4917c41d.begin = '1994-02-22'
SET perf_a13b4917c41d.end = '1994-02-23'
SET perf_a13b4917c41d.source = 'musicbrainz.org'
SET perf_a13b4917c41d.timestamp = timestamp()

MERGE (perf_b3ef61c4e3ed:Performance{ uuid: '29edfec3-b0f2-4419-855d-b3ef61c4e3ed' })
SET perf_b3ef61c4e3ed.name = 'Wanton Spirit'
SET perf_b3ef61c4e3ed.duration = '5:24'
SET perf_b3ef61c4e3ed.begin = '1994-02-22'
SET perf_b3ef61c4e3ed.end = '1994-02-23'
SET perf_b3ef61c4e3ed.source = 'musicbrainz.org'
SET perf_b3ef61c4e3ed.timestamp = timestamp()

MERGE (perf_f929bd631042:Performance{ uuid: '6f2ff3f2-36f0-4581-b4dc-f929bd631042' })
SET perf_f929bd631042.name = 'Melancholia'
SET perf_f929bd631042.duration = '2:40'
SET perf_f929bd631042.begin = '1994-02-22'
SET perf_f929bd631042.end = '1994-02-23'
SET perf_f929bd631042.source = 'musicbrainz.org'
SET perf_f929bd631042.timestamp = timestamp()

MERGE (perf_c8a71b502f20:Performance{ uuid: '7173a1c0-e098-48f5-b23a-c8a71b502f20' })
SET perf_c8a71b502f20.name = 'One Finger Snap'
SET perf_c8a71b502f20.duration = '5:58'
SET perf_c8a71b502f20.begin = '1994-02-22'
SET perf_c8a71b502f20.end = '1994-02-23'
SET perf_c8a71b502f20.source = 'musicbrainz.org'
SET perf_c8a71b502f20.timestamp = timestamp()



// labels
MERGE (release_2bfffd00cdc9)-[:HAS_LABEL]->(label_4b4670dc9f4f)


// tracks
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_846ac138be11)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_7e10ca2eeeb1)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_58dba01eacda)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_72269e7d4a7e)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_cd2ed8659dc5)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_3e3577099637)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '7', sequence: 7}]->(perf_a13b4917c41d)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '8', sequence: 8}]->(perf_b3ef61c4e3ed)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '9', sequence: 9}]->(perf_f929bd631042)
MERGE (release_2bfffd00cdc9)-[:HAS_TRACK {name: '10', sequence: 10}]->(perf_c8a71b502f20)

// works

MERGE (person_65998d0d35b5:Person{ uuid: 'e9ba8ccb-505f-4e5c-b909-65998d0d35b5' }) 
SET person_65998d0d35b5.name = 'Dizzy Gillespie'
SET person_65998d0d35b5.gender = 'Male'
SET person_65998d0d35b5.country = 'US'
SET person_65998d0d35b5.allmusic = 'https://www.allmusic.com/artist/mn0000162677'
SET person_65998d0d35b5.bbc = 'https://www.bbc.co.uk/music/artists/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.discogs = 'https://www.discogs.com/artist/64694'
SET person_65998d0d35b5.imdb = 'https://www.imdb.com/name/nm0318926/'
SET person_65998d0d35b5.viaf = 'http://viaf.org/viaf/77110276'
SET person_65998d0d35b5.wikidata = 'https://www.wikidata.org/wiki/Q49575'
SET person_65998d0d35b5.databases = ['http://d-nb.info/gnd/118694960', 'http://id.loc.gov/authorities/names/n50033872', 'https://adp.library.ucsb.edu/names/102015', 'https://catalogue.bnf.fr/ark:/12148/cb138944733', 'https://ibdb.com/person.php?id=83656', 'http://snaccooperative.org/ark:/99166/w6jw8cjh', 'https://openlibrary.org/works/OL1238547A', 'https://rateyourmusic.com/artist/dizzy_gillespie', 'https://www.musik-sammler.de/artist/dizzy-gillespie/', 'https://www.worldcat.org/identities/lccn-n50033872']
SET person_65998d0d35b5.musicbrainz = 'https://musicbrainz.org/artist/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.isni_list = ['http://isni.org/isni/0000000109181520']
SET person_65998d0d35b5.source = 'musicbrainz.org'
SET person_65998d0d35b5.timestamp = timestamp()

MERGE (person_d6ddfe8fd0a9:Person{ uuid: '23ec9ce1-2dae-437d-ba33-d6ddfe8fd0a9' }) 
SET person_d6ddfe8fd0a9.name = 'Billy Strayhorn'
SET person_d6ddfe8fd0a9.gender = 'Male'
SET person_d6ddfe8fd0a9.country = 'US'
SET person_d6ddfe8fd0a9.allmusic = 'https://www.allmusic.com/artist/mn0000359199'
SET person_d6ddfe8fd0a9.discogs = 'https://www.discogs.com/artist/258464'
SET person_d6ddfe8fd0a9.imdb = 'https://www.imdb.com/name/nm0833968/'
SET person_d6ddfe8fd0a9.viaf = 'http://viaf.org/viaf/64193228'
SET person_d6ddfe8fd0a9.wikidata = 'https://www.wikidata.org/wiki/Q380626'
SET person_d6ddfe8fd0a9.databases = ['http://d-nb.info/gnd/119403544', 'http://id.loc.gov/authorities/names/n81072976', 'https://catalogue.bnf.fr/ark:/12148/cb13900127f', 'https://ibdb.com/person.php?id=12699', 'http://snaccooperative.org/ark:/99166/w6w6867m', 'https://rateyourmusic.com/artist/billy_strayhorn', 'https://www.worldcat.org/identities/lccn-n81072976']
SET person_d6ddfe8fd0a9.musicbrainz = 'https://musicbrainz.org/artist/23ec9ce1-2dae-437d-ba33-d6ddfe8fd0a9'
SET person_d6ddfe8fd0a9.isni_list = ['http://isni.org/isni/000000007360288X']
SET person_d6ddfe8fd0a9.source = 'musicbrainz.org'
SET person_d6ddfe8fd0a9.timestamp = timestamp()

MERGE (person_fa0743465fdd:Person{ uuid: '27613b78-1b9d-4ec3-9db5-fa0743465fdd' }) 
SET person_fa0743465fdd.name = 'Herbie Hancock'
SET person_fa0743465fdd.gender = 'Male'
SET person_fa0743465fdd.disambiguation = 'US jazz pianist, keyboardist, bandleader and composer'
SET person_fa0743465fdd.country = 'US'
SET person_fa0743465fdd.allmusic = 'https://www.allmusic.com/artist/mn0000957296'
SET person_fa0743465fdd.bbc = 'https://www.bbc.co.uk/music/artists/27613b78-1b9d-4ec3-9db5-fa0743465fdd'
SET person_fa0743465fdd.discogs = 'https://www.discogs.com/artist/3865'
SET person_fa0743465fdd.imdb = 'https://www.imdb.com/name/nm0359372/'
SET person_fa0743465fdd.viaf = 'http://viaf.org/viaf/49408202'
SET person_fa0743465fdd.wikidata = 'https://www.wikidata.org/wiki/Q105875'
SET person_fa0743465fdd.databases = ['http://d-nb.info/gnd/121542157', 'http://id.loc.gov/authorities/names/n81014575', 'http://musicmoz.org/Bands_and_Artists/H/Hancock,_Herbie/', 'https://catalogue.bnf.fr/ark:/12148/cb13894938z', 'https://imvdb.com/n/herbie-hancock', 'http://snaccooperative.org/ark:/99166/w6rf5z7r', 'https://rateyourmusic.com/artist/herbie_hancock', 'https://www.whosampled.com/Herbie-Hancock/', 'https://www.worldcat.org/identities/lccn-n81014575']
SET person_fa0743465fdd.musicbrainz = 'https://musicbrainz.org/artist/27613b78-1b9d-4ec3-9db5-fa0743465fdd'
SET person_fa0743465fdd.isni_list = ['http://isni.org/isni/0000000108993797']
SET person_fa0743465fdd.source = 'musicbrainz.org'
SET person_fa0743465fdd.timestamp = timestamp()

MERGE (person_8df4a5b5fd62:Person{ uuid: '8943189a-0f1e-486c-b639-8df4a5b5fd62' }) 
SET person_8df4a5b5fd62.name = 'Tom Harrell'
SET person_8df4a5b5fd62.gender = 'Male'
SET person_8df4a5b5fd62.country = 'US'
SET person_8df4a5b5fd62.allmusic = 'https://www.allmusic.com/artist/mn0000605535'
SET person_8df4a5b5fd62.discogs = 'https://www.discogs.com/artist/297675'
SET person_8df4a5b5fd62.viaf = 'http://viaf.org/viaf/85704070'
SET person_8df4a5b5fd62.wikidata = 'https://www.wikidata.org/wiki/Q427035'
SET person_8df4a5b5fd62.wikipedia = 'https://en.wikipedia.org/wiki/Tom_Harrell'
SET person_8df4a5b5fd62.databases = ['http://d-nb.info/gnd/134398254', 'http://id.loc.gov/authorities/names/n80120383', 'https://catalogue.bnf.fr/ark:/12148/cb139215187', 'https://www.worldcat.org/identities/lccn-n80120383']
SET person_8df4a5b5fd62.musicbrainz = 'https://musicbrainz.org/artist/8943189a-0f1e-486c-b639-8df4a5b5fd62'
SET person_8df4a5b5fd62.isni_list = ['http://isni.org/isni/000000011450710X']
SET person_8df4a5b5fd62.source = 'musicbrainz.org'
SET person_8df4a5b5fd62.timestamp = timestamp()

MERGE (person_7eeeb45e411f:Person{ uuid: '3af06bc4-68ad-4cae-bb7a-7eeeb45e411f' }) 
SET person_7eeeb45e411f.name = 'Duke Ellington'
SET person_7eeeb45e411f.gender = 'Male'
SET person_7eeeb45e411f.disambiguation = 'US composer, pianist & jazz bandleader'
SET person_7eeeb45e411f.country = 'US'
SET person_7eeeb45e411f.allmusic = 'https://www.allmusic.com/artist/mn0000120323'
SET person_7eeeb45e411f.bbc = 'https://www.bbc.co.uk/music/artists/3af06bc4-68ad-4cae-bb7a-7eeeb45e411f'
SET person_7eeeb45e411f.discogs = 'https://www.discogs.com/artist/145257'
SET person_7eeeb45e411f.imdb = 'https://www.imdb.com/name/nm0254153/'
SET person_7eeeb45e411f.viaf = 'http://viaf.org/viaf/66651610'
SET person_7eeeb45e411f.wikidata = 'https://www.wikidata.org/wiki/Q4030'
SET person_7eeeb45e411f.databases = ['http://d-nb.info/gnd/118529994', 'http://id.loc.gov/authorities/names/n50080187', 'https://catalogue.bnf.fr/ark:/12148/cb13893638w', 'https://ibdb.com/person.php?id=11631', 'http://snaccooperative.org/ark:/99166/w6639nkm', 'https://nla.gov.au/nla.party-815399', 'https://openlibrary.org/works/OL1953949A', 'https://rateyourmusic.com/artist/duke_ellington', 'https://www.worldcat.org/identities/lccn-n50080187/']
SET person_7eeeb45e411f.musicbrainz = 'https://musicbrainz.org/artist/3af06bc4-68ad-4cae-bb7a-7eeeb45e411f'
SET person_7eeeb45e411f.isni_list = ['http://isni.org/isni/0000000109110810']
SET person_7eeeb45e411f.source = 'musicbrainz.org'
SET person_7eeeb45e411f.timestamp = timestamp()

MERGE (work_9847f580afdd:Work{ uuid: 'd8c53997-b4b2-4036-bfae-9847f580afdd' })
SET work_9847f580afdd.name = 'Sail Away'
SET work_9847f580afdd.type = 'Song'
SET work_9847f580afdd.source = 'musicbrainz.org'
SET work_9847f580afdd.timestamp = timestamp()

MERGE (work_c12a89b7f7b5:Work{ uuid: 'c525203b-dee8-4035-aca5-c12a89b7f7b5' })
SET work_c12a89b7f7b5.name = 'One Finger Snap'
SET work_c12a89b7f7b5.iswc = 'T-070.242.704-0'
SET work_c12a89b7f7b5.source = 'musicbrainz.org'
SET work_c12a89b7f7b5.timestamp = timestamp()

MERGE (work_f8cf8068feef:Work{ uuid: '867ff2bc-b318-4656-b6ce-f8cf8068feef' })
SET work_f8cf8068feef.name = 'Passion Flower'
SET work_f8cf8068feef.source = 'musicbrainz.org'
SET work_f8cf8068feef.timestamp = timestamp()

MERGE (work_80382fc1903d:Work{ uuid: 'b37ec581-af04-3992-9aec-80382fc1903d' })
SET work_80382fc1903d.name = 'Take the Coltrane'
SET work_80382fc1903d.source = 'musicbrainz.org'
SET work_80382fc1903d.timestamp = timestamp()

MERGE (work_f584158b6a29:Work{ uuid: 'bebc1a20-e28e-42f1-816c-f584158b6a29' })
SET work_f584158b6a29.name = 'Be-Bop'
SET work_f584158b6a29.iswc = 'T-070.010.535-6'
SET work_f584158b6a29.type = 'Song'
SET work_f584158b6a29.wikidata = 'https://www.wikidata.org/wiki/Q97178615'
SET work_f584158b6a29.musicbrainz = 'https://musicbrainz.org/work/bebc1a20-e28e-42f1-816c-f584158b6a29'
SET work_f584158b6a29.source = 'musicbrainz.org'
SET work_f584158b6a29.timestamp = timestamp()

MERGE (work_e49c32bee5c5:Work{ uuid: '84ff7e9b-d0e2-4464-abbb-e49c32bee5c5' })
SET work_e49c32bee5c5.name = 'Melancholia'
SET work_e49c32bee5c5.type = 'Song'
SET work_e49c32bee5c5.source = 'musicbrainz.org'
SET work_e49c32bee5c5.timestamp = timestamp()


// performances of
MERGE (perf_7e10ca2eeeb1)-[:PERFORMANCE_OF]->(work_9847f580afdd)
MERGE (perf_c8a71b502f20)-[:PERFORMANCE_OF]->(work_c12a89b7f7b5)
MERGE (perf_72269e7d4a7e)-[:PERFORMANCE_OF]->(work_f8cf8068feef)
MERGE (perf_846ac138be11)-[:PERFORMANCE_OF]->(work_80382fc1903d)
MERGE (perf_58dba01eacda)-[:PERFORMANCE_OF]->(work_f584158b6a29)
MERGE (perf_f929bd631042)-[:PERFORMANCE_OF]->(work_e49c32bee5c5)


// composers
MERGE (person_8df4a5b5fd62)-[:COMPOSED]->(work_9847f580afdd)
MERGE (person_fa0743465fdd)-[:COMPOSED]->(work_c12a89b7f7b5)
MERGE (person_d6ddfe8fd0a9)-[:COMPOSED]->(work_f8cf8068feef)
MERGE (person_7eeeb45e411f)-[:COMPOSED]->(work_80382fc1903d)
MERGE (person_65998d0d35b5)-[:COMPOSED]->(work_f584158b6a29)
MERGE (person_7eeeb45e411f)-[:COMPOSED]->(work_e49c32bee5c5)


// place nodes

MERGE (place_70b236d3aa47:Place{ uuid: 'f1526c4b-b38e-42e5-897e-70b236d3aa47' })
SET place_70b236d3aa47.name = 'Systems Two Recording Studio'
SET place_70b236d3aa47.source = 'musicbrainz.org'


// place relationships
MERGE (perf_846ac138be11)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_7e10ca2eeeb1)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_58dba01eacda)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_72269e7d4a7e)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_cd2ed8659dc5)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_3e3577099637)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_a13b4917c41d)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_b3ef61c4e3ed)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_f929bd631042)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)
MERGE (perf_c8a71b502f20)-[:HAS_PLACE { type: 'recorded at', begin: '1994-02-22', end: '1994-02-23' }]->(place_70b236d3aa47)

MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_846ac138be11)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_846ac138be11)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_846ac138be11)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_846ac138be11)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_846ac138be11)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_846ac138be11)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_7e10ca2eeeb1)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_7e10ca2eeeb1)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_7e10ca2eeeb1)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_7e10ca2eeeb1)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_7e10ca2eeeb1)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_7e10ca2eeeb1)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_58dba01eacda)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_58dba01eacda)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_58dba01eacda)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_58dba01eacda)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_58dba01eacda)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_58dba01eacda)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_72269e7d4a7e)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_72269e7d4a7e)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_72269e7d4a7e)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_72269e7d4a7e)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_72269e7d4a7e)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_72269e7d4a7e)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_cd2ed8659dc5)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_cd2ed8659dc5)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_cd2ed8659dc5)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_cd2ed8659dc5)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_cd2ed8659dc5)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_cd2ed8659dc5)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_3e3577099637)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_3e3577099637)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_3e3577099637)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_3e3577099637)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_3e3577099637)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_3e3577099637)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_a13b4917c41d)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_a13b4917c41d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_a13b4917c41d)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_a13b4917c41d)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_a13b4917c41d)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_a13b4917c41d)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_b3ef61c4e3ed)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_b3ef61c4e3ed)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_b3ef61c4e3ed)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_b3ef61c4e3ed)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_b3ef61c4e3ed)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_b3ef61c4e3ed)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_f929bd631042)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_f929bd631042)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_f929bd631042)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_f929bd631042)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_f929bd631042)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_f929bd631042)
MERGE (person_120e386da267)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_c8a71b502f20)
MERGE (person_37ec0c289b48)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_c8a71b502f20)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_c8a71b502f20)
MERGE (person_82d3fd2469d4)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_c8a71b502f20)
MERGE (person_6d0bc0ca74fd)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_c8a71b502f20)
MERGE (person_b0f2dfbe8828)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_c8a71b502f20)

