
MERGE (release_64867f07b984:Release{ uuid: '6d83ae06-bc3c-3663-9864-64867f07b984' })
SET release_64867f07b984.name = 'Out of the Afternoon'
SET release_64867f07b984.country = 'US'
SET release_64867f07b984.date = '1962'
SET release_64867f07b984.format = 'Vinyl'
SET release_64867f07b984.discode = 'A 23'
SET release_64867f07b984.musicbrainz = 'http://musicbrainz.org/release/6d83ae06-bc3c-3663-9864-64867f07b984'
SET release_64867f07b984.source = 'musicbrainz.org'
SET release_64867f07b984.timestamp = timestamp()

MERGE (person_4ffdc92b0241:Person{ uuid: 'c39a1eeb-e646-43e9-b984-4ffdc92b0241' })
SET person_4ffdc92b0241.name = 'Tommy Flanagan'
SET person_4ffdc92b0241.gender = 'Male'
SET person_4ffdc92b0241.country = 'US'
SET person_4ffdc92b0241.wikipedia = 'http://en.wikipedia.org/wiki/Tommy_Flanagan'
SET person_4ffdc92b0241.viaf = 'http://viaf.org/viaf/2656064'
SET person_4ffdc92b0241.allmusic = 'http://www.allmusic.com/artist/mn0000519715'
SET person_4ffdc92b0241.discogs = 'http://www.discogs.com/artist/253443'
SET person_4ffdc92b0241.wikidata = 'http://www.wikidata.org/wiki/Q498723'
SET person_4ffdc92b0241.musicbrainz = 'https://musicbrainz.org/artist/c39a1eeb-e646-43e9-b984-4ffdc92b0241'
SET person_4ffdc92b0241.isni_list = ['http://isni.org/isni/0000000059466009']
SET person_4ffdc92b0241.source = 'musicbrainz.org'
SET person_4ffdc92b0241.timestamp = timestamp()

MERGE (person_615f0f35fd24:Person{ uuid: '5ade8ffa-4e9c-42b7-ac4d-615f0f35fd24' })
SET person_615f0f35fd24.name = 'Roy Haynes Quartet'
SET person_615f0f35fd24.country = 'US'
SET person_615f0f35fd24.source = 'musicbrainz.org'
SET person_615f0f35fd24.timestamp = timestamp()

MERGE (person_9cf6c3ca891c:Person{ uuid: '4a1f7fe0-e509-4c4a-9fa1-9cf6c3ca891c' })
SET person_9cf6c3ca891c.name = 'Rahsaan Roland Kirk'
SET person_9cf6c3ca891c.gender = 'Male'
SET person_9cf6c3ca891c.country = 'US'
SET person_9cf6c3ca891c.wikipedia = 'http://en.wikipedia.org/wiki/Rahsaan_Roland_Kirk'
SET person_9cf6c3ca891c.viaf = 'http://viaf.org/viaf/74037985'
SET person_9cf6c3ca891c.allmusic = 'http://www.allmusic.com/artist/mn0000864257'
SET person_9cf6c3ca891c.bbc = 'http://www.bbc.co.uk/music/artists/4a1f7fe0-e509-4c4a-9fa1-9cf6c3ca891c'
SET person_9cf6c3ca891c.discogs = 'http://www.discogs.com/artist/218045'
SET person_9cf6c3ca891c.wikidata = 'http://www.wikidata.org/wiki/Q553921'
SET person_9cf6c3ca891c.discographies = ['http://www.jazzdisco.org/roland-kirk/discography/']
SET person_9cf6c3ca891c.databases = ['https://rateyourmusic.com/artist/rahsaan_roland_kirk']
SET person_9cf6c3ca891c.musicbrainz = 'https://musicbrainz.org/artist/4a1f7fe0-e509-4c4a-9fa1-9cf6c3ca891c'
SET person_9cf6c3ca891c.isni_list = ['http://isni.org/isni/0000000083943098']
SET person_9cf6c3ca891c.source = 'musicbrainz.org'
SET person_9cf6c3ca891c.timestamp = timestamp()

MERGE (person_b3c603bca943:Person{ uuid: 'e1c6e5cc-ef06-4648-b554-b3c603bca943' })
SET person_b3c603bca943.name = 'Henry Grimes'
SET person_b3c603bca943.gender = 'Male'
SET person_b3c603bca943.country = 'US'
SET person_b3c603bca943.wikipedia = 'http://en.wikipedia.org/wiki/Henry_Grimes'
SET person_b3c603bca943.viaf = 'http://viaf.org/viaf/18399512'
SET person_b3c603bca943.allmusic = 'http://www.allmusic.com/artist/mn0000672608'
SET person_b3c603bca943.discogs = 'http://www.discogs.com/artist/258130'
SET person_b3c603bca943.wikidata = 'http://www.wikidata.org/wiki/Q719759'
SET person_b3c603bca943.discographies = ['http://www.jazzdiscography.com/Artists/Grimes/index.html']
SET person_b3c603bca943.musicbrainz = 'https://musicbrainz.org/artist/e1c6e5cc-ef06-4648-b554-b3c603bca943'
SET person_b3c603bca943.source = 'musicbrainz.org'
SET person_b3c603bca943.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' })
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.wikipedia = 'http://en.wikipedia.org/wiki/Roy_Haynes'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.allmusic = 'http://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'http://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'http://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'http://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.wikidata = 'http://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_05d508e09a73:Person{ uuid: 'f0707f1d-55e1-46b6-8a9c-05d508e09a73' })
SET person_05d508e09a73.name = 'Rudy van Gelder'
SET person_05d508e09a73.gender = 'Male'
SET person_05d508e09a73.country = 'US'
SET person_05d508e09a73.wikipedia = 'http://en.wikipedia.org/wiki/Rudy_Van_Gelder'
SET person_05d508e09a73.viaf = 'http://viaf.org/viaf/33997197'
SET person_05d508e09a73.allmusic = 'http://www.allmusic.com/artist/mn0000305301'
SET person_05d508e09a73.discogs = 'http://www.discogs.com/artist/252966'
SET person_05d508e09a73.wikidata = 'http://www.wikidata.org/wiki/Q945681'
SET person_05d508e09a73.databases = ['http://rateyourmusic.com/artist/rudy_van_gelder']
SET person_05d508e09a73.musicbrainz = 'https://musicbrainz.org/artist/f0707f1d-55e1-46b6-8a9c-05d508e09a73'
SET person_05d508e09a73.isni_list = ['http://isni.org/isni/0000000019691076']
SET person_05d508e09a73.source = 'musicbrainz.org'
SET person_05d508e09a73.timestamp = timestamp()
// labels

MERGE (label_8fb76f3e6ca9:Label{ uuid: '93c3b044-2b4e-4239-a73b-8fb76f3e6ca9' })
SET label_8fb76f3e6ca9.name= 'impulse!'

// performances

MERGE (perf_2e459451fc42:Performance{ uuid: '759dd0a0-c6ac-48e4-8e35-2e459451fc42' })
SET perf_2e459451fc42.name = 'Moon Ray'
SET perf_2e459451fc42.duration = '6:41'
SET perf_2e459451fc42.begin = '1962-05-23'
SET perf_2e459451fc42.end = '1962-05-23'
SET perf_2e459451fc42.source = 'musicbrainz.org'
SET perf_2e459451fc42.timestamp = timestamp()

MERGE (perf_4881658375b2:Performance{ uuid: '453856be-0133-4880-a28b-4881658375b2' })
SET perf_4881658375b2.name = 'Fly Me to the Moon (In Other Words)'
SET perf_4881658375b2.duration = '6:40'
SET perf_4881658375b2.begin = '1962-05-16'
SET perf_4881658375b2.end = '1962-05-16'
SET perf_4881658375b2.source = 'musicbrainz.org'
SET perf_4881658375b2.timestamp = timestamp()

MERGE (perf_305a6094cce1:Performance{ uuid: '1553d7a5-786d-4c8c-a82d-305a6094cce1' })
SET perf_305a6094cce1.name = 'Raoul'
SET perf_305a6094cce1.duration = '6:01'
SET perf_305a6094cce1.begin = '1962-05-16'
SET perf_305a6094cce1.end = '1962-05-16'
SET perf_305a6094cce1.source = 'musicbrainz.org'
SET perf_305a6094cce1.timestamp = timestamp()

MERGE (perf_ba720a0916b7:Performance{ uuid: '7f7d97b1-d3f0-4f4f-a1af-ba720a0916b7' })
SET perf_ba720a0916b7.name = 'Snap Crackle'
SET perf_ba720a0916b7.duration = '4:11'
SET perf_ba720a0916b7.begin = '1962-05-16'
SET perf_ba720a0916b7.end = '1962-05-16'
SET perf_ba720a0916b7.source = 'musicbrainz.org'
SET perf_ba720a0916b7.timestamp = timestamp()

MERGE (perf_7ea6527c95bc:Performance{ uuid: 'd39a5a12-846a-494f-9dc3-7ea6527c95bc' })
SET perf_7ea6527c95bc.name = 'If I Should Lose You'
SET perf_7ea6527c95bc.duration = '5:49'
SET perf_7ea6527c95bc.begin = '1962-05-16'
SET perf_7ea6527c95bc.end = '1962-05-16'
SET perf_7ea6527c95bc.source = 'musicbrainz.org'
SET perf_7ea6527c95bc.timestamp = timestamp()

MERGE (perf_1328187f528d:Performance{ uuid: '4b3827ee-60ed-4423-8d1f-1328187f528d' })
SET perf_1328187f528d.name = 'Long Wharf'
SET perf_1328187f528d.duration = '4:42'
SET perf_1328187f528d.begin = '1962-05-23'
SET perf_1328187f528d.end = '1962-05-23'
SET perf_1328187f528d.source = 'musicbrainz.org'
SET perf_1328187f528d.timestamp = timestamp()

MERGE (perf_1e23821cf5b6:Performance{ uuid: '6169b142-2705-419f-a133-1e23821cf5b6' })
SET perf_1e23821cf5b6.name = 'Some Other Spring'
SET perf_1e23821cf5b6.duration = '3:29'
SET perf_1e23821cf5b6.begin = '1962-05-23'
SET perf_1e23821cf5b6.end = '1962-05-23'
SET perf_1e23821cf5b6.source = 'musicbrainz.org'
SET perf_1e23821cf5b6.timestamp = timestamp()



// labels
MERGE (release_64867f07b984)-[:HAS_LABEL]->(label_8fb76f3e6ca9)


// tracks
MERGE (release_64867f07b984)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_2e459451fc42)
MERGE (release_64867f07b984)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_4881658375b2)
MERGE (release_64867f07b984)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_305a6094cce1)
MERGE (release_64867f07b984)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_ba720a0916b7)
MERGE (release_64867f07b984)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_7ea6527c95bc)
MERGE (release_64867f07b984)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_1328187f528d)
MERGE (release_64867f07b984)-[:HAS_TRACK {name: '7', sequence: 7}]->(perf_1e23821cf5b6)

// works

MERGE (person_30ff55018df9:Person{ uuid: '85545102-7c29-4707-aea2-30ff55018df9' })
SET person_30ff55018df9.name = 'Artie Shaw'
SET person_30ff55018df9.gender = 'Male'
SET person_30ff55018df9.country = 'US'
SET person_30ff55018df9.wikipedia = 'http://en.wikipedia.org/wiki/Artie_Shaw'
SET person_30ff55018df9.viaf = 'http://viaf.org/viaf/34644584'
SET person_30ff55018df9.allmusic = 'http://www.allmusic.com/artist/mn0000511029'
SET person_30ff55018df9.discogs = 'http://www.discogs.com/artist/269597'
SET person_30ff55018df9.imdb = 'http://www.imdb.com/name/nm0789600/'
SET person_30ff55018df9.wikidata = 'http://www.wikidata.org/wiki/Q320065'
SET person_30ff55018df9.databases = ['https://rateyourmusic.com/artist/artie_shaw']
SET person_30ff55018df9.musicbrainz = 'https://musicbrainz.org/artist/85545102-7c29-4707-aea2-30ff55018df9'
SET person_30ff55018df9.isni_list = ['http://isni.org/isni/0000000081138220']
SET person_30ff55018df9.source = 'musicbrainz.org'
SET person_30ff55018df9.timestamp = timestamp()

MERGE (person_44ac04208e17:Person{ uuid: '6727725b-9247-484d-bea8-44ac04208e17' })
SET person_44ac04208e17.name = 'Arthur Herzog, Jr.'
SET person_44ac04208e17.gender = 'Male'
SET person_44ac04208e17.country = 'US'
SET person_44ac04208e17.wikipedia = 'http://en.wikipedia.org/wiki/Arthur_Herzog,_Jr.'
SET person_44ac04208e17.allmusic = 'http://www.allmusic.com/artist/mn0000098646'
SET person_44ac04208e17.discogs = 'http://www.discogs.com/artist/734249'
SET person_44ac04208e17.imdb = 'http://www.imdb.com/name/nm0381290/'
SET person_44ac04208e17.wikidata = 'http://www.wikidata.org/wiki/Q4799057'
SET person_44ac04208e17.databases = ['https://rateyourmusic.com/artist/arthur_herzog__jr_']
SET person_44ac04208e17.musicbrainz = 'https://musicbrainz.org/artist/6727725b-9247-484d-bea8-44ac04208e17'
SET person_44ac04208e17.isni_list = ['http://isni.org/isni/0000000116693989']
SET person_44ac04208e17.source = 'musicbrainz.org'
SET person_44ac04208e17.timestamp = timestamp()

MERGE (person_10080d3079f2:Person{ uuid: '1febab34-36bb-499c-a370-10080d3079f2' })
SET person_10080d3079f2.name = 'Bart Howard'
SET person_10080d3079f2.gender = 'Male'
SET person_10080d3079f2.country = 'US'
SET person_10080d3079f2.wikipedia = 'http://en.wikipedia.org/wiki/Bart_Howard'
SET person_10080d3079f2.viaf = 'http://viaf.org/viaf/58353006'
SET person_10080d3079f2.allmusic = 'http://www.allmusic.com/artist/mn0001008919'
SET person_10080d3079f2.discogs = 'http://www.discogs.com/artist/370782'
SET person_10080d3079f2.wikidata = 'http://www.wikidata.org/wiki/Q809196'
SET person_10080d3079f2.databases = ['https://rateyourmusic.com/artist/bart_howard']
SET person_10080d3079f2.musicbrainz = 'https://musicbrainz.org/artist/1febab34-36bb-499c-a370-10080d3079f2'
SET person_10080d3079f2.isni_list = ['http://isni.org/isni/0000000083857181']
SET person_10080d3079f2.source = 'musicbrainz.org'
SET person_10080d3079f2.timestamp = timestamp()

MERGE (person_6565dc36a994:Person{ uuid: '890022a1-6d43-4fd8-94a8-6565dc36a994' })
SET person_6565dc36a994.name = 'Ralph Rainger'
SET person_6565dc36a994.country = 'US'
SET person_6565dc36a994.wikipedia = 'http://en.wikipedia.org/wiki/Ralph_Rainger'
SET person_6565dc36a994.wikidata = 'http://www.wikidata.org/wiki/Q364163'
SET person_6565dc36a994.musicbrainz = 'https://musicbrainz.org/artist/890022a1-6d43-4fd8-94a8-6565dc36a994'
SET person_6565dc36a994.source = 'musicbrainz.org'
SET person_6565dc36a994.timestamp = timestamp()

MERGE (work_51521339bb63:Work{ uuid: '012728e9-de3c-4833-b834-51521339bb63' })
SET work_51521339bb63.name = 'Moonray'
SET work_51521339bb63.type = 'Song'
SET work_51521339bb63.source = 'musicbrainz.org'
SET work_51521339bb63.timestamp = timestamp()

MERGE (work_da3f8e61b3c4:Work{ uuid: '3431f95f-5b1b-3ba3-8ede-da3f8e61b3c4' })
SET work_da3f8e61b3c4.name = 'Fly Me to the Moon'
SET work_da3f8e61b3c4.iswc = 'T-070.055.949-4'
SET work_da3f8e61b3c4.type = 'Song'
SET work_da3f8e61b3c4.wikidata = 'http://www.wikidata.org/wiki/Q1066479'
SET work_da3f8e61b3c4.musicbrainz = 'https://musicbrainz.org/work/3431f95f-5b1b-3ba3-8ede-da3f8e61b3c4'
SET work_da3f8e61b3c4.source = 'musicbrainz.org'
SET work_da3f8e61b3c4.timestamp = timestamp()

MERGE (work_38986a437fea:Work{ uuid: 'cc2a66e4-2d4d-4147-8db5-38986a437fea' })
SET work_38986a437fea.name = 'Raoul'
SET work_38986a437fea.type = 'Song'
SET work_38986a437fea.source = 'musicbrainz.org'
SET work_38986a437fea.timestamp = timestamp()

MERGE (work_7706d8057b10:Work{ uuid: '18ca054a-5ead-4b89-85f7-7706d8057b10' })
SET work_7706d8057b10.name = 'Snap Crackle'
SET work_7706d8057b10.type = 'Song'
SET work_7706d8057b10.source = 'musicbrainz.org'
SET work_7706d8057b10.timestamp = timestamp()

MERGE (work_27385309acf6:Work{ uuid: 'b5506172-a22e-36e3-ae7e-27385309acf6' })
SET work_27385309acf6.name = 'If I Should Lose You'
SET work_27385309acf6.iswc = 'T-070.905.173-9'
SET work_27385309acf6.type = 'Song'
SET work_27385309acf6.wikidata = 'http://www.wikidata.org/wiki/Q5990520'
SET work_27385309acf6.musicbrainz = 'https://musicbrainz.org/work/b5506172-a22e-36e3-ae7e-27385309acf6'
SET work_27385309acf6.source = 'musicbrainz.org'
SET work_27385309acf6.timestamp = timestamp()

MERGE (work_ac406555f605:Work{ uuid: '4169937b-b6d3-442b-8992-ac406555f605' })
SET work_ac406555f605.name = 'Long Wharf'
SET work_ac406555f605.type = 'Song'
SET work_ac406555f605.source = 'musicbrainz.org'
SET work_ac406555f605.timestamp = timestamp()

MERGE (work_841f9178afcc:Work{ uuid: '5a91a554-2576-42bb-8a8b-841f9178afcc' })
SET work_841f9178afcc.name = 'Some Other Spring'
SET work_841f9178afcc.source = 'musicbrainz.org'
SET work_841f9178afcc.timestamp = timestamp()


// performances of
MERGE (perf_2e459451fc42)-[:PERFORMANCE_OF]->(work_51521339bb63)
MERGE (perf_4881658375b2)-[:PERFORMANCE_OF]->(work_da3f8e61b3c4)
MERGE (perf_305a6094cce1)-[:PERFORMANCE_OF]->(work_38986a437fea)
MERGE (perf_ba720a0916b7)-[:PERFORMANCE_OF]->(work_7706d8057b10)
MERGE (perf_7ea6527c95bc)-[:PERFORMANCE_OF]->(work_27385309acf6)
MERGE (perf_1328187f528d)-[:PERFORMANCE_OF]->(work_ac406555f605)
MERGE (perf_1e23821cf5b6)-[:PERFORMANCE_OF]->(work_841f9178afcc)


// composers
MERGE (person_30ff55018df9)-[:COMPOSED]->(work_51521339bb63)
MERGE (person_10080d3079f2)-[:COMPOSED]->(work_da3f8e61b3c4)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_38986a437fea)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_7706d8057b10)
MERGE (person_6565dc36a994)-[:COMPOSED]->(work_27385309acf6)
MERGE (person_6f0a331cc1ca)-[:COMPOSED]->(work_ac406555f605)
MERGE (person_44ac04208e17)-[:COMPOSED]->(work_841f9178afcc)


// place nodes

MERGE (place_569fa8b97644:Place{ uuid: '1165ef7d-371c-4e03-98db-569fa8b97644' })
SET place_569fa8b97644.name = 'Van Gelder Studio'
SET place_569fa8b97644.address = '445, Sylvan Avenue, Englewood Cliffs, Bergen County, New Jersey, 07632, United States of America'
SET place_569fa8b97644.lat = '40.8764374074488'
SET place_569fa8b97644.lng = '-73.9519546846822'
SET place_569fa8b97644.source = 'musicbrainz.org'


// place relationships
MERGE (perf_2e459451fc42)-[:HAS_PLACE { type: 'recorded at', begin: '1962-05-23', end: '1962-05-23' }]->(place_569fa8b97644)
MERGE (perf_4881658375b2)-[:HAS_PLACE { type: 'recorded at', begin: '1962-05-16', end: '1962-05-16' }]->(place_569fa8b97644)
MERGE (perf_305a6094cce1)-[:HAS_PLACE { type: 'recorded at', begin: '1962-05-16', end: '1962-05-16' }]->(place_569fa8b97644)
MERGE (perf_ba720a0916b7)-[:HAS_PLACE { type: 'recorded at', begin: '1962-05-16', end: '1962-05-16' }]->(place_569fa8b97644)
MERGE (perf_7ea6527c95bc)-[:HAS_PLACE { type: 'recorded at', begin: '1962-05-16', end: '1962-05-16' }]->(place_569fa8b97644)
MERGE (perf_1328187f528d)-[:HAS_PLACE { type: 'recorded at', begin: '1962-05-23', end: '1962-05-23' }]->(place_569fa8b97644)
MERGE (perf_1e23821cf5b6)-[:HAS_PLACE { type: 'recorded at', begin: '1962-05-23', end: '1962-05-23' }]->(place_569fa8b97644)

MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_2e459451fc42)
MERGE (person_9cf6c3ca891c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'saxophone'] }]->(perf_2e459451fc42)
MERGE (person_4ffdc92b0241)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_2e459451fc42)
MERGE (person_b3c603bca943)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_2e459451fc42)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_4881658375b2)
MERGE (person_9cf6c3ca891c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'saxophone'] }]->(perf_4881658375b2)
MERGE (person_4ffdc92b0241)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_4881658375b2)
MERGE (person_b3c603bca943)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_4881658375b2)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_305a6094cce1)
MERGE (person_9cf6c3ca891c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'saxophone'] }]->(perf_305a6094cce1)
MERGE (person_4ffdc92b0241)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_305a6094cce1)
MERGE (person_b3c603bca943)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_305a6094cce1)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_ba720a0916b7)
MERGE (person_9cf6c3ca891c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'saxophone'] }]->(perf_ba720a0916b7)
MERGE (person_4ffdc92b0241)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_ba720a0916b7)
MERGE (person_b3c603bca943)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_ba720a0916b7)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_7ea6527c95bc)
MERGE (person_9cf6c3ca891c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'saxophone'] }]->(perf_7ea6527c95bc)
MERGE (person_4ffdc92b0241)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_7ea6527c95bc)
MERGE (person_b3c603bca943)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_7ea6527c95bc)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_1328187f528d)
MERGE (person_9cf6c3ca891c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'saxophone'] }]->(perf_1328187f528d)
MERGE (person_4ffdc92b0241)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_1328187f528d)
MERGE (person_b3c603bca943)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_1328187f528d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_1e23821cf5b6)
MERGE (person_9cf6c3ca891c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'saxophone'] }]->(perf_1e23821cf5b6)
MERGE (person_4ffdc92b0241)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_1e23821cf5b6)
MERGE (person_b3c603bca943)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_1e23821cf5b6)

