// releases

MERGE (release_958f393dfab9:Release{ uuid: '09d238f8-22b0-4d52-aa73-958f393dfab9' })
SET release_958f393dfab9.name = 'Bohemia After Dark'
SET release_958f393dfab9.country = 'US'
SET release_958f393dfab9.date = '1955'
SET release_958f393dfab9.format = '12" Vinyl'
SET release_958f393dfab9.discode = 'MG-12017'
SET release_958f393dfab9.discogs = 'https://www.discogs.com/release/8843394'
SET release_958f393dfab9.musicbrainz = 'http://musicbrainz.org/release/09d238f8-22b0-4d52-aa73-958f393dfab9'
SET release_958f393dfab9.source = 'musicbrainz.org'
SET release_958f393dfab9.timestamp = timestamp()

MERGE (person_736867f1ba50:Person{ uuid: '48eaf8a1-6e44-488c-a91a-736867f1ba50' }) 
SET person_736867f1ba50.name = 'Kenny Clarke'
SET person_736867f1ba50.gender = 'Male'
SET person_736867f1ba50.country = 'US'
SET person_736867f1ba50.allmusic = 'https://www.allmusic.com/artist/mn0000081796'
SET person_736867f1ba50.discogs = 'https://www.discogs.com/artist/228917'
SET person_736867f1ba50.imdb = 'https://www.imdb.com/name/nm0164858/'
SET person_736867f1ba50.viaf = 'http://viaf.org/viaf/116335684'
SET person_736867f1ba50.wikidata = 'https://www.wikidata.org/wiki/Q346779'
SET person_736867f1ba50.databases = ['http://id.loc.gov/authorities/names/n81055676', 'https://adp.library.ucsb.edu/names/103158', 'https://catalogue.bnf.fr/ark:/12148/cb13892538c', 'https://d-nb.info/gnd/118834827', 'http://snaccooperative.org/ark:/99166/w6cj91b2', 'https://nla.gov.au/nla.party-1176449', 'https://rateyourmusic.com/artist/kenny_clarke', 'https://www.worldcat.org/identities/lccn-n81055676']
SET person_736867f1ba50.musicbrainz = 'https://musicbrainz.org/artist/48eaf8a1-6e44-488c-a91a-736867f1ba50'
SET person_736867f1ba50.isni_list = ['http://isni.org/isni/0000000084131382']
SET person_736867f1ba50.source = 'musicbrainz.org'
SET person_736867f1ba50.timestamp = timestamp()

MERGE (person_2fe1f9f27da8:Person{ uuid: 'a4c73ebe-b2c7-4f13-b99d-2fe1f9f27da8' }) 
SET person_2fe1f9f27da8.name = 'Cannonball Adderley'
SET person_2fe1f9f27da8.gender = 'Male'
SET person_2fe1f9f27da8.country = 'US'
SET person_2fe1f9f27da8.allmusic = 'https://www.allmusic.com/artist/mn0000548338'
SET person_2fe1f9f27da8.discogs = 'https://www.discogs.com/artist/61585'
SET person_2fe1f9f27da8.imdb = 'https://www.imdb.com/name/nm0011645/'
SET person_2fe1f9f27da8.viaf = 'http://viaf.org/viaf/36906016'
SET person_2fe1f9f27da8.wikidata = 'https://www.wikidata.org/wiki/Q110477'
SET person_2fe1f9f27da8.databases = ['http://id.loc.gov/authorities/names/n84163049', 'https://catalogue.bnf.fr/ark:/12148/cb138905900', 'https://d-nb.info/gnd/122466616', 'http://snaccooperative.org/ark:/99166/w65q52jh', 'https://rateyourmusic.com/artist/cannonball_adderley', 'https://www.worldcat.org/identities/lccn-n84163049']
SET person_2fe1f9f27da8.musicbrainz = 'https://musicbrainz.org/artist/a4c73ebe-b2c7-4f13-b99d-2fe1f9f27da8'
SET person_2fe1f9f27da8.isni_list = ['http://isni.org/isni/000000011566991X']
SET person_2fe1f9f27da8.source = 'musicbrainz.org'
SET person_2fe1f9f27da8.timestamp = timestamp()

MERGE (person_43ac1e7a092c:Person{ uuid: '17e2ae06-6200-476c-b904-43ac1e7a092c' }) 
SET person_43ac1e7a092c.name = 'Jerome Richardson'
SET person_43ac1e7a092c.gender = 'Male'
SET person_43ac1e7a092c.country = 'US'
SET person_43ac1e7a092c.allmusic = 'https://www.allmusic.com/artist/mn0000273205'
SET person_43ac1e7a092c.discogs = 'https://www.discogs.com/artist/72480'
SET person_43ac1e7a092c.viaf = 'http://viaf.org/viaf/42026472'
SET person_43ac1e7a092c.wikidata = 'https://www.wikidata.org/wiki/Q720693'
SET person_43ac1e7a092c.wikipedia = 'https://en.wikipedia.org/wiki/Jerome_Richardson'
SET person_43ac1e7a092c.databases = ['http://id.loc.gov/authorities/names/n83189459', 'https://adp.library.ucsb.edu/names/208507', 'https://catalogue.bnf.fr/ark:/12148/cb13898983r', 'https://d-nb.info/gnd/134496787', 'https://www.worldcat.org/identities/lccn-n83189459']
SET person_43ac1e7a092c.musicbrainz = 'https://musicbrainz.org/artist/17e2ae06-6200-476c-b904-43ac1e7a092c'
SET person_43ac1e7a092c.isni_list = ['http://isni.org/isni/0000000063021168']
SET person_43ac1e7a092c.source = 'musicbrainz.org'
SET person_43ac1e7a092c.timestamp = timestamp()

MERGE (person_8c848a4765b6:Person{ uuid: 'd185d986-ee96-4fd3-bd61-8c848a4765b6' }) 
SET person_8c848a4765b6.name = 'Horace Silver'
SET person_8c848a4765b6.gender = 'Male'
SET person_8c848a4765b6.country = 'US'
SET person_8c848a4765b6.allmusic = 'https://www.allmusic.com/artist/mn0000267354'
SET person_8c848a4765b6.discogs = 'https://www.discogs.com/artist/29973'
SET person_8c848a4765b6.imdb = 'https://www.imdb.com/name/nm0798701/'
SET person_8c848a4765b6.viaf = 'http://viaf.org/viaf/8537804'
SET person_8c848a4765b6.wikidata = 'https://www.wikidata.org/wiki/Q365560'
SET person_8c848a4765b6.databases = ['http://id.loc.gov/authorities/names/n82003124', 'https://adp.library.ucsb.edu/names/343818', 'https://catalogue.bnf.fr/ark:/12148/cb13899777h', 'https://d-nb.info/gnd/132099594', 'http://snaccooperative.org/ark:/99166/w6p015gr', 'https://rateyourmusic.com/artist/horace_silver', 'https://www.45cat.com/artist/horace-silver', 'https://www.45worlds.com/cdalbum/artist/horace-silver', 'https://www.45worlds.com/vinyl/artist/horace-silver', 'https://www.musik-sammler.de/artist/horace-silver/', 'https://www.worldcat.org/identities/lccn-n82003124']
SET person_8c848a4765b6.musicbrainz = 'https://musicbrainz.org/artist/d185d986-ee96-4fd3-bd61-8c848a4765b6'
SET person_8c848a4765b6.isni_list = ['http://isni.org/isni/0000000108681996']
SET person_8c848a4765b6.source = 'musicbrainz.org'
SET person_8c848a4765b6.timestamp = timestamp()

MERGE (person_bd5cc139caef:Person{ uuid: '312945ac-de2b-489a-900f-bd5cc139caef' }) 
SET person_bd5cc139caef.name = 'Ozzie Cadena'
SET person_bd5cc139caef.gender = 'Male'
SET person_bd5cc139caef.country = 'US'
SET person_bd5cc139caef.discogs = 'https://www.discogs.com/artist/256568'
SET person_bd5cc139caef.viaf = 'http://viaf.org/viaf/170522620'
SET person_bd5cc139caef.wikidata = 'https://www.wikidata.org/wiki/Q2043126'
SET person_bd5cc139caef.wikipedia = 'https://en.wikipedia.org/wiki/Ozzie_Cadena'
SET person_bd5cc139caef.databases = ['http://id.loc.gov/authorities/names/n2011026669', 'https://d-nb.info/gnd/174031378', 'https://www.worldcat.org/identities/lccn-n2011026669']
SET person_bd5cc139caef.musicbrainz = 'https://musicbrainz.org/artist/312945ac-de2b-489a-900f-bd5cc139caef'
SET person_bd5cc139caef.isni_list = ['http://isni.org/isni/0000000119288217']
SET person_bd5cc139caef.source = 'musicbrainz.org'
SET person_bd5cc139caef.timestamp = timestamp()

MERGE (person_7de13124b970:Person{ uuid: 'b6ff4fd0-03ae-41a6-942e-7de13124b970' }) 
SET person_7de13124b970.name = 'Paul Chambers'
SET person_7de13124b970.gender = 'Male'
SET person_7de13124b970.disambiguation = 'US jazz bassist'
SET person_7de13124b970.country = 'US'
SET person_7de13124b970.allmusic = 'https://www.allmusic.com/artist/mn0000747984'
SET person_7de13124b970.discogs = 'https://www.discogs.com/artist/259778'
SET person_7de13124b970.imdb = 'https://www.imdb.com/name/nm2424848/'
SET person_7de13124b970.viaf = 'http://viaf.org/viaf/100313280'
SET person_7de13124b970.wikidata = 'https://www.wikidata.org/wiki/Q541659'
SET person_7de13124b970.databases = ['http://id.loc.gov/authorities/names/n84148412', 'https://adp.library.ucsb.edu/names/308013', 'https://catalogue.bnf.fr/ark:/12148/cb138923573', 'https://d-nb.info/gnd/134345797', 'http://snaccooperative.org/ark:/99166/w6ht3khn', 'https://www.worldcat.org/identities/lccn-n84148412']
SET person_7de13124b970.musicbrainz = 'https://musicbrainz.org/artist/b6ff4fd0-03ae-41a6-942e-7de13124b970'
SET person_7de13124b970.isni_list = ['http://isni.org/isni/0000000109289128']
SET person_7de13124b970.source = 'musicbrainz.org'
SET person_7de13124b970.timestamp = timestamp()

MERGE (person_c59f9296195a:Person{ uuid: '69f95e5c-4b34-4c8b-b8fe-c59f9296195a' }) 
SET person_c59f9296195a.name = 'Donald Byrd'
SET person_c59f9296195a.gender = 'Male'
SET person_c59f9296195a.disambiguation = 'American jazz trumpeter'
SET person_c59f9296195a.country = 'US'
SET person_c59f9296195a.allmusic = 'https://www.allmusic.com/artist/mn0000149946'
SET person_c59f9296195a.bbc = 'https://www.bbc.co.uk/music/artists/69f95e5c-4b34-4c8b-b8fe-c59f9296195a'
SET person_c59f9296195a.discogs = 'https://www.discogs.com/artist/20956'
SET person_c59f9296195a.imdb = 'https://www.imdb.com/name/nm0126014/'
SET person_c59f9296195a.viaf = 'http://viaf.org/viaf/195495'
SET person_c59f9296195a.wikidata = 'https://www.wikidata.org/wiki/Q362764'
SET person_c59f9296195a.databases = ['http://id.loc.gov/authorities/names/n81011276', 'https://catalogue.bnf.fr/ark:/12148/cb13892039b', 'https://d-nb.info/gnd/11951947X', 'http://snaccooperative.org/ark:/99166/w6380n0c', 'https://rateyourmusic.com/artist/donald_byrd', 'https://www.musik-sammler.de/artist/donald-byrd/', 'https://www.worldcat.org/identities/lccn-n81-011276']
SET person_c59f9296195a.musicbrainz = 'https://musicbrainz.org/artist/69f95e5c-4b34-4c8b-b8fe-c59f9296195a'
SET person_c59f9296195a.isni_list = ['http://isni.org/isni/0000000114363273']
SET person_c59f9296195a.source = 'musicbrainz.org'
SET person_c59f9296195a.timestamp = timestamp()

MERGE (person_68151336a430:Person{ uuid: 'a9e79d89-f90b-4cef-943e-68151336a430' }) 
SET person_68151336a430.name = 'Nat Adderley'
SET person_68151336a430.gender = 'Male'
SET person_68151336a430.country = 'US'
SET person_68151336a430.allmusic = 'https://www.allmusic.com/artist/mn0000377060'
SET person_68151336a430.discogs = 'https://www.discogs.com/artist/160829'
SET person_68151336a430.imdb = 'https://www.imdb.com/name/nm0011650/'
SET person_68151336a430.viaf = 'http://viaf.org/viaf/114609437'
SET person_68151336a430.wikidata = 'https://www.wikidata.org/wiki/Q499649'
SET person_68151336a430.databases = ['http://id.loc.gov/authorities/names/n83183584', 'https://catalogue.bnf.fr/ark:/12148/cb13890592p', 'https://d-nb.info/gnd/134311108', 'http://snaccooperative.org/ark:/99166/w6qj9vk7', 'https://rateyourmusic.com/artist/nat_adderley', 'https://www.worldcat.org/identities/lccn-n83183584']
SET person_68151336a430.musicbrainz = 'https://musicbrainz.org/artist/a9e79d89-f90b-4cef-943e-68151336a430'
SET person_68151336a430.isni_list = ['http://isni.org/isni/0000000116999822']
SET person_68151336a430.source = 'musicbrainz.org'
SET person_68151336a430.timestamp = timestamp()

MERGE (person_950944791698:Person{ uuid: '80d610fe-7771-4226-aa9b-950944791698' }) 
SET person_950944791698.name = 'Hank Jones'
SET person_950944791698.gender = 'Male'
SET person_950944791698.disambiguation = 'piano'
SET person_950944791698.country = 'US'
SET person_950944791698.allmusic = 'https://www.allmusic.com/artist/mn0000558339'
SET person_950944791698.bbc = 'https://www.bbc.co.uk/music/artists/80d610fe-7771-4226-aa9b-950944791698'
SET person_950944791698.discogs = 'https://www.discogs.com/artist/265629'
SET person_950944791698.imdb = 'https://www.imdb.com/name/nm0428192/'
SET person_950944791698.viaf = 'http://viaf.org/viaf/114552168'
SET person_950944791698.wikidata = 'https://www.wikidata.org/wiki/Q447907'
SET person_950944791698.databases = ['http://id.loc.gov/authorities/names/n81058273', 'https://adp.library.ucsb.edu/names/323999', 'https://catalogue.bnf.fr/ark:/12148/cb138957259', 'https://d-nb.info/gnd/134419448', 'http://snaccooperative.org/ark:/99166/w6qg27rp', 'https://rateyourmusic.com/artist/hank_jones', 'https://www.worldcat.org/identities/lccn-n81058273']
SET person_950944791698.musicbrainz = 'https://musicbrainz.org/artist/80d610fe-7771-4226-aa9b-950944791698'
SET person_950944791698.isni_list = ['http://isni.org/isni/0000000081828205']
SET person_950944791698.source = 'musicbrainz.org'
SET person_950944791698.timestamp = timestamp()
// labels

MERGE (label_5822644d3a96:Label{ uuid: 'afca1966-d675-4754-8baf-5822644d3a96' })
SET label_5822644d3a96.name= 'Savoy Records'

// performances

MERGE (perf_f29ae986bae2:Performance{ uuid: 'a4c6da16-eb39-44ba-9d1a-f29ae986bae2' })
SET perf_f29ae986bae2.name = 'Bohemia After Dark'
SET perf_f29ae986bae2.disambiguation = 'original LP mono mix'
SET perf_f29ae986bae2.duration = '6:05'
SET perf_f29ae986bae2.begin = '1955-06-28'
SET perf_f29ae986bae2.end = '1955-06-28'
SET perf_f29ae986bae2.source = 'musicbrainz.org'
SET perf_f29ae986bae2.timestamp = timestamp()

MERGE (perf_3ac2e8d2b9dc:Performance{ uuid: 'c2953513-f135-4c16-b1a7-3ac2e8d2b9dc' })
SET perf_3ac2e8d2b9dc.name = 'Chasm'
SET perf_3ac2e8d2b9dc.disambiguation = 'original LP mono mix'
SET perf_3ac2e8d2b9dc.duration = '4:22'
SET perf_3ac2e8d2b9dc.begin = '1955-06-28'
SET perf_3ac2e8d2b9dc.end = '1955-06-28'
SET perf_3ac2e8d2b9dc.source = 'musicbrainz.org'
SET perf_3ac2e8d2b9dc.timestamp = timestamp()

MERGE (perf_00adca3a4eda:Performance{ uuid: 'fd82d5be-c0d3-4a4f-a544-00adca3a4eda' })
SET perf_00adca3a4eda.name = 'Willow Weep for Me'
SET perf_00adca3a4eda.disambiguation = 'original LP mono mix'
SET perf_00adca3a4eda.duration = '6:22'
SET perf_00adca3a4eda.begin = '1955-06-28'
SET perf_00adca3a4eda.end = '1955-06-28'
SET perf_00adca3a4eda.source = 'musicbrainz.org'
SET perf_00adca3a4eda.timestamp = timestamp()

MERGE (perf_b1b605fd1d67:Performance{ uuid: '8bed55a9-b9b1-4ed4-a9f4-b1b605fd1d67' })
SET perf_b1b605fd1d67.name = 'Late Entry'
SET perf_b1b605fd1d67.disambiguation = 'original LP mono mix'
SET perf_b1b605fd1d67.duration = '3:10'
SET perf_b1b605fd1d67.begin = '1955-06-28'
SET perf_b1b605fd1d67.end = '1955-06-28'
SET perf_b1b605fd1d67.source = 'musicbrainz.org'
SET perf_b1b605fd1d67.timestamp = timestamp()

MERGE (perf_6a57513718fd:Performance{ uuid: '8a319956-812c-40a9-8d48-6a57513718fd' })
SET perf_6a57513718fd.name = 'Hear Me Talkin’ to Ya'
SET perf_6a57513718fd.disambiguation = 'original LP mono mix'
SET perf_6a57513718fd.duration = '3:12'
SET perf_6a57513718fd.begin = '1955-06-28'
SET perf_6a57513718fd.end = '1955-06-28'
SET perf_6a57513718fd.source = 'musicbrainz.org'
SET perf_6a57513718fd.timestamp = timestamp()

MERGE (perf_fcd621df4f70:Performance{ uuid: 'd1217717-eaf6-436b-8812-fcd621df4f70' })
SET perf_fcd621df4f70.name = 'With Apologies to Oscar'
SET perf_fcd621df4f70.disambiguation = 'original LP mono mix'
SET perf_fcd621df4f70.duration = '9:06'
SET perf_fcd621df4f70.begin = '1955-06-28'
SET perf_fcd621df4f70.end = '1955-06-28'
SET perf_fcd621df4f70.source = 'musicbrainz.org'
SET perf_fcd621df4f70.timestamp = timestamp()

MERGE (perf_e7e15bb77fe6:Performance{ uuid: 'b5dedc8f-9652-467a-8f59-e7e15bb77fe6' })
SET perf_e7e15bb77fe6.name = 'We’ll Be Together Again'
SET perf_e7e15bb77fe6.disambiguation = 'original LP mono mix'
SET perf_e7e15bb77fe6.duration = '5:42'
SET perf_e7e15bb77fe6.begin = '1955-07-14'
SET perf_e7e15bb77fe6.end = '1955-07-14'
SET perf_e7e15bb77fe6.source = 'musicbrainz.org'
SET perf_e7e15bb77fe6.timestamp = timestamp()



// labels
MERGE (release_958f393dfab9)-[:HAS_LABEL]->(label_5822644d3a96)


// tracks
MERGE (release_958f393dfab9)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_f29ae986bae2)
MERGE (release_958f393dfab9)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_3ac2e8d2b9dc)
MERGE (release_958f393dfab9)-[:HAS_TRACK {name: 'A3', sequence: 3}]->(perf_00adca3a4eda)
MERGE (release_958f393dfab9)-[:HAS_TRACK {name: 'A4', sequence: 4}]->(perf_b1b605fd1d67)
MERGE (release_958f393dfab9)-[:HAS_TRACK {name: 'B1', sequence: 5}]->(perf_6a57513718fd)
MERGE (release_958f393dfab9)-[:HAS_TRACK {name: 'B2', sequence: 6}]->(perf_fcd621df4f70)
MERGE (release_958f393dfab9)-[:HAS_TRACK {name: 'B3', sequence: 7}]->(perf_e7e15bb77fe6)

// works

MERGE (person_1d4909875ca1:Person{ uuid: '28f6d494-d44b-4bd3-aed9-1d4909875ca1' }) 
SET person_1d4909875ca1.name = 'Oscar Pettiford'
SET person_1d4909875ca1.gender = 'Male'
SET person_1d4909875ca1.country = 'US'
SET person_1d4909875ca1.allmusic = 'https://www.allmusic.com/artist/mn0000896298'
SET person_1d4909875ca1.discogs = 'https://www.discogs.com/artist/255767'
SET person_1d4909875ca1.imdb = 'https://www.imdb.com/name/nm0678652/'
SET person_1d4909875ca1.viaf = 'http://viaf.org/viaf/24788159'
SET person_1d4909875ca1.wikidata = 'https://www.wikidata.org/wiki/Q497183'
SET person_1d4909875ca1.wikipedia = 'https://en.wikipedia.org/wiki/Oscar_Pettiford'
SET person_1d4909875ca1.databases = ['http://id.loc.gov/authorities/names/n85098446', 'https://adp.library.ucsb.edu/names/104881', 'https://catalogue.bnf.fr/ark:/12148/cb13898427w', 'https://d-nb.info/gnd/133111644', 'http://snaccooperative.org/ark:/99166/w6df7c1p', 'https://rateyourmusic.com/artist/oscar-pettiford', 'https://www.worldcat.org/identities/lccn-n85098446']
SET person_1d4909875ca1.musicbrainz = 'https://musicbrainz.org/artist/28f6d494-d44b-4bd3-aed9-1d4909875ca1'
SET person_1d4909875ca1.isni_list = ['http://isni.org/isni/0000000081037921']
SET person_1d4909875ca1.source = 'musicbrainz.org'
SET person_1d4909875ca1.timestamp = timestamp()

MERGE (person_fb6943c03214:Person{ uuid: 'bb56bf3b-053d-470a-945e-fb6943c03214' }) 
SET person_fb6943c03214.name = 'Frankie Laine'
SET person_fb6943c03214.gender = 'Male'
SET person_fb6943c03214.country = 'US'
SET person_fb6943c03214.allmusic = 'https://www.allmusic.com/artist/mn0000142178'
SET person_fb6943c03214.bbc = 'https://www.bbc.co.uk/music/artists/bb56bf3b-053d-470a-945e-fb6943c03214'
SET person_fb6943c03214.discogs = 'https://www.discogs.com/artist/377935'
SET person_fb6943c03214.imdb = 'https://www.imdb.com/name/nm0481840/'
SET person_fb6943c03214.viaf = 'http://viaf.org/viaf/112734547'
SET person_fb6943c03214.wikidata = 'https://www.wikidata.org/wiki/Q342774'
SET person_fb6943c03214.databases = ['http://id.loc.gov/authorities/names/n84145390', 'https://adp.library.ucsb.edu/names/360297', 'https://catalogue.bnf.fr/ark:/12148/cb13896272p', 'https://d-nb.info/gnd/119140314', 'http://snaccooperative.org/ark:/99166/w6r52dwr', 'https://rateyourmusic.com/artist/frankie_laine', 'https://www.ibdb.com/person.php?id=413377', 'https://www.worldcat.org/identities/lccn-n84145390']
SET person_fb6943c03214.musicbrainz = 'https://musicbrainz.org/artist/bb56bf3b-053d-470a-945e-fb6943c03214'
SET person_fb6943c03214.isni_list = ['http://isni.org/isni/0000000081802267']
SET person_fb6943c03214.source = 'musicbrainz.org'
SET person_fb6943c03214.timestamp = timestamp()

MERGE (person_20608cddce49:Person{ uuid: '9bb2e341-a898-46b8-9e57-20608cddce49' }) 
SET person_20608cddce49.name = 'Carl Fischer'
SET person_20608cddce49.gender = 'Male'
SET person_20608cddce49.disambiguation = 'Native American jazz pianist and composer'
SET person_20608cddce49.country = 'US'
SET person_20608cddce49.allmusic = 'https://www.allmusic.com/artist/mn0000177121'
SET person_20608cddce49.discogs = 'https://www.discogs.com/artist/708475'
SET person_20608cddce49.viaf = 'http://viaf.org/viaf/10115406'
SET person_20608cddce49.wikidata = 'https://www.wikidata.org/wiki/Q5040863'
SET person_20608cddce49.databases = ['http://id.loc.gov/authorities/names/n84145391', 'https://catalogue.bnf.fr/ark:/12148/cb14839416c', 'https://nla.gov.au/nla.party-1530507', 'https://rateyourmusic.com/artist/carl_fischer_f1', 'https://www.worldcat.org/identities/lccn-n84145391/']
SET person_20608cddce49.musicbrainz = 'https://musicbrainz.org/artist/9bb2e341-a898-46b8-9e57-20608cddce49'
SET person_20608cddce49.isni_list = ['http://isni.org/isni/0000000073571526']
SET person_20608cddce49.source = 'musicbrainz.org'
SET person_20608cddce49.timestamp = timestamp()

MERGE (person_e63d8de33aa2:Person{ uuid: '475e4df5-358a-45b3-89c9-e63d8de33aa2' }) 
SET person_e63d8de33aa2.name = 'Ann Ronell'
SET person_e63d8de33aa2.gender = 'Female'
SET person_e63d8de33aa2.country = 'US'
SET person_e63d8de33aa2.discogs = 'https://www.discogs.com/artist/565717'
SET person_e63d8de33aa2.imdb = 'https://www.imdb.com/name/nm0740056/'
SET person_e63d8de33aa2.viaf = 'http://viaf.org/viaf/101182977'
SET person_e63d8de33aa2.wikidata = 'https://www.wikidata.org/wiki/Q532253'
SET person_e63d8de33aa2.databases = ['http://id.loc.gov/authorities/names/n85342742', 'https://adp.library.ucsb.edu/names/105158', 'https://catalogue.bnf.fr/ark:/12148/cb138100919', 'https://d-nb.info/gnd/139443649', 'http://snaccooperative.org/ark:/99166/w6vx8d1b', 'https://www.ibdb.com/person.php?id=12319', 'https://www.worldcat.org/identities/lccn-n85342742/']
SET person_e63d8de33aa2.musicbrainz = 'https://musicbrainz.org/artist/475e4df5-358a-45b3-89c9-e63d8de33aa2'
SET person_e63d8de33aa2.isni_list = ['http://isni.org/isni/0000000119450325']
SET person_e63d8de33aa2.source = 'musicbrainz.org'
SET person_e63d8de33aa2.timestamp = timestamp()

MERGE (work_9f0138cf01bb:Work{ uuid: 'ce5a2a2a-1243-4d58-a665-9f0138cf01bb' })
SET work_9f0138cf01bb.name = 'Hear Me Talkin’ to Ya'
SET work_9f0138cf01bb.iswc = 'T-911.060.816-7'
SET work_9f0138cf01bb.type = 'Song'
SET work_9f0138cf01bb.source = 'musicbrainz.org'
SET work_9f0138cf01bb.timestamp = timestamp()

MERGE (work_ce6762643e0e:Work{ uuid: '61eb15ba-45f4-4708-9d9d-ce6762643e0e' })
SET work_ce6762643e0e.name = 'Chasm'
SET work_ce6762643e0e.source = 'musicbrainz.org'
SET work_ce6762643e0e.timestamp = timestamp()

MERGE (work_d184b59d742f:Work{ uuid: '219d7e1d-64fa-3e0d-bb07-d184b59d742f' })
SET work_d184b59d742f.name = 'Willow Weep for Me'
SET work_d184b59d742f.iswc = 'T-070.200.285-4'
SET work_d184b59d742f.type = 'Song'
SET work_d184b59d742f.tags = ['instrumental', 'jazz']
SET work_d184b59d742f.wikidata = 'https://www.wikidata.org/wiki/Q820873'
SET work_d184b59d742f.wikipedia = 'https://en.wikipedia.org/wiki/Willow_Weep_for_Me'
SET work_d184b59d742f.musicbrainz = 'https://musicbrainz.org/work/219d7e1d-64fa-3e0d-bb07-d184b59d742f'
SET work_d184b59d742f.source = 'musicbrainz.org'
SET work_d184b59d742f.timestamp = timestamp()

MERGE (work_d218d6258683:Work{ uuid: 'f17194e6-e0e0-3843-ae01-d218d6258683' })
SET work_d218d6258683.name = 'We’ll Be Together Again'
SET work_d218d6258683.iswc = 'T-070.197.808-6'
SET work_d218d6258683.type = 'Song'
SET work_d218d6258683.wikidata = 'https://www.wikidata.org/wiki/Q7977050'
SET work_d218d6258683.musicbrainz = 'https://musicbrainz.org/work/f17194e6-e0e0-3843-ae01-d218d6258683'
SET work_d218d6258683.source = 'musicbrainz.org'
SET work_d218d6258683.timestamp = timestamp()

MERGE (work_613a71af98eb:Work{ uuid: 'c9d74c45-28ca-481f-8a01-613a71af98eb' })
SET work_613a71af98eb.name = 'Bohemia After Dark'
SET work_613a71af98eb.iswc = 'T-070.233.020-8'
SET work_613a71af98eb.type = 'Song'
SET work_613a71af98eb.wikipedia = 'https://en.wikipedia.org/wiki/Bohemia_After_Dark'
SET work_613a71af98eb.musicbrainz = 'https://musicbrainz.org/work/c9d74c45-28ca-481f-8a01-613a71af98eb'
SET work_613a71af98eb.source = 'musicbrainz.org'
SET work_613a71af98eb.timestamp = timestamp()

MERGE (work_06fde2831767:Work{ uuid: 'c02b43a6-6ef6-490d-9829-06fde2831767' })
SET work_06fde2831767.name = 'With Apologies to Oscar'
SET work_06fde2831767.iswc = 'T-918.301.314-1'
SET work_06fde2831767.type = 'Song'
SET work_06fde2831767.source = 'musicbrainz.org'
SET work_06fde2831767.timestamp = timestamp()

MERGE (work_c8d3fd21f5be:Work{ uuid: 'a253b9bf-7141-4512-910d-c8d3fd21f5be' })
SET work_c8d3fd21f5be.name = 'Late Entry'
SET work_c8d3fd21f5be.source = 'musicbrainz.org'
SET work_c8d3fd21f5be.timestamp = timestamp()


// performances of
MERGE (perf_6a57513718fd)-[:PERFORMANCE_OF]->(work_9f0138cf01bb)
MERGE (perf_3ac2e8d2b9dc)-[:PERFORMANCE_OF]->(work_ce6762643e0e)
MERGE (perf_00adca3a4eda)-[:PERFORMANCE_OF]->(work_d184b59d742f)
MERGE (perf_e7e15bb77fe6)-[:PERFORMANCE_OF]->(work_d218d6258683)
MERGE (perf_f29ae986bae2)-[:PERFORMANCE_OF]->(work_613a71af98eb)
MERGE (perf_fcd621df4f70)-[:PERFORMANCE_OF]->(work_06fde2831767)
MERGE (perf_b1b605fd1d67)-[:PERFORMANCE_OF]->(work_c8d3fd21f5be)


// composers
MERGE (person_2fe1f9f27da8)-[:COMPOSED]->(work_9f0138cf01bb)
MERGE (person_68151336a430)-[:COMPOSED]->(work_9f0138cf01bb)
MERGE (person_2fe1f9f27da8)-[:COMPOSED]->(work_ce6762643e0e)
MERGE (person_68151336a430)-[:COMPOSED]->(work_ce6762643e0e)
MERGE (person_e63d8de33aa2)-[:COMPOSED]->(work_d184b59d742f)
MERGE (person_e63d8de33aa2)-[:WROTE_LYRICS]->(work_d184b59d742f)
MERGE (person_20608cddce49)-[:COMPOSED]->(work_d218d6258683)
MERGE (person_fb6943c03214)-[:WROTE_LYRICS]->(work_d218d6258683)
MERGE (person_1d4909875ca1)-[:COMPOSED]->(work_613a71af98eb)
MERGE (person_2fe1f9f27da8)-[:COMPOSED]->(work_06fde2831767)
MERGE (person_68151336a430)-[:COMPOSED]->(work_06fde2831767)
MERGE (person_2fe1f9f27da8)-[:COMPOSED]->(work_c8d3fd21f5be)
MERGE (person_68151336a430)-[:COMPOSED]->(work_c8d3fd21f5be)


// place nodes

MERGE (place_271570d01045:Place{ uuid: '695da5d6-a0a0-40bc-828a-271570d01045' })
SET place_271570d01045.name = 'Beltone Studios'
SET place_271570d01045.source = 'musicbrainz.org'

MERGE (place_decbb365c07f:Place{ uuid: '74e50e58-5deb-4b99-93a2-decbb365c07f' })
SET place_decbb365c07f.name = 'New York'
SET place_decbb365c07f.source = 'musicbrainz.org'


// place relationships
MERGE (perf_f29ae986bae2)-[:HAS_PLACE { type: 'recorded at', begin: '1955-06-28', end: '1955-06-28' }]->(place_271570d01045)
MERGE (perf_f29ae986bae2)-[:HAS_PLACE { type: 'recorded in', begin: '1955-06-28', end: '1955-06-28' }]->(place_decbb365c07f)
MERGE (perf_3ac2e8d2b9dc)-[:HAS_PLACE { type: 'recorded at', begin: '1955-06-28', end: '1955-06-28' }]->(place_271570d01045)
MERGE (perf_3ac2e8d2b9dc)-[:HAS_PLACE { type: 'recorded in', begin: '1955-06-28', end: '1955-06-28' }]->(place_decbb365c07f)
MERGE (perf_00adca3a4eda)-[:HAS_PLACE { type: 'recorded at', begin: '1955-06-28', end: '1955-06-28' }]->(place_271570d01045)
MERGE (perf_00adca3a4eda)-[:HAS_PLACE { type: 'recorded in', begin: '1955-06-28', end: '1955-06-28' }]->(place_decbb365c07f)
MERGE (perf_b1b605fd1d67)-[:HAS_PLACE { type: 'recorded at', begin: '1955-06-28', end: '1955-06-28' }]->(place_271570d01045)
MERGE (perf_b1b605fd1d67)-[:HAS_PLACE { type: 'recorded in', begin: '1955-06-28', end: '1955-06-28' }]->(place_decbb365c07f)
MERGE (perf_6a57513718fd)-[:HAS_PLACE { type: 'recorded in', begin: '1955-06-28', end: '1955-06-28' }]->(place_decbb365c07f)
MERGE (perf_fcd621df4f70)-[:HAS_PLACE { type: 'recorded in', begin: '1955-06-28', end: '1955-06-28' }]->(place_decbb365c07f)
MERGE (perf_e7e15bb77fe6)-[:HAS_PLACE { type: 'recorded in', begin: '1955-07-14', end: '1955-07-14' }]->(place_decbb365c07f)

MERGE (person_2fe1f9f27da8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_f29ae986bae2)
MERGE (person_68151336a430)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['cornet'] }]->(perf_f29ae986bae2)
MERGE (person_c59f9296195a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_f29ae986bae2)
MERGE (person_7de13124b970)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_f29ae986bae2)
MERGE (person_736867f1ba50)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_f29ae986bae2)
MERGE (person_43ac1e7a092c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone', 'flute'] }]->(perf_f29ae986bae2)
MERGE (person_8c848a4765b6)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_f29ae986bae2)
MERGE (person_bd5cc139caef)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_f29ae986bae2)
MERGE (person_2fe1f9f27da8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_68151336a430)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['cornet'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_c59f9296195a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_7de13124b970)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_736867f1ba50)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_43ac1e7a092c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone', 'flute'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_8c848a4765b6)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_bd5cc139caef)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_3ac2e8d2b9dc)
MERGE (person_2fe1f9f27da8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_00adca3a4eda)
MERGE (person_68151336a430)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['cornet'] }]->(perf_00adca3a4eda)
MERGE (person_c59f9296195a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_00adca3a4eda)
MERGE (person_7de13124b970)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_00adca3a4eda)
MERGE (person_736867f1ba50)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_00adca3a4eda)
MERGE (person_43ac1e7a092c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone', 'flute'] }]->(perf_00adca3a4eda)
MERGE (person_8c848a4765b6)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_00adca3a4eda)
MERGE (person_bd5cc139caef)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_00adca3a4eda)
MERGE (person_2fe1f9f27da8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_b1b605fd1d67)
MERGE (person_68151336a430)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['cornet'] }]->(perf_b1b605fd1d67)
MERGE (person_7de13124b970)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_b1b605fd1d67)
MERGE (person_736867f1ba50)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_b1b605fd1d67)
MERGE (person_43ac1e7a092c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone', 'flute'] }]->(perf_b1b605fd1d67)
MERGE (person_8c848a4765b6)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_b1b605fd1d67)
MERGE (person_c59f9296195a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_b1b605fd1d67)
MERGE (person_2fe1f9f27da8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_6a57513718fd)
MERGE (person_68151336a430)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['cornet'] }]->(perf_6a57513718fd)
MERGE (person_c59f9296195a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_6a57513718fd)
MERGE (person_7de13124b970)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_6a57513718fd)
MERGE (person_736867f1ba50)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_6a57513718fd)
MERGE (person_8c848a4765b6)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_6a57513718fd)
MERGE (person_2fe1f9f27da8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_fcd621df4f70)
MERGE (person_68151336a430)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['cornet'] }]->(perf_fcd621df4f70)
MERGE (person_c59f9296195a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_fcd621df4f70)
MERGE (person_7de13124b970)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_fcd621df4f70)
MERGE (person_736867f1ba50)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_fcd621df4f70)
MERGE (person_43ac1e7a092c)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flute', 'tenor saxophone'] }]->(perf_fcd621df4f70)
MERGE (person_8c848a4765b6)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_fcd621df4f70)
MERGE (person_68151336a430)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['cornet'] }]->(perf_e7e15bb77fe6)
MERGE (person_7de13124b970)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_e7e15bb77fe6)
MERGE (person_736867f1ba50)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_e7e15bb77fe6)
MERGE (person_950944791698)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e7e15bb77fe6)

