// releases

MERGE (release_722909072753:Release{ uuid: '065a2ee7-f9a2-4eb6-b8c0-722909072753' })
SET release_722909072753.name = 'Jazz Club Montmartre - CPH 1988'
SET release_722909072753.country = 'XW'
SET release_722909072753.date = '2024-11-15'
SET release_722909072753.format = 'Digital Media'
SET release_722909072753.format = 'Digital Media'
SET release_722909072753.allmusic = 'https://www.allmusic.com/album/release/mr0006525837'
SET release_722909072753.musicbrainz = 'http://musicbrainz.org/release/065a2ee7-f9a2-4eb6-b8c0-722909072753'
SET release_722909072753.source = 'musicbrainz.org'
SET release_722909072753.timestamp = timestamp()

MERGE (person_6695d86cdc19:Person{ uuid: '2b75141c-05e9-42eb-ae63-6695d86cdc19' }) 
SET person_6695d86cdc19.name = 'Michel Petrucciani'
SET person_6695d86cdc19.gender = 'Male'
SET person_6695d86cdc19.country = 'FR'
SET person_6695d86cdc19.allmusic = 'https://www.allmusic.com/artist/mn0000890236'
SET person_6695d86cdc19.discogs = 'https://www.discogs.com/artist/44122'
SET person_6695d86cdc19.imdb = 'https://www.imdb.com/name/nm0997737/'
SET person_6695d86cdc19.viaf = 'http://viaf.org/viaf/56797351'
SET person_6695d86cdc19.wikidata = 'https://www.wikidata.org/wiki/Q317155'
SET person_6695d86cdc19.databases = ['http://id.loc.gov/authorities/names/n84163016', 'https://catalogue.bnf.fr/ark:/12148/cb13898424v', 'https://d-nb.info/gnd/124458939', 'https://www.metal-archives.com/artists/Michel_Petrucciani/463912', 'https://www.worldcat.org/identities/lccn-n84163016']
SET person_6695d86cdc19.musicbrainz = 'https://musicbrainz.org/artist/2b75141c-05e9-42eb-ae63-6695d86cdc19'
SET person_6695d86cdc19.isni_list = ['http://isni.org/isni/0000000055146374']
SET person_6695d86cdc19.source = 'musicbrainz.org'
SET person_6695d86cdc19.timestamp = timestamp()

MERGE (person_644705f6e4f4:Person{ uuid: '0cd9e25c-1cb1-45e3-aba2-644705f6e4f4' }) 
SET person_644705f6e4f4.name = 'Gary Peacock'
SET person_644705f6e4f4.gender = 'Male'
SET person_644705f6e4f4.disambiguation = 'American jazz bassist'
SET person_644705f6e4f4.country = 'US'
SET person_644705f6e4f4.allmusic = 'https://www.allmusic.com/artist/mn0000153503'
SET person_644705f6e4f4.discogs = 'https://www.discogs.com/artist/255129'
SET person_644705f6e4f4.imdb = 'https://www.imdb.com/name/nm1034190/'
SET person_644705f6e4f4.viaf = 'http://viaf.org/viaf/119979251'
SET person_644705f6e4f4.wikidata = 'https://www.wikidata.org/wiki/Q466198'
SET person_644705f6e4f4.databases = ['http://id.loc.gov/authorities/names/n81058247', 'https://catalogue.bnf.fr/ark:/12148/cb13898318n', 'https://d-nb.info/gnd/134481836', 'https://rateyourmusic.com/artist/gary_peacock', 'https://www.worldcat.org/identities/lccn-n81058247']
SET person_644705f6e4f4.musicbrainz = 'https://musicbrainz.org/artist/0cd9e25c-1cb1-45e3-aba2-644705f6e4f4'
SET person_644705f6e4f4.isni_list = ['http://isni.org/isni/0000000081889913']
SET person_644705f6e4f4.source = 'musicbrainz.org'
SET person_644705f6e4f4.timestamp = timestamp()

MERGE (person_0b42e7f7b76d:Person{ uuid: 'e12abb8b-64a9-4fac-a200-0b42e7f7b76d' }) 
SET person_0b42e7f7b76d.name = 'Ole Matthiesen'
SET person_0b42e7f7b76d.gender = 'Male'
SET person_0b42e7f7b76d.country = 'DK'
SET person_0b42e7f7b76d.source = 'musicbrainz.org'
SET person_0b42e7f7b76d.timestamp = timestamp()

MERGE (person_fafbe605caeb:Person{ uuid: '0638d80c-b4dc-44ac-9c87-fafbe605caeb' }) 
SET person_fafbe605caeb.name = 'Christian Brorsen'
SET person_fafbe605caeb.gender = 'Male'
SET person_fafbe605caeb.disambiguation = 'Producer'
SET person_fafbe605caeb.country = 'DK'
SET person_fafbe605caeb.source = 'musicbrainz.org'
SET person_fafbe605caeb.timestamp = timestamp()

MERGE (person_07c490be8632:Person{ uuid: '0556fc6a-e6b9-4633-9c7d-07c490be8632' }) 
SET person_07c490be8632.name = 'Jørgen Vad'
SET person_07c490be8632.gender = 'Male'
SET person_07c490be8632.allmusic = 'https://www.allmusic.com/artist/mn0001015106'
SET person_07c490be8632.musicbrainz = 'https://musicbrainz.org/artist/0556fc6a-e6b9-4633-9c7d-07c490be8632'
SET person_07c490be8632.source = 'musicbrainz.org'
SET person_07c490be8632.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://id.loc.gov/authorities/names/n81140108', 'https://adp.library.ucsb.edu/names/320530', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'https://d-nb.info/gnd/134400623', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_8da285b4734c:Person{ uuid: '3abd4b6d-af5f-4efc-83aa-8da285b4734c' }) 
SET person_8da285b4734c.name = 'Lars Palsig'
SET person_8da285b4734c.gender = 'Male'
SET person_8da285b4734c.source = 'musicbrainz.org'
SET person_8da285b4734c.timestamp = timestamp()
// labels

MERGE (label_311a35f78d9f:Label{ uuid: '6a1cf9f8-fbb6-414e-9445-311a35f78d9f' })
SET label_311a35f78d9f.name= 'Storyville Records'

// performances

MERGE (perf_9fd2519c7341:Performance{ uuid: '0079348f-bc22-429b-9ec3-9fd2519c7341' })
SET perf_9fd2519c7341.name = '13th'
SET perf_9fd2519c7341.duration = '6:17'
SET perf_9fd2519c7341.begin = '1988-07-03'
SET perf_9fd2519c7341.end = '1988-07-03'
SET perf_9fd2519c7341.source = 'musicbrainz.org'
SET perf_9fd2519c7341.timestamp = timestamp()

MERGE (perf_f373078b0e9b:Performance{ uuid: '2d5afd2c-afb1-4a0f-90f7-f373078b0e9b' })
SET perf_f373078b0e9b.name = 'She Did It Again'
SET perf_f373078b0e9b.duration = '8:03'
SET perf_f373078b0e9b.begin = '1988-07-03'
SET perf_f373078b0e9b.end = '1988-07-03'
SET perf_f373078b0e9b.source = 'musicbrainz.org'
SET perf_f373078b0e9b.timestamp = timestamp()

MERGE (perf_ee034aab9554:Performance{ uuid: '234aad5c-4c7c-424a-b1f7-ee034aab9554' })
SET perf_ee034aab9554.name = 'My Funny Valentine'
SET perf_ee034aab9554.duration = '11:23'
SET perf_ee034aab9554.begin = '1988-07-03'
SET perf_ee034aab9554.end = '1988-07-03'
SET perf_ee034aab9554.source = 'musicbrainz.org'
SET perf_ee034aab9554.timestamp = timestamp()

MERGE (perf_24e088576bcf:Performance{ uuid: '1830fe0c-540b-4188-a522-24e088576bcf' })
SET perf_24e088576bcf.name = 'In a Sentimental Mood'
SET perf_24e088576bcf.duration = '6:27'
SET perf_24e088576bcf.begin = '1988-07-03'
SET perf_24e088576bcf.end = '1988-07-03'
SET perf_24e088576bcf.source = 'musicbrainz.org'
SET perf_24e088576bcf.timestamp = timestamp()

MERGE (perf_c1fd19cb1de7:Performance{ uuid: 'ffaafada-99bb-4820-b84b-c1fd19cb1de7' })
SET perf_c1fd19cb1de7.name = 'Mr. KJ'
SET perf_c1fd19cb1de7.duration = '8:38'
SET perf_c1fd19cb1de7.begin = '1988-07-03'
SET perf_c1fd19cb1de7.end = '1988-07-03'
SET perf_c1fd19cb1de7.source = 'musicbrainz.org'
SET perf_c1fd19cb1de7.timestamp = timestamp()

MERGE (perf_12a9c5b564cb:Performance{ uuid: 'f77f9f86-20bf-4979-a0e7-12a9c5b564cb' })
SET perf_12a9c5b564cb.name = 'One For Us'
SET perf_12a9c5b564cb.duration = '9:07'
SET perf_12a9c5b564cb.begin = '1988-07-03'
SET perf_12a9c5b564cb.end = '1988-07-03'
SET perf_12a9c5b564cb.source = 'musicbrainz.org'
SET perf_12a9c5b564cb.timestamp = timestamp()

MERGE (perf_337e6ba25750:Performance{ uuid: '15e45828-b70c-4ee2-add1-337e6ba25750' })
SET perf_337e6ba25750.name = 'Turnaround'
SET perf_337e6ba25750.duration = '11:11'
SET perf_337e6ba25750.begin = '1988-07-03'
SET perf_337e6ba25750.end = '1988-07-03'
SET perf_337e6ba25750.source = 'musicbrainz.org'
SET perf_337e6ba25750.timestamp = timestamp()

MERGE (perf_25cdc61ebc9d:Performance{ uuid: '2c8a1aa2-e393-4d19-a466-25cdc61ebc9d' })
SET perf_25cdc61ebc9d.name = 'It\'s a Dance'
SET perf_25cdc61ebc9d.duration = '8:33'
SET perf_25cdc61ebc9d.begin = '1988-07-03'
SET perf_25cdc61ebc9d.end = '1988-07-03'
SET perf_25cdc61ebc9d.source = 'musicbrainz.org'
SET perf_25cdc61ebc9d.timestamp = timestamp()

MERGE (perf_372c1eb48948:Performance{ uuid: '947c4be7-699e-492a-a29c-372c1eb48948' })
SET perf_372c1eb48948.name = 'Autumn Leaves'
SET perf_372c1eb48948.duration = '11:54'
SET perf_372c1eb48948.begin = '1988-07-03'
SET perf_372c1eb48948.end = '1988-07-03'
SET perf_372c1eb48948.source = 'musicbrainz.org'
SET perf_372c1eb48948.timestamp = timestamp()

MERGE (perf_e3801114b3bd:Performance{ uuid: '56bf16a2-7ba7-4533-8b3b-e3801114b3bd' })
SET perf_e3801114b3bd.name = 'La Champagne'
SET perf_e3801114b3bd.duration = '7:07'
SET perf_e3801114b3bd.begin = '1988-07-03'
SET perf_e3801114b3bd.end = '1988-07-03'
SET perf_e3801114b3bd.source = 'musicbrainz.org'
SET perf_e3801114b3bd.timestamp = timestamp()

MERGE (perf_6af2f2d7831e:Performance{ uuid: 'e73535a7-1e96-4f85-b224-6af2f2d7831e' })
SET perf_6af2f2d7831e.name = 'Giant Steps'
SET perf_6af2f2d7831e.duration = '12:39'
SET perf_6af2f2d7831e.begin = '1988-07-03'
SET perf_6af2f2d7831e.end = '1988-07-03'
SET perf_6af2f2d7831e.source = 'musicbrainz.org'
SET perf_6af2f2d7831e.timestamp = timestamp()

MERGE (perf_5d1e9dafb02c:Performance{ uuid: '62fe02fe-8ff4-40a2-9985-5d1e9dafb02c' })
SET perf_5d1e9dafb02c.name = 'Someday My Prince Will Come'
SET perf_5d1e9dafb02c.duration = '4:36'
SET perf_5d1e9dafb02c.begin = '1988-07-03'
SET perf_5d1e9dafb02c.end = '1988-07-03'
SET perf_5d1e9dafb02c.source = 'musicbrainz.org'
SET perf_5d1e9dafb02c.timestamp = timestamp()



// labels
MERGE (release_722909072753)-[:HAS_LABEL]->(label_311a35f78d9f)


// tracks
MERGE (release_722909072753)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_9fd2519c7341)
MERGE (release_722909072753)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_f373078b0e9b)
MERGE (release_722909072753)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_ee034aab9554)
MERGE (release_722909072753)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_24e088576bcf)
MERGE (release_722909072753)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_c1fd19cb1de7)
MERGE (release_722909072753)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_12a9c5b564cb)
MERGE (release_722909072753)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_337e6ba25750)
MERGE (release_722909072753)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_25cdc61ebc9d)
MERGE (release_722909072753)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_372c1eb48948)
MERGE (release_722909072753)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_e3801114b3bd)
MERGE (release_722909072753)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_6af2f2d7831e)
MERGE (release_722909072753)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_5d1e9dafb02c)


// place nodes

MERGE (place_77e283d799c3:Place{ uuid: 'd1a4c67e-e77e-4481-bb4c-77e283d799c3' })
SET place_77e283d799c3.name = 'Jazzhus Montmartre'
SET place_77e283d799c3.source = 'musicbrainz.org'


// place relationships
MERGE (perf_9fd2519c7341)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_f373078b0e9b)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_ee034aab9554)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_24e088576bcf)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_c1fd19cb1de7)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_12a9c5b564cb)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_337e6ba25750)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_25cdc61ebc9d)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_372c1eb48948)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_e3801114b3bd)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_6af2f2d7831e)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)
MERGE (perf_5d1e9dafb02c)-[:HAS_PLACE { type: 'recorded at', begin: '1988-07-03', end: '1988-07-03' }]->(place_77e283d799c3)

MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_9fd2519c7341)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_9fd2519c7341)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_9fd2519c7341)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_9fd2519c7341)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_9fd2519c7341)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_f373078b0e9b)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_f373078b0e9b)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_f373078b0e9b)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_f373078b0e9b)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_f373078b0e9b)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_ee034aab9554)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_ee034aab9554)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_ee034aab9554)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_ee034aab9554)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_ee034aab9554)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_24e088576bcf)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_24e088576bcf)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_24e088576bcf)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_24e088576bcf)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_24e088576bcf)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_c1fd19cb1de7)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_c1fd19cb1de7)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_c1fd19cb1de7)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_c1fd19cb1de7)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_c1fd19cb1de7)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_12a9c5b564cb)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_12a9c5b564cb)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_12a9c5b564cb)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_12a9c5b564cb)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_12a9c5b564cb)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_337e6ba25750)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_337e6ba25750)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_337e6ba25750)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_337e6ba25750)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_337e6ba25750)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_25cdc61ebc9d)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_25cdc61ebc9d)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_25cdc61ebc9d)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_25cdc61ebc9d)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_25cdc61ebc9d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_372c1eb48948)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_372c1eb48948)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_372c1eb48948)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_372c1eb48948)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_372c1eb48948)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_e3801114b3bd)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_e3801114b3bd)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e3801114b3bd)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_e3801114b3bd)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_e3801114b3bd)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_6af2f2d7831e)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_6af2f2d7831e)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_6af2f2d7831e)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_6af2f2d7831e)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_6af2f2d7831e)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_5d1e9dafb02c)
MERGE (person_644705f6e4f4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_5d1e9dafb02c)
MERGE (person_6695d86cdc19)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_5d1e9dafb02c)
MERGE (person_fafbe605caeb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_5d1e9dafb02c)
MERGE (person_8da285b4734c)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_5d1e9dafb02c)

