// releases

MERGE (release_8bfd59539b52:Release{ uuid: '1d4d633f-088b-4ca0-b436-8bfd59539b52' })
SET release_8bfd59539b52.name = 'Live at the Fivespot'
SET release_8bfd59539b52.country = 'US'
SET release_8bfd59539b52.date = '1960'
SET release_8bfd59539b52.format = '12" Vinyl'
SET release_8bfd59539b52.discode = 'UAL 4066'
SET release_8bfd59539b52.discogs = 'https://www.discogs.com/release/6578236'
SET release_8bfd59539b52.musicbrainz = 'http://musicbrainz.org/release/1d4d633f-088b-4ca0-b436-8bfd59539b52'
SET release_8bfd59539b52.source = 'musicbrainz.org'
SET release_8bfd59539b52.timestamp = timestamp()

MERGE (person_a180e3113ca1:Person{ uuid: '790ed08c-c8f6-448c-a86d-a180e3113ca1' }) 
SET person_a180e3113ca1.name = 'Clifford Jarvis'
SET person_a180e3113ca1.gender = 'Male'
SET person_a180e3113ca1.country = 'US'
SET person_a180e3113ca1.allmusic = 'https://www.allmusic.com/artist/mn0000158617'
SET person_a180e3113ca1.discogs = 'https://www.discogs.com/artist/256606'
SET person_a180e3113ca1.imdb = 'https://www.imdb.com/name/nm0419039/'
SET person_a180e3113ca1.viaf = 'http://viaf.org/viaf/27252094'
SET person_a180e3113ca1.wikidata = 'https://www.wikidata.org/wiki/Q356881'
SET person_a180e3113ca1.wikipedia = 'https://en.wikipedia.org/wiki/Clifford_Jarvis'
SET person_a180e3113ca1.databases = ['http://id.loc.gov/authorities/names/no91018919', 'https://catalogue.bnf.fr/ark:/12148/cb138955999', 'https://d-nb.info/gnd/134416961', 'https://www.worldcat.org/identities/lccn-no91018919']
SET person_a180e3113ca1.musicbrainz = 'https://musicbrainz.org/artist/790ed08c-c8f6-448c-a86d-a180e3113ca1'
SET person_a180e3113ca1.isni_list = ['http://isni.org/isni/0000000055137865']
SET person_a180e3113ca1.source = 'musicbrainz.org'
SET person_a180e3113ca1.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://id.loc.gov/authorities/names/n81140108', 'https://adp.library.ucsb.edu/names/320530', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'https://d-nb.info/gnd/134400623', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_91075fd0f5af:Person{ uuid: '7e198258-7093-46ac-a71e-91075fd0f5af' }) 
SET person_91075fd0f5af.name = 'Randy Weston'
SET person_91075fd0f5af.gender = 'Male'
SET person_91075fd0f5af.country = 'US'
SET person_91075fd0f5af.allmusic = 'https://www.allmusic.com/artist/mn0000396908'
SET person_91075fd0f5af.discogs = 'https://www.discogs.com/artist/281957'
SET person_91075fd0f5af.viaf = 'http://viaf.org/viaf/24788821'
SET person_91075fd0f5af.wikidata = 'https://www.wikidata.org/wiki/Q1371187'
SET person_91075fd0f5af.databases = ['http://id.loc.gov/authorities/names/n84162381', 'https://catalogue.bnf.fr/ark:/12148/cb139011161', 'https://d-nb.info/gnd/134555279', 'http://snaccooperative.org/ark:/99166/w6379dph', 'https://rateyourmusic.com/artist/randy_weston', 'https://www.musik-sammler.de/artist/randy-weston/', 'https://www.worldcat.org/identities/lccn-n84162381']
SET person_91075fd0f5af.musicbrainz = 'https://musicbrainz.org/artist/7e198258-7093-46ac-a71e-91075fd0f5af'
SET person_91075fd0f5af.isni_list = ['http://isni.org/isni/0000000081037964']
SET person_91075fd0f5af.source = 'musicbrainz.org'
SET person_91075fd0f5af.timestamp = timestamp()

MERGE (person_650b2ed0258f:Person{ uuid: '5c8cb181-38fe-4300-8153-650b2ed0258f' }) 
SET person_650b2ed0258f.name = 'Coleman Hawkins'
SET person_650b2ed0258f.gender = 'Male'
SET person_650b2ed0258f.country = 'US'
SET person_650b2ed0258f.allmusic = 'https://www.allmusic.com/artist/mn0000776363'
SET person_650b2ed0258f.bbc = 'https://www.bbc.co.uk/music/artists/5c8cb181-38fe-4300-8153-650b2ed0258f'
SET person_650b2ed0258f.discogs = 'https://www.discogs.com/artist/251769'
SET person_650b2ed0258f.imdb = 'https://www.imdb.com/name/nm0370098/'
SET person_650b2ed0258f.viaf = 'http://viaf.org/viaf/7574109'
SET person_650b2ed0258f.wikidata = 'https://www.wikidata.org/wiki/Q217812'
SET person_650b2ed0258f.databases = ['http://id.loc.gov/authorities/names/n81150284', 'https://adp.library.ucsb.edu/names/103427', 'https://catalogue.bnf.fr/ark:/12148/cb13895041m', 'https://d-nb.info/gnd/12305835X', 'http://snaccooperative.org/ark:/99166/w6xh06s5', 'https://nla.gov.au/nla.party-1047357', 'https://openlibrary.org/works/OL5932997A', 'https://rateyourmusic.com/artist/coleman-hawkins', 'https://www.musik-sammler.de/artist/coleman-hawkins/', 'https://www.worldcat.org/identities/lccn-n81150284']
SET person_650b2ed0258f.musicbrainz = 'https://musicbrainz.org/artist/5c8cb181-38fe-4300-8153-650b2ed0258f'
SET person_650b2ed0258f.isni_list = ['http://isni.org/isni/0000000080869929']
SET person_650b2ed0258f.source = 'musicbrainz.org'
SET person_650b2ed0258f.timestamp = timestamp()

MERGE (person_07c90b6fa661:Person{ uuid: '4476453a-d37e-4c52-b60d-07c90b6fa661' }) 
SET person_07c90b6fa661.name = 'Kenny Dorham'
SET person_07c90b6fa661.gender = 'Male'
SET person_07c90b6fa661.disambiguation = 'US jazz trumpeter, singer, and composer'
SET person_07c90b6fa661.country = 'US'
SET person_07c90b6fa661.allmusic = 'https://www.allmusic.com/artist/mn0000768027'
SET person_07c90b6fa661.discogs = 'https://www.discogs.com/artist/254945'
SET person_07c90b6fa661.viaf = 'http://viaf.org/viaf/76403361'
SET person_07c90b6fa661.wikidata = 'https://www.wikidata.org/wiki/Q498729'
SET person_07c90b6fa661.databases = ['http://id.loc.gov/authorities/names/n83056867', 'https://adp.library.ucsb.edu/names/312661', 'https://catalogue.bnf.fr/ark:/12148/cb12407498g', 'https://d-nb.info/gnd/134361253', 'http://snaccooperative.org/ark:/99166/w6q263n2', 'https://rateyourmusic.com/artist/kenny_dorham', 'https://www.worldcat.org/identities/lccn-n83056867']
SET person_07c90b6fa661.musicbrainz = 'https://musicbrainz.org/artist/4476453a-d37e-4c52-b60d-07c90b6fa661'
SET person_07c90b6fa661.isni_list = ['http://isni.org/isni/0000000083954272']
SET person_07c90b6fa661.source = 'musicbrainz.org'
SET person_07c90b6fa661.timestamp = timestamp()

MERGE (person_0d900ec97086:Person{ uuid: '5a69f1a0-fd8c-4b86-86dd-0d900ec97086' }) 
SET person_0d900ec97086.name = 'Tom Wilson'
SET person_0d900ec97086.gender = 'Male'
SET person_0d900ec97086.disambiguation = 'producer, worked with Dylan, Simon & Garfunkel, Zappa, VU, etc.'
SET person_0d900ec97086.country = 'US'
SET person_0d900ec97086.allmusic = 'https://www.allmusic.com/artist/mn0000932854'
SET person_0d900ec97086.discogs = 'https://www.discogs.com/artist/253021'
SET person_0d900ec97086.viaf = 'http://viaf.org/viaf/51146825214307631650'
SET person_0d900ec97086.wikidata = 'https://www.wikidata.org/wiki/Q2007168'
SET person_0d900ec97086.databases = ['https://d-nb.info/gnd/1105051064', 'https://rateyourmusic.com/artist/tom_wilson_f4']
SET person_0d900ec97086.musicbrainz = 'https://musicbrainz.org/artist/5a69f1a0-fd8c-4b86-86dd-0d900ec97086'
SET person_0d900ec97086.source = 'musicbrainz.org'
SET person_0d900ec97086.timestamp = timestamp()

MERGE (person_9b26acda1ea3:Person{ uuid: '90b5459b-6f1a-4dc7-a27a-9b26acda1ea3' }) 
SET person_9b26acda1ea3.name = 'Melba Liston'
SET person_9b26acda1ea3.gender = 'Female'
SET person_9b26acda1ea3.disambiguation = 'US jazz trombonist'
SET person_9b26acda1ea3.country = 'US'
SET person_9b26acda1ea3.allmusic = 'https://www.allmusic.com/artist/mn0000404399'
SET person_9b26acda1ea3.discogs = 'https://www.discogs.com/artist/311952'
SET person_9b26acda1ea3.imdb = 'https://www.imdb.com/name/nm0514285/'
SET person_9b26acda1ea3.viaf = 'http://viaf.org/viaf/42025880'
SET person_9b26acda1ea3.wikidata = 'https://www.wikidata.org/wiki/Q274146'
SET person_9b26acda1ea3.wikipedia = 'https://en.wikipedia.org/wiki/Melba_Liston'
SET person_9b26acda1ea3.databases = ['http://id.loc.gov/authorities/names/no91017680', 'https://catalogue.bnf.fr/ark:/12148/cb13896695f', 'http://snaccooperative.org/ark:/99166/w64b6f4z', 'https://www.worldcat.org/identities/lccn-no91017680']
SET person_9b26acda1ea3.musicbrainz = 'https://musicbrainz.org/artist/90b5459b-6f1a-4dc7-a27a-9b26acda1ea3'
SET person_9b26acda1ea3.isni_list = ['http://isni.org/isni/0000000059435122']
SET person_9b26acda1ea3.source = 'musicbrainz.org'
SET person_9b26acda1ea3.timestamp = timestamp()

MERGE (person_ac59cbd82246:Person{ uuid: 'f3edba06-dad2-4916-98da-ac59cbd82246' }) 
SET person_ac59cbd82246.name = 'Wilbur Little'
SET person_ac59cbd82246.gender = 'Male'
SET person_ac59cbd82246.country = 'US'
SET person_ac59cbd82246.allmusic = 'https://www.allmusic.com/artist/mn0000845025'
SET person_ac59cbd82246.discogs = 'https://www.discogs.com/artist/634055'
SET person_ac59cbd82246.viaf = 'http://viaf.org/viaf/76500764'
SET person_ac59cbd82246.wikidata = 'https://www.wikidata.org/wiki/Q950919'
SET person_ac59cbd82246.wikipedia = 'https://en.wikipedia.org/wiki/Wilbur_Little'
SET person_ac59cbd82246.databases = ['http://id.loc.gov/authorities/names/no99082008', 'https://catalogue.bnf.fr/ark:/12148/cb138967126', 'https://d-nb.info/gnd/135240395', 'https://www.worldcat.org/identities/lccn-no99082008']
SET person_ac59cbd82246.musicbrainz = 'https://musicbrainz.org/artist/f3edba06-dad2-4916-98da-ac59cbd82246'
SET person_ac59cbd82246.isni_list = ['http://isni.org/isni/0000000055151835']
SET person_ac59cbd82246.source = 'musicbrainz.org'
SET person_ac59cbd82246.timestamp = timestamp()
// labels

MERGE (label_870a199728ee:Label{ uuid: 'f1477534-482c-41bd-8219-870a199728ee' })
SET label_870a199728ee.name= 'United Artists'

// performances

MERGE (perf_25b2980cf585:Performance{ uuid: 'efb986ec-bf5d-496e-90b7-25b2980cf585' })
SET perf_25b2980cf585.name = 'High Fly'
SET perf_25b2980cf585.duration = '7:21'
SET perf_25b2980cf585.begin = '1959-10-26'
SET perf_25b2980cf585.end = '1959-10-26'
SET perf_25b2980cf585.source = 'musicbrainz.org'
SET perf_25b2980cf585.timestamp = timestamp()

MERGE (perf_ee7622103b11:Performance{ uuid: 'fc34204a-06b7-473d-918c-ee7622103b11' })
SET perf_ee7622103b11.name = 'Beef Blues Stew'
SET perf_ee7622103b11.duration = '5:00'
SET perf_ee7622103b11.begin = '1959-10-26'
SET perf_ee7622103b11.end = '1959-10-26'
SET perf_ee7622103b11.source = 'musicbrainz.org'
SET perf_ee7622103b11.timestamp = timestamp()

MERGE (perf_967c09f61a47:Performance{ uuid: 'd176210e-bb3f-4dde-84e6-967c09f61a47' })
SET perf_967c09f61a47.name = 'Where'
SET perf_967c09f61a47.duration = '5:53'
SET perf_967c09f61a47.begin = '1959-10-26'
SET perf_967c09f61a47.end = '1959-10-26'
SET perf_967c09f61a47.source = 'musicbrainz.org'
SET perf_967c09f61a47.timestamp = timestamp()

MERGE (perf_17f381f56067:Performance{ uuid: 'cdf63286-481b-4b56-ad83-17f381f56067' })
SET perf_17f381f56067.name = 'Spot Five Blues'
SET perf_17f381f56067.duration = '5:09'
SET perf_17f381f56067.begin = '1959-10-26'
SET perf_17f381f56067.end = '1959-10-26'
SET perf_17f381f56067.source = 'musicbrainz.org'
SET perf_17f381f56067.timestamp = timestamp()

MERGE (perf_e8ca823d1ada:Performance{ uuid: 'cf5c5408-d40f-4ae0-b56a-e8ca823d1ada' })
SET perf_e8ca823d1ada.name = 'Star Crossed Lovers'
SET perf_e8ca823d1ada.duration = '10:42'
SET perf_e8ca823d1ada.begin = '1959-10-26'
SET perf_e8ca823d1ada.end = '1959-10-26'
SET perf_e8ca823d1ada.source = 'musicbrainz.org'
SET perf_e8ca823d1ada.timestamp = timestamp()

MERGE (perf_dc952d9b1c66:Performance{ uuid: 'f6c8c56f-f714-4324-aea5-dc952d9b1c66' })
SET perf_dc952d9b1c66.name = 'Lisa Lovely'
SET perf_dc952d9b1c66.duration = '4:38'
SET perf_dc952d9b1c66.begin = '1959-10-26'
SET perf_dc952d9b1c66.end = '1959-10-26'
SET perf_dc952d9b1c66.source = 'musicbrainz.org'
SET perf_dc952d9b1c66.timestamp = timestamp()



// labels
MERGE (release_8bfd59539b52)-[:HAS_LABEL]->(label_870a199728ee)


// tracks
MERGE (release_8bfd59539b52)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_25b2980cf585)
MERGE (release_8bfd59539b52)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_ee7622103b11)
MERGE (release_8bfd59539b52)-[:HAS_TRACK {name: 'A3', sequence: 3}]->(perf_967c09f61a47)
MERGE (release_8bfd59539b52)-[:HAS_TRACK {name: 'B1', sequence: 4}]->(perf_17f381f56067)
MERGE (release_8bfd59539b52)-[:HAS_TRACK {name: 'B2', sequence: 5}]->(perf_e8ca823d1ada)
MERGE (release_8bfd59539b52)-[:HAS_TRACK {name: 'B3', sequence: 6}]->(perf_dc952d9b1c66)

// works

MERGE (person_d6ddfe8fd0a9:Person{ uuid: '23ec9ce1-2dae-437d-ba33-d6ddfe8fd0a9' }) 
SET person_d6ddfe8fd0a9.name = 'Billy Strayhorn'
SET person_d6ddfe8fd0a9.gender = 'Male'
SET person_d6ddfe8fd0a9.country = 'US'
SET person_d6ddfe8fd0a9.allmusic = 'https://www.allmusic.com/artist/mn0000359199'
SET person_d6ddfe8fd0a9.discogs = 'https://www.discogs.com/artist/258464'
SET person_d6ddfe8fd0a9.imdb = 'https://www.imdb.com/name/nm0833968/'
SET person_d6ddfe8fd0a9.viaf = 'http://viaf.org/viaf/64193228'
SET person_d6ddfe8fd0a9.wikidata = 'https://www.wikidata.org/wiki/Q380626'
SET person_d6ddfe8fd0a9.databases = ['http://id.loc.gov/authorities/names/n81072976', 'https://adp.library.ucsb.edu/names/103202', 'https://catalogue.bnf.fr/ark:/12148/cb13900127f', 'https://d-nb.info/gnd/119403544', 'https://ibdb.com/person.php?id=12699', 'http://snaccooperative.org/ark:/99166/w6w6867m', 'https://rateyourmusic.com/artist/billy_strayhorn', 'https://www.worldcat.org/identities/lccn-n81072976']
SET person_d6ddfe8fd0a9.musicbrainz = 'https://musicbrainz.org/artist/23ec9ce1-2dae-437d-ba33-d6ddfe8fd0a9'
SET person_d6ddfe8fd0a9.isni_list = ['http://isni.org/isni/000000007360288X']
SET person_d6ddfe8fd0a9.source = 'musicbrainz.org'
SET person_d6ddfe8fd0a9.timestamp = timestamp()

MERGE (person_7eeeb45e411f:Person{ uuid: '3af06bc4-68ad-4cae-bb7a-7eeeb45e411f' }) 
SET person_7eeeb45e411f.name = 'Duke Ellington'
SET person_7eeeb45e411f.gender = 'Male'
SET person_7eeeb45e411f.disambiguation = 'US composer, pianist & jazz bandleader'
SET person_7eeeb45e411f.country = 'US'
SET person_7eeeb45e411f.allmusic = 'https://www.allmusic.com/artist/mn0000120323'
SET person_7eeeb45e411f.bbc = 'https://www.bbc.co.uk/music/artists/3af06bc4-68ad-4cae-bb7a-7eeeb45e411f'
SET person_7eeeb45e411f.discogs = 'https://www.discogs.com/artist/145257'
SET person_7eeeb45e411f.imdb = 'https://www.imdb.com/name/nm0254153/'
SET person_7eeeb45e411f.viaf = 'http://viaf.org/viaf/66651610'
SET person_7eeeb45e411f.wikidata = 'https://www.wikidata.org/wiki/Q4030'
SET person_7eeeb45e411f.databases = ['http://id.loc.gov/authorities/names/n50080187', 'https://adp.library.ucsb.edu/names/102155', 'https://catalogue.bnf.fr/ark:/12148/cb13893638w', 'https://d-nb.info/gnd/118529994', 'https://ibdb.com/person.php?id=11631', 'http://snaccooperative.org/ark:/99166/w6639nkm', 'https://nla.gov.au/nla.party-815399', 'https://openlibrary.org/works/OL1953949A', 'https://rateyourmusic.com/artist/duke_ellington', 'https://www.worldcat.org/identities/lccn-n50080187/']
SET person_7eeeb45e411f.musicbrainz = 'https://musicbrainz.org/artist/3af06bc4-68ad-4cae-bb7a-7eeeb45e411f'
SET person_7eeeb45e411f.isni_list = ['http://isni.org/isni/0000000109110810']
SET person_7eeeb45e411f.source = 'musicbrainz.org'
SET person_7eeeb45e411f.timestamp = timestamp()

MERGE (work_a08a02c17387:Work{ uuid: 'e64bf2b1-c2ba-4798-886d-a08a02c17387' })
SET work_a08a02c17387.name = 'Beef Stew Blues'
SET work_a08a02c17387.type = 'Song'
SET work_a08a02c17387.source = 'musicbrainz.org'
SET work_a08a02c17387.timestamp = timestamp()

MERGE (work_c4696c596d20:Work{ uuid: '4f06fa8d-5313-47a2-888b-c4696c596d20' })
SET work_c4696c596d20.name = 'Lisa Lovely'
SET work_c4696c596d20.iswc = 'T-900.767.572-1'
SET work_c4696c596d20.type = 'Song'
SET work_c4696c596d20.source = 'musicbrainz.org'
SET work_c4696c596d20.timestamp = timestamp()

MERGE (work_4e4a2d90b591:Work{ uuid: '3e1b24c2-a4ed-4981-8535-4e4a2d90b591' })
SET work_4e4a2d90b591.name = 'The Star-Crossed Lovers'
SET work_4e4a2d90b591.iswc = 'T-070.137.553-2'
SET work_4e4a2d90b591.type = 'Song'
SET work_4e4a2d90b591.musicbrainz = 'https://musicbrainz.org/work/3e1b24c2-a4ed-4981-8535-4e4a2d90b591'
SET work_4e4a2d90b591.source = 'musicbrainz.org'
SET work_4e4a2d90b591.timestamp = timestamp()

MERGE (work_124bbc85cb16:Work{ uuid: 'c3ff6f36-2886-488e-8deb-124bbc85cb16' })
SET work_124bbc85cb16.name = 'Spot Five Blues'
SET work_124bbc85cb16.iswc = 'T-923.202.967-3'
SET work_124bbc85cb16.type = 'Song'
SET work_124bbc85cb16.source = 'musicbrainz.org'
SET work_124bbc85cb16.timestamp = timestamp()

MERGE (work_3a7f38208a08:Work{ uuid: '60d9d1af-22bd-4b22-b5be-3a7f38208a08' })
SET work_3a7f38208a08.name = 'Hi Fly'
SET work_3a7f38208a08.iswc = 'T-900.757.496-1'
SET work_3a7f38208a08.type = 'Song'
SET work_3a7f38208a08.wikidata = 'https://www.wikidata.org/wiki/Q18663652'
SET work_3a7f38208a08.musicbrainz = 'https://musicbrainz.org/work/60d9d1af-22bd-4b22-b5be-3a7f38208a08'
SET work_3a7f38208a08.source = 'musicbrainz.org'
SET work_3a7f38208a08.timestamp = timestamp()

MERGE (work_c5dc66391336:Work{ uuid: 'bff0d41d-23e2-4123-8389-c5dc66391336' })
SET work_c5dc66391336.name = 'Where'
SET work_c5dc66391336.iswc = 'T-071.192.877-6'
SET work_c5dc66391336.type = 'Song'
SET work_c5dc66391336.source = 'musicbrainz.org'
SET work_c5dc66391336.timestamp = timestamp()


// performances of
MERGE (perf_ee7622103b11)-[:PERFORMANCE_OF]->(work_a08a02c17387)
MERGE (perf_dc952d9b1c66)-[:PERFORMANCE_OF]->(work_c4696c596d20)
MERGE (perf_e8ca823d1ada)-[:PERFORMANCE_OF]->(work_4e4a2d90b591)
MERGE (perf_17f381f56067)-[:PERFORMANCE_OF]->(work_124bbc85cb16)
MERGE (perf_25b2980cf585)-[:PERFORMANCE_OF]->(work_3a7f38208a08)
MERGE (perf_967c09f61a47)-[:PERFORMANCE_OF]->(work_c5dc66391336)


// composers
MERGE (person_91075fd0f5af)-[:COMPOSED]->(work_a08a02c17387)
MERGE (person_91075fd0f5af)-[:COMPOSED]->(work_c4696c596d20)
MERGE (person_7eeeb45e411f)-[:COMPOSED]->(work_4e4a2d90b591)
MERGE (person_d6ddfe8fd0a9)-[:COMPOSED]->(work_4e4a2d90b591)
MERGE (person_91075fd0f5af)-[:COMPOSED]->(work_124bbc85cb16)
MERGE (person_91075fd0f5af)-[:COMPOSED]->(work_3a7f38208a08)
MERGE (person_91075fd0f5af)-[:COMPOSED]->(work_c5dc66391336)


// place nodes

MERGE (place_b90c91be7781:Place{ uuid: '47f8291d-c765-465d-a363-b90c91be7781' })
SET place_b90c91be7781.name = 'Five Spot'
SET place_b90c91be7781.source = 'musicbrainz.org'


// place relationships
MERGE (perf_25b2980cf585)-[:HAS_PLACE { type: 'recorded at', begin: '1959-10-26', end: '1959-10-26' }]->(place_b90c91be7781)
MERGE (perf_ee7622103b11)-[:HAS_PLACE { type: 'recorded at', begin: '1959-10-26', end: '1959-10-26' }]->(place_b90c91be7781)
MERGE (perf_967c09f61a47)-[:HAS_PLACE { type: 'recorded at', begin: '1959-10-26', end: '1959-10-26' }]->(place_b90c91be7781)
MERGE (perf_17f381f56067)-[:HAS_PLACE { type: 'recorded at', begin: '1959-10-26', end: '1959-10-26' }]->(place_b90c91be7781)
MERGE (perf_e8ca823d1ada)-[:HAS_PLACE { type: 'recorded at', begin: '1959-10-26', end: '1959-10-26' }]->(place_b90c91be7781)
MERGE (perf_dc952d9b1c66)-[:HAS_PLACE { type: 'recorded at', begin: '1959-10-26', end: '1959-10-26' }]->(place_b90c91be7781)

MERGE (person_07c90b6fa661)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_25b2980cf585)
MERGE (person_650b2ed0258f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_25b2980cf585)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_25b2980cf585)
MERGE (person_ac59cbd82246)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_25b2980cf585)
MERGE (person_91075fd0f5af)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_25b2980cf585)
MERGE (person_0d900ec97086)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_25b2980cf585)
MERGE (person_07c90b6fa661)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_ee7622103b11)
MERGE (person_650b2ed0258f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_ee7622103b11)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_ee7622103b11)
MERGE (person_ac59cbd82246)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_ee7622103b11)
MERGE (person_91075fd0f5af)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_ee7622103b11)
MERGE (person_0d900ec97086)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_ee7622103b11)
MERGE (person_07c90b6fa661)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_967c09f61a47)
MERGE (person_650b2ed0258f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_967c09f61a47)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_967c09f61a47)
MERGE (person_ac59cbd82246)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_967c09f61a47)
MERGE (person_91075fd0f5af)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_967c09f61a47)
MERGE (person_0d900ec97086)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_967c09f61a47)
MERGE (person_07c90b6fa661)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_17f381f56067)
MERGE (person_650b2ed0258f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_17f381f56067)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_17f381f56067)
MERGE (person_ac59cbd82246)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_17f381f56067)
MERGE (person_91075fd0f5af)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_17f381f56067)
MERGE (person_0d900ec97086)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_17f381f56067)
MERGE (person_650b2ed0258f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_e8ca823d1ada)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_e8ca823d1ada)
MERGE (person_ac59cbd82246)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_e8ca823d1ada)
MERGE (person_91075fd0f5af)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_e8ca823d1ada)
MERGE (person_0d900ec97086)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_e8ca823d1ada)
MERGE (person_07c90b6fa661)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_dc952d9b1c66)
MERGE (person_650b2ed0258f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_dc952d9b1c66)
MERGE (person_a180e3113ca1)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_dc952d9b1c66)
MERGE (person_ac59cbd82246)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_dc952d9b1c66)
MERGE (person_91075fd0f5af)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_dc952d9b1c66)
MERGE (person_0d900ec97086)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_dc952d9b1c66)

