// releases

MERGE (release_1be3de627458:Release{ uuid: 'a0c621eb-21da-4594-849c-1be3de627458' })
SET release_1be3de627458.name = 'In Performance at the White House'
SET release_1be3de627458.disambiguation = 'Young Artists at the White House: Dizzy Gillespie, Stan Getz, Chic Corea, Jim Faddis, Diane Schuur'
SET release_1be3de627458.country = 'US'
SET release_1be3de627458.date = '1982-12-04'
SET release_1be3de627458.format = 'Digital Media'
SET release_1be3de627458.musicbrainz = 'http://musicbrainz.org/release/a0c621eb-21da-4594-849c-1be3de627458'
SET release_1be3de627458.source = 'musicbrainz.org'
SET release_1be3de627458.timestamp = timestamp()

MERGE (person_65998d0d35b5:Person{ uuid: 'e9ba8ccb-505f-4e5c-b909-65998d0d35b5' })
SET person_65998d0d35b5.name = 'Dizzy Gillespie'
SET person_65998d0d35b5.gender = 'Male'
SET person_65998d0d35b5.country = 'US'
SET person_65998d0d35b5.wikipedia = 'http://en.wikipedia.org/wiki/Dizzy_Gillespie'
SET person_65998d0d35b5.viaf = 'http://viaf.org/viaf/77110276'
SET person_65998d0d35b5.allmusic = 'http://www.allmusic.com/artist/mn0000162677'
SET person_65998d0d35b5.bbc = 'http://www.bbc.co.uk/music/artists/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.discogs = 'http://www.discogs.com/artist/64694'
SET person_65998d0d35b5.wikidata = 'http://www.wikidata.org/wiki/Q49575'
SET person_65998d0d35b5.discographies = ['http://www.jazzdisco.org/dizzy-gillespie/']
SET person_65998d0d35b5.databases = ['http://rateyourmusic.com/artist/dizzy_gillespie']
SET person_65998d0d35b5.musicbrainz = 'https://musicbrainz.org/artist/e9ba8ccb-505f-4e5c-b909-65998d0d35b5'
SET person_65998d0d35b5.isni_list = ['http://isni.org/isni/0000000109181520']
SET person_65998d0d35b5.source = 'musicbrainz.org'
SET person_65998d0d35b5.timestamp = timestamp()

MERGE (person_b09140e07364:Person{ uuid: 'd224a365-0356-40ef-92ba-b09140e07364' })
SET person_b09140e07364.name = 'Diane Schuur'
SET person_b09140e07364.gender = 'Female'
SET person_b09140e07364.country = 'US'
SET person_b09140e07364.wikipedia = 'http://en.wikipedia.org/wiki/Diane_Schuur'
SET person_b09140e07364.viaf = 'http://viaf.org/viaf/84970855'
SET person_b09140e07364.allmusic = 'http://www.allmusic.com/artist/mn0000256482'
SET person_b09140e07364.discogs = 'http://www.discogs.com/artist/450733'
SET person_b09140e07364.imdb = 'http://www.imdb.com/name/nm1174099/'
SET person_b09140e07364.wikidata = 'http://www.wikidata.org/wiki/Q439121'
SET person_b09140e07364.musicbrainz = 'https://musicbrainz.org/artist/d224a365-0356-40ef-92ba-b09140e07364'
SET person_b09140e07364.source = 'musicbrainz.org'
SET person_b09140e07364.timestamp = timestamp()

MERGE (person_be027b7bb16e:Person{ uuid: 'd214235c-cf6f-4c8a-bf68-be027b7bb16e' })
SET person_be027b7bb16e.name = 'Miroslav Vitouš'
SET person_be027b7bb16e.gender = 'Male'
SET person_be027b7bb16e.country = 'CZ'
SET person_be027b7bb16e.wikipedia = 'http://en.wikipedia.org/wiki/Miroslav_Vitou%C5%A1'
SET person_be027b7bb16e.viaf = 'http://viaf.org/viaf/49409692'
SET person_be027b7bb16e.allmusic = 'http://www.allmusic.com/artist/mn0000499683'
SET person_be027b7bb16e.bbc = 'http://www.bbc.co.uk/music/artists/d214235c-cf6f-4c8a-bf68-be027b7bb16e'
SET person_be027b7bb16e.discogs = 'http://www.discogs.com/artist/128396'
SET person_be027b7bb16e.wikidata = 'http://www.wikidata.org/wiki/Q558162'
SET person_be027b7bb16e.musicbrainz = 'https://musicbrainz.org/artist/d214235c-cf6f-4c8a-bf68-be027b7bb16e'
SET person_be027b7bb16e.source = 'musicbrainz.org'
SET person_be027b7bb16e.timestamp = timestamp()

MERGE (person_40a6b1b17a3f:Person{ uuid: '2103a430-9bb8-4dd1-8c6a-40a6b1b17a3f' })
SET person_40a6b1b17a3f.name = 'Jon Faddis'
SET person_40a6b1b17a3f.gender = 'Male'
SET person_40a6b1b17a3f.country = 'US'
SET person_40a6b1b17a3f.wikipedia = 'http://en.wikipedia.org/wiki/Jon_Faddis'
SET person_40a6b1b17a3f.viaf = 'http://viaf.org/viaf/85686452'
SET person_40a6b1b17a3f.allmusic = 'http://www.allmusic.com/artist/mn0000211277'
SET person_40a6b1b17a3f.discogs = 'http://www.discogs.com/artist/156019'
SET person_40a6b1b17a3f.wikidata = 'http://www.wikidata.org/wiki/Q1350269'
SET person_40a6b1b17a3f.databases = ['https://rateyourmusic.com/artist/jon_faddis']
SET person_40a6b1b17a3f.musicbrainz = 'https://musicbrainz.org/artist/2103a430-9bb8-4dd1-8c6a-40a6b1b17a3f'
SET person_40a6b1b17a3f.isni_list = ['http://isni.org/isni/0000000114947690']
SET person_40a6b1b17a3f.source = 'musicbrainz.org'
SET person_40a6b1b17a3f.timestamp = timestamp()

MERGE (person_afe9622fab32:Person{ uuid: '8f2422ab-0ec6-4c92-80c4-afe9622fab32' })
SET person_afe9622fab32.name = 'Stan Getz'
SET person_afe9622fab32.gender = 'Male'
SET person_afe9622fab32.country = 'US'
SET person_afe9622fab32.wikipedia = 'http://en.wikipedia.org/wiki/Stan_Getz'
SET person_afe9622fab32.viaf = 'http://viaf.org/viaf/113597520'
SET person_afe9622fab32.allmusic = 'http://www.allmusic.com/artist/mn0000742899'
SET person_afe9622fab32.discogs = 'http://www.discogs.com/artist/30486'
SET person_afe9622fab32.imdb = 'http://www.imdb.com/name/nm0315295/'
SET person_afe9622fab32.wikidata = 'http://www.wikidata.org/wiki/Q30587'
SET person_afe9622fab32.databases = ['http://d-nb.info/gnd/119189941', 'http://rateyourmusic.com/artist/stan_getz', 'https://www.worldcat.org/identities/lccn-n81-018141']
SET person_afe9622fab32.musicbrainz = 'https://musicbrainz.org/artist/8f2422ab-0ec6-4c92-80c4-afe9622fab32'
SET person_afe9622fab32.isni_list = ['http://isni.org/isni/0000000110330511']
SET person_afe9622fab32.source = 'musicbrainz.org'
SET person_afe9622fab32.timestamp = timestamp()

MERGE (person_6065c5e997d4:Person{ uuid: '5e85f4f1-a491-4e63-9103-6065c5e997d4' })
SET person_6065c5e997d4.name = 'Itzhak Perlman'
SET person_6065c5e997d4.gender = 'Male'
SET person_6065c5e997d4.country = 'IL'
SET person_6065c5e997d4.wikipedia = 'http://en.wikipedia.org/wiki/Itzhak_Perlman'
SET person_6065c5e997d4.viaf = 'http://viaf.org/viaf/98526544'
SET person_6065c5e997d4.allmusic = 'http://www.allmusic.com/artist/mn0000922859'
SET person_6065c5e997d4.discogs = 'http://www.discogs.com/artist/377139'
SET person_6065c5e997d4.wikidata = 'http://www.wikidata.org/wiki/Q215905'
SET person_6065c5e997d4.musicbrainz = 'https://musicbrainz.org/artist/5e85f4f1-a491-4e63-9103-6065c5e997d4'
SET person_6065c5e997d4.isni_list = ['http://isni.org/isni/0000000110791457']
SET person_6065c5e997d4.source = 'musicbrainz.org'
SET person_6065c5e997d4.timestamp = timestamp()

MERGE (person_5a269b32b4c2:Person{ uuid: '8446fcca-109e-4c6d-a2ff-5a269b32b4c2' })
SET person_5a269b32b4c2.name = 'Chick Corea'
SET person_5a269b32b4c2.gender = 'Male'
SET person_5a269b32b4c2.country = 'US'
SET person_5a269b32b4c2.wikipedia = 'http://en.wikipedia.org/wiki/Chick_Corea'
SET person_5a269b32b4c2.viaf = 'http://viaf.org/viaf/37337806'
SET person_5a269b32b4c2.allmusic = 'http://www.allmusic.com/artist/mn0000110541'
SET person_5a269b32b4c2.bbc = 'http://www.bbc.co.uk/music/artists/8446fcca-109e-4c6d-a2ff-5a269b32b4c2'
SET person_5a269b32b4c2.discogs = 'http://www.discogs.com/artist/37731'
SET person_5a269b32b4c2.wikidata = 'http://www.wikidata.org/wiki/Q192465'
SET person_5a269b32b4c2.discographies = ['http://www.chickcorea.com/discography.html']
SET person_5a269b32b4c2.databases = ['https://rateyourmusic.com/artist/chick_corea']
SET person_5a269b32b4c2.musicbrainz = 'https://musicbrainz.org/artist/8446fcca-109e-4c6d-a2ff-5a269b32b4c2'
SET person_5a269b32b4c2.source = 'musicbrainz.org'
SET person_5a269b32b4c2.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' })
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.wikipedia = 'http://en.wikipedia.org/wiki/Roy_Haynes'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.allmusic = 'http://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'http://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'http://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'http://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.wikidata = 'http://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_56509c546377:Person{ uuid: '89ad4ac3-39f7-470e-963a-56509c546377' })
SET person_56509c546377.name = 'Various Artists'
SET person_56509c546377.disambiguation = 'add compilations to this artist'
SET person_56509c546377.wikipedia = 'http://en.wikipedia.org/wiki/Various_Artists'
SET person_56509c546377.discogs = 'http://www.discogs.com/artist/194'
SET person_56509c546377.wikidata = 'http://www.wikidata.org/wiki/Q3108914'
SET person_56509c546377.musicbrainz = 'https://musicbrainz.org/artist/89ad4ac3-39f7-470e-963a-56509c546377'
SET person_56509c546377.source = 'musicbrainz.org'
SET person_56509c546377.timestamp = timestamp()
// labels

MERGE (label_6ca42dd3df22:Label{ uuid: 'e4cebc64-776b-4039-8e80-6ca42dd3df22' })
SET label_6ca42dd3df22.name= 'PBS'

// performances

MERGE (perf_dde7bcc4e41b:Performance{ uuid: 'de36de9b-452e-4df9-8573-dde7bcc4e41b' })
SET perf_dde7bcc4e41b.name = 'Groovin\' High'
SET perf_dde7bcc4e41b.begin = '1982-12-04'
SET perf_dde7bcc4e41b.end = '1982-12-04'
SET perf_dde7bcc4e41b.source = 'musicbrainz.org'
SET perf_dde7bcc4e41b.timestamp = timestamp()

MERGE (perf_5747de403f51:Performance{ uuid: '95af6cde-c3d1-4172-9366-5747de403f51' })
SET perf_5747de403f51.name = 'free improvisation/Autumn Leaves/Rhythm-A-Ning'
SET perf_5747de403f51.begin = '1982-12-04'
SET perf_5747de403f51.end = '1982-12-04'
SET perf_5747de403f51.source = 'musicbrainz.org'
SET perf_5747de403f51.timestamp = timestamp()

MERGE (perf_81bad085ef70:Performance{ uuid: 'b09c79fe-1a53-4326-bcd1-81bad085ef70' })
SET perf_81bad085ef70.name = 'And Then She Stopped'
SET perf_81bad085ef70.begin = '1982-12-04'
SET perf_81bad085ef70.end = '1982-12-04'
SET perf_81bad085ef70.source = 'musicbrainz.org'
SET perf_81bad085ef70.timestamp = timestamp()

MERGE (perf_57db14509c62:Performance{ uuid: '64b5b012-e4f8-4ee4-8b45-57db14509c62' })
SET perf_57db14509c62.name = 'Summertime'
SET perf_57db14509c62.begin = '1982-12-04'
SET perf_57db14509c62.end = '1982-12-04'
SET perf_57db14509c62.source = 'musicbrainz.org'
SET perf_57db14509c62.timestamp = timestamp()



// labels
MERGE (release_1be3de627458)-[:HAS_LABEL]->(label_6ca42dd3df22)


// tracks
MERGE (release_1be3de627458)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_dde7bcc4e41b)
MERGE (release_1be3de627458)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_5747de403f51)
MERGE (release_1be3de627458)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_81bad085ef70)
MERGE (release_1be3de627458)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_57db14509c62)

// works
MERGE (person_5260b4274ed4:Person{ uuid: '8e8c7417-c905-46b1-b42a-5260b4274ed4' })
SET person_5260b4274ed4.name = 'Thelonious Monk'
SET person_5260b4274ed4.gender = 'Male'
SET person_5260b4274ed4.country = 'US'
SET person_5260b4274ed4.wikipedia = 'http://en.wikipedia.org/wiki/Thelonious_Monk'
SET person_5260b4274ed4.viaf = 'http://viaf.org/viaf/44485892'
SET person_5260b4274ed4.allmusic = 'http://www.allmusic.com/artist/mn0000490416'
SET person_5260b4274ed4.bbc = 'http://www.bbc.co.uk/music/artists/8e8c7417-c905-46b1-b42a-5260b4274ed4'
SET person_5260b4274ed4.discogs = 'http://www.discogs.com/artist/145256'
SET person_5260b4274ed4.imdb = 'http://www.imdb.com/name/nm0598243/'
SET person_5260b4274ed4.wikidata = 'http://www.wikidata.org/wiki/Q109612'
SET person_5260b4274ed4.discographies = ['http://www.howardm.net/tsmonk/tsmonk.php', 'http://www.jazzdisco.org/monk/']
SET person_5260b4274ed4.databases = ['http://rateyourmusic.com/artist/thelonious_monk']
SET person_5260b4274ed4.musicbrainz = 'https://musicbrainz.org/artist/8e8c7417-c905-46b1-b42a-5260b4274ed4'
SET person_5260b4274ed4.isni_list = ['http://isni.org/isni/0000000120249127']
SET person_5260b4274ed4.source = 'musicbrainz.org'
SET person_5260b4274ed4.timestamp = timestamp()

MERGE (person_c73775716312:Person{ uuid: 'c7356af9-9ea6-4a78-a55b-c73775716312' })
SET person_c73775716312.name = 'Charlie Parker'
SET person_c73775716312.gender = 'Male'
SET person_c73775716312.disambiguation = 'aka "Bird", jazz alto saxophonist'
SET person_c73775716312.country = 'US'
SET person_c73775716312.wikipedia = 'http://en.wikipedia.org/wiki/Charlie_Parker'
SET person_c73775716312.viaf = 'http://viaf.org/viaf/10034216'
SET person_c73775716312.allmusic = 'http://www.allmusic.com/artist/mn0000211758'
SET person_c73775716312.bbc = 'http://www.bbc.co.uk/music/artists/c7356af9-9ea6-4a78-a55b-c73775716312'
SET person_c73775716312.discogs = 'http://www.discogs.com/artist/75617'
SET person_c73775716312.imdb = 'http://www.imdb.com/name/nm0662127/'
SET person_c73775716312.wikidata = 'http://www.wikidata.org/wiki/Q103767'
SET person_c73775716312.discographies = ['http://www.jazzdisco.org/bird/', 'http://www.kyushu-ns.ac.jp/~allan/Documents/CP_M.html']
SET person_c73775716312.databases = ['http://rateyourmusic.com/artist/charlie_parker']
SET person_c73775716312.musicbrainz = 'https://musicbrainz.org/artist/c7356af9-9ea6-4a78-a55b-c73775716312'
SET person_c73775716312.isni_list = ['http://isni.org/isni/0000000120955806']
SET person_c73775716312.source = 'musicbrainz.org'
SET person_c73775716312.timestamp = timestamp()

MERGE (person_635888a66dea:Person{ uuid: '114ec00a-c6cf-42cf-af03-635888a66dea' })
SET person_635888a66dea.name = 'Joseph Kosma'
SET person_635888a66dea.gender = 'Male'
SET person_635888a66dea.country = 'FR'
SET person_635888a66dea.wikipedia = 'http://en.wikipedia.org/wiki/Joseph_Kosma'
SET person_635888a66dea.viaf = 'http://viaf.org/viaf/10033644'
SET person_635888a66dea.discogs = 'http://www.discogs.com/artist/445911'
SET person_635888a66dea.wikidata = 'http://www.wikidata.org/wiki/Q213661'
SET person_635888a66dea.musicbrainz = 'https://musicbrainz.org/artist/114ec00a-c6cf-42cf-af03-635888a66dea'
SET person_635888a66dea.source = 'musicbrainz.org'
SET person_635888a66dea.timestamp = timestamp()

MERGE (person_66f3736e0ac5:Person{ uuid: '67ec74fe-0e96-4e3d-96a7-66f3736e0ac5' })
SET person_66f3736e0ac5.name = 'Frank Paparelli'
SET person_66f3736e0ac5.gender = 'Male'
SET person_66f3736e0ac5.country = 'US'
SET person_66f3736e0ac5.allmusic = 'http://www.allmusic.com/artist/mn0000146400'
SET person_66f3736e0ac5.discogs = 'http://www.discogs.com/artist/370787'
SET person_66f3736e0ac5.musicbrainz = 'https://musicbrainz.org/artist/67ec74fe-0e96-4e3d-96a7-66f3736e0ac5'
SET person_66f3736e0ac5.source = 'musicbrainz.org'
SET person_66f3736e0ac5.timestamp = timestamp()

MERGE (person_b693a808a158:Person{ uuid: '65744963-191a-44ef-a3c7-b693a808a158' })
SET person_b693a808a158.name = 'George Gershwin'
SET person_b693a808a158.gender = 'Male'
SET person_b693a808a158.country = 'US'
SET person_b693a808a158.wikipedia = 'http://en.wikipedia.org/wiki/George_Gershwin'
SET person_b693a808a158.viaf = 'http://viaf.org/viaf/61554329'
SET person_b693a808a158.allmusic = 'http://www.allmusic.com/artist/mn0000197918'
SET person_b693a808a158.bbc = 'http://www.bbc.co.uk/music/artists/65744963-191a-44ef-a3c7-b693a808a158'
SET person_b693a808a158.discogs = 'http://www.discogs.com/artist/261293'
SET person_b693a808a158.imdb = 'http://www.imdb.com/name/nm0006097/'
SET person_b693a808a158.wikidata = 'http://www.wikidata.org/wiki/Q123829'
SET person_b693a808a158.databases = ['http://ibdb.com/person.php?id=5813', 'http://soundtrackcollector.com/composer/33/', 'https://rateyourmusic.com/artist/george_gershwin']
SET person_b693a808a158.musicbrainz = 'https://musicbrainz.org/artist/65744963-191a-44ef-a3c7-b693a808a158'
SET person_b693a808a158.isni_list = ['http://isni.org/isni/0000000121355968']
SET person_b693a808a158.source = 'musicbrainz.org'
SET person_b693a808a158.timestamp = timestamp()

MERGE (work_4a42969f41f5:Work{ uuid: '8d0b02b7-b27b-3f8d-a05b-4a42969f41f5' })
SET work_4a42969f41f5.name = 'Groovin\' High'
SET work_4a42969f41f5.source = 'musicbrainz.org'
SET work_4a42969f41f5.timestamp = timestamp()

MERGE (work_268199324401:Work{ uuid: '048b4b7a-07c4-3e33-959f-268199324401' })
SET work_268199324401.name = 'Autumn Leaves'
SET work_268199324401.iswc = 'T-070.002.297-4'
SET work_268199324401.type = 'Song'
SET work_268199324401.wikidata = 'http://www.wikidata.org/wiki/Q789392'
SET work_268199324401.wikipedia = 'https://en.wikipedia.org/wiki/Autumn_Leaves_(1945_song)'
SET work_268199324401.musicbrainz = 'https://musicbrainz.org/work/048b4b7a-07c4-3e33-959f-268199324401'
SET work_268199324401.source = 'musicbrainz.org'
SET work_268199324401.timestamp = timestamp()

MERGE (work_ecaeddf44a98:Work{ uuid: 'ee619352-ce88-3fe2-a065-ecaeddf44a98' })
SET work_ecaeddf44a98.name = 'Rhythm-a-Ning'
SET work_ecaeddf44a98.source = 'musicbrainz.org'
SET work_ecaeddf44a98.timestamp = timestamp()

MERGE (work_d76a4de89563:Work{ uuid: 'bc26b050-2a65-4707-aa0c-d76a4de89563' })
SET work_d76a4de89563.name = 'And Then She Stopped'
SET work_d76a4de89563.source = 'musicbrainz.org'
SET work_d76a4de89563.timestamp = timestamp()

MERGE (work_155b5f167975:Work{ uuid: '986359d8-34ff-3fe2-84fe-155b5f167975' })
SET work_155b5f167975.name = 'Summertime'
SET work_155b5f167975.iswc = 'T-800.364.991-1'
SET work_155b5f167975.type = 'Aria'
SET work_155b5f167975.wikidata = 'http://www.wikidata.org/wiki/Q844046'
SET work_155b5f167975.musicbrainz = 'https://musicbrainz.org/work/986359d8-34ff-3fe2-84fe-155b5f167975'
SET work_155b5f167975.source = 'musicbrainz.org'
SET work_155b5f167975.timestamp = timestamp()


// performances of
MERGE (perf_dde7bcc4e41b)-[:PERFORMANCE_OF]->(work_4a42969f41f5)
MERGE (perf_5747de403f51)-[:PERFORMANCE_OF {medley: true}]->(work_268199324401)
MERGE (perf_5747de403f51)-[:PERFORMANCE_OF {medley: true}]->(work_ecaeddf44a98)
MERGE (perf_81bad085ef70)-[:PERFORMANCE_OF]->(work_d76a4de89563)
MERGE (perf_57db14509c62)-[:PERFORMANCE_OF]->(work_155b5f167975)


// composers
MERGE (person_66f3736e0ac5)-[:COMPOSED]->(work_4a42969f41f5)
MERGE (person_c73775716312)-[:COMPOSED]->(work_4a42969f41f5)
MERGE (person_65998d0d35b5)-[:COMPOSED]->(work_4a42969f41f5)
MERGE (person_635888a66dea)-[:COMPOSED]->(work_268199324401)
MERGE (person_5260b4274ed4)-[:COMPOSED]->(work_ecaeddf44a98)
MERGE (person_65998d0d35b5)-[:COMPOSED]->(work_d76a4de89563)
MERGE (person_b693a808a158)-[:COMPOSED]->(work_155b5f167975)


// place nodes

MERGE (place_13c91aabaa00:Place{ uuid: '5df4ac64-d016-4ecf-96b6-13c91aabaa00' })
SET place_13c91aabaa00.name = 'White House'
SET place_13c91aabaa00.address = 'White House, 1600, Pennsylvania Avenue Northwest, Monumental Core, Logan Circle, Washington, District of Columbia, 20500, United States of America'
SET place_13c91aabaa00.lat = '38.8976989'
SET place_13c91aabaa00.lng = '-77.036553192281'
SET place_13c91aabaa00.source = 'musicbrainz.org'


// place relationships
MERGE (perf_dde7bcc4e41b)-[:HAS_PLACE { type: 'recorded at', begin: '1982-12-04', end: '1982-12-04' }]->(place_13c91aabaa00)
MERGE (perf_5747de403f51)-[:HAS_PLACE { type: 'recorded at', begin: '1982-12-04', end: '1982-12-04' }]->(place_13c91aabaa00)
MERGE (perf_81bad085ef70)-[:HAS_PLACE { type: 'recorded at', begin: '1982-12-04', end: '1982-12-04' }]->(place_13c91aabaa00)
MERGE (perf_57db14509c62)-[:HAS_PLACE { type: 'recorded at', begin: '1982-12-04', end: '1982-12-04' }]->(place_13c91aabaa00)

MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_dde7bcc4e41b)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_dde7bcc4e41b)
MERGE (person_afe9622fab32)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_dde7bcc4e41b)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_dde7bcc4e41b)
MERGE (person_65998d0d35b5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_dde7bcc4e41b)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_5747de403f51)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_5747de403f51)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_5747de403f51)
MERGE (person_40a6b1b17a3f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_81bad085ef70)
MERGE (person_65998d0d35b5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_81bad085ef70)
MERGE (person_40a6b1b17a3f)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_57db14509c62)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_57db14509c62)
MERGE (person_6065c5e997d4)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['violin'] }]->(perf_57db14509c62)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_57db14509c62)
MERGE (person_afe9622fab32)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_57db14509c62)
MERGE (person_be027b7bb16e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_57db14509c62)
MERGE (person_b09140e07364)-[:PARTICIPATED_IN { roles: ['singer'] }]->(perf_57db14509c62)
MERGE (person_65998d0d35b5)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_57db14509c62)

