// releases

MERGE (release_c428e760a3e2:Release{ uuid: 'a933a25a-3ce5-453e-aa4e-c428e760a3e2' })
SET release_c428e760a3e2.name = 'Like Minds'
SET release_c428e760a3e2.country = 'US'
SET release_c428e760a3e2.date = '2003'
SET release_c428e760a3e2.format = 'Hybrid SACD'
SET release_c428e760a3e2.discode = 'SACD-1029-6'
SET release_c428e760a3e2.discogs = 'https://www.discogs.com/release/5465554'
SET release_c428e760a3e2.musicbrainz = 'http://musicbrainz.org/release/a933a25a-3ce5-453e-aa4e-c428e760a3e2'
SET release_c428e760a3e2.source = 'musicbrainz.org'
SET release_c428e760a3e2.timestamp = timestamp()

MERGE (person_5a269b32b4c2:Person{ uuid: '8446fcca-109e-4c6d-a2ff-5a269b32b4c2' }) 
SET person_5a269b32b4c2.name = 'Chick Corea'
SET person_5a269b32b4c2.gender = 'Male'
SET person_5a269b32b4c2.disambiguation = 'jazz pianist'
SET person_5a269b32b4c2.country = 'US'
SET person_5a269b32b4c2.allmusic = 'https://www.allmusic.com/artist/mn0000110541'
SET person_5a269b32b4c2.discogs = 'https://www.discogs.com/artist/37731'
SET person_5a269b32b4c2.imdb = 'https://www.imdb.com/name/nm0179706/'
SET person_5a269b32b4c2.viaf = 'http://viaf.org/viaf/37337806'
SET person_5a269b32b4c2.wikidata = 'https://www.wikidata.org/wiki/Q192465'
SET person_5a269b32b4c2.databases = ['http://id.loc.gov/authorities/names/n81080890', 'https://adp.library.ucsb.edu/names/309754', 'https://catalogue.bnf.fr/ark:/12148/cb13892744v', 'https://d-nb.info/gnd/119238489', 'https://rateyourmusic.com/artist/chick_corea', 'https://www.worldcat.org/identities/lccn-n81080890']
SET person_5a269b32b4c2.musicbrainz = 'https://musicbrainz.org/artist/8446fcca-109e-4c6d-a2ff-5a269b32b4c2'
SET person_5a269b32b4c2.isni_list = ['http://isni.org/isni/0000000121285074']
SET person_5a269b32b4c2.source = 'musicbrainz.org'
SET person_5a269b32b4c2.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' }) 
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.disambiguation = 'American jazz drummer and bandleader'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.allmusic = 'https://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'https://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'https://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'https://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.wikidata = 'https://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.databases = ['http://id.loc.gov/authorities/names/n81140108', 'https://adp.library.ucsb.edu/names/320530', 'https://catalogue.bnf.fr/ark:/12148/cb13895060w', 'https://d-nb.info/gnd/134400623', 'http://snaccooperative.org/ark:/99166/w6fj33d4', 'https://www.worldcat.org/identities/lccn-n81140108']
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.isni_list = ['http://isni.org/isni/0000000078266176']
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_f8091d98cf25:Person{ uuid: '7daac7f9-8fcc-485f-a14f-f8091d98cf25' }) 
SET person_f8091d98cf25.name = 'Pat Metheny'
SET person_f8091d98cf25.gender = 'Male'
SET person_f8091d98cf25.country = 'US'
SET person_f8091d98cf25.allmusic = 'https://www.allmusic.com/artist/mn0000179698'
SET person_f8091d98cf25.bbc = 'https://www.bbc.co.uk/music/artists/7daac7f9-8fcc-485f-a14f-f8091d98cf25'
SET person_f8091d98cf25.discogs = 'https://www.discogs.com/artist/20185'
SET person_f8091d98cf25.imdb = 'https://www.imdb.com/name/nm0582533/'
SET person_f8091d98cf25.viaf = 'http://viaf.org/viaf/22188874'
SET person_f8091d98cf25.wikidata = 'https://www.wikidata.org/wiki/Q213887'
SET person_f8091d98cf25.databases = ['http://id.loc.gov/authorities/names/n78096789', 'https://catalogue.bnf.fr/ark:/12148/cb122016747', 'https://d-nb.info/gnd/118946803', 'http://snaccooperative.org/ark:/99166/w6gj10fw', 'https://rateyourmusic.com/artist/pat-metheny', 'https://www.musik-sammler.de/artist/pat-metheny/', 'https://www.progarchives.com/artist.asp?id=2445', 'https://www.worldcat.org/identities/lccn-n78096789']
SET person_f8091d98cf25.musicbrainz = 'https://musicbrainz.org/artist/7daac7f9-8fcc-485f-a14f-f8091d98cf25'
SET person_f8091d98cf25.isni_list = ['http://isni.org/isni/0000000121236985']
SET person_f8091d98cf25.source = 'musicbrainz.org'
SET person_f8091d98cf25.timestamp = timestamp()

MERGE (person_dabcde5dade7:Person{ uuid: '9e5638d9-1f11-42a8-ab1c-dabcde5dade7' }) 
SET person_dabcde5dade7.name = 'James A. Farber'
SET person_dabcde5dade7.gender = 'Male'
SET person_dabcde5dade7.disambiguation = 'sound engineer'
SET person_dabcde5dade7.country = 'US'
SET person_dabcde5dade7.allmusic = 'https://www.allmusic.com/artist/mn0000143439'
SET person_dabcde5dade7.discogs = 'https://www.discogs.com/artist/82811'
SET person_dabcde5dade7.imdb = 'https://www.imdb.com/name/nm9229858/'
SET person_dabcde5dade7.databases = ['https://rateyourmusic.com/artist/james_farber/credits/']
SET person_dabcde5dade7.musicbrainz = 'https://musicbrainz.org/artist/9e5638d9-1f11-42a8-ab1c-dabcde5dade7'
SET person_dabcde5dade7.source = 'musicbrainz.org'
SET person_dabcde5dade7.timestamp = timestamp()

MERGE (person_b1f20fcef5dc:Person{ uuid: '7b5b8b1b-414b-44e8-862f-b1f20fcef5dc' }) 
SET person_b1f20fcef5dc.name = 'Gary Burton'
SET person_b1f20fcef5dc.gender = 'Male'
SET person_b1f20fcef5dc.disambiguation = 'jazz vibraphonist and composer'
SET person_b1f20fcef5dc.country = 'US'
SET person_b1f20fcef5dc.allmusic = 'https://www.allmusic.com/artist/mn0000738182'
SET person_b1f20fcef5dc.bbc = 'https://www.bbc.co.uk/music/artists/7b5b8b1b-414b-44e8-862f-b1f20fcef5dc'
SET person_b1f20fcef5dc.discogs = 'https://www.discogs.com/artist/256558'
SET person_b1f20fcef5dc.imdb = 'https://www.imdb.com/name/nm0123585/'
SET person_b1f20fcef5dc.viaf = 'http://viaf.org/viaf/85329553'
SET person_b1f20fcef5dc.wikidata = 'https://www.wikidata.org/wiki/Q353096'
SET person_b1f20fcef5dc.wikipedia = 'https://en.wikipedia.org/wiki/Gary_Burton'
SET person_b1f20fcef5dc.databases = ['http://id.loc.gov/authorities/names/n81080891', 'https://catalogue.bnf.fr/ark:/12148/cb13892003b', 'https://d-nb.info/gnd/134341082', 'http://snaccooperative.org/ark:/99166/w64p1ghv', 'https://www.worldcat.org/identities/lccn-n81080891']
SET person_b1f20fcef5dc.musicbrainz = 'https://musicbrainz.org/artist/7b5b8b1b-414b-44e8-862f-b1f20fcef5dc'
SET person_b1f20fcef5dc.isni_list = ['http://isni.org/isni/000000011074903X']
SET person_b1f20fcef5dc.source = 'musicbrainz.org'
SET person_b1f20fcef5dc.timestamp = timestamp()

MERGE (person_dbad528aa58e:Person{ uuid: '7ea233ad-c340-4f62-8678-dbad528aa58e' }) 
SET person_dbad528aa58e.name = 'Dave Holland'
SET person_dbad528aa58e.gender = 'Male'
SET person_dbad528aa58e.disambiguation = 'British jazz bassist and composer'
SET person_dbad528aa58e.country = 'GB'
SET person_dbad528aa58e.allmusic = 'https://www.allmusic.com/artist/mn0000585092'
SET person_dbad528aa58e.bbc = 'https://www.bbc.co.uk/music/artists/7ea233ad-c340-4f62-8678-dbad528aa58e'
SET person_dbad528aa58e.discogs = 'https://www.discogs.com/artist/84214'
SET person_dbad528aa58e.imdb = 'https://www.imdb.com/name/nm1180224/'
SET person_dbad528aa58e.viaf = 'http://viaf.org/viaf/115064351'
SET person_dbad528aa58e.wikidata = 'https://www.wikidata.org/wiki/Q504671'
SET person_dbad528aa58e.databases = ['http://id.loc.gov/authorities/names/n84163014', 'https://catalogue.bnf.fr/ark:/12148/cb13895278h', 'https://d-nb.info/gnd/134409361', 'http://snaccooperative.org/ark:/99166/w6dn45cm', 'https://www.worldcat.org/identities/lccn-n84163014']
SET person_dbad528aa58e.musicbrainz = 'https://musicbrainz.org/artist/7ea233ad-c340-4f62-8678-dbad528aa58e'
SET person_dbad528aa58e.isni_list = ['http://isni.org/isni/0000000084120907']
SET person_dbad528aa58e.source = 'musicbrainz.org'
SET person_dbad528aa58e.timestamp = timestamp()

MERGE (person_08ad76203a69:Person{ uuid: '79391790-9e00-4617-a285-08ad76203a69' }) 
SET person_08ad76203a69.name = 'Aya Takemura'
SET person_08ad76203a69.discogs = 'https://www.discogs.com/artist/252928'
SET person_08ad76203a69.musicbrainz = 'https://musicbrainz.org/artist/79391790-9e00-4617-a285-08ad76203a69'
SET person_08ad76203a69.source = 'musicbrainz.org'
SET person_08ad76203a69.timestamp = timestamp()
// labels

MERGE (label_935dbdbb598a:Label{ uuid: '8ec4f16d-a43f-4e80-b3b0-935dbdbb598a' })
SET label_935dbdbb598a.name= 'Concord Jazz'
// labels

MERGE (label_46612304aca6:Label{ uuid: 'c5f3bc66-5e1e-47bf-8737-46612304aca6' })
SET label_46612304aca6.name= 'Concord Records'

// performances

MERGE (perf_b636a6564ae5:Performance{ uuid: 'a8128964-3e97-4c71-b50b-b636a6564ae5' })
SET perf_b636a6564ae5.name = 'Question and Answer'
SET perf_b636a6564ae5.duration = '6:23'
SET perf_b636a6564ae5.begin = '1997-12-15'
SET perf_b636a6564ae5.end = '1997-12-17'
SET perf_b636a6564ae5.source = 'musicbrainz.org'
SET perf_b636a6564ae5.timestamp = timestamp()

MERGE (perf_ffec9da58ff6:Performance{ uuid: '3ee8b0cc-e367-4c98-b518-ffec9da58ff6' })
SET perf_ffec9da58ff6.name = 'Elucidation'
SET perf_ffec9da58ff6.duration = '5:21'
SET perf_ffec9da58ff6.begin = '1997-12-15'
SET perf_ffec9da58ff6.end = '1997-12-17'
SET perf_ffec9da58ff6.source = 'musicbrainz.org'
SET perf_ffec9da58ff6.timestamp = timestamp()

MERGE (perf_af0531a1f675:Performance{ uuid: '3bf327ea-c3d8-44f1-9c39-af0531a1f675' })
SET perf_af0531a1f675.name = 'Windows'
SET perf_af0531a1f675.duration = '6:17'
SET perf_af0531a1f675.begin = '1997-12-15'
SET perf_af0531a1f675.end = '1997-12-17'
SET perf_af0531a1f675.source = 'musicbrainz.org'
SET perf_af0531a1f675.timestamp = timestamp()

MERGE (perf_fe09eaecfc03:Performance{ uuid: '48d5ee48-4626-437d-8f4c-fe09eaecfc03' })
SET perf_fe09eaecfc03.name = 'Futures'
SET perf_fe09eaecfc03.duration = '10:41'
SET perf_fe09eaecfc03.begin = '1997-12-15'
SET perf_fe09eaecfc03.end = '1997-12-17'
SET perf_fe09eaecfc03.source = 'musicbrainz.org'
SET perf_fe09eaecfc03.timestamp = timestamp()

MERGE (perf_eb42a3ac2549:Performance{ uuid: 'a18e7d51-9911-45f5-a5a5-eb42a3ac2549' })
SET perf_eb42a3ac2549.name = 'Like Minds'
SET perf_eb42a3ac2549.duration = '5:50'
SET perf_eb42a3ac2549.begin = '1997-12-15'
SET perf_eb42a3ac2549.end = '1997-12-17'
SET perf_eb42a3ac2549.source = 'musicbrainz.org'
SET perf_eb42a3ac2549.timestamp = timestamp()

MERGE (perf_1ec6cbd5e2ab:Performance{ uuid: '127bc972-ad8b-4bcc-be26-1ec6cbd5e2ab' })
SET perf_1ec6cbd5e2ab.name = 'Country Roads'
SET perf_1ec6cbd5e2ab.duration = '6:26'
SET perf_1ec6cbd5e2ab.begin = '1997-12-15'
SET perf_1ec6cbd5e2ab.end = '1997-12-17'
SET perf_1ec6cbd5e2ab.source = 'musicbrainz.org'
SET perf_1ec6cbd5e2ab.timestamp = timestamp()

MERGE (perf_a0564c9640d8:Performance{ uuid: 'c914ab4f-aa30-474d-8919-a0564c9640d8' })
SET perf_a0564c9640d8.name = 'Tears of Rain'
SET perf_a0564c9640d8.duration = '6:33'
SET perf_a0564c9640d8.begin = '1997-12-15'
SET perf_a0564c9640d8.end = '1997-12-17'
SET perf_a0564c9640d8.source = 'musicbrainz.org'
SET perf_a0564c9640d8.timestamp = timestamp()

MERGE (perf_1c6fa5fcee0d:Performance{ uuid: '83658daf-0a71-4ad3-a8f2-1c6fa5fcee0d' })
SET perf_1c6fa5fcee0d.name = 'Soon'
SET perf_1c6fa5fcee0d.duration = '6:24'
SET perf_1c6fa5fcee0d.begin = '1997-12-15'
SET perf_1c6fa5fcee0d.end = '1997-12-17'
SET perf_1c6fa5fcee0d.source = 'musicbrainz.org'
SET perf_1c6fa5fcee0d.timestamp = timestamp()

MERGE (perf_bfa3ec107627:Performance{ uuid: '08f4aa37-7b8a-4e35-8216-bfa3ec107627' })
SET perf_bfa3ec107627.name = 'For a Thousand Years'
SET perf_bfa3ec107627.duration = '5:23'
SET perf_bfa3ec107627.begin = '1997-12-15'
SET perf_bfa3ec107627.end = '1997-12-17'
SET perf_bfa3ec107627.source = 'musicbrainz.org'
SET perf_bfa3ec107627.timestamp = timestamp()

MERGE (perf_0249c5d5914b:Performance{ uuid: 'be9cb874-a299-4ba0-994a-0249c5d5914b' })
SET perf_0249c5d5914b.name = 'Straight Up and Down'
SET perf_0249c5d5914b.duration = '9:01'
SET perf_0249c5d5914b.begin = '1997-12-15'
SET perf_0249c5d5914b.end = '1997-12-17'
SET perf_0249c5d5914b.source = 'musicbrainz.org'
SET perf_0249c5d5914b.timestamp = timestamp()



// labels
MERGE (release_c428e760a3e2)-[:HAS_LABEL]->(label_935dbdbb598a)
MERGE (release_c428e760a3e2)-[:HAS_LABEL]->(label_46612304aca6)


// tracks
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_b636a6564ae5)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_ffec9da58ff6)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_af0531a1f675)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_fe09eaecfc03)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_eb42a3ac2549)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_1ec6cbd5e2ab)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '7', sequence: 7}]->(perf_a0564c9640d8)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '8', sequence: 8}]->(perf_1c6fa5fcee0d)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '9', sequence: 9}]->(perf_bfa3ec107627)
MERGE (release_c428e760a3e2)-[:HAS_TRACK {name: '10', sequence: 10}]->(perf_0249c5d5914b)

// works

MERGE (person_b693a808a158:Person{ uuid: '65744963-191a-44ef-a3c7-b693a808a158' }) 
SET person_b693a808a158.name = 'George Gershwin'
SET person_b693a808a158.gender = 'Male'
SET person_b693a808a158.disambiguation = 'composer'
SET person_b693a808a158.country = 'US'
SET person_b693a808a158.allmusic = 'https://www.allmusic.com/artist/mn0000197918'
SET person_b693a808a158.bbc = 'https://www.bbc.co.uk/music/artists/65744963-191a-44ef-a3c7-b693a808a158'
SET person_b693a808a158.discogs = 'https://www.discogs.com/artist/261293'
SET person_b693a808a158.imdb = 'https://www.imdb.com/name/nm0006097/'
SET person_b693a808a158.viaf = 'http://viaf.org/viaf/61554329'
SET person_b693a808a158.wikidata = 'https://www.wikidata.org/wiki/Q123829'
SET person_b693a808a158.databases = ['http://id.loc.gov/authorities/names/n79077265', 'https://adp.library.ucsb.edu/names/102427', 'https://catalogue.bnf.fr/ark:/12148/cb119493251', 'https://d-nb.info/gnd/118639226', 'https://ibdb.com/person.php?id=5813', 'http://snaccooperative.org/ark:/99166/w6x065dx', 'https://nla.gov.au/nla.party-832382', 'https://openlibrary.org/works/OL67761A', 'http://soundtrackcollector.com/composer/33/', 'https://rateyourmusic.com/artist/george_gershwin', 'https://www.worldcat.org/identities/lccn-n79077265']
SET person_b693a808a158.musicbrainz = 'https://musicbrainz.org/artist/65744963-191a-44ef-a3c7-b693a808a158'
SET person_b693a808a158.isni_list = ['http://isni.org/isni/0000000121355968']
SET person_b693a808a158.source = 'musicbrainz.org'
SET person_b693a808a158.timestamp = timestamp()

MERGE (person_322e34240ffc:Person{ uuid: '509086c2-9cc8-4e77-89e9-322e34240ffc' }) 
SET person_322e34240ffc.name = 'Ira Gershwin'
SET person_322e34240ffc.gender = 'Male'
SET person_322e34240ffc.country = 'US'
SET person_322e34240ffc.allmusic = 'https://www.allmusic.com/artist/mn0000200301'
SET person_322e34240ffc.discogs = 'https://www.discogs.com/artist/264105'
SET person_322e34240ffc.imdb = 'https://www.imdb.com/name/nm0314857/'
SET person_322e34240ffc.viaf = 'http://viaf.org/viaf/39519496'
SET person_322e34240ffc.wikidata = 'https://www.wikidata.org/wiki/Q61059'
SET person_322e34240ffc.databases = ['http://id.loc.gov/authorities/names/n50076010', 'https://adp.library.ucsb.edu/names/102148', 'https://catalogue.bnf.fr/ark:/12148/cb13194929s', 'https://d-nb.info/gnd/119500027', 'https://ibdb.com/person.php?id=6435', 'http://snaccooperative.org/ark:/99166/w60w94tm', 'https://nla.gov.au/nla.party-965252', 'https://openlibrary.org/works/OL233692A', 'https://rateyourmusic.com/artist/ira_gershwin', 'https://www.worldcat.org/identities/lccn-n50076010/']
SET person_322e34240ffc.musicbrainz = 'https://musicbrainz.org/artist/509086c2-9cc8-4e77-89e9-322e34240ffc'
SET person_322e34240ffc.isni_list = ['http://isni.org/isni/0000000108901469']
SET person_322e34240ffc.source = 'musicbrainz.org'
SET person_322e34240ffc.timestamp = timestamp()

MERGE (work_9eae6375ecb0:Work{ uuid: '6ae0f429-cd54-3ac2-b635-9eae6375ecb0' })
SET work_9eae6375ecb0.name = 'Question and Answer'
SET work_9eae6375ecb0.iswc = 'T-070.243.048-5'
SET work_9eae6375ecb0.type = 'Song'
SET work_9eae6375ecb0.source = 'musicbrainz.org'
SET work_9eae6375ecb0.timestamp = timestamp()

MERGE (work_107f7d852c3b:Work{ uuid: '6367a418-3e87-35b5-83ee-107f7d852c3b' })
SET work_107f7d852c3b.name = 'For a Thousand Years'
SET work_107f7d852c3b.source = 'musicbrainz.org'
SET work_107f7d852c3b.timestamp = timestamp()

MERGE (work_edcbaf398374:Work{ uuid: '6bb1382b-cb91-3d38-a37f-edcbaf398374' })
SET work_edcbaf398374.name = 'Tears of Rain'
SET work_edcbaf398374.source = 'musicbrainz.org'
SET work_edcbaf398374.timestamp = timestamp()

MERGE (work_4c3c24ca2a2d:Work{ uuid: 'ca21f3ed-3d49-3b5d-bb83-4c3c24ca2a2d' })
SET work_4c3c24ca2a2d.name = 'Country Roads'
SET work_4c3c24ca2a2d.source = 'musicbrainz.org'
SET work_4c3c24ca2a2d.timestamp = timestamp()

MERGE (work_2d23f44a30e4:Work{ uuid: '481f13c3-84e9-3890-abb4-2d23f44a30e4' })
SET work_2d23f44a30e4.name = 'Straight Up and Down'
SET work_2d23f44a30e4.source = 'musicbrainz.org'
SET work_2d23f44a30e4.timestamp = timestamp()

MERGE (work_702c61180860:Work{ uuid: 'ddf678a6-a75f-3235-bf12-702c61180860' })
SET work_702c61180860.name = 'Soon'
SET work_702c61180860.iswc = 'T-070.137.026-4'
SET work_702c61180860.type = 'Song'
SET work_702c61180860.wikidata = 'https://www.wikidata.org/wiki/Q7562677'
SET work_702c61180860.musicbrainz = 'https://musicbrainz.org/work/ddf678a6-a75f-3235-bf12-702c61180860'
SET work_702c61180860.source = 'musicbrainz.org'
SET work_702c61180860.timestamp = timestamp()

MERGE (work_30d5e416b1e8:Work{ uuid: 'd2382b9b-2838-384f-b18a-30d5e416b1e8' })
SET work_30d5e416b1e8.name = 'Windows'
SET work_30d5e416b1e8.iswc = 'T-904.321.382-7'
SET work_30d5e416b1e8.wikidata = 'https://www.wikidata.org/wiki/Q30601025'
SET work_30d5e416b1e8.musicbrainz = 'https://musicbrainz.org/work/d2382b9b-2838-384f-b18a-30d5e416b1e8'
SET work_30d5e416b1e8.source = 'musicbrainz.org'
SET work_30d5e416b1e8.timestamp = timestamp()

MERGE (work_607fa67a3167:Work{ uuid: '0bde6dee-0af6-3886-9c9f-607fa67a3167' })
SET work_607fa67a3167.name = 'Futures'
SET work_607fa67a3167.source = 'musicbrainz.org'
SET work_607fa67a3167.timestamp = timestamp()

MERGE (work_e5f9bcae0338:Work{ uuid: '4d103117-eba6-36e4-bfe2-e5f9bcae0338' })
SET work_e5f9bcae0338.name = 'Elucidation'
SET work_e5f9bcae0338.source = 'musicbrainz.org'
SET work_e5f9bcae0338.timestamp = timestamp()

MERGE (work_f06708e61695:Work{ uuid: '0b33a38d-81b1-368a-9194-f06708e61695' })
SET work_f06708e61695.name = 'Like Minds'
SET work_f06708e61695.source = 'musicbrainz.org'
SET work_f06708e61695.timestamp = timestamp()


// performances of
MERGE (perf_b636a6564ae5)-[:PERFORMANCE_OF]->(work_9eae6375ecb0)
MERGE (perf_bfa3ec107627)-[:PERFORMANCE_OF]->(work_107f7d852c3b)
MERGE (perf_a0564c9640d8)-[:PERFORMANCE_OF]->(work_edcbaf398374)
MERGE (perf_1ec6cbd5e2ab)-[:PERFORMANCE_OF]->(work_4c3c24ca2a2d)
MERGE (perf_0249c5d5914b)-[:PERFORMANCE_OF]->(work_2d23f44a30e4)
MERGE (perf_1c6fa5fcee0d)-[:PERFORMANCE_OF]->(work_702c61180860)
MERGE (perf_af0531a1f675)-[:PERFORMANCE_OF]->(work_30d5e416b1e8)
MERGE (perf_fe09eaecfc03)-[:PERFORMANCE_OF]->(work_607fa67a3167)
MERGE (perf_ffec9da58ff6)-[:PERFORMANCE_OF]->(work_e5f9bcae0338)
MERGE (perf_eb42a3ac2549)-[:PERFORMANCE_OF]->(work_f06708e61695)


// composers
MERGE (person_f8091d98cf25)-[:COMPOSED]->(work_9eae6375ecb0)
MERGE (person_f8091d98cf25)-[:COMPOSED]->(work_107f7d852c3b)
MERGE (person_f8091d98cf25)-[:COMPOSED]->(work_edcbaf398374)
MERGE (person_b1f20fcef5dc)-[:COMPOSED]->(work_4c3c24ca2a2d)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_2d23f44a30e4)
MERGE (person_b693a808a158)-[:COMPOSED]->(work_702c61180860)
MERGE (person_322e34240ffc)-[:WROTE_LYRICS]->(work_702c61180860)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_30d5e416b1e8)
MERGE (person_5a269b32b4c2)-[:COMPOSED]->(work_607fa67a3167)
MERGE (person_f8091d98cf25)-[:COMPOSED]->(work_e5f9bcae0338)
MERGE (person_b1f20fcef5dc)-[:COMPOSED]->(work_f06708e61695)


// place nodes

MERGE (place_d3f1bab1fdad:Place{ uuid: 'ed121457-87f6-4df9-a24b-d3f1bab1fdad' })
SET place_d3f1bab1fdad.name = 'Sony Music Studios'
SET place_d3f1bab1fdad.source = 'musicbrainz.org'

MERGE (place_6e44f7dfcf98:Place{ uuid: '859fdb68-9363-4ea0-b35a-6e44f7dfcf98' })
SET place_6e44f7dfcf98.name = 'Power Station at BerkleeNYC'
SET place_6e44f7dfcf98.source = 'musicbrainz.org'


// place relationships
MERGE (perf_b636a6564ae5)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_b636a6564ae5)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_ffec9da58ff6)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_ffec9da58ff6)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_af0531a1f675)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_af0531a1f675)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_fe09eaecfc03)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_fe09eaecfc03)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_eb42a3ac2549)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_eb42a3ac2549)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_1ec6cbd5e2ab)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_1ec6cbd5e2ab)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_a0564c9640d8)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_a0564c9640d8)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_1c6fa5fcee0d)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_1c6fa5fcee0d)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_bfa3ec107627)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_bfa3ec107627)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)
MERGE (perf_0249c5d5914b)-[:HAS_PLACE { type: 'mixed at' }]->(place_d3f1bab1fdad)
MERGE (perf_0249c5d5914b)-[:HAS_PLACE { type: 'recorded at', begin: '1997-12-15', end: '1997-12-17' }]->(place_6e44f7dfcf98)

MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_b636a6564ae5)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_b636a6564ae5)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_b636a6564ae5)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_b636a6564ae5)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_b636a6564ae5)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_b636a6564ae5)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_ffec9da58ff6)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_ffec9da58ff6)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_ffec9da58ff6)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_ffec9da58ff6)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_ffec9da58ff6)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_ffec9da58ff6)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_af0531a1f675)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_af0531a1f675)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_af0531a1f675)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_af0531a1f675)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_af0531a1f675)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_af0531a1f675)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_fe09eaecfc03)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_fe09eaecfc03)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_fe09eaecfc03)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_fe09eaecfc03)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_fe09eaecfc03)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_fe09eaecfc03)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_eb42a3ac2549)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_eb42a3ac2549)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_eb42a3ac2549)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_eb42a3ac2549)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_eb42a3ac2549)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_eb42a3ac2549)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_1ec6cbd5e2ab)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_1ec6cbd5e2ab)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_1ec6cbd5e2ab)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_1ec6cbd5e2ab)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_1ec6cbd5e2ab)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_1ec6cbd5e2ab)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_a0564c9640d8)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_a0564c9640d8)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_a0564c9640d8)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_a0564c9640d8)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_a0564c9640d8)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_a0564c9640d8)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_1c6fa5fcee0d)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_1c6fa5fcee0d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_1c6fa5fcee0d)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_1c6fa5fcee0d)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_1c6fa5fcee0d)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_1c6fa5fcee0d)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_bfa3ec107627)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_bfa3ec107627)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_bfa3ec107627)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_bfa3ec107627)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_bfa3ec107627)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_bfa3ec107627)
MERGE (person_b1f20fcef5dc)-[:PARTICIPATED_IN { roles: ['musician', 'producer'], instruments: ['vibraphone'] }]->(perf_0249c5d5914b)
MERGE (person_5a269b32b4c2)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_0249c5d5914b)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_0249c5d5914b)
MERGE (person_dbad528aa58e)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['double bass'] }]->(perf_0249c5d5914b)
MERGE (person_f8091d98cf25)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['guitar'] }]->(perf_0249c5d5914b)
MERGE (person_dabcde5dade7)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_0249c5d5914b)

