// releases

MERGE (release_4be0c962cbd3:Release{ uuid: 'b3b44589-ef7f-3630-a9c6-4be0c962cbd3' })
SET release_4be0c962cbd3.name = 'Screamin\' the Blues'
SET release_4be0c962cbd3.country = 'US'
SET release_4be0c962cbd3.date = '1963'
SET release_4be0c962cbd3.format = 'Vinyl'
SET release_4be0c962cbd3.discode = 'NJLP-8243'
SET release_4be0c962cbd3.musicbrainz = 'http://musicbrainz.org/release/b3b44589-ef7f-3630-a9c6-4be0c962cbd3'
SET release_4be0c962cbd3.source = 'musicbrainz.org'
SET release_4be0c962cbd3.timestamp = timestamp()

MERGE (person_8dc55a55a005:Person{ uuid: 'd8ffdb3c-34b7-4985-afd8-8dc55a55a005' })
SET person_8dc55a55a005.name = 'Richard Williams'
SET person_8dc55a55a005.gender = 'Male'
SET person_8dc55a55a005.disambiguation = 'jazz trumpeter'
SET person_8dc55a55a005.country = 'US'
SET person_8dc55a55a005.wikipedia = 'http://en.wikipedia.org/wiki/Richard_Williams_(musician)'
SET person_8dc55a55a005.viaf = 'http://viaf.org/viaf/100255328'
SET person_8dc55a55a005.allmusic = 'http://www.allmusic.com/artist/mn0000727557'
SET person_8dc55a55a005.discogs = 'http://www.discogs.com/artist/43786'
SET person_8dc55a55a005.wikidata = 'http://www.wikidata.org/wiki/Q2150923'
SET person_8dc55a55a005.musicbrainz = 'https://musicbrainz.org/artist/d8ffdb3c-34b7-4985-afd8-8dc55a55a005'
SET person_8dc55a55a005.source = 'musicbrainz.org'
SET person_8dc55a55a005.timestamp = timestamp()

MERGE (person_ceec49387371:Person{ uuid: 'c7f9dc85-ebff-4a0c-8957-ceec49387371' })
SET person_ceec49387371.name = 'Richard Wyands'
SET person_ceec49387371.gender = 'Male'
SET person_ceec49387371.country = 'US'
SET person_ceec49387371.wikipedia = 'http://en.wikipedia.org/wiki/Richard_Wyands'
SET person_ceec49387371.viaf = 'http://viaf.org/viaf/27253612'
SET person_ceec49387371.allmusic = 'http://www.allmusic.com/artist/mn0000850987'
SET person_ceec49387371.discogs = 'http://www.discogs.com/artist/278730'
SET person_ceec49387371.wikidata = 'http://www.wikidata.org/wiki/Q2150973'
SET person_ceec49387371.musicbrainz = 'https://musicbrainz.org/artist/c7f9dc85-ebff-4a0c-8957-ceec49387371'
SET person_ceec49387371.source = 'musicbrainz.org'
SET person_ceec49387371.timestamp = timestamp()

MERGE (person_07467bdf0f71:Person{ uuid: 'badda5cf-f2c5-4dc2-b3d3-07467bdf0f71' })
SET person_07467bdf0f71.name = 'Eric Dolphy'
SET person_07467bdf0f71.gender = 'Male'
SET person_07467bdf0f71.country = 'US'
SET person_07467bdf0f71.wikipedia = 'http://en.wikipedia.org/wiki/Eric_Dolphy'
SET person_07467bdf0f71.viaf = 'http://viaf.org/viaf/66651545'
SET person_07467bdf0f71.allmusic = 'http://www.allmusic.com/artist/mn0000800100'
SET person_07467bdf0f71.bbc = 'http://www.bbc.co.uk/music/artists/badda5cf-f2c5-4dc2-b3d3-07467bdf0f71'
SET person_07467bdf0f71.discogs = 'http://www.discogs.com/artist/145272'
SET person_07467bdf0f71.wikidata = 'http://www.wikidata.org/wiki/Q367508'
SET person_07467bdf0f71.discographies = ['http://adale.org/Discographies/EDIntro.html', 'http://www.jazzdisco.org/dolphy/']
SET person_07467bdf0f71.databases = ['https://rateyourmusic.com/artist/eric_dolphy']
SET person_07467bdf0f71.musicbrainz = 'https://musicbrainz.org/artist/badda5cf-f2c5-4dc2-b3d3-07467bdf0f71'
SET person_07467bdf0f71.isni_list = ['http://isni.org/isni/000000008146531X']
SET person_07467bdf0f71.source = 'musicbrainz.org'
SET person_07467bdf0f71.timestamp = timestamp()

MERGE (person_8f9b52869d74:Person{ uuid: '4704f86b-33b0-458a-9460-8f9b52869d74' })
SET person_8f9b52869d74.name = 'Oliver Nelson'
SET person_8f9b52869d74.gender = 'Male'
SET person_8f9b52869d74.country = 'US'
SET person_8f9b52869d74.wikipedia = 'http://en.wikipedia.org/wiki/Oliver_Nelson'
SET person_8f9b52869d74.viaf = 'http://viaf.org/viaf/46947276'
SET person_8f9b52869d74.allmusic = 'http://www.allmusic.com/artist/mn0000398615'
SET person_8f9b52869d74.discogs = 'http://www.discogs.com/artist/10095'
SET person_8f9b52869d74.imdb = 'http://www.imdb.com/name/nm0625648/'
SET person_8f9b52869d74.wikidata = 'http://www.wikidata.org/wiki/Q720687'
SET person_8f9b52869d74.musicbrainz = 'https://musicbrainz.org/artist/4704f86b-33b0-458a-9460-8f9b52869d74'
SET person_8f9b52869d74.source = 'musicbrainz.org'
SET person_8f9b52869d74.timestamp = timestamp()

MERGE (person_b804df7fa6bb:Person{ uuid: '68c93572-8296-49ea-b94e-b804df7fa6bb' })
SET person_b804df7fa6bb.name = 'Esmond Edwards'
SET person_b804df7fa6bb.discogs = 'http://www.discogs.com/artist/254944'
SET person_b804df7fa6bb.musicbrainz = 'https://musicbrainz.org/artist/68c93572-8296-49ea-b94e-b804df7fa6bb'
SET person_b804df7fa6bb.source = 'musicbrainz.org'
SET person_b804df7fa6bb.timestamp = timestamp()

MERGE (person_d639b04f8006:Person{ uuid: 'fda81bdf-37b1-47e2-86fe-d639b04f8006' })
SET person_d639b04f8006.name = 'George Duvivier'
SET person_d639b04f8006.gender = 'Male'
SET person_d639b04f8006.country = 'US'
SET person_d639b04f8006.wikipedia = 'http://en.wikipedia.org/wiki/George_Duvivier'
SET person_d639b04f8006.viaf = 'http://viaf.org/viaf/10033055'
SET person_d639b04f8006.allmusic = 'http://www.allmusic.com/artist/mn0000642920'
SET person_d639b04f8006.discogs = 'http://www.discogs.com/artist/262160'
SET person_d639b04f8006.wikidata = 'http://www.wikidata.org/wiki/Q1370288'
SET person_d639b04f8006.musicbrainz = 'https://musicbrainz.org/artist/fda81bdf-37b1-47e2-86fe-d639b04f8006'
SET person_d639b04f8006.source = 'musicbrainz.org'
SET person_d639b04f8006.timestamp = timestamp()

MERGE (person_6f0a331cc1ca:Person{ uuid: '2c090b57-5e9d-49c5-9b71-6f0a331cc1ca' })
SET person_6f0a331cc1ca.name = 'Roy Haynes'
SET person_6f0a331cc1ca.gender = 'Male'
SET person_6f0a331cc1ca.country = 'US'
SET person_6f0a331cc1ca.wikipedia = 'http://en.wikipedia.org/wiki/Roy_Haynes'
SET person_6f0a331cc1ca.viaf = 'http://viaf.org/viaf/84975999'
SET person_6f0a331cc1ca.allmusic = 'http://www.allmusic.com/artist/mn0000290464'
SET person_6f0a331cc1ca.bbc = 'http://www.bbc.co.uk/music/artists/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.discogs = 'http://www.discogs.com/artist/255556'
SET person_6f0a331cc1ca.imdb = 'http://www.imdb.com/name/nm0371542/'
SET person_6f0a331cc1ca.wikidata = 'http://www.wikidata.org/wiki/Q448235'
SET person_6f0a331cc1ca.musicbrainz = 'https://musicbrainz.org/artist/2c090b57-5e9d-49c5-9b71-6f0a331cc1ca'
SET person_6f0a331cc1ca.source = 'musicbrainz.org'
SET person_6f0a331cc1ca.timestamp = timestamp()

MERGE (person_05d508e09a73:Person{ uuid: 'f0707f1d-55e1-46b6-8a9c-05d508e09a73' })
SET person_05d508e09a73.name = 'Rudy van Gelder'
SET person_05d508e09a73.gender = 'Male'
SET person_05d508e09a73.country = 'US'
SET person_05d508e09a73.wikipedia = 'http://en.wikipedia.org/wiki/Rudy_Van_Gelder'
SET person_05d508e09a73.viaf = 'http://viaf.org/viaf/33997197'
SET person_05d508e09a73.allmusic = 'http://www.allmusic.com/artist/mn0000305301'
SET person_05d508e09a73.discogs = 'http://www.discogs.com/artist/252966'
SET person_05d508e09a73.wikidata = 'http://www.wikidata.org/wiki/Q945681'
SET person_05d508e09a73.databases = ['http://rateyourmusic.com/artist/rudy_van_gelder']
SET person_05d508e09a73.musicbrainz = 'https://musicbrainz.org/artist/f0707f1d-55e1-46b6-8a9c-05d508e09a73'
SET person_05d508e09a73.isni_list = ['http://isni.org/isni/0000000019691076']
SET person_05d508e09a73.source = 'musicbrainz.org'
SET person_05d508e09a73.timestamp = timestamp()
// labels

MERGE (label_d510b586b396:Label{ uuid: '3690758a-3ec1-4fd3-a250-d510b586b396' })
SET label_d510b586b396.name= 'New Jazz'

// performances

MERGE (perf_3fdff773e0c8:Performance{ uuid: '306fd7a3-5ee9-4294-a5d7-3fdff773e0c8' })
SET perf_3fdff773e0c8.name = 'Screamin\' the Blues'
SET perf_3fdff773e0c8.duration = '10:59'
SET perf_3fdff773e0c8.begin = '1960-05-27'
SET perf_3fdff773e0c8.end = '1960-05-27'
SET perf_3fdff773e0c8.source = 'musicbrainz.org'
SET perf_3fdff773e0c8.timestamp = timestamp()

MERGE (perf_8df2f206c71d:Performance{ uuid: '4134de8b-7a73-4a0e-a657-8df2f206c71d' })
SET perf_8df2f206c71d.name = 'March on, March On'
SET perf_8df2f206c71d.duration = '4:59'
SET perf_8df2f206c71d.begin = '1960-05-27'
SET perf_8df2f206c71d.end = '1960-05-27'
SET perf_8df2f206c71d.source = 'musicbrainz.org'
SET perf_8df2f206c71d.timestamp = timestamp()

MERGE (perf_9bf6dea1b195:Performance{ uuid: '49ea190f-a881-465c-bbfa-9bf6dea1b195' })
SET perf_9bf6dea1b195.name = 'The Drive'
SET perf_9bf6dea1b195.duration = '5:48'
SET perf_9bf6dea1b195.begin = '1960-05-27'
SET perf_9bf6dea1b195.end = '1960-05-27'
SET perf_9bf6dea1b195.source = 'musicbrainz.org'
SET perf_9bf6dea1b195.timestamp = timestamp()

MERGE (perf_98370aa94ce1:Performance{ uuid: 'd9610702-4af7-493b-8008-98370aa94ce1' })
SET perf_98370aa94ce1.name = 'The Meetin\''
SET perf_98370aa94ce1.duration = '6:43'
SET perf_98370aa94ce1.begin = '1960-05-27'
SET perf_98370aa94ce1.end = '1960-05-27'
SET perf_98370aa94ce1.source = 'musicbrainz.org'
SET perf_98370aa94ce1.timestamp = timestamp()

MERGE (perf_34aac5bab400:Performance{ uuid: '9d87fe4d-0825-420a-91dd-34aac5bab400' })
SET perf_34aac5bab400.name = 'Three Seconds'
SET perf_34aac5bab400.duration = '6:25'
SET perf_34aac5bab400.begin = '1960-05-27'
SET perf_34aac5bab400.end = '1960-05-27'
SET perf_34aac5bab400.source = 'musicbrainz.org'
SET perf_34aac5bab400.timestamp = timestamp()

MERGE (perf_57e2fa0804fe:Performance{ uuid: '29ae033c-3838-4d59-ac0d-57e2fa0804fe' })
SET perf_57e2fa0804fe.name = 'Alto-itis'
SET perf_57e2fa0804fe.duration = '4:58'
SET perf_57e2fa0804fe.begin = '1960-05-27'
SET perf_57e2fa0804fe.end = '1960-05-27'
SET perf_57e2fa0804fe.source = 'musicbrainz.org'
SET perf_57e2fa0804fe.timestamp = timestamp()



// labels
MERGE (release_4be0c962cbd3)-[:HAS_LABEL]->(label_d510b586b396)


// tracks
MERGE (release_4be0c962cbd3)-[:HAS_TRACK {name: '1', sequence: 1}]->(perf_3fdff773e0c8)
MERGE (release_4be0c962cbd3)-[:HAS_TRACK {name: '2', sequence: 2}]->(perf_8df2f206c71d)
MERGE (release_4be0c962cbd3)-[:HAS_TRACK {name: '3', sequence: 3}]->(perf_9bf6dea1b195)
MERGE (release_4be0c962cbd3)-[:HAS_TRACK {name: '4', sequence: 4}]->(perf_98370aa94ce1)
MERGE (release_4be0c962cbd3)-[:HAS_TRACK {name: '5', sequence: 5}]->(perf_34aac5bab400)
MERGE (release_4be0c962cbd3)-[:HAS_TRACK {name: '6', sequence: 6}]->(perf_57e2fa0804fe)


// place nodes

MERGE (place_569fa8b97644:Place{ uuid: '1165ef7d-371c-4e03-98db-569fa8b97644' })
SET place_569fa8b97644.name = 'Van Gelder Studio'
SET place_569fa8b97644.address = '445, Sylvan Avenue, Englewood Cliffs, Bergen County, New Jersey, 07632, United States of America'
SET place_569fa8b97644.lat = '40.8764374074488'
SET place_569fa8b97644.lng = '-73.9519546846822'
SET place_569fa8b97644.source = 'musicbrainz.org'


// place relationships
MERGE (perf_3fdff773e0c8)-[:HAS_PLACE { type: 'recorded at', begin: '1960-05-27', end: '1960-05-27' }]->(place_569fa8b97644)
MERGE (perf_8df2f206c71d)-[:HAS_PLACE { type: 'recorded at', begin: '1960-05-27', end: '1960-05-27' }]->(place_569fa8b97644)
MERGE (perf_9bf6dea1b195)-[:HAS_PLACE { type: 'recorded at', begin: '1960-05-27', end: '1960-05-27' }]->(place_569fa8b97644)
MERGE (perf_98370aa94ce1)-[:HAS_PLACE { type: 'recorded at', begin: '1960-05-27', end: '1960-05-27' }]->(place_569fa8b97644)
MERGE (perf_34aac5bab400)-[:HAS_PLACE { type: 'recorded at', begin: '1960-05-27', end: '1960-05-27' }]->(place_569fa8b97644)
MERGE (perf_57e2fa0804fe)-[:HAS_PLACE { type: 'recorded at', begin: '1960-05-27', end: '1960-05-27' }]->(place_569fa8b97644)

MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_3fdff773e0c8)
MERGE (person_8f9b52869d74)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['saxophone'] }]->(perf_3fdff773e0c8)
MERGE (person_b804df7fa6bb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_3fdff773e0c8)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone', 'bass clarinet'] }]->(perf_3fdff773e0c8)
MERGE (person_ceec49387371)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_3fdff773e0c8)
MERGE (person_8dc55a55a005)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_3fdff773e0c8)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_3fdff773e0c8)
MERGE (person_d639b04f8006)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_3fdff773e0c8)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_8df2f206c71d)
MERGE (person_8f9b52869d74)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['saxophone'] }]->(perf_8df2f206c71d)
MERGE (person_b804df7fa6bb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_8df2f206c71d)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone', 'bass clarinet'] }]->(perf_8df2f206c71d)
MERGE (person_ceec49387371)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_8df2f206c71d)
MERGE (person_8dc55a55a005)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_8df2f206c71d)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_8df2f206c71d)
MERGE (person_d639b04f8006)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_8df2f206c71d)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_9bf6dea1b195)
MERGE (person_8f9b52869d74)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['saxophone'] }]->(perf_9bf6dea1b195)
MERGE (person_b804df7fa6bb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_9bf6dea1b195)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone', 'bass clarinet'] }]->(perf_9bf6dea1b195)
MERGE (person_ceec49387371)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_9bf6dea1b195)
MERGE (person_8dc55a55a005)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_9bf6dea1b195)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_9bf6dea1b195)
MERGE (person_d639b04f8006)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_9bf6dea1b195)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_98370aa94ce1)
MERGE (person_8f9b52869d74)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['saxophone'] }]->(perf_98370aa94ce1)
MERGE (person_b804df7fa6bb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_98370aa94ce1)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone', 'bass clarinet'] }]->(perf_98370aa94ce1)
MERGE (person_ceec49387371)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_98370aa94ce1)
MERGE (person_8dc55a55a005)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_98370aa94ce1)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_98370aa94ce1)
MERGE (person_d639b04f8006)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_98370aa94ce1)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_34aac5bab400)
MERGE (person_8f9b52869d74)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['saxophone'] }]->(perf_34aac5bab400)
MERGE (person_b804df7fa6bb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_34aac5bab400)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone', 'bass clarinet'] }]->(perf_34aac5bab400)
MERGE (person_ceec49387371)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_34aac5bab400)
MERGE (person_8dc55a55a005)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_34aac5bab400)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_34aac5bab400)
MERGE (person_d639b04f8006)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_34aac5bab400)
MERGE (person_6f0a331cc1ca)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums'] }]->(perf_57e2fa0804fe)
MERGE (person_8f9b52869d74)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['saxophone'] }]->(perf_57e2fa0804fe)
MERGE (person_b804df7fa6bb)-[:PARTICIPATED_IN { roles: ['producer'] }]->(perf_57e2fa0804fe)
MERGE (person_07467bdf0f71)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone', 'bass clarinet'] }]->(perf_57e2fa0804fe)
MERGE (person_ceec49387371)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_57e2fa0804fe)
MERGE (person_8dc55a55a005)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trumpet'] }]->(perf_57e2fa0804fe)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_57e2fa0804fe)
MERGE (person_d639b04f8006)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_57e2fa0804fe)

