// releases

MERGE (release_f80f79330f0d:Release{ uuid: '55bca2db-8787-47db-86ea-f80f79330f0d' })
SET release_f80f79330f0d.name = 'The All Seeing Eye'
SET release_f80f79330f0d.disambiguation = 'mono'
SET release_f80f79330f0d.country = 'US'
SET release_f80f79330f0d.date = '1966-10'
SET release_f80f79330f0d.format = '12" Vinyl'
SET release_f80f79330f0d.discode = 'BLP 4219'
SET release_f80f79330f0d.discogs = 'https://www.discogs.com/release/1199967'
SET release_f80f79330f0d.musicbrainz = 'http://musicbrainz.org/release/55bca2db-8787-47db-86ea-f80f79330f0d'
SET release_f80f79330f0d.source = 'musicbrainz.org'
SET release_f80f79330f0d.timestamp = timestamp()

MERGE (person_e327e692bb5a:Person{ uuid: '59ae7a1a-f454-435b-8a5a-e327e692bb5a' }) 
SET person_e327e692bb5a.name = 'Freddie Hubbard'
SET person_e327e692bb5a.gender = 'Male'
SET person_e327e692bb5a.country = 'US'
SET person_e327e692bb5a.allmusic = 'https://www.allmusic.com/artist/mn0000798326'
SET person_e327e692bb5a.bbc = 'https://www.bbc.co.uk/music/artists/59ae7a1a-f454-435b-8a5a-e327e692bb5a'
SET person_e327e692bb5a.discogs = 'https://www.discogs.com/artist/55745'
SET person_e327e692bb5a.imdb = 'https://www.imdb.com/name/nm0399174/'
SET person_e327e692bb5a.viaf = 'http://viaf.org/viaf/64192087'
SET person_e327e692bb5a.wikidata = 'https://www.wikidata.org/wiki/Q346762'
SET person_e327e692bb5a.databases = ['http://d-nb.info/gnd/134411773', 'http://id.loc.gov/authorities/names/n83163529', 'https://catalogue.bnf.fr/ark:/12148/cb13895374d', 'https://rateyourmusic.com/artist/freddie_hubbard', 'https://www.worldcat.org/identities/lccn-n83163529']
SET person_e327e692bb5a.musicbrainz = 'https://musicbrainz.org/artist/59ae7a1a-f454-435b-8a5a-e327e692bb5a'
SET person_e327e692bb5a.isni_list = ['http://isni.org/isni/0000000114462300']
SET person_e327e692bb5a.source = 'musicbrainz.org'
SET person_e327e692bb5a.timestamp = timestamp()

MERGE (person_e044666c4828:Person{ uuid: '57db3f59-9c58-4f68-a00e-e044666c4828' }) 
SET person_e044666c4828.name = 'Ron Carter'
SET person_e044666c4828.gender = 'Male'
SET person_e044666c4828.disambiguation = 'US jazz double-bassist'
SET person_e044666c4828.country = 'US'
SET person_e044666c4828.allmusic = 'https://www.allmusic.com/artist/mn0000275832'
SET person_e044666c4828.discogs = 'https://www.discogs.com/artist/95088'
SET person_e044666c4828.imdb = 'https://www.imdb.com/name/nm0141909/'
SET person_e044666c4828.viaf = 'http://viaf.org/viaf/22326766'
SET person_e044666c4828.wikidata = 'https://www.wikidata.org/wiki/Q434593'
SET person_e044666c4828.databases = ['http://d-nb.info/gnd/134344332', 'http://id.loc.gov/authorities/names/n81014576', 'https://catalogue.bnf.fr/ark:/12148/cb138922167', 'http://snaccooperative.org/ark:/99166/w67m16sc', 'https://rateyourmusic.com/artist/ron_carter', 'https://www.worldcat.org/identities/lccn-n81014576']
SET person_e044666c4828.musicbrainz = 'https://musicbrainz.org/artist/57db3f59-9c58-4f68-a00e-e044666c4828'
SET person_e044666c4828.isni_list = ['http://isni.org/isni/0000000114394862']
SET person_e044666c4828.source = 'musicbrainz.org'
SET person_e044666c4828.timestamp = timestamp()

MERGE (person_6b59db246899:Person{ uuid: 'd7dfd39c-c5fd-4c16-b7ec-6b59db246899' }) 
SET person_6b59db246899.name = 'James Spaulding'
SET person_6b59db246899.gender = 'Male'
SET person_6b59db246899.disambiguation = 'jazz'
SET person_6b59db246899.country = 'US'
SET person_6b59db246899.allmusic = 'https://www.allmusic.com/artist/mn0000174506'
SET person_6b59db246899.discogs = 'https://www.discogs.com/artist/262505'
SET person_6b59db246899.viaf = 'http://viaf.org/viaf/42026706'
SET person_6b59db246899.wikidata = 'https://www.wikidata.org/wiki/Q1681118'
SET person_6b59db246899.databases = ['http://d-nb.info/gnd/134526473', 'http://id.loc.gov/authorities/names/n88627476', 'https://catalogue.bnf.fr/ark:/12148/cb13899961p', 'http://snaccooperative.org/ark:/99166/w6gg4tcc', 'https://www.worldcat.org/identities/lccn-n88627476']
SET person_6b59db246899.musicbrainz = 'https://musicbrainz.org/artist/d7dfd39c-c5fd-4c16-b7ec-6b59db246899'
SET person_6b59db246899.isni_list = ['http://isni.org/isni/0000000055141995']
SET person_6b59db246899.source = 'musicbrainz.org'
SET person_6b59db246899.timestamp = timestamp()

MERGE (person_05d508e09a73:Person{ uuid: 'f0707f1d-55e1-46b6-8a9c-05d508e09a73' }) 
SET person_05d508e09a73.name = 'Rudy van Gelder'
SET person_05d508e09a73.gender = 'Male'
SET person_05d508e09a73.country = 'US'
SET person_05d508e09a73.allmusic = 'https://www.allmusic.com/artist/mn0000305301'
SET person_05d508e09a73.discogs = 'https://www.discogs.com/artist/252966'
SET person_05d508e09a73.viaf = 'http://viaf.org/viaf/33997197'
SET person_05d508e09a73.wikidata = 'https://www.wikidata.org/wiki/Q945681'
SET person_05d508e09a73.databases = ['http://d-nb.info/gnd/133648508', 'http://id.loc.gov/authorities/names/no00020144', 'https://rateyourmusic.com/artist/rudy_van_gelder', 'https://www.worldcat.org/identities/lccn-no00020144']
SET person_05d508e09a73.musicbrainz = 'https://musicbrainz.org/artist/f0707f1d-55e1-46b6-8a9c-05d508e09a73'
SET person_05d508e09a73.isni_list = ['http://isni.org/isni/0000000019691076']
SET person_05d508e09a73.source = 'musicbrainz.org'
SET person_05d508e09a73.timestamp = timestamp()

MERGE (person_633fafd72002:Person{ uuid: '2379937f-6e0d-46a2-b8ff-633fafd72002' }) 
SET person_633fafd72002.name = 'Wayne Shorter'
SET person_633fafd72002.gender = 'Male'
SET person_633fafd72002.disambiguation = 'US jazz saxophonist and composer'
SET person_633fafd72002.country = 'US'
SET person_633fafd72002.allmusic = 'https://www.allmusic.com/artist/mn0000250435'
SET person_633fafd72002.bbc = 'https://www.bbc.co.uk/music/artists/2379937f-6e0d-46a2-b8ff-633fafd72002'
SET person_633fafd72002.discogs = 'https://www.discogs.com/artist/29979'
SET person_633fafd72002.imdb = 'https://www.imdb.com/name/nm0795147/'
SET person_633fafd72002.viaf = 'http://viaf.org/viaf/86650174'
SET person_633fafd72002.wikidata = 'https://www.wikidata.org/wiki/Q317161'
SET person_633fafd72002.databases = ['http://d-nb.info/gnd/124938981', 'http://id.loc.gov/authorities/names/n81014577', 'https://catalogue.bnf.fr/ark:/12148/cb138997525', 'http://snaccooperative.org/ark:/99166/w63n3pcn', 'https://rateyourmusic.com/artist/wayne-shorter', 'https://www.musik-sammler.de/artist/wayne-shorter/', 'https://www.worldcat.org/identities/lccn-n81014577']
SET person_633fafd72002.musicbrainz = 'https://musicbrainz.org/artist/2379937f-6e0d-46a2-b8ff-633fafd72002'
SET person_633fafd72002.isni_list = ['http://isni.org/isni/0000000121424206']
SET person_633fafd72002.source = 'musicbrainz.org'
SET person_633fafd72002.timestamp = timestamp()

MERGE (person_942e690a4f1a:Person{ uuid: '926ae0b4-6ba2-4907-9e40-942e690a4f1a' }) 
SET person_942e690a4f1a.name = 'Alan Shorter'
SET person_942e690a4f1a.gender = 'Male'
SET person_942e690a4f1a.country = 'US'
SET person_942e690a4f1a.allmusic = 'https://www.allmusic.com/artist/mn0000931865'
SET person_942e690a4f1a.discogs = 'https://www.discogs.com/artist/258036'
SET person_942e690a4f1a.viaf = 'http://viaf.org/viaf/59280522'
SET person_942e690a4f1a.wikidata = 'https://www.wikidata.org/wiki/Q2622326'
SET person_942e690a4f1a.wikipedia = 'https://en.wikipedia.org/wiki/Alan_Shorter'
SET person_942e690a4f1a.databases = ['http://d-nb.info/gnd/135089492', 'http://id.loc.gov/authorities/names/no91018475', 'https://catalogue.bnf.fr/ark:/12148/cb140025117', 'https://www.worldcat.org/identities/lccn-no91018475']
SET person_942e690a4f1a.musicbrainz = 'https://musicbrainz.org/artist/926ae0b4-6ba2-4907-9e40-942e690a4f1a'
SET person_942e690a4f1a.isni_list = ['http://isni.org/isni/0000000055187002']
SET person_942e690a4f1a.source = 'musicbrainz.org'
SET person_942e690a4f1a.timestamp = timestamp()

MERGE (person_0ab0782360e8:Person{ uuid: '2098836b-6ee4-45fd-a5cc-0ab0782360e8' }) 
SET person_0ab0782360e8.name = 'Grachan Moncur III'
SET person_0ab0782360e8.gender = 'Male'
SET person_0ab0782360e8.disambiguation = 'trombonist'
SET person_0ab0782360e8.country = 'US'
SET person_0ab0782360e8.allmusic = 'https://www.allmusic.com/artist/mn0000803589'
SET person_0ab0782360e8.discogs = 'https://www.discogs.com/artist/253102'
SET person_0ab0782360e8.viaf = 'http://viaf.org/viaf/54333298'
SET person_0ab0782360e8.wikidata = 'https://www.wikidata.org/wiki/Q489239'
SET person_0ab0782360e8.databases = ['http://d-nb.info/gnd/134465261', 'http://id.loc.gov/authorities/names/n91066945', 'https://catalogue.bnf.fr/ark:/12148/cb13897616j', 'https://ibdb.com/person.php?id=95716', 'https://rateyourmusic.com/artist/grachan_moncur_iii', 'https://www.worldcat.org/identities/lccn-n91066945']
SET person_0ab0782360e8.musicbrainz = 'https://musicbrainz.org/artist/2098836b-6ee4-45fd-a5cc-0ab0782360e8'
SET person_0ab0782360e8.isni_list = ['http://isni.org/isni/0000000114443935']
SET person_0ab0782360e8.source = 'musicbrainz.org'
SET person_0ab0782360e8.timestamp = timestamp()

MERGE (person_b03012cc81ef:Person{ uuid: '74061fae-e2c8-4fea-92b9-b03012cc81ef' }) 
SET person_b03012cc81ef.name = 'Joe Chambers'
SET person_b03012cc81ef.gender = 'Male'
SET person_b03012cc81ef.disambiguation = 'American jazz drummer, vibraphonist and pianist'
SET person_b03012cc81ef.country = 'US'
SET person_b03012cc81ef.allmusic = 'https://www.allmusic.com/artist/mn0000122897'
SET person_b03012cc81ef.discogs = 'https://www.discogs.com/artist/256581'
SET person_b03012cc81ef.viaf = 'http://viaf.org/viaf/7573461'
SET person_b03012cc81ef.wikidata = 'https://www.wikidata.org/wiki/Q717207'
SET person_b03012cc81ef.databases = ['http://d-nb.info/gnd/134345770', 'http://id.loc.gov/authorities/names/n81149295', 'https://catalogue.bnf.fr/ark:/12148/cb13892356r', 'http://snaccooperative.org/ark:/99166/w6z0589r', 'https://rateyourmusic.com/artist/joe-chambers', 'https://www.worldcat.org/identities/lccn-n81149295']
SET person_b03012cc81ef.musicbrainz = 'https://musicbrainz.org/artist/74061fae-e2c8-4fea-92b9-b03012cc81ef'
SET person_b03012cc81ef.isni_list = ['http://isni.org/isni/0000000114671399']
SET person_b03012cc81ef.source = 'musicbrainz.org'
SET person_b03012cc81ef.timestamp = timestamp()

MERGE (person_fa0743465fdd:Person{ uuid: '27613b78-1b9d-4ec3-9db5-fa0743465fdd' }) 
SET person_fa0743465fdd.name = 'Herbie Hancock'
SET person_fa0743465fdd.gender = 'Male'
SET person_fa0743465fdd.disambiguation = 'US jazz pianist, keyboardist, bandleader and composer'
SET person_fa0743465fdd.country = 'US'
SET person_fa0743465fdd.allmusic = 'https://www.allmusic.com/artist/mn0000957296'
SET person_fa0743465fdd.bbc = 'https://www.bbc.co.uk/music/artists/27613b78-1b9d-4ec3-9db5-fa0743465fdd'
SET person_fa0743465fdd.discogs = 'https://www.discogs.com/artist/3865'
SET person_fa0743465fdd.imdb = 'https://www.imdb.com/name/nm0359372/'
SET person_fa0743465fdd.viaf = 'http://viaf.org/viaf/49408202'
SET person_fa0743465fdd.wikidata = 'https://www.wikidata.org/wiki/Q105875'
SET person_fa0743465fdd.databases = ['http://d-nb.info/gnd/121542157', 'http://id.loc.gov/authorities/names/n81014575', 'http://musicmoz.org/Bands_and_Artists/H/Hancock,_Herbie/', 'https://catalogue.bnf.fr/ark:/12148/cb13894938z', 'https://imvdb.com/n/herbie-hancock', 'http://snaccooperative.org/ark:/99166/w6rf5z7r', 'https://rateyourmusic.com/artist/herbie_hancock', 'https://www.whosampled.com/Herbie-Hancock/', 'https://www.worldcat.org/identities/lccn-n81014575']
SET person_fa0743465fdd.musicbrainz = 'https://musicbrainz.org/artist/27613b78-1b9d-4ec3-9db5-fa0743465fdd'
SET person_fa0743465fdd.isni_list = ['http://isni.org/isni/0000000108993797']
SET person_fa0743465fdd.source = 'musicbrainz.org'
SET person_fa0743465fdd.timestamp = timestamp()
// labels

MERGE (label_14e1ddfd5946:Label{ uuid: '713c4a95-6616-442b-9cf6-14e1ddfd5946' })
SET label_14e1ddfd5946.name= 'Blue Note'

// performances

MERGE (perf_4e7d872be72a:Performance{ uuid: 'e29295bd-e40d-44f0-b1b8-4e7d872be72a' })
SET perf_4e7d872be72a.name = 'The All Seeing Eye'
SET perf_4e7d872be72a.disambiguation = 'mono'
SET perf_4e7d872be72a.begin = '1965-10-15'
SET perf_4e7d872be72a.end = '1965-10-15'
SET perf_4e7d872be72a.source = 'musicbrainz.org'
SET perf_4e7d872be72a.timestamp = timestamp()

MERGE (perf_1a1fd87d289a:Performance{ uuid: 'f89e5dfc-1196-4a18-b2ae-1a1fd87d289a' })
SET perf_1a1fd87d289a.name = 'Genesis'
SET perf_1a1fd87d289a.disambiguation = 'mono'
SET perf_1a1fd87d289a.begin = '1965-10-15'
SET perf_1a1fd87d289a.end = '1965-10-15'
SET perf_1a1fd87d289a.source = 'musicbrainz.org'
SET perf_1a1fd87d289a.timestamp = timestamp()

MERGE (perf_aac3bb9ccbe8:Performance{ uuid: '6c310d3b-f553-4f0f-9975-aac3bb9ccbe8' })
SET perf_aac3bb9ccbe8.name = 'Chaos'
SET perf_aac3bb9ccbe8.disambiguation = 'mono'
SET perf_aac3bb9ccbe8.begin = '1965-10-15'
SET perf_aac3bb9ccbe8.end = '1965-10-15'
SET perf_aac3bb9ccbe8.source = 'musicbrainz.org'
SET perf_aac3bb9ccbe8.timestamp = timestamp()

MERGE (perf_4bb3a2a36351:Performance{ uuid: 'e1b2270c-f245-4c18-8426-4bb3a2a36351' })
SET perf_4bb3a2a36351.name = 'Face of the Deep'
SET perf_4bb3a2a36351.disambiguation = 'mono'
SET perf_4bb3a2a36351.begin = '1965-10-15'
SET perf_4bb3a2a36351.end = '1965-10-15'
SET perf_4bb3a2a36351.source = 'musicbrainz.org'
SET perf_4bb3a2a36351.timestamp = timestamp()

MERGE (perf_fbff2fbec1b7:Performance{ uuid: 'a62dc132-4db3-4daf-abd6-fbff2fbec1b7' })
SET perf_fbff2fbec1b7.name = 'Mephistopheles'
SET perf_fbff2fbec1b7.disambiguation = 'mono'
SET perf_fbff2fbec1b7.begin = '1965-10-15'
SET perf_fbff2fbec1b7.end = '1965-10-15'
SET perf_fbff2fbec1b7.source = 'musicbrainz.org'
SET perf_fbff2fbec1b7.timestamp = timestamp()



// labels
MERGE (release_f80f79330f0d)-[:HAS_LABEL]->(label_14e1ddfd5946)


// tracks
MERGE (release_f80f79330f0d)-[:HAS_TRACK {name: 'A1', sequence: 1}]->(perf_4e7d872be72a)
MERGE (release_f80f79330f0d)-[:HAS_TRACK {name: 'A2', sequence: 2}]->(perf_1a1fd87d289a)
MERGE (release_f80f79330f0d)-[:HAS_TRACK {name: 'B1', sequence: 3}]->(perf_aac3bb9ccbe8)
MERGE (release_f80f79330f0d)-[:HAS_TRACK {name: 'B2', sequence: 4}]->(perf_4bb3a2a36351)
MERGE (release_f80f79330f0d)-[:HAS_TRACK {name: 'B3', sequence: 5}]->(perf_fbff2fbec1b7)

// works

MERGE (work_1a8c4cd6ed28:Work{ uuid: '55c67105-a623-405f-8d2e-1a8c4cd6ed28' })
SET work_1a8c4cd6ed28.name = 'Chaos'
SET work_1a8c4cd6ed28.source = 'musicbrainz.org'
SET work_1a8c4cd6ed28.timestamp = timestamp()

MERGE (work_f1fc68d443ed:Work{ uuid: '2dd58c37-7645-4752-9cb6-f1fc68d443ed' })
SET work_f1fc68d443ed.name = 'Face of the Deep'
SET work_f1fc68d443ed.source = 'musicbrainz.org'
SET work_f1fc68d443ed.timestamp = timestamp()

MERGE (work_fc9ae6a9671f:Work{ uuid: 'e621c4ec-66a8-44a7-b011-fc9ae6a9671f' })
SET work_fc9ae6a9671f.name = 'The All Seeing Eye'
SET work_fc9ae6a9671f.source = 'musicbrainz.org'
SET work_fc9ae6a9671f.timestamp = timestamp()

MERGE (work_37d255a885d6:Work{ uuid: 'd92abb58-d625-40fd-9a63-37d255a885d6' })
SET work_37d255a885d6.name = 'Genesis'
SET work_37d255a885d6.source = 'musicbrainz.org'
SET work_37d255a885d6.timestamp = timestamp()

MERGE (work_2f44b4bfafdc:Work{ uuid: '3dbfb9f2-c15b-4416-a841-2f44b4bfafdc' })
SET work_2f44b4bfafdc.name = 'Mephistopheles'
SET work_2f44b4bfafdc.type = 'Song'
SET work_2f44b4bfafdc.source = 'musicbrainz.org'
SET work_2f44b4bfafdc.timestamp = timestamp()


// performances of
MERGE (perf_aac3bb9ccbe8)-[:PERFORMANCE_OF]->(work_1a8c4cd6ed28)
MERGE (perf_4bb3a2a36351)-[:PERFORMANCE_OF]->(work_f1fc68d443ed)
MERGE (perf_4e7d872be72a)-[:PERFORMANCE_OF]->(work_fc9ae6a9671f)
MERGE (perf_1a1fd87d289a)-[:PERFORMANCE_OF]->(work_37d255a885d6)
MERGE (perf_fbff2fbec1b7)-[:PERFORMANCE_OF]->(work_2f44b4bfafdc)


// composers
MERGE (person_633fafd72002)-[:COMPOSED]->(work_1a8c4cd6ed28)
MERGE (person_633fafd72002)-[:COMPOSED]->(work_f1fc68d443ed)
MERGE (person_633fafd72002)-[:COMPOSED]->(work_fc9ae6a9671f)
MERGE (person_633fafd72002)-[:COMPOSED]->(work_37d255a885d6)
MERGE (person_942e690a4f1a)-[:COMPOSED]->(work_2f44b4bfafdc)


// place nodes

MERGE (place_569fa8b97644:Place{ uuid: '1165ef7d-371c-4e03-98db-569fa8b97644' })
SET place_569fa8b97644.name = 'Van Gelder Studio'
SET place_569fa8b97644.source = 'musicbrainz.org'


// place relationships
MERGE (perf_4e7d872be72a)-[:HAS_PLACE { type: 'recorded at', begin: '1965-10-15', end: '1965-10-15' }]->(place_569fa8b97644)
MERGE (perf_1a1fd87d289a)-[:HAS_PLACE { type: 'recorded at', begin: '1965-10-15', end: '1965-10-15' }]->(place_569fa8b97644)
MERGE (perf_aac3bb9ccbe8)-[:HAS_PLACE { type: 'recorded at', begin: '1965-10-15', end: '1965-10-15' }]->(place_569fa8b97644)
MERGE (perf_4bb3a2a36351)-[:HAS_PLACE { type: 'recorded at', begin: '1965-10-15', end: '1965-10-15' }]->(place_569fa8b97644)
MERGE (perf_fbff2fbec1b7)-[:HAS_PLACE { type: 'recorded at', begin: '1965-10-15', end: '1965-10-15' }]->(place_569fa8b97644)

MERGE (person_e044666c4828)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_4e7d872be72a)
MERGE (person_b03012cc81ef)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_4e7d872be72a)
MERGE (person_fa0743465fdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_4e7d872be72a)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['brass'] }]->(perf_4e7d872be72a)
MERGE (person_0ab0782360e8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trombone'] }]->(perf_4e7d872be72a)
MERGE (person_633fafd72002)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_4e7d872be72a)
MERGE (person_6b59db246899)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_4e7d872be72a)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_4e7d872be72a)
MERGE (person_e044666c4828)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_1a1fd87d289a)
MERGE (person_b03012cc81ef)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_1a1fd87d289a)
MERGE (person_fa0743465fdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_1a1fd87d289a)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['brass'] }]->(perf_1a1fd87d289a)
MERGE (person_0ab0782360e8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trombone'] }]->(perf_1a1fd87d289a)
MERGE (person_633fafd72002)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_1a1fd87d289a)
MERGE (person_6b59db246899)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_1a1fd87d289a)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_1a1fd87d289a)
MERGE (person_e044666c4828)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_aac3bb9ccbe8)
MERGE (person_b03012cc81ef)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_aac3bb9ccbe8)
MERGE (person_fa0743465fdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_aac3bb9ccbe8)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['brass'] }]->(perf_aac3bb9ccbe8)
MERGE (person_0ab0782360e8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trombone'] }]->(perf_aac3bb9ccbe8)
MERGE (person_633fafd72002)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_aac3bb9ccbe8)
MERGE (person_6b59db246899)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_aac3bb9ccbe8)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_aac3bb9ccbe8)
MERGE (person_e044666c4828)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_4bb3a2a36351)
MERGE (person_b03012cc81ef)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_4bb3a2a36351)
MERGE (person_fa0743465fdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_4bb3a2a36351)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['brass'] }]->(perf_4bb3a2a36351)
MERGE (person_0ab0782360e8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trombone'] }]->(perf_4bb3a2a36351)
MERGE (person_633fafd72002)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_4bb3a2a36351)
MERGE (person_6b59db246899)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_4bb3a2a36351)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_4bb3a2a36351)
MERGE (person_e044666c4828)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['bass'] }]->(perf_fbff2fbec1b7)
MERGE (person_b03012cc81ef)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['drums (drum set)'] }]->(perf_fbff2fbec1b7)
MERGE (person_fa0743465fdd)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['piano'] }]->(perf_fbff2fbec1b7)
MERGE (person_e327e692bb5a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['brass'] }]->(perf_fbff2fbec1b7)
MERGE (person_0ab0782360e8)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['trombone'] }]->(perf_fbff2fbec1b7)
MERGE (person_942e690a4f1a)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['flugelhorn'] }]->(perf_fbff2fbec1b7)
MERGE (person_633fafd72002)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['tenor saxophone'] }]->(perf_fbff2fbec1b7)
MERGE (person_6b59db246899)-[:PARTICIPATED_IN { roles: ['musician'], instruments: ['alto saxophone'] }]->(perf_fbff2fbec1b7)
MERGE (person_05d508e09a73)-[:PARTICIPATED_IN { roles: ['recording engineer'] }]->(perf_fbff2fbec1b7)

