version: '3.8'

networks:
  caddy:

services:
  kuzudb-explorer:
    image: kuzudb/explorer:latest
    container_name: kuzudb-explorer
    restart: unless-stopped
    volumes:
      - ${KUZUDB_ABSOLUTE_PATH}:/database
    environment:
      - MODE=READ_ONLY
    ports:
      - "8000:8000"
    networks:
     - caddy

  kuzudb-api-server:
    image: kuzudb/api-server:latest
    container_name: kuzudb-api-server
    restart: unless-stopped
    volumes:
      - ${KUZUDB_ABSOLUTE_PATH}:/database
    environment:
      - MODE=READ_ONLY
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
     - caddy


  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    env_file:
        - ./.env
    networks:
     - caddy

volumes:
  caddy_data:
    external: true
  caddy_config: